<?php

use Illuminate\Database\Seeder;
use App\Echipe;
use App\Etape;

class juniori_e extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $echipe = [
			[
				'echipa' => 'CSS Targoviste U11',
				'liga'   => 8,
				'serie'  => null,
			],[
				'echipa' => 'CSM Flacara Moreni U11',
				'liga'   => 8,
				'serie'  => null,
			],[
				'echipa' => 'ACS Fortis Valea Lunga U11',
				'liga'   => 8,
				'serie'  => null,
			],[
				'echipa' => 'A.S. Luceafarul Dragomiresti U11',
				'liga'   => 8,
				'serie'  => null,
			],[
				'echipa' => 'C.S.M Fieni U11',
				'liga'   => 8,
				'serie'  => null,
			],[
				'echipa' => 'A.S. F.C Pucioasa U11',
				'liga'   => 8,
				'serie'  => null,
			],[
				'echipa' => 'CS Kinder Targoviste U11',
				'liga'   => 8,
				'serie'  => null,
			],[
				'echipa' => 'AFC Chindia Targoviste U11',
				'liga'   => 8,
				'serie'  => null,
			]
		];

		$etape = [
			[
				'data'      => '2018-09-07',
				'ora'       => '16:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 1,
				'gazde'     => 'CSS Targoviste U11',
				'g_gazde'   => 0,
				'oaspeti'   => 'CSM Flacara Moreni U11',
				'g_oaspeti' => 2,
			],
			[
				'data'      => '2018-09-07',
				'ora'       => '17:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 1,
				'gazde'     => 'ACS Fortis Valea Lunga U11',
				'g_gazde'   => 0,
				'oaspeti'   => 'A.S. Luceafarul Dragomiresti U11',
				'g_oaspeti' => 5,
			],
			[
				'data'      => '2018-09-07',
				'ora'       => '17:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 1,
				'gazde'     => 'C.S.M Fieni U11',
				'g_gazde'   => 5,
				'oaspeti'   => 'A.S. F.C Pucioasa U11',
				'g_oaspeti' => 2,
			],
			[
				'data'      => '2018-09-07',
				'ora'       => '17:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 1,
				'gazde'     => 'CS Kinder Targoviste U11',
				'g_gazde'   => 1,
				'oaspeti'   => 'AFC Chindia Targoviste U11',
				'g_oaspeti' => 8,
			],
			[
				'data'      => '2018-09-14',
				'ora'       => '15:30',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 2,
				'gazde'     => 'CSM Flacara Moreni U11',
				'g_gazde'   => 11,
				'oaspeti'   => 'C.S.M Fieni U11',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-09-14',
				'ora'       => '17:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 2,
				'gazde'     => 'A.S. F.C Pucioasa U11',
				'g_gazde'   => 2,
				'oaspeti'   => 'ACS Fortis Valea Lunga U11',
				'g_oaspeti' => 8,
			],
			[
				'data'      => '2018-09-14',
				'ora'       => '17:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 2,
				'gazde'     => 'AFC Chindia Targoviste U11',
				'g_gazde'   => 13,
				'oaspeti'   => 'CSS Targoviste U11',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-09-14',
				'ora'       => '17:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 2,
				'gazde'     => 'A.S. Luceafarul Dragomiresti U11',
				'g_gazde'   => 2,
				'oaspeti'   => 'CS Kinder Targoviste U11',
				'g_oaspeti' => 5,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 3,
				'gazde'     => 'ACS Fortis Valea Lunga U11',
				'g_gazde'   => 0,
				'oaspeti'   => 'CSM Flacara Moreni U11',
				'g_oaspeti' => 2,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 3,
				'gazde'     => 'C.S.M Fieni U11',
				'g_gazde'   => 0,
				'oaspeti'   => 'AFC Chindia Targoviste U11',
				'g_oaspeti' => 18,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 3,
				'gazde'     => 'CSS Targoviste U11',
				'g_gazde'   => 1,
				'oaspeti'   => 'CS Kinder Targoviste U11',
				'g_oaspeti' => 2,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 3,
				'gazde'     => 'A.S. F.C Pucioasa U11',
				'g_gazde'   => 0,
				'oaspeti'   => 'A.S. Luceafarul Dragomiresti U11',
				'g_oaspeti' => 3,
			],
			[
				'data'      => '2018-09-28',
				'ora'       => '17:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 4,
				'gazde'     => 'AFC Chindia Targoviste U11',
				'g_gazde'   => 20,
				'oaspeti'   => 'ACS Fortis Valea Lunga U11',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-09-28',
				'ora'       => '17:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 4,
				'gazde'     => 'CS Kinder Targoviste U11',
				'g_gazde'   => 2,
				'oaspeti'   => 'C.S.M Fieni U11',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-09-28',
				'ora'       => '17:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 4,
				'gazde'     => 'A.S. Luceafarul Dragomiresti U11',
				'g_gazde'   => 7,
				'oaspeti'   => 'CSS Targoviste U11',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-09-28',
				'ora'       => '17:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 4,
				'gazde'     => 'CSM Flacara Moreni U11',
				'g_gazde'   => 24,
				'oaspeti'   => 'A.S. F.C Pucioasa U11',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-10-05',
				'ora'       => '16:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 5,
				'gazde'     => 'ACS Fortis Valea Lunga U11',
				'g_gazde'   => 3,
				'oaspeti'   => 'CS Kinder Targoviste U11',
				'g_oaspeti' => 4,
			],
			[
				'data'      => '2018-10-05',
				'ora'       => '16:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 5,
				'gazde'     => 'C.S.M Fieni U11',
				'g_gazde'   => 2,
				'oaspeti'   => 'CSS Targoviste U11',
				'g_oaspeti' => 1,
			],
			[
				'data'      => '2018-10-05',
				'ora'       => '16:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 5,
				'gazde'     => 'CSM Flacara Moreni U11',
				'g_gazde'   => 3,
				'oaspeti'   => 'A.S. Luceafarul Dragomiresti U11',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-10-05',
				'ora'       => '16:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 5,
				'gazde'     => 'A.S. F.C Pucioasa U11',
				'g_gazde'   => 0,
				'oaspeti'   => 'AFC Chindia Targoviste U11',
				'g_oaspeti' => 33,
			],
			[
				'data'      => '2018-10-12',
				'ora'       => '14:30',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 6,
				'gazde'     => 'CSS Targoviste U11',
				'g_gazde'   => 2,
				'oaspeti'   => 'ACS Fortis Valea Lunga U11',
				'g_oaspeti' => 2,
			],
			[
				'data'      => '2018-10-12',
				'ora'       => '16:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 6,
				'gazde'     => 'C.S.M Fieni U11',
				'g_gazde'   => 3,
				'oaspeti'   => 'A.S. Luceafarul Dragomiresti U11',
				'g_oaspeti' => 3,
			],
			[
				'data'      => '2018-10-12',
				'ora'       => '16:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 6,
				'gazde'     => 'CS Kinder Targoviste U11',
				'g_gazde'   => 19,
				'oaspeti'   => 'A.S. F.C Pucioasa U11',
				'g_oaspeti' => 1,
			],
			[
				'data'      => '2018-10-12',
				'ora'       => '16:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 6,
				'gazde'     => 'AFC Chindia Targoviste U11',
				'g_gazde'   => 4,
				'oaspeti'   => 'CSM Flacara Moreni U11',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-10-19',
				'ora'       => '16:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 7,
				'gazde'     => 'ACS Fortis Valea Lunga U11',
				'g_gazde'   => 0,
				'oaspeti'   => 'C.S.M Fieni U11',
				'g_oaspeti' => 1,
			],
			[
				'data'      => '2018-10-19',
				'ora'       => '16:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 7,
				'gazde'     => 'A.S. F.C Pucioasa U11',
				'g_gazde'   => 1,
				'oaspeti'   => 'CSS Targoviste U11',
				'g_oaspeti' => 6,
			],
			[
				'data'      => '2018-10-19',
				'ora'       => '16:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 7,
				'gazde'     => 'CSM Flacara Moreni U11',
				'g_gazde'   => 5,
				'oaspeti'   => 'CS Kinder Targoviste U11',
				'g_oaspeti' => 2,
			],
			[
				'data'      => '2018-10-19',
				'ora'       => '16:00',
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 7,
				'gazde'     => 'A.S. Luceafarul Dragomiresti U11',
				'g_gazde'   => 4,
				'oaspeti'   => 'AFC Chindia Targoviste U11',
				'g_oaspeti' => 13,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 8,
				'gazde'     => 'A.S. Luceafarul Dragomiresti U11',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Fortis Valea Lunga U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 8,
				'gazde'     => 'A.S. F.C Pucioasa U11',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S.M Fieni U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 8,
				'gazde'     => 'CSM Flacara Moreni U11',
				'g_gazde'   => null,
				'oaspeti'   => 'CSS Targoviste U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 8,
				'gazde'     => 'AFC Chindia Targoviste U11',
				'g_gazde'   => null,
				'oaspeti'   => 'CS Kinder Targoviste U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 9,
				'gazde'     => 'ACS Fortis Valea Lunga U11',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. F.C Pucioasa U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 9,
				'gazde'     => 'C.S.M Fieni U11',
				'g_gazde'   => null,
				'oaspeti'   => 'CSM Flacara Moreni U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 9,
				'gazde'     => 'CSS Targoviste U11',
				'g_gazde'   => null,
				'oaspeti'   => 'AFC Chindia Targoviste U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 9,
				'gazde'     => 'CS Kinder Targoviste U11',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. Luceafarul Dragomiresti U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 10,
				'gazde'     => 'CSM Flacara Moreni U11',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Fortis Valea Lunga U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 10,
				'gazde'     => 'AFC Chindia Targoviste U11',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S.M Fieni U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 10,
				'gazde'     => 'CS Kinder Targoviste U11',
				'g_gazde'   => null,
				'oaspeti'   => 'CSS Targoviste U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 10,
				'gazde'     => 'A.S. Luceafarul Dragomiresti U11',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. F.C Pucioasa U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 11,
				'gazde'     => 'ACS Fortis Valea Lunga U11',
				'g_gazde'   => null,
				'oaspeti'   => 'AFC Chindia Targoviste U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 11,
				'gazde'     => 'C.S.M Fieni U11',
				'g_gazde'   => null,
				'oaspeti'   => 'CS Kinder Targoviste U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 11,
				'gazde'     => 'CSS Targoviste U11',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. Luceafarul Dragomiresti U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 11,
				'gazde'     => 'A.S. F.C Pucioasa U11',
				'g_gazde'   => null,
				'oaspeti'   => 'CSM Flacara Moreni U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 12,
				'gazde'     => 'CS Kinder Targoviste U11',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Fortis Valea Lunga U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 12,
				'gazde'     => 'CSS Targoviste U11',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S.M Fieni U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 12,
				'gazde'     => 'A.S. Luceafarul Dragomiresti U11',
				'g_gazde'   => null,
				'oaspeti'   => 'CSM Flacara Moreni U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 12,
				'gazde'     => 'AFC Chindia Targoviste U11',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. F.C Pucioasa U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 13,
				'gazde'     => 'ACS Fortis Valea Lunga U11',
				'g_gazde'   => null,
				'oaspeti'   => 'CSS Targoviste U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 13,
				'gazde'     => 'A.S. Luceafarul Dragomiresti U11',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S.M Fieni U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 13,
				'gazde'     => 'A.S. F.C Pucioasa U11',
				'g_gazde'   => null,
				'oaspeti'   => 'CS Kinder Targoviste U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 13,
				'gazde'     => 'CSM Flacara Moreni U11',
				'g_gazde'   => null,
				'oaspeti'   => 'AFC Chindia Targoviste U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 14,
				'gazde'     => 'C.S.M Fieni U11',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Fortis Valea Lunga U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 14,
				'gazde'     => 'CSS Targoviste U11',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. F.C Pucioasa U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 14,
				'gazde'     => 'CS Kinder Targoviste U11',
				'g_gazde'   => null,
				'oaspeti'   => 'CSM Flacara Moreni U11',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 8,
				'serie'     => null,
				'etapa'     => 14,
				'gazde'     => 'AFC Chindia Targoviste U11',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. Luceafarul Dragomiresti U11',
				'g_oaspeti' => null,
			]
		];

		Echipe::where('liga', 8)->where('serie', null)->delete();
		foreach ($echipe as $echipa) {
			$adauga = new Echipe;
			$adauga->echipa = trim($echipa['echipa']);
			$adauga->liga   = $echipa['liga'];
			$adauga->serie  = $echipa['serie'];
			$adauga->save();
		}

		Etape::where('liga', 8)->where('serie', null)->delete();
		foreach ($etape as $etapa) {
			$adauga = new Etape;
			$adauga->gazde     = trim($etapa['gazde']);
			$adauga->oaspeti   = trim($etapa['oaspeti']);
			$adauga->g_gazde   = $etapa['g_gazde'];
			$adauga->g_oaspeti = $etapa['g_oaspeti'];
			$adauga->liga      = $etapa['liga'];
			$adauga->serie     = $etapa['serie'];
			$adauga->etapa     = $etapa['etapa'];
			$adauga->data      = $etapa['data'];
			$adauga->ora       = $etapa['ora'];
			$adauga->save();
		}
    }
}
