<?php

use Illuminate\Database\Seeder;
use App\Echipe;
use App\Etape;

class juniori_e extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $echipe = [
			[
				'echipa' => 'Kinder Targoviste 2',
				'liga'   => 8,
				'serie'  => null,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'Flacara Moreni',
				'liga'   => 8,
				'serie'  => null,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'Flacara Moreni 2',
				'liga'   => 8,
				'serie'  => null,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'Olimpia Picior de Munte',
				'liga'   => 8,
				'serie'  => null,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'Progresul Gaesti',
				'liga'   => 8,
				'serie'  => null,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'STA',
				'liga'   => 8,
				'serie'  => null,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'C.S.M Fieni',
				'liga'   => 8,
				'serie'  => null,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'FC Pucioasa',
				'liga'   => 8,
				'serie'  => null,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'Kinder Targoviste',
				'liga'   => 8,
				'serie'  => null,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'Chindia Targoviste',
				'liga'   => 8,
				'serie'  => null,
				'sezon'  => '2019/2020'
			]
		];

		$etape = [
			[
				'data' => '2019-09-13',
				'ora'  => '17:00',
				'gazde' => 'Kinder Targoviste',
				'oaspeti' => 'STA',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 1,
			],[
				'data' => '2019-09-13',
				'ora'  => '17:00',
				'gazde' => 'Kinder Targoviste 2',
				'oaspeti' => 'Chindia Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 1,
			],[
				'data' => '2019-09-13',
				'ora'  => '17:00',
				'gazde' => 'Flacara Moreni',
				'oaspeti' => 'FC Pucioasa',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 1,
			],[
				'data' => '2019-09-13',
				'ora'  => '17:00',
				'gazde' => 'Flacara Moreni 2',
				'oaspeti' => 'Olimpia Picior de Munte',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 1,
			],[
				'data' => '2019-09-13',
				'ora'  => '17:00',
				'gazde' => 'Progresul Gaesti',
				'oaspeti' => 'C.S.M Fieni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 1,
			],[
				'data' => '2019-09-20',
				'ora'  => '17:00',
				'gazde' => 'Chindia Targoviste',
				'oaspeti' => 'Kinder Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 2,
			],[
				'data' => '2019-09-20',
				'ora'  => '17:00',
				'gazde' => 'FC Pucioasa',
				'oaspeti' => 'Kinder Targoviste 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 2,
			],[
				'data' => '2019-09-20',
				'ora'  => '17:00',
				'gazde' => 'Olimpia Picior de Munte',
				'oaspeti' => 'Flacara Moreni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 2,
			],[
				'data' => '2019-09-20',
				'ora'  => '17:00',
				'gazde' => 'C.S.M Fieni',
				'oaspeti' => 'Flacara Moreni 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 2,
			],[
				'data' => '2019-09-20',
				'ora'  => '17:00',
				'gazde' => 'STA',
				'oaspeti' => 'Progresul Gaesti',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 2,
			],[
				'data' => '2019-09-27',
				'ora'  => '17:00',
				'gazde' => 'Kinder Targoviste',
				'oaspeti' => 'FC Pucioasa',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 3,
			],[
				'data' => '2019-09-27',
				'ora'  => '17:00',
				'gazde' => 'Kinder Targoviste 2',
				'oaspeti' => 'Olimpia Picior de Munte',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 3,
			],[
				'data' => '2019-09-27',
				'ora'  => '17:00',
				'gazde' => 'Flacara Moreni',
				'oaspeti' => 'C.S.M Fieni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 3,
			],[
				'data' => '2019-09-27',
				'ora'  => '17:00',
				'gazde' => 'Flacara Moreni 2',
				'oaspeti' => 'Progresul Gaesti',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 3,
			],[
				'data' => '2019-09-27',
				'ora'  => '17:00',
				'gazde' => 'Chindia Targoviste',
				'oaspeti' => 'STA',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 3,
			],[
				'data' => '2019-10-04',
				'ora'  => '16:00',
				'gazde' => 'Olimpia Picior de Munte',
				'oaspeti' => 'Kinder Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 4,
			],[
				'data' => '2019-10-04',
				'ora'  => '16:00',
				'gazde' => 'C.S.M Fieni',
				'oaspeti' => 'Kinder Targoviste 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 4,
			],[
				'data' => '2019-10-04',
				'ora'  => '16:00',
				'gazde' => 'Progresul Gaesti',
				'oaspeti' => 'Flacara Moreni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 4,
			],[
				'data' => '2019-10-04',
				'ora'  => '16:00',
				'gazde' => 'STA',
				'oaspeti' => 'Flacara Moreni 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 4,
			],[
				'data' => '2019-10-04',
				'ora'  => '16:00',
				'gazde' => 'FC Pucioasa',
				'oaspeti' => 'Chindia Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 4,
			],[
				'data' => '2019-10-11',
				'ora'  => '16:00',
				'gazde' => 'Kinder Targoviste',
				'oaspeti' => 'C.S.M Fieni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 5,
			],[
				'data' => '2019-10-11',
				'ora'  => '16:00',
				'gazde' => 'Kinder Targoviste 2',
				'oaspeti' => 'Progresul Gaesti',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 5,
			],[
				'data' => '2019-10-11',
				'ora'  => '16:00',
				'gazde' => 'Flacara Moreni',
				'oaspeti' => 'Flacara Moreni 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 5,
			],[
				'data' => '2019-10-11',
				'ora'  => '16:00',
				'gazde' => 'Chindia Targoviste',
				'oaspeti' => 'Olimpia Picior de Munte',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 5,
			],[
				'data' => '2019-10-11',
				'ora'  => '16:00',
				'gazde' => 'FC Pucioasa',
				'oaspeti' => 'STA',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 5,
			],[
				'data' => '2019-10-18',
				'ora'  => '16:00',
				'gazde' => 'Progresul Gaesti',
				'oaspeti' => 'Kinder Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 6,
			],[
				'data' => '2019-10-18',
				'ora'  => '16:00',
				'gazde' => 'Flacara Moreni 2',
				'oaspeti' => 'Kinder Targoviste 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 6,
			],[
				'data' => '2019-10-18',
				'ora'  => '16:00',
				'gazde' => 'STA',
				'oaspeti' => 'Flacara Moreni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 6,
			],[
				'data' => '2019-10-18',
				'ora'  => '16:00',
				'gazde' => 'C.S.M Fieni',
				'oaspeti' => 'Chindia Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 6,
			],[
				'data' => '2019-10-18',
				'ora'  => '16:00',
				'gazde' => 'Olimpia Picior de Munte',
				'oaspeti' => 'FC Pucioasa',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 6,
			],[
				'data' => '2019-10-25',
				'ora'  => '16:00',
				'gazde' => 'Kinder Targoviste',
				'oaspeti' => 'Flacara Moreni 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 7,
			],[
				'data' => '2019-10-25',
				'ora'  => '16:00',
				'gazde' => 'Kinder Targoviste 2',
				'oaspeti' => 'Flacara Moreni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 7,
			],[
				'data' => '2019-10-25',
				'ora'  => '16:00',
				'gazde' => 'Chindia Targoviste',
				'oaspeti' => 'Progresul Gaesti',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 7,
			],[
				'data' => '2019-10-25',
				'ora'  => '16:00',
				'gazde' => 'FC Pucioasa',
				'oaspeti' => 'C.S.M Fieni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 7,
			],[
				'data' => '2019-10-25',
				'ora'  => '16:00',
				'gazde' => 'Olimpia Picior de Munte',
				'oaspeti' => 'STA',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 7,
			],[
				'data' => '2019-11-01',
				'ora'  => '15:00',
				'gazde' => 'Flacara Moreni',
				'oaspeti' => 'Kinder Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 8,
			],[
				'data' => '2019-11-01',
				'ora'  => '15:00',
				'gazde' => 'Kinder Targoviste 2',
				'oaspeti' => 'STA',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 8,
			],[
				'data' => '2019-11-01',
				'ora'  => '15:00',
				'gazde' => 'Flacara Moreni 2',
				'oaspeti' => 'Chindia Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 8,
			],[
				'data' => '2019-11-01',
				'ora'  => '15:00',
				'gazde' => 'Progresul Gaesti',
				'oaspeti' => 'FC Pucioasa',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 8,
			],[
				'data' => '2019-11-01',
				'ora'  => '15:00',
				'gazde' => 'C.S.M Fieni',
				'oaspeti' => 'Olimpia Picior de Munte',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 8,
			],[
				'data' => '2019-11-08',
				'ora'  => '15:00',
				'gazde' => 'Kinder Targoviste',
				'oaspeti' => 'Kinder Targoviste 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 9,
			],[
				'data' => '2019-11-08',
				'ora'  => '15:00',
				'gazde' => 'Chindia Targoviste',
				'oaspeti' => 'Flacara Moreni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 9,
			],[
				'data' => '2019-11-08',
				'ora'  => '15:00',
				'gazde' => 'FC Pucioasa',
				'oaspeti' => 'Flacara Moreni 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 9,
			],[
				'data' => '2019-11-08',
				'ora'  => '15:00',
				'gazde' => 'Olimpia Picior de Munte',
				'oaspeti' => 'Progresul Gaesti',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 9,
			],[
				'data' => '2019-11-08',
				'ora'  => '15:00',
				'gazde' => 'STA',
				'oaspeti' => 'C.S.M Fieni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 9,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'STA',
				'oaspeti' => 'Kinder Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 10,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Chindia Targoviste',
				'oaspeti' => 'Kinder Targoviste 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 10,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'FC Pucioasa',
				'oaspeti' => 'Flacara Moreni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 10,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Olimpia Picior de Munte',
				'oaspeti' => 'Flacara Moreni 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 10,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'C.S.M Fieni',
				'oaspeti' => 'Progresul Gaesti',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 10,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Kinder Targoviste',
				'oaspeti' => 'Chindia Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 11,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Kinder Targoviste 2',
				'oaspeti' => 'FC Pucioasa',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 11,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Flacara Moreni',
				'oaspeti' => 'Olimpia Picior de Munte',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 11,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Flacara Moreni 2',
				'oaspeti' => 'C.S.M Fieni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 11,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Progresul Gaesti',
				'oaspeti' => 'STA',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 11,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'FC Pucioasa',
				'oaspeti' => 'Kinder Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 12,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Olimpia Picior de Munte',
				'oaspeti' => 'Kinder Targoviste 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 12,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'C.S.M Fieni',
				'oaspeti' => 'Flacara Moreni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 12,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Progresul Gaesti',
				'oaspeti' => 'Flacara Moreni 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 12,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'STA',
				'oaspeti' => 'Chindia Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 12,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Kinder Targoviste',
				'oaspeti' => 'Olimpia Picior de Munte',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 13,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Kinder Targoviste 2',
				'oaspeti' => 'C.S.M Fieni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 13,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Flacara Moreni',
				'oaspeti' => 'Progresul Gaesti',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 13,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Flacara Moreni 2',
				'oaspeti' => 'STA',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 13,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Chindia Targoviste',
				'oaspeti' => 'FC Pucioasa',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 13,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'C.S.M Fieni',
				'oaspeti' => 'Kinder Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 14,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Progresul Gaesti',
				'oaspeti' => 'Kinder Targoviste 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 14,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Flacara Moreni 2',
				'oaspeti' => 'Flacara Moreni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 14,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Olimpia Picior de Munte',
				'oaspeti' => 'Chindia Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 14,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'STA',
				'oaspeti' => 'FC Pucioasa',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 14,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Kinder Targoviste',
				'oaspeti' => 'Progresul Gaesti',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 15,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Kinder Targoviste 2',
				'oaspeti' => 'Flacara Moreni 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 15,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Flacara Moreni',
				'oaspeti' => 'STA',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 15,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Chindia Targoviste',
				'oaspeti' => 'C.S.M Fieni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 15,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'FC Pucioasa',
				'oaspeti' => 'Olimpia Picior de Munte',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 15,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Flacara Moreni 2',
				'oaspeti' => 'Kinder Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 16,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Flacara Moreni',
				'oaspeti' => 'Kinder Targoviste 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 16,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Progresul Gaesti',
				'oaspeti' => 'Chindia Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 16,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'C.S.M Fieni',
				'oaspeti' => 'FC Pucioasa',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 16,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'STA',
				'oaspeti' => 'Olimpia Picior de Munte',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 16,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Kinder Targoviste',
				'oaspeti' => 'Flacara Moreni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 17,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'STA',
				'oaspeti' => 'Kinder Targoviste 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 17,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Chindia Targoviste',
				'oaspeti' => 'Flacara Moreni 2',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 17,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'FC Pucioasa',
				'oaspeti' => 'Progresul Gaesti',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 17,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Olimpia Picior de Munte',
				'oaspeti' => 'C.S.M Fieni',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 17,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Kinder Targoviste 2',
				'oaspeti' => 'Kinder Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 18,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Flacara Moreni',
				'oaspeti' => 'Chindia Targoviste',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 18,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Flacara Moreni 2',
				'oaspeti' => 'FC Pucioasa',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 18,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'Progresul Gaesti',
				'oaspeti' => 'Olimpia Picior de Munte',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 18,
			],[
				'data' => null,
				'ora'  => null,
				'gazde' => 'C.S.M Fieni',
				'oaspeti' => 'STA',
				'g_gazde' => null,
				'g_oaspeti' => null,
				'liga' => 8,
				'serie' => null,
				'sezon' => '2019/2020',
				'etapa' => 18,
			]
		];

		/*Echipe::where('liga', 8)->where('serie', null)
								->where('sezon', '2019/2020')
								->delete();*/
		foreach ($echipe as $echipa) {
			$adauga = new Echipe;
			$adauga->echipa = trim($echipa['echipa']);
			$adauga->liga   = $echipa['liga'];
			$adauga->serie  = $echipa['serie'];
			$adauga->sezon  = $echipa['sezon'];
			$adauga->save();
		}

		/*Etape::where('liga', 7)->where('serie', null)
								->where('sezon', '2019/2020')
								->delete();*/
		foreach ($etape as $etapa) {
			$adauga = new Etape;
			$adauga->gazde     = trim($etapa['gazde']);
			$adauga->oaspeti   = trim($etapa['oaspeti']);
			$adauga->g_gazde   = $etapa['g_gazde'];
			$adauga->g_oaspeti = $etapa['g_oaspeti'];
			$adauga->liga      = $etapa['liga'];
			$adauga->serie     = $etapa['serie'];
			$adauga->etapa     = $etapa['etapa'];
			$adauga->data      = $etapa['data'];
			$adauga->ora       = $etapa['ora'];
			$adauga->sezon     = $etapa['sezon'];
			$adauga->save();
		}
    }
}
