<?php

use Illuminate\Database\Seeder;
use App\Echipe;
use App\Etape;

class juniori_d extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $echipe = [
			[
				'echipa' => 'ACS Progresul Gaesti U13',
				'liga'   => 7,
				'serie'  => null,
			],[
				'echipa' => 'Fc Chindia 2 Targoviste U13',
				'liga'   => 7,
				'serie'  => null,
			],[
				'echipa' => 'C.S.M Fieni U13',
				'liga'   => 7,
				'serie'  => null,
			],[
				'echipa' => 'CSS Targoviste U13',
				'liga'   => 7,
				'serie'  => null,
			],[
				'echipa' => 'A.S. F.C Pucioasa U13',
				'liga'   => 7,
				'serie'  => null,
			],[
				'echipa' => 'ACS Urban Titu U13',
				'liga'   => 7,
				'serie'  => null,
			],[
				'echipa' => 'CSM Flacara Moreni U13',
				'liga'   => 7,
				'serie'  => null,
			],[
				'echipa' => 'CS Kinder Targoviste U13',
				'liga'   => 7,
				'serie'  => null,
			],[
				'echipa' => 'Grupul Scolar Agricol Nucet U13',
				'liga'   => 7,
				'serie'  => null,
			],[
				'echipa' => 'Kinder 2 Targoviste U13',
				'liga'   => 7,
				'serie'  => null,
			],[
				'echipa' => 'A.S. Olimpicii Ulmi U13',
				'liga'   => 7,
				'serie'  => null,
			],[
				'echipa' => 'ACS Progresul Gaesti U13 2',
				'liga'   => 7,
				'serie'  => null,
			],[
				'echipa' => 'AFC Chindia Targoviste U13',
				'liga'   => 7,
				'serie'  => null,
			],[
				'echipa' => 'STA',
				'liga'   => 7,
				'serie'  => null,
			]
		];

		$etape = [
			[
				'data'      => '2018-09-02',
				'ora'       => '15:30',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 1,
				'gazde'     => 'ACS Progresul Gaesti U13',
				'g_gazde'   => 2,
				'oaspeti'   => 'Fc Chindia 2 Targoviste U13',
				'g_oaspeti' => 3,
			],
			[
				'data'      => '2018-09-02',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 1,
				'gazde'     => 'C.S.M Fieni U13',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],
			[
				'data'      => '2018-09-02',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 1,
				'gazde'     => 'CSS Targoviste U13',
				'g_gazde'   => 5,
				'oaspeti'   => 'A.S. F.C Pucioasa U13',
				'g_oaspeti' => 4,
			],
			[
				'data'      => '2018-09-02',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 1,
				'gazde'     => 'ACS Urban Titu U13',
				'g_gazde'   => 0,
				'oaspeti'   => 'CSM Flacara Moreni U13',
				'g_oaspeti' => 6,
			],
			[
				'data'      => '2018-09-02',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 1,
				'gazde'     => 'CS Kinder Targoviste U13',
				'g_gazde'   => 13,
				'oaspeti'   => 'Grupul Scolar Agricol Nucet U13',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-09-02',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 1,
				'gazde'     => 'Kinder 2 Targoviste U13',
				'g_gazde'   => 9,
				'oaspeti'   => 'A.S. Olimpicii Ulmi U13',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-09-02',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 1,
				'gazde'     => 'ACS Progresul Gaesti U13 2',
				'g_gazde'   => 1,
				'oaspeti'   => 'AFC Chindia Targoviste U13',
				'g_oaspeti' => 7,
			],
			[
				'data'      => '2018-09-06',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 2,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'AFC Chindia Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => '2018-09-06',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 2,
				'gazde'     => 'Fc Chindia 2 Targoviste U13',
				'g_gazde'   => 5,
				'oaspeti'   => 'ACS Progresul Gaesti U13 2',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-09-06',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 2,
				'gazde'     => 'A.S. Olimpicii Ulmi U13',
				'g_gazde'   => 0,
				'oaspeti'   => 'ACS Progresul Gaesti U13',
				'g_oaspeti' => 3,
			],
			[
				'data'      => '2018-09-06',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 2,
				'gazde'     => 'Grupul Scolar Agricol Nucet U13',
				'g_gazde'   => 1,
				'oaspeti'   => 'Kinder 2 Targoviste U13',
				'g_oaspeti' => 5,
			],
			[
				'data'      => '2018-09-06',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 2,
				'gazde'     => 'CSM Flacara Moreni U13',
				'g_gazde'   => 1,
				'oaspeti'   => 'CS Kinder Targoviste U13',
				'g_oaspeti' => 3,
			],
			[
				'data'      => '2018-09-06',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 2,
				'gazde'     => 'A.S. F.C Pucioasa U13',
				'g_gazde'   => 5,
				'oaspeti'   => 'ACS Urban Titu U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => '2018-09-06',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 2,
				'gazde'     => 'C.S.M Fieni U13',
				'g_gazde'   => 1,
				'oaspeti'   => 'CSS Targoviste U13',
				'g_oaspeti' => 7,
			],
			[
				'data'      => '2018-09-09',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 3,
				'gazde'     => 'CSS Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],
			[
				'data'      => '2018-09-09',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 3,
				'gazde'     => 'ACS Urban Titu U13',
				'g_gazde'   => 5,
				'oaspeti'   => 'C.S.M Fieni U13',
				'g_oaspeti' => 3,
			],
			[
				'data'      => '2018-09-09',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 3,
				'gazde'     => 'CS Kinder Targoviste U13',
				'g_gazde'   => 16,
				'oaspeti'   => 'A.S. F.C Pucioasa U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => '2018-09-09',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 3,
				'gazde'     => 'Kinder 2 Targoviste U13',
				'g_gazde'   => 2,
				'oaspeti'   => 'CSM Flacara Moreni U13',
				'g_oaspeti' => 2,
			],
			[
				'data'      => '2018-09-09',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 3,
				'gazde'     => 'ACS Progresul Gaesti U13',
				'g_gazde'   => 3,
				'oaspeti'   => 'Grupul Scolar Agricol Nucet U13',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-09-09',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 3,
				'gazde'     => 'ACS Progresul Gaesti U13 2',
				'g_gazde'   => 3,
				'oaspeti'   => 'A.S. Olimpicii Ulmi U13',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-09-09',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 3,
				'gazde'     => 'AFC Chindia Targoviste U13',
				'g_gazde'   => 2,
				'oaspeti'   => 'Fc Chindia 2 Targoviste U13',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-09-16',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 4,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Fc Chindia 2 Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => '2018-09-16',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 4,
				'gazde'     => 'A.S. Olimpicii Ulmi U13',
				'g_gazde'   => 0,
				'oaspeti'   => 'AFC Chindia Targoviste U13',
				'g_oaspeti' => 5,
			],
			[
				'data'      => '2018-09-16',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 4,
				'gazde'     => 'Grupul Scolar Agricol Nucet U13',
				'g_gazde'   => 4,
				'oaspeti'   => 'ACS Progresul Gaesti U13 2',
				'g_oaspeti' => 3,
			],
			[
				'data'      => '2018-09-16',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 4,
				'gazde'     => 'CSM Flacara Moreni U13',
				'g_gazde'   => 3,
				'oaspeti'   => 'ACS Progresul Gaesti U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => '2018-09-16',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 4,
				'gazde'     => 'A.S. F.C Pucioasa U13',
				'g_gazde'   => 2,
				'oaspeti'   => 'Kinder 2 Targoviste U13',
				'g_oaspeti' => 6,
			],
			[
				'data'      => '2018-09-16',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 4,
				'gazde'     => 'CSS Targoviste U13',
				'g_gazde'   => 2,
				'oaspeti'   => 'ACS Urban Titu U13',
				'g_oaspeti' => 2,
			],
			[
				'data'      => '2018-10-03',
				'ora'       => '16:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 4,
				'gazde'     => 'C.S.M Fieni U13',
				'g_gazde'   => 0,
				'oaspeti'   => 'CS Kinder Targoviste U13',
				'g_oaspeti' => 13,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 5,
				'gazde'     => 'ACS Urban Titu U13',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 5,
				'gazde'     => 'CS Kinder Targoviste U13',
				'g_gazde'   => 2,
				'oaspeti'   => 'CSS Targoviste U13',
				'g_oaspeti' => 0,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 5,
				'gazde'     => 'Kinder 2 Targoviste U13',
				'g_gazde'   => 6,
				'oaspeti'   => 'C.S.M Fieni U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 5,
				'gazde'     => 'ACS Progresul Gaesti U13',
				'g_gazde'   => 2,
				'oaspeti'   => 'A.S. F.C Pucioasa U13',
				'g_oaspeti' => 8,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 5,
				'gazde'     => 'ACS Progresul Gaesti U13 2',
				'g_gazde'   => 5,
				'oaspeti'   => 'CSM Flacara Moreni U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 5,
				'gazde'     => 'AFC Chindia Targoviste U13',
				'g_gazde'   => 5,
				'oaspeti'   => 'Grupul Scolar Agricol Nucet U13',
				'g_oaspeti' => 0,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 5,
				'gazde'     => 'Fc Chindia 2 Targoviste U13',
				'g_gazde'   => 5,
				'oaspeti'   => 'A.S. Olimpicii Ulmi U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 6,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. Olimpicii Ulmi U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => '2018-09-30',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 6,
				'gazde'     => 'Grupul Scolar Agricol Nucet U13',
				'g_gazde'   => 1,
				'oaspeti'   => 'Fc Chindia 2 Targoviste U13',
				'g_oaspeti' => 4,
			],
			[
				'data'      => '2018-09-30',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 6,
				'gazde'     => 'CSM Flacara Moreni U13',
				'g_gazde'   => 0,
				'oaspeti'   => 'AFC Chindia Targoviste U13',
				'g_oaspeti' => 4,
			],
			[
				'data'      => '2018-09-30',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 6,
				'gazde'     => 'A.S. F.C Pucioasa U13',
				'g_gazde'   => 1,
				'oaspeti'   => 'ACS Progresul Gaesti U13 2',
				'g_oaspeti' => 1,
			],
			[
				'data'      => '2018-09-30',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 6,
				'gazde'     => 'C.S.M Fieni U13',
				'g_gazde'   => 3,
				'oaspeti'   => 'ACS Progresul Gaesti U13',
				'g_oaspeti' => 5,
			],
			[
				'data'      => '2018-09-30',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 6,
				'gazde'     => 'CSS Targoviste U13',
				'g_gazde'   => 1,
				'oaspeti'   => 'Kinder 2 Targoviste U13',
				'g_oaspeti' => 2,
			],
			[
				'data'      => '2018-09-30',
				'ora'       => '17:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 6,
				'gazde'     => 'ACS Urban Titu U13',
				'g_gazde'   => 0,
				'oaspeti'   => 'CS Kinder Targoviste U13',
				'g_oaspeti' => 10,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 7,
				'gazde'     => 'CS Kinder Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],
			[
				'data'      => '2018-10-07',
				'ora'       => '14:30',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 7,
				'gazde'     => 'ACS Progresul Gaesti U13',
				'g_gazde'   => 2,
				'oaspeti'   => 'CSS Targoviste U13',
				'g_oaspeti' => 4,
			],
			[
				'data'      => '2018-10-07',
				'ora'       => '14:30',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 7,
				'gazde'     => 'AFC Chindia Targoviste U13',
				'g_gazde'   => 19,
				'oaspeti'   => 'A.S. F.C Pucioasa U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => '2018-10-07',
				'ora'       => '16:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 7,
				'gazde'     => 'Kinder 2 Targoviste U13',
				'g_gazde'   => 3,
				'oaspeti'   => 'ACS Urban Titu U13',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-10-07',
				'ora'       => '16:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 7,
				'gazde'     => 'ACS Progresul Gaesti U13 2',
				'g_gazde'   => 4,
				'oaspeti'   => 'C.S.M Fieni U13',
				'g_oaspeti' => 2,
			],
			[
				'data'      => '2018-10-07',
				'ora'       => '16:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 7,
				'gazde'     => 'Fc Chindia 2 Targoviste U13',
				'g_gazde'   => 1,
				'oaspeti'   => 'CSM Flacara Moreni U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => '2018-10-07',
				'ora'       => '16:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 7,
				'gazde'     => 'A.S. Olimpicii Ulmi U13',
				'g_gazde'   => 1,
				'oaspeti'   => 'Grupul Scolar Agricol Nucet U13',
				'g_oaspeti' => 3,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 8,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Grupul Scolar Agricol Nucet U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => '2018-10-11',
				'ora'       => '14:30',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 8,
				'gazde'     => 'CSS Targoviste U13',
				'g_gazde'   => 5,
				'oaspeti'   => 'ACS Progresul Gaesti U13 2',
				'g_oaspeti' => 1,
			],
			[
				'data'      => '2018-10-11',
				'ora'       => '15:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 8,
				'gazde'     => 'CSM Flacara Moreni U13',
				'g_gazde'   => 7,
				'oaspeti'   => 'A.S. Olimpicii Ulmi U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => '2018-10-11',
				'ora'       => '16:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 8,
				'gazde'     => 'A.S. F.C Pucioasa U13',
				'g_gazde'   => 0,
				'oaspeti'   => 'Fc Chindia 2 Targoviste U13',
				'g_oaspeti' => 5,
			],
			[
				'data'      => '2018-10-11',
				'ora'       => '16:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 8,
				'gazde'     => 'C.S.M Fieni U13',
				'g_gazde'   => 1,
				'oaspeti'   => 'AFC Chindia Targoviste U13',
				'g_oaspeti' => 7,
			],
			[
				'data'      => '2018-10-11',
				'ora'       => '16:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 8,
				'gazde'     => 'ACS Urban Titu U13',
				'g_gazde'   => 1,
				'oaspeti'   => 'ACS Progresul Gaesti U13',
				'g_oaspeti' => 5,
			],
			[
				'data'      => '2018-10-11',
				'ora'       => '16:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 8,
				'gazde'     => 'CS Kinder Targoviste U13',
				'g_gazde'   => 3,
				'oaspeti'   => 'Kinder 2 Targoviste U13',
				'g_oaspeti' => 2,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 9,
				'gazde'     => 'Kinder 2 Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],
			[
				'data'      => '2018-10-14',
				'ora'       => '14:30',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 9,
				'gazde'     => 'ACS Progresul Gaesti U13',
				'g_gazde'   => 1,
				'oaspeti'   => 'CS Kinder Targoviste U13',
				'g_oaspeti' => 6,
			],
			[
				'data'      => '2018-10-14',
				'ora'       => '14:30',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 9,
				'gazde'     => 'AFC Chindia Targoviste U13',
				'g_gazde'   => 3,
				'oaspeti'   => 'CSS Targoviste U13',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-10-14',
				'ora'       => '16:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 9,
				'gazde'     => 'ACS Progresul Gaesti U13 2',
				'g_gazde'   => 5,
				'oaspeti'   => 'ACS Urban Titu U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => '2018-10-14',
				'ora'       => '16:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 9,
				'gazde'     => 'Fc Chindia 2 Targoviste U13',
				'g_gazde'   => 4,
				'oaspeti'   => 'C.S.M Fieni U13',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-10-14',
				'ora'       => '16:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 9,
				'gazde'     => 'A.S. Olimpicii Ulmi U13',
				'g_gazde'   => 3,
				'oaspeti'   => 'A.S. F.C Pucioasa U13',
				'g_oaspeti' => 2,
			],
			[
				'data'      => '2018-10-14',
				'ora'       => '16:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 9,
				'gazde'     => 'Grupul Scolar Agricol Nucet U13',
				'g_gazde'   => 0,
				'oaspeti'   => 'CSM Flacara Moreni U13',
				'g_oaspeti' => 2,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 10,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'CSM Flacara Moreni U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => '2018-10-21',
				'ora'       => '12:30',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 10,
				'gazde'     => 'CSS Targoviste U13',
				'g_gazde'   => 0,
				'oaspeti'   => 'Fc Chindia 2 Targoviste U13',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-10-21',
				'ora'       => '14:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 10,
				'gazde'     => 'CS Kinder Targoviste U13',
				'g_gazde'   => 9,
				'oaspeti'   => 'ACS Progresul Gaesti U13 2',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-10-21',
				'ora'       => '15:30',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 10,
				'gazde'     => 'Kinder 2 Targoviste U13',
				'g_gazde'   => 3,
				'oaspeti'   => 'ACS Progresul Gaesti U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => '2018-10-21',
				'ora'       => '16:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 10,
				'gazde'     => 'A.S. F.C Pucioasa U13',
				'g_gazde'   => null,
				'oaspeti'   => 'Grupul Scolar Agricol Nucet U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => '2018-10-21',
				'ora'       => '16:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 10,
				'gazde'     => 'C.S.M Fieni U13',
				'g_gazde'   => 3,
				'oaspeti'   => 'A.S. Olimpicii Ulmi U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => '2018-10-21',
				'ora'       => '16:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 10,
				'gazde'     => 'ACS Urban Titu U13',
				'g_gazde'   => 0,
				'oaspeti'   => 'AFC Chindia Targoviste U13',
				'g_oaspeti' => 9,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 11,
				'gazde'     => 'ACS Progresul Gaesti U13',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],
			[
				'data'      => '2018-10-28',
				'ora'       => '14:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 11,
				'gazde'     => 'AFC Chindia Targoviste U13',
				'g_gazde'   => 2,
				'oaspeti'   => 'CS Kinder Targoviste U13',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-10-28',
				'ora'       => '15:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 11,
				'gazde'     => 'ACS Progresul Gaesti U13 2',
				'g_gazde'   => 4,
				'oaspeti'   => 'Kinder 2 Targoviste U13',
				'g_oaspeti' => 2,
			],
			[
				'data'      => '2018-10-28',
				'ora'       => '15:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 11,
				'gazde'     => 'A.S. Olimpicii Ulmi U13',
				'g_gazde'   => 3,
				'oaspeti'   => 'CSS Targoviste U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => '2018-10-28',
				'ora'       => '15:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 11,
				'gazde'     => 'Grupul Scolar Agricol Nucet U13',
				'g_gazde'   => 3,
				'oaspeti'   => 'C.S.M Fieni U13',
				'g_oaspeti' => 0,
			],
			[
				'data'      => '2018-10-28',
				'ora'       => '15:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 11,
				'gazde'     => 'CSM Flacara Moreni U13',
				'g_gazde'   => 11,
				'oaspeti'   => 'A.S. F.C Pucioasa U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => '2018-10-28',
				'ora'       => '15:30',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 11,
				'gazde'     => 'Fc Chindia 2 Targoviste U13',
				'g_gazde'   => 3,
				'oaspeti'   => 'ACS Urban Titu U13',
				'g_oaspeti' => 2,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 12,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. F.C Pucioasa U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => '13:30',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 12,
				'gazde'     => 'CS Kinder Targoviste U13',
				'g_gazde'   => 2,
				'oaspeti'   => 'Fc Chindia 2 Targoviste U13',
				'g_oaspeti' => 0,
			],
			[
				'data'      => null,
				'ora'       => '15:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 12,
				'gazde'     => 'C.S.M Fieni U13',
				'g_gazde'   => 1,
				'oaspeti'   => 'CSM Flacara Moreni U13',
				'g_oaspeti' => 3,
			],
			[
				'data'      => null,
				'ora'       => '15:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 12,
				'gazde'     => 'CSS Targoviste U13',
				'g_gazde'   => 1,
				'oaspeti'   => 'Grupul Scolar Agricol Nucet U13',
				'g_oaspeti' => 0,
			],
			[
				'data'      => null,
				'ora'       => '15:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 12,
				'gazde'     => 'ACS Urban Titu U13',
				'g_gazde'   => 2,
				'oaspeti'   => 'A.S. Olimpicii Ulmi U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => null,
				'ora'       => '15:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 12,
				'gazde'     => 'ACS Progresul Gaesti U13',
				'g_gazde'   => 2,
				'oaspeti'   => 'ACS Progresul Gaesti U13 2',
				'g_oaspeti' => 2,
			],
			[
				'data'      => null,
				'ora'       => '15:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 12,
				'gazde'     => 'Kinder 2 Targoviste U13',
				'g_gazde'   => 0,
				'oaspeti'   => 'AFC Chindia Targoviste U13',
				'g_oaspeti' => 6,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 13,
				'gazde'     => 'ACS Progresul Gaesti U13 2',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => '15:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 13,
				'gazde'     => 'AFC Chindia Targoviste U13',
				'g_gazde'   => 3,
				'oaspeti'   => 'ACS Progresul Gaesti U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => null,
				'ora'       => '15:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 13,
				'gazde'     => 'A.S. Olimpicii Ulmi U13',
				'g_gazde'   => 0,
				'oaspeti'   => 'CS Kinder Targoviste U13',
				'g_oaspeti' => 10,
			],
			[
				'data'      => null,
				'ora'       => '15:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 13,
				'gazde'     => 'Grupul Scolar Agricol Nucet U13',
				'g_gazde'   => 5,
				'oaspeti'   => 'ACS Urban Titu U13',
				'g_oaspeti' => 2,
			],
			[
				'data'      => null,
				'ora'       => '15:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 13,
				'gazde'     => 'CSM Flacara Moreni U13',
				'g_gazde'   => 2,
				'oaspeti'   => 'CSS Targoviste U13',
				'g_oaspeti' => 0,
			],
			[
				'data'      => null,
				'ora'       => '15:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 13,
				'gazde'     => 'A.S. F.C Pucioasa U13',
				'g_gazde'   => 3,
				'oaspeti'   => 'C.S.M Fieni U13',
				'g_oaspeti' => 0,
			],
			[
				'data'      => null,
				'ora'       => '15:30',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 13,
				'gazde'     => 'Fc Chindia 2 Targoviste U13',
				'g_gazde'   => 1,
				'oaspeti'   => 'Kinder 2 Targoviste U13',
				'g_oaspeti' => 2,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 14,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S.M Fieni U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => '13:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 14,
				'gazde'     => 'A.S. Olimpicii Ulmi U13',
				'g_gazde'   => 1,
				'oaspeti'   => 'Kinder 2 Targoviste U13',
				'g_oaspeti' => 4,
			],
			[
				'data'      => null,
				'ora'       => '13:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 14,
				'gazde'     => 'Fc Chindia 2 Targoviste U13',
				'g_gazde'   => 3,
				'oaspeti'   => 'ACS Progresul Gaesti U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => null,
				'ora'       => '13:30',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 14,
				'gazde'     => 'Grupul Scolar Agricol Nucet U13',
				'g_gazde'   => 0,
				'oaspeti'   => 'CS Kinder Targoviste U13',
				'g_oaspeti' => 3,
			],
			[
				'data'      => null,
				'ora'       => '14:30',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 14,
				'gazde'     => 'CSM Flacara Moreni U13',
				'g_gazde'   => 3,
				'oaspeti'   => 'ACS Urban Titu U13',
				'g_oaspeti' => 1,
			],
			[
				'data'      => null,
				'ora'       => '14:30',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 14,
				'gazde'     => 'AFC Chindia Targoviste U13',
				'g_gazde'   => 7,
				'oaspeti'   => 'ACS Progresul Gaesti U13 2',
				'g_oaspeti' => 1,
			],
			[
				'data'      => null,
				'ora'       => '15:00',
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 14,
				'gazde'     => 'A.S. F.C Pucioasa U13',
				'g_gazde'   => 2,
				'oaspeti'   => 'CSS Targoviste U13',
				'g_oaspeti' => 4,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 15,
				'gazde'     => 'AFC Chindia Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 15,
				'gazde'     => 'ACS Progresul Gaesti U13 2',
				'g_gazde'   => null,
				'oaspeti'   => 'Fc Chindia 2 Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 15,
				'gazde'     => 'ACS Progresul Gaesti U13',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. Olimpicii Ulmi U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 15,
				'gazde'     => 'Kinder 2 Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'Grupul Scolar Agricol Nucet U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 15,
				'gazde'     => 'CS Kinder Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'CSM Flacara Moreni U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 15,
				'gazde'     => 'ACS Urban Titu U13',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. F.C Pucioasa U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 15,
				'gazde'     => 'CSS Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S.M Fieni U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 16,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'CSS Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 16,
				'gazde'     => 'C.S.M Fieni U13',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Urban Titu U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 16,
				'gazde'     => 'A.S. F.C Pucioasa U13',
				'g_gazde'   => null,
				'oaspeti'   => 'CS Kinder Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 16,
				'gazde'     => 'CSM Flacara Moreni U13',
				'g_gazde'   => null,
				'oaspeti'   => 'Kinder 2 Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 16,
				'gazde'     => 'Grupul Scolar Agricol Nucet U13',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Progresul Gaesti U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 16,
				'gazde'     => 'A.S. Olimpicii Ulmi U13',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Progresul Gaesti U13 2',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 16,
				'gazde'     => 'Fc Chindia 2 Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'AFC Chindia Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 17,
				'gazde'     => 'Fc Chindia 2 Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 17,
				'gazde'     => 'AFC Chindia Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. Olimpicii Ulmi U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 17,
				'gazde'     => 'ACS Progresul Gaesti U13 2',
				'g_gazde'   => null,
				'oaspeti'   => 'Grupul Scolar Agricol Nucet U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 17,
				'gazde'     => 'ACS Progresul Gaesti U13',
				'g_gazde'   => null,
				'oaspeti'   => 'CSM Flacara Moreni U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 17,
				'gazde'     => 'Kinder 2 Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. F.C Pucioasa U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 17,
				'gazde'     => 'CS Kinder Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S.M Fieni U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 17,
				'gazde'     => 'ACS Urban Titu U13',
				'g_gazde'   => null,
				'oaspeti'   => 'CSS Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 18,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Urban Titu U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 18,
				'gazde'     => 'CSS Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'CS Kinder Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 18,
				'gazde'     => 'C.S.M Fieni U13',
				'g_gazde'   => null,
				'oaspeti'   => 'Kinder 2 Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 18,
				'gazde'     => 'A.S. F.C Pucioasa U13',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Progresul Gaesti U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 18,
				'gazde'     => 'CSM Flacara Moreni U13',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Progresul Gaesti U13 2',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 18,
				'gazde'     => 'Grupul Scolar Agricol Nucet U13',
				'g_gazde'   => null,
				'oaspeti'   => 'AFC Chindia Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 18,
				'gazde'     => 'A.S. Olimpicii Ulmi U13',
				'g_gazde'   => null,
				'oaspeti'   => 'Fc Chindia 2 Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 19,
				'gazde'     => 'A.S. Olimpicii Ulmi U13',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 19,
				'gazde'     => 'Fc Chindia 2 Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'Grupul Scolar Agricol Nucet U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 19,
				'gazde'     => 'AFC Chindia Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'CSM Flacara Moreni U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 19,
				'gazde'     => 'ACS Progresul Gaesti U13 2',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. F.C Pucioasa U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 19,
				'gazde'     => 'ACS Progresul Gaesti U13',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S.M Fieni U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 19,
				'gazde'     => 'Kinder 2 Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'CSS Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 19,
				'gazde'     => 'CS Kinder Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Urban Titu U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 20,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'CS Kinder Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 20,
				'gazde'     => 'ACS Urban Titu U13',
				'g_gazde'   => null,
				'oaspeti'   => 'Kinder 2 Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 20,
				'gazde'     => 'CSS Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Progresul Gaesti U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 20,
				'gazde'     => 'C.S.M Fieni U13',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Progresul Gaesti U13 2',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 20,
				'gazde'     => 'A.S. F.C Pucioasa U13',
				'g_gazde'   => null,
				'oaspeti'   => 'AFC Chindia Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 20,
				'gazde'     => 'CSM Flacara Moreni U13',
				'g_gazde'   => null,
				'oaspeti'   => 'Fc Chindia 2 Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 20,
				'gazde'     => 'Grupul Scolar Agricol Nucet U13',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. Olimpicii Ulmi U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 21,
				'gazde'     => 'Grupul Scolar Agricol Nucet U13',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 21,
				'gazde'     => 'A.S. Olimpicii Ulmi U13',
				'g_gazde'   => null,
				'oaspeti'   => 'CSM Flacara Moreni U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 21,
				'gazde'     => 'Fc Chindia 2 Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. F.C Pucioasa U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 21,
				'gazde'     => 'AFC Chindia Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S.M Fieni U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 21,
				'gazde'     => 'ACS Progresul Gaesti U13 2',
				'g_gazde'   => null,
				'oaspeti'   => 'CSS Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 21,
				'gazde'     => 'ACS Progresul Gaesti U13',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Urban Titu U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 21,
				'gazde'     => 'Kinder 2 Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'CS Kinder Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 22,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Kinder 2 Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 22,
				'gazde'     => 'CS Kinder Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Progresul Gaesti U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 22,
				'gazde'     => 'ACS Urban Titu U13',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Progresul Gaesti U13 2',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 22,
				'gazde'     => 'CSS Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'AFC Chindia Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 22,
				'gazde'     => 'C.S.M Fieni U13',
				'g_gazde'   => null,
				'oaspeti'   => 'Fc Chindia 2 Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 22,
				'gazde'     => 'A.S. F.C Pucioasa U13',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. Olimpicii Ulmi U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 22,
				'gazde'     => 'CSM Flacara Moreni U13',
				'g_gazde'   => null,
				'oaspeti'   => 'Grupul Scolar Agricol Nucet U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 23,
				'gazde'     => 'CSM Flacara Moreni U13',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 23,
				'gazde'     => 'Grupul Scolar Agricol Nucet U13',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. F.C Pucioasa U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 23,
				'gazde'     => 'A.S. Olimpicii Ulmi U13',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S.M Fieni U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 23,
				'gazde'     => 'Fc Chindia 2 Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'CSS Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 23,
				'gazde'     => 'AFC Chindia Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Urban Titu U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 23,
				'gazde'     => 'ACS Progresul Gaesti U13 2',
				'g_gazde'   => null,
				'oaspeti'   => 'CS Kinder Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 23,
				'gazde'     => 'ACS Progresul Gaesti U13',
				'g_gazde'   => null,
				'oaspeti'   => 'Kinder 2 Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 24,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Progresul Gaesti U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 24,
				'gazde'     => 'Kinder 2 Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Progresul Gaesti U13 2',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 24,
				'gazde'     => 'CS Kinder Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'AFC Chindia Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 24,
				'gazde'     => 'ACS Urban Titu U13',
				'g_gazde'   => null,
				'oaspeti'   => 'Fc Chindia 2 Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 24,
				'gazde'     => 'CSS Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. Olimpicii Ulmi U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 24,
				'gazde'     => 'C.S.M Fieni U13',
				'g_gazde'   => null,
				'oaspeti'   => 'Grupul Scolar Agricol Nucet U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 24,
				'gazde'     => 'A.S. F.C Pucioasa U13',
				'g_gazde'   => null,
				'oaspeti'   => 'CSM Flacara Moreni U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 25,
				'gazde'     => 'A.S. F.C Pucioasa U13',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 25,
				'gazde'     => 'CSM Flacara Moreni U13',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S.M Fieni U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 25,
				'gazde'     => 'Grupul Scolar Agricol Nucet U13',
				'g_gazde'   => null,
				'oaspeti'   => 'CSS Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 25,
				'gazde'     => 'A.S. Olimpicii Ulmi U13',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Urban Titu U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 25,
				'gazde'     => 'Fc Chindia 2 Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'CS Kinder Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 25,
				'gazde'     => 'AFC Chindia Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'Kinder 2 Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 25,
				'gazde'     => 'ACS Progresul Gaesti U13 2',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Progresul Gaesti U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 26,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Progresul Gaesti U13 2',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 26,
				'gazde'     => 'ACS Progresul Gaesti U13',
				'g_gazde'   => null,
				'oaspeti'   => 'AFC Chindia Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 26,
				'gazde'     => 'Kinder 2 Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'Fc Chindia 2 Targoviste U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 26,
				'gazde'     => 'CS Kinder Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. Olimpicii Ulmi U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 26,
				'gazde'     => 'ACS Urban Titu U13',
				'g_gazde'   => null,
				'oaspeti'   => 'Grupul Scolar Agricol Nucet U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 26,
				'gazde'     => 'CSS Targoviste U13',
				'g_gazde'   => null,
				'oaspeti'   => 'CSM Flacara Moreni U13',
				'g_oaspeti' => null,
			],
			[
				'data'      => null,
				'ora'       => null,
				'liga'      => 7,
				'serie'     => null,
				'etapa'     => 26,
				'gazde'     => 'C.S.M Fieni U13',
				'g_gazde'   => null,
				'oaspeti'   => 'A.S. F.C Pucioasa U13',
				'g_oaspeti' => null,
			]
		];

		Echipe::where('liga', 7)->where('serie', null)->delete();
		foreach ($echipe as $echipa) {
			$adauga = new Echipe;
			$adauga->echipa = trim($echipa['echipa']);
			$adauga->liga   = $echipa['liga'];
			$adauga->serie  = $echipa['serie'];
			$adauga->save();
		}

		Etape::where('liga', 7)->where('serie', null)->delete();
		foreach ($etape as $etapa) {
			$adauga = new Etape;
			$adauga->gazde     = trim($etapa['gazde']);
			$adauga->oaspeti   = trim($etapa['oaspeti']);
			$adauga->g_gazde   = $etapa['g_gazde'];
			$adauga->g_oaspeti = $etapa['g_oaspeti'];
			$adauga->liga      = $etapa['liga'];
			$adauga->serie     = $etapa['serie'];
			$adauga->etapa     = $etapa['etapa'];
			$adauga->data      = $etapa['data'];
			$adauga->ora       = $etapa['ora'];
			$adauga->save();
		}
    }
}
