<?php

use Illuminate\Database\Seeder;
use App\Echipe;
use App\Etape;
use App\ToateEchipele;

class liga_3_serie_1_2019_2020 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $echipe = [  
	      [
	         'echipa' => 'CS Aerostar Bacău'
	      ],[
	         'echipa' => 'ACSM Ceahlăul Piatra Neamţ'
	      ],[
	         'echipa' => 'CSM Bucovina Rădăuţi'
	      ],[
	         'echipa' => 'ACS Suporter Club Oţelul Galaţi'
	      ],[
	         'echipa' => 'ACS Foresta Suceava'
	      ],[
	         'echipa' => 'CSM Focşani 2007'
	      ],[
	         'echipa' => 'FC Ozana Târgu Neamț'
	      ],[
	         'echipa' => 'CS Ştiinţa Miroslava'
	      ],[
	         'echipa' => 'AFC Botoşani 2'
	      ],[
	         'echipa' => 'ACS Şomuz Fălticeni'
	      ],[
	         'echipa' => 'CS Sporting Lieşti'
	      ],[
	         'echipa' => 'ACS Hușana Huși'
	      ],[
	         'echipa' => 'ACS Universitatea Dunărea de Jos Galaţi'
	      ],[
	         'echipa' => 'CSM Bacău'
	      ],[
	         'echipa' => 'ACS KSE Târgu Secuiesc'
	      ],[
	         'echipa' => 'CSM Paşcani'
	      ]
	   ];

		$etape = [
		   [ 
		      "data" => "2019-08-23",
		      "ora" => "18:00",
		      "gazde" => "AFC Botoşani 2",
		      "oaspeti" => "CS Aerostar Bacău",
		      "g_gazde" => 1,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-23",
		      "ora" => "18:00",
		      "gazde" => "FC Ozana Târgu Neamț",
		      "oaspeti" => "CSM Focşani 2007",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-23",
		      "ora" => "18:00",
		      "gazde" => "CSM Bacău",
		      "oaspeti" => "ACS Şomuz Fălticeni",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "ACSM Ceahlăul Piatra Neamţ",
		      "oaspeti" => "CS Ştiinţa Miroslava",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "CSM Paşcani",
		      "oaspeti" => "ACS Suporter Club Oţelul Galaţi",
		      "g_gazde" => 1,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "oaspeti" => "ACS KSE Târgu Secuiesc",
		      "g_gazde" => 0,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "ACS Foresta Suceava",
		      "oaspeti" => "CS Sporting Lieşti",
		      "g_gazde" => 3,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "ACS Hușana Huși",
		      "oaspeti" => "CSM Bucovina Rădăuţi",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-30",
		      "ora" => "18:00",
		      "gazde" => "CS Aerostar Bacău",
		      "oaspeti" => "ACS Şomuz Fălticeni",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-30",
		      "ora" => "18:00",
		      "gazde" => "AFC Botoşani 2",
		      "oaspeti" => "FC Ozana Târgu Neamț",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "CSM Bucovina Rădăuţi",
		      "oaspeti" => "CSM Bacău",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "CS Sporting Lieşti",
		      "oaspeti" => "ACS Hușana Huși",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "ACS KSE Târgu Secuiesc",
		      "oaspeti" => "ACS Foresta Suceava",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "CS Ştiinţa Miroslava",
		      "oaspeti" => "CSM Paşcani",
		      "g_gazde" => 3,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "CSM Focşani 2007",
		      "oaspeti" => "ACSM Ceahlăul Piatra Neamţ",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "19:00",
		      "gazde" => "ACS Suporter Club Oţelul Galaţi",
		      "oaspeti" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-09-06",
		      "ora" => "17:00",
		      "gazde" => "FC Ozana Târgu Neamț",
		      "oaspeti" => "CS Aerostar Bacău",
		      "g_gazde" => 1,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-06",
		      "ora" => "17:00",
		      "gazde" => "CSM Bacău",
		      "oaspeti" => "CS Sporting Lieşti",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "ACSM Ceahlăul Piatra Neamţ",
		      "oaspeti" => "AFC Botoşani 2",
		      "g_gazde" => 4,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "CSM Paşcani",
		      "oaspeti" => "CSM Focşani 2007",
		      "g_gazde" => 0,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "oaspeti" => "CS Ştiinţa Miroslava",
		      "g_gazde" => 2,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "ACS Foresta Suceava",
		      "oaspeti" => "ACS Suporter Club Oţelul Galaţi",
		      "g_gazde" => 3,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "ACS Hușana Huși",
		      "oaspeti" => "ACS KSE Târgu Secuiesc",
		      "g_gazde" => 0,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "ACS Şomuz Fălticeni",
		      "oaspeti" => "CSM Bucovina Rădăuţi",
		      "g_gazde" => 0,
		      "g_oaspeti" => 5,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-13",
		      "ora" => "17:00",
		      "gazde" => "CS Aerostar Bacău",
		      "oaspeti" => "CSM Bucovina Rădăuţi",
		      "g_gazde" => 3,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-13",
		      "ora" => "17:00",
		      "gazde" => "AFC Botoşani 2",
		      "oaspeti" => "CSM Paşcani",
		      "g_gazde" => 4,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-13",
		      "ora" => "17:00",
		      "gazde" => "FC Ozana Târgu Neamț",
		      "oaspeti" => "ACSM Ceahlăul Piatra Neamţ",
		      "g_gazde" => 1,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "CS Sporting Lieşti",
		      "oaspeti" => "ACS Şomuz Fălticeni",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "ACS KSE Târgu Secuiesc",
		      "oaspeti" => "CSM Bacău",
		      "g_gazde" => 0,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "CS Ştiinţa Miroslava",
		      "oaspeti" => "ACS Foresta Suceava",
		      "g_gazde" => 2,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "CSM Focşani 2007",
		      "oaspeti" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "18:00",
		      "gazde" => "ACS Suporter Club Oţelul Galaţi",
		      "oaspeti" => "ACS Hușana Huși",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-20",
		      "ora" => "17:00",
		      "gazde" => "CSM Bacău",
		      "oaspeti" => "ACS Suporter Club Oţelul Galaţi",
		      "g_gazde" => 0,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "ACSM Ceahlăul Piatra Neamţ",
		      "oaspeti" => "CS Aerostar Bacău",
		      "g_gazde" => 0,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "CSM Paşcani",
		      "oaspeti" => "FC Ozana Târgu Neamț",
		      "g_gazde" => 2,
		      "g_oaspeti" => 6,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "oaspeti" => "AFC Botoşani 2",
		      "g_gazde" => 2,
		      "g_oaspeti" => 4,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "ACS Foresta Suceava",
		      "oaspeti" => "CSM Focşani 2007",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "ACS Hușana Huși",
		      "oaspeti" => "CS Ştiinţa Miroslava",
		      "g_gazde" => 3,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "ACS Şomuz Fălticeni",
		      "oaspeti" => "ACS KSE Târgu Secuiesc",
		      "g_gazde" => 2,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "CSM Bucovina Rădăuţi",
		      "oaspeti" => "CS Sporting Lieşti",
		      "g_gazde" => 4,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-27",
		      "ora" => "17:00",
		      "gazde" => "CS Aerostar Bacău",
		      "oaspeti" => "CS Sporting Lieşti",
		      "g_gazde" => 3,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-27",
		      "ora" => "17:00",
		      "gazde" => "AFC Botoşani 2",
		      "oaspeti" => "ACS Foresta Suceava",
		      "g_gazde" => 4,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-27",
		      "ora" => "17:00",
		      "gazde" => "FC Ozana Târgu Neamț",
		      "oaspeti" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-28",
		      "ora" => "16:00",
		      "gazde" => "CSM Focşani 2007",
		      "oaspeti" => "ACS Hușana Huși",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-28",
		      "ora" => "17:00",
		      "gazde" => "ACS KSE Târgu Secuiesc",
		      "oaspeti" => "CSM Bucovina Rădăuţi",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-28",
		      "ora" => "17:00",
		      "gazde" => "CS Ştiinţa Miroslava",
		      "oaspeti" => "CSM Bacău",
		      "g_gazde" => 4,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-28",
		      "ora" => "17:00",
		      "gazde" => "ACSM Ceahlăul Piatra Neamţ",
		      "oaspeti" => "CSM Paşcani",
		      "g_gazde" => 7,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-28",
		      "ora" => "18:00",
		      "gazde" => "ACS Suporter Club Oţelul Galaţi",
		      "oaspeti" => "ACS Şomuz Fălticeni",
		      "g_gazde" => 3,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-10-04",
		      "ora" => "15:00",
		      "gazde" => "CSM Bacău",
		      "oaspeti" => "CSM Focşani 2007",
		      "g_gazde" => 0,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "CSM Paşcani",
		      "oaspeti" => "CS Aerostar Bacău",
		      "g_gazde" => 0,
		      "g_oaspeti" => 7,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "oaspeti" => "ACSM Ceahlăul Piatra Neamţ",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "ACS Foresta Suceava",
		      "oaspeti" => "FC Ozana Târgu Neamț",
		      "g_gazde" => 3,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "ACS Hușana Huși",
		      "oaspeti" => "AFC Botoşani 2",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "ACS Şomuz Fălticeni",
		      "oaspeti" => "CS Ştiinţa Miroslava",
		      "g_gazde" => 0,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "CSM Bucovina Rădăuţi",
		      "oaspeti" => "ACS Suporter Club Oţelul Galaţi",
		      "g_gazde" => 1,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "CS Sporting Lieşti",
		      "oaspeti" => "ACS KSE Târgu Secuiesc",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-11",
		      "ora" => "15:00",
		      "gazde" => "CS Aerostar Bacău",
		      "oaspeti" => "ACS KSE Târgu Secuiesc",
		      "g_gazde" => 5,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-11",
		      "ora" => "15:00",
		      "gazde" => "AFC Botoşani 2",
		      "oaspeti" => "CSM Bacău",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-11",
		      "ora" => "15:00",
		      "gazde" => "FC Ozana Târgu Neamț",
		      "oaspeti" => "ACS Hușana Huși",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-12",
		      "ora" => "15:00",
		      "gazde" => "CS Ştiinţa Miroslava",
		      "oaspeti" => "CSM Bucovina Rădăuţi",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-12",
		      "ora" => "15:00",
		      "gazde" => "CSM Focşani 2007",
		      "oaspeti" => "ACS Şomuz Fălticeni",
		      "g_gazde" => 2,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-12",
		      "ora" => "15:00",
		      "gazde" => "ACSM Ceahlăul Piatra Neamţ",
		      "oaspeti" => "ACS Foresta Suceava",
		      "g_gazde" => 5,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-12",
		      "ora" => "15:00",
		      "gazde" => "CSM Paşcani",
		      "oaspeti" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "g_gazde" => 1,
		      "g_oaspeti" => 4,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-12",
		      "ora" => "17:00",
		      "gazde" => "ACS Suporter Club Oţelul Galaţi",
		      "oaspeti" => "CS Sporting Lieşti",
		      "g_gazde" => 0,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-18",
		      "ora" => "15:00",
		      "gazde" => "CSM Bacău",
		      "oaspeti" => "FC Ozana Târgu Neamț",
		      "g_gazde" => 1,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "oaspeti" => "CS Aerostar Bacău",
		      "g_gazde" => 0,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "ACS Foresta Suceava",
		      "oaspeti" => "CSM Paşcani",
		      "g_gazde" => 10,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "ACS Hușana Huși",
		      "oaspeti" => "ACSM Ceahlăul Piatra Neamţ",
		      "g_gazde" => 0,
		      "g_oaspeti" => 4,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "ACS Şomuz Fălticeni",
		      "oaspeti" => "AFC Botoşani 2",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "CSM Bucovina Rădăuţi",
		      "oaspeti" => "CSM Focşani 2007",
		      "g_gazde" => 4,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "CS Sporting Lieşti",
		      "oaspeti" => "CS Ştiinţa Miroslava",
		      "g_gazde" => 1,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "ACS KSE Târgu Secuiesc",
		      "oaspeti" => "ACS Suporter Club Oţelul Galaţi",
		      "g_gazde" => 3,
		      "g_oaspeti" => 4,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-25",
		      "ora" => "15:00",
		      "gazde" => "CS Aerostar Bacău",
		      "oaspeti" => "ACS Suporter Club Oţelul Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-25",
		      "ora" => "15:00",
		      "gazde" => "AFC Botoşani 2",
		      "oaspeti" => "CSM Bucovina Rădăuţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-25",
		      "ora" => "15:00",
		      "gazde" => "FC Ozana Târgu Neamț",
		      "oaspeti" => "ACS Şomuz Fălticeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-26",
		      "ora" => "14:00",
		      "gazde" => "ACSM Ceahlăul Piatra Neamţ",
		      "oaspeti" => "CSM Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "CS Ştiinţa Miroslava",
		      "oaspeti" => "ACS KSE Târgu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "CSM Focşani 2007",
		      "oaspeti" => "CS Sporting Lieşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "CSM Paşcani",
		      "oaspeti" => "ACS Hușana Huși",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "oaspeti" => "ACS Foresta Suceava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-11-01",
		      "ora" => "14:00",
		      "gazde" => "CSM Bacău",
		      "oaspeti" => "CSM Paşcani",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "ACS Hușana Huși",
		      "oaspeti" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "ACS Şomuz Fălticeni",
		      "oaspeti" => "ACSM Ceahlăul Piatra Neamţ",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "CSM Bucovina Rădăuţi",
		      "oaspeti" => "FC Ozana Târgu Neamț",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "CS Sporting Lieşti",
		      "oaspeti" => "AFC Botoşani 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "ACS KSE Târgu Secuiesc",
		      "oaspeti" => "CSM Focşani 2007",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "ACS Suporter Club Oţelul Galaţi",
		      "oaspeti" => "CS Ştiinţa Miroslava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-03",
		      "ora" => "14:00",
		      "gazde" => "ACS Foresta Suceava",
		      "oaspeti" => "CS Aerostar Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "CS Aerostar Bacău",
		      "oaspeti" => "CS Ştiinţa Miroslava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "CSM Focşani 2007",
		      "oaspeti" => "ACS Suporter Club Oţelul Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "AFC Botoşani 2",
		      "oaspeti" => "ACS KSE Târgu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "FC Ozana Târgu Neamț",
		      "oaspeti" => "CS Sporting Lieşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "ACSM Ceahlăul Piatra Neamţ",
		      "oaspeti" => "CSM Bucovina Rădăuţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "CSM Paşcani",
		      "oaspeti" => "ACS Şomuz Fălticeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "oaspeti" => "CSM Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "ACS Foresta Suceava",
		      "oaspeti" => "ACS Hușana Huși",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "ACS Hușana Huși",
		      "oaspeti" => "CS Aerostar Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "CSM Bacău",
		      "oaspeti" => "ACS Foresta Suceava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "ACS Şomuz Fălticeni",
		      "oaspeti" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "CSM Bucovina Rădăuţi",
		      "oaspeti" => "CSM Paşcani",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "CS Sporting Lieşti",
		      "oaspeti" => "ACSM Ceahlăul Piatra Neamţ",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "ACS KSE Târgu Secuiesc",
		      "oaspeti" => "FC Ozana Târgu Neamț",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "ACS Suporter Club Oţelul Galaţi",
		      "oaspeti" => "AFC Botoşani 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "CS Ştiinţa Miroslava",
		      "oaspeti" => "CSM Focşani 2007",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "CS Aerostar Bacău",
		      "oaspeti" => "CSM Focşani 2007",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "AFC Botoşani 2",
		      "oaspeti" => "CS Ştiinţa Miroslava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "FC Ozana Târgu Neamț",
		      "oaspeti" => "ACS Suporter Club Oţelul Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "ACSM Ceahlăul Piatra Neamţ",
		      "oaspeti" => "ACS KSE Târgu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "CSM Paşcani",
		      "oaspeti" => "CS Sporting Lieşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "oaspeti" => "CSM Bucovina Rădăuţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "ACS Foresta Suceava",
		      "oaspeti" => "ACS Şomuz Fălticeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "ACS Hușana Huși",
		      "oaspeti" => "CSM Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "CSM Bacău",
		      "oaspeti" => "CS Aerostar Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "ACS Şomuz Fălticeni",
		      "oaspeti" => "ACS Hușana Huși",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "CSM Bucovina Rădăuţi",
		      "oaspeti" => "ACS Foresta Suceava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "CS Sporting Lieşti",
		      "oaspeti" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "ACS KSE Târgu Secuiesc",
		      "oaspeti" => "CSM Paşcani",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "ACS Suporter Club Oţelul Galaţi",
		      "oaspeti" => "ACSM Ceahlăul Piatra Neamţ",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "CS Ştiinţa Miroslava",
		      "oaspeti" => "FC Ozana Târgu Neamț",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "CSM Focşani 2007",
		      "oaspeti" => "AFC Botoşani 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "CS Aerostar Bacău",
		      "oaspeti" => "AFC Botoşani 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "CSM Focşani 2007",
		      "oaspeti" => "FC Ozana Târgu Neamț",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "CS Ştiinţa Miroslava",
		      "oaspeti" => "ACSM Ceahlăul Piatra Neamţ",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "ACS Suporter Club Oţelul Galaţi",
		      "oaspeti" => "CSM Paşcani",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "ACS KSE Târgu Secuiesc",
		      "oaspeti" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "CS Sporting Lieşti",
		      "oaspeti" => "ACS Foresta Suceava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "CSM Bucovina Rădăuţi",
		      "oaspeti" => "ACS Hușana Huși",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "ACS Şomuz Fălticeni",
		      "oaspeti" => "CSM Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "ACS Şomuz Fălticeni",
		      "oaspeti" => "CS Aerostar Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "CSM Bacău",
		      "oaspeti" => "CSM Bucovina Rădăuţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "ACS Hușana Huși",
		      "oaspeti" => "CS Sporting Lieşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "ACS Foresta Suceava",
		      "oaspeti" => "ACS KSE Târgu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "oaspeti" => "ACS Suporter Club Oţelul Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "CSM Paşcani",
		      "oaspeti" => "CS Ştiinţa Miroslava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "ACSM Ceahlăul Piatra Neamţ",
		      "oaspeti" => "CSM Focşani 2007",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "FC Ozana Târgu Neamț",
		      "oaspeti" => "AFC Botoşani 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "CS Aerostar Bacău",
		      "oaspeti" => "FC Ozana Târgu Neamț",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "AFC Botoşani 2",
		      "oaspeti" => "ACSM Ceahlăul Piatra Neamţ",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "CSM Focşani 2007",
		      "oaspeti" => "CSM Paşcani",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "CS Ştiinţa Miroslava",
		      "oaspeti" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "ACS Suporter Club Oţelul Galaţi",
		      "oaspeti" => "ACS Foresta Suceava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "ACS KSE Târgu Secuiesc",
		      "oaspeti" => "ACS Hușana Huși",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "CS Sporting Lieşti",
		      "oaspeti" => "CSM Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "CSM Bucovina Rădăuţi",
		      "oaspeti" => "ACS Şomuz Fălticeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "CSM Bucovina Rădăuţi",
		      "oaspeti" => "CS Aerostar Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "ACS Şomuz Fălticeni",
		      "oaspeti" => "CS Sporting Lieşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "CSM Bacău",
		      "oaspeti" => "ACS KSE Târgu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "ACS Hușana Huși",
		      "oaspeti" => "ACS Suporter Club Oţelul Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "ACS Foresta Suceava",
		      "oaspeti" => "CS Ştiinţa Miroslava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "oaspeti" => "CSM Focşani 2007",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "CSM Paşcani",
		      "oaspeti" => "AFC Botoşani 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "ACSM Ceahlăul Piatra Neamţ",
		      "oaspeti" => "FC Ozana Târgu Neamț",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "CS Aerostar Bacău",
		      "oaspeti" => "ACSM Ceahlăul Piatra Neamţ",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "FC Ozana Târgu Neamț",
		      "oaspeti" => "CSM Paşcani",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "AFC Botoşani 2",
		      "oaspeti" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "CSM Focşani 2007",
		      "oaspeti" => "ACS Foresta Suceava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "CS Ştiinţa Miroslava",
		      "oaspeti" => "ACS Hușana Huși",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "ACS Suporter Club Oţelul Galaţi",
		      "oaspeti" => "CSM Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "ACS KSE Târgu Secuiesc",
		      "oaspeti" => "ACS Şomuz Fălticeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "CS Sporting Lieşti",
		      "oaspeti" => "CSM Bucovina Rădăuţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "CS Sporting Lieşti",
		      "oaspeti" => "CS Aerostar Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "CSM Bucovina Rădăuţi",
		      "oaspeti" => "ACS KSE Târgu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "ACS Şomuz Fălticeni",
		      "oaspeti" => "ACS Suporter Club Oţelul Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "CSM Bacău",
		      "oaspeti" => "CS Ştiinţa Miroslava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "ACS Hușana Huși",
		      "oaspeti" => "CSM Focşani 2007",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "ACS Foresta Suceava",
		      "oaspeti" => "AFC Botoşani 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "oaspeti" => "FC Ozana Târgu Neamț",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "CSM Paşcani",
		      "oaspeti" => "ACSM Ceahlăul Piatra Neamţ",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "CS Aerostar Bacău",
		      "oaspeti" => "CSM Paşcani",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "ACSM Ceahlăul Piatra Neamţ",
		      "oaspeti" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "FC Ozana Târgu Neamț",
		      "oaspeti" => "ACS Foresta Suceava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "AFC Botoşani 2",
		      "oaspeti" => "ACS Hușana Huși",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "CSM Focşani 2007",
		      "oaspeti" => "CSM Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "CS Ştiinţa Miroslava",
		      "oaspeti" => "ACS Şomuz Fălticeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "ACS Suporter Club Oţelul Galaţi",
		      "oaspeti" => "CSM Bucovina Rădăuţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "ACS KSE Târgu Secuiesc",
		      "oaspeti" => "CS Sporting Lieşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "ACS KSE Târgu Secuiesc",
		      "oaspeti" => "CS Aerostar Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "CS Sporting Lieşti",
		      "oaspeti" => "ACS Suporter Club Oţelul Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "CSM Bucovina Rădăuţi",
		      "oaspeti" => "CS Ştiinţa Miroslava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "ACS Şomuz Fălticeni",
		      "oaspeti" => "CSM Focşani 2007",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "CSM Bacău",
		      "oaspeti" => "AFC Botoşani 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "ACS Hușana Huși",
		      "oaspeti" => "FC Ozana Târgu Neamț",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "ACS Foresta Suceava",
		      "oaspeti" => "ACSM Ceahlăul Piatra Neamţ",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "oaspeti" => "CSM Paşcani",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "CS Aerostar Bacău",
		      "oaspeti" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "CSM Paşcani",
		      "oaspeti" => "ACS Foresta Suceava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "ACSM Ceahlăul Piatra Neamţ",
		      "oaspeti" => "ACS Hușana Huși",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "FC Ozana Târgu Neamț",
		      "oaspeti" => "CSM Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "AFC Botoşani 2",
		      "oaspeti" => "ACS Şomuz Fălticeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "CSM Focşani 2007",
		      "oaspeti" => "CSM Bucovina Rădăuţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "CS Ştiinţa Miroslava",
		      "oaspeti" => "CS Sporting Lieşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "ACS Suporter Club Oţelul Galaţi",
		      "oaspeti" => "ACS KSE Târgu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "ACS Suporter Club Oţelul Galaţi",
		      "oaspeti" => "CS Aerostar Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "ACS KSE Târgu Secuiesc",
		      "oaspeti" => "CS Ştiinţa Miroslava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "CS Sporting Lieşti",
		      "oaspeti" => "CSM Focşani 2007",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "CSM Bucovina Rădăuţi",
		      "oaspeti" => "AFC Botoşani 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "ACS Şomuz Fălticeni",
		      "oaspeti" => "FC Ozana Târgu Neamț",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "CSM Bacău",
		      "oaspeti" => "ACSM Ceahlăul Piatra Neamţ",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "ACS Hușana Huși",
		      "oaspeti" => "CSM Paşcani",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "ACS Foresta Suceava",
		      "oaspeti" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "CS Aerostar Bacău",
		      "oaspeti" => "ACS Foresta Suceava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "oaspeti" => "ACS Hușana Huși",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "CSM Paşcani",
		      "oaspeti" => "CSM Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "ACSM Ceahlăul Piatra Neamţ",
		      "oaspeti" => "ACS Şomuz Fălticeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "FC Ozana Târgu Neamț",
		      "oaspeti" => "CSM Bucovina Rădăuţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "AFC Botoşani 2",
		      "oaspeti" => "CS Sporting Lieşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "CSM Focşani 2007",
		      "oaspeti" => "ACS KSE Târgu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "CS Ştiinţa Miroslava",
		      "oaspeti" => "ACS Suporter Club Oţelul Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "CS Ştiinţa Miroslava",
		      "oaspeti" => "CS Aerostar Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "ACS Suporter Club Oţelul Galaţi",
		      "oaspeti" => "CSM Focşani 2007",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "ACS KSE Târgu Secuiesc",
		      "oaspeti" => "AFC Botoşani 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "CS Sporting Lieşti",
		      "oaspeti" => "FC Ozana Târgu Neamț",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "CSM Bucovina Rădăuţi",
		      "oaspeti" => "ACSM Ceahlăul Piatra Neamţ",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "ACS Şomuz Fălticeni",
		      "oaspeti" => "CSM Paşcani",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "CSM Bacău",
		      "oaspeti" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "ACS Hușana Huși",
		      "oaspeti" => "ACS Foresta Suceava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "CS Aerostar Bacău",
		      "oaspeti" => "ACS Hușana Huși",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "ACS Foresta Suceava",
		      "oaspeti" => "CSM Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "oaspeti" => "ACS Şomuz Fălticeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "CSM Paşcani",
		      "oaspeti" => "CSM Bucovina Rădăuţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "ACSM Ceahlăul Piatra Neamţ",
		      "oaspeti" => "CS Sporting Lieşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "FC Ozana Târgu Neamț",
		      "oaspeti" => "ACS KSE Târgu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "AFC Botoşani 2",
		      "oaspeti" => "ACS Suporter Club Oţelul Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "CSM Focşani 2007",
		      "oaspeti" => "CS Ştiinţa Miroslava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "CSM Focşani 2007",
		      "oaspeti" => "CS Aerostar Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "CS Ştiinţa Miroslava",
		      "oaspeti" => "AFC Botoşani 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "ACS Suporter Club Oţelul Galaţi",
		      "oaspeti" => "FC Ozana Târgu Neamț",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "ACS KSE Târgu Secuiesc",
		      "oaspeti" => "ACSM Ceahlăul Piatra Neamţ",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "CS Sporting Lieşti",
		      "oaspeti" => "CSM Paşcani",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "CSM Bucovina Rădăuţi",
		      "oaspeti" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "ACS Şomuz Fălticeni",
		      "oaspeti" => "ACS Foresta Suceava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "CSM Bacău",
		      "oaspeti" => "ACS Hușana Huși",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "CS Aerostar Bacău",
		      "oaspeti" => "CSM Bacău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "ACS Hușana Huși",
		      "oaspeti" => "ACS Şomuz Fălticeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "ACS Foresta Suceava",
		      "oaspeti" => "CSM Bucovina Rădăuţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "ACS Universitatea Dunărea de Jos Galaţi",
		      "oaspeti" => "CS Sporting Lieşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "CSM Paşcani",
		      "oaspeti" => "ACS KSE Târgu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "ACSM Ceahlăul Piatra Neamţ",
		      "oaspeti" => "ACS Suporter Club Oţelul Galaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "FC Ozana Târgu Neamț",
		      "oaspeti" => "CS Ştiinţa Miroslava",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "AFC Botoşani 2",
		      "oaspeti" => "CSM Focşani 2007",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 1,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ]
		];

		// foreach ($echipe as $echipa) {
		// 	$adauga = new ToateEchipele;
		// 	$adauga->team = trim($echipa['echipa']);
		// 	$adauga->save();

			// $e = ToateEchipele::where('team', trim($echipa['echipa']))->first();

			// $clasament = new Echipe;
			// $clasament->echipa_id = $e->id;
			// $clasament->liga = 3;
			// $clasament->serie = 1;
			// $clasament->save();
		// }


		Etape::where('liga', 3)->where('serie', 1)->where('sezon', '2019/2020')->delete();

		foreach ($etape as $etapa) {
			$gazde = ToateEchipele::where('team', trim($etapa['gazde']))->first();
			$oaspeti = ToateEchipele::where('team', trim($etapa['oaspeti']))->first();

			$adauga = new Etape;
			$adauga->gazde_id   = $gazde['id'];
			$adauga->oaspeti_id = $oaspeti['id'];
			$adauga->g_gazde    = $etapa['g_gazde'];
			$adauga->g_oaspeti  = $etapa['g_oaspeti'];
			$adauga->liga       = $etapa['liga'];
			$adauga->serie      = $etapa['serie'];
			$adauga->etapa      = $etapa['etapa'];
			$adauga->data       = $etapa['data'];
			$adauga->ora        = $etapa['ora'];
			$adauga->sezon      = $etapa['sezon'];
			$adauga->save();
		}
    }
}
