<?php

use Illuminate\Database\Seeder;
use App\Echipe;
use App\Etape;

class liga_6_nord extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $echipe = [
			[
				'echipa' => 'Gloria 2018 Bucsani',
				'liga'   => 6,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Olimpicii Ulmi 3',
				'liga'   => 6,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Fortis Valea Lunga',
				'liga'   => 6,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Comertul 2014 Viisoara',
				'liga'   => 6,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Vointa Valea Voievozilor',
				'liga'   => 6,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Viitorul Pietrari',
				'liga'   => 6,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Gaz Metan Vladeni',
				'liga'   => 6,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Unirea Ogrea',
				'liga'   => 6,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Varcolacii Comisani',
				'liga'   => 6,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Muscelul Valeni',
				'liga'   => 6,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Victoria Vacaresti 2018',
				'liga'   => 6,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Rapid Gemenea',
				'liga'   => 6,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Victoria Vacaresti 2017',
				'liga'   => 6,
				'serie'  => 'NORD',
			],[
				'echipa' => 'STA',
				'liga'   => 6,
				'serie'  => 'NORD',
			]
		];

		$etape = [
			[
				'data'      => '02-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 1,
				'gazde'     => 'Viitorul Pietrari',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '02-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 1,
				'gazde'     => 'Comertul 2014 Viisoara',
				'g_gazde'   => 3,
				'oaspeti'   => 'Victoria Vacaresti 2018',
				'g_oaspeti' => 0,
			],[
				'data'      => '02-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 1,
				'gazde'     => 'Gaz Metan Vladeni',
				'g_gazde'   => 2,
				'oaspeti'   => 'Vointa Valea Voievozilor',
				'g_oaspeti' => 0,
			],[
				'data'      => '02-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 1,
				'gazde'     => 'Varcolacii Comisani',
				'g_gazde'   => 3,
				'oaspeti'   => 'Olimpicii Ulmi 3',
				'g_oaspeti' => 0,
			],[
				'data'      => '02-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 1,
				'gazde'     => 'Gloria 2018 Bucsani',
				'g_gazde'   => 6,
				'oaspeti'   => 'Unirea Ogrea',
				'g_oaspeti' => 3,
			],[
				'data'      => '02-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 1,
				'gazde'     => 'Victoria Vacaresti 2017',
				'g_gazde'   => null,
				'oaspeti'   => 'Fortis Valea Lunga',
				'g_oaspeti' => null,
			],[
				'data'      => '02-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 1,
				'gazde'     => 'Rapid Gemenea',
				'g_gazde'   => 2,
				'oaspeti'   => 'Muscelul Valeni',
				'g_oaspeti' => 5,
			],[
				'data'      => '09-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 2,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Muscelul Valeni',
				'g_oaspeti' => null,
			],[
				'data'      => '09-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 2,
				'gazde'     => 'Fortis Valea Lunga',
				'g_gazde'   => 8,
				'oaspeti'   => 'Rapid Gemenea',
				'g_oaspeti' => 1,
			],[
				'data'      => '09-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 2,
				'gazde'     => 'Unirea Ogrea',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2017',
				'g_oaspeti' => null,
			],[
				'data'      => '09-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 2,
				'gazde'     => 'Olimpicii Ulmi 3',
				'g_gazde'   => 3,
				'oaspeti'   => 'Gloria 2018 Bucsani',
				'g_oaspeti' => 1,
			],[
				'data'      => '09-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 2,
				'gazde'     => 'Vointa Valea Voievozilor',
				'g_gazde'   => 5,
				'oaspeti'   => 'Varcolacii Comisani',
				'g_oaspeti' => 2,
			],[
				'data'      => '09-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 2,
				'gazde'     => 'Victoria Vacaresti 2018',
				'g_gazde'   => 4,
				'oaspeti'   => 'Gaz Metan Vladeni',
				'g_oaspeti' => 1,
			],[
				'data'      => '09-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 2,
				'gazde'     => 'Viitorul Pietrari',
				'g_gazde'   => 3,
				'oaspeti'   => 'Comertul 2014 Viisoara',
				'g_oaspeti' => 0,
			],[
				'data'      => '16-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 3,
				'gazde'     => 'Comertul 2014 Viisoara',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '16-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 3,
				'gazde'     => 'Gaz Metan Vladeni',
				'g_gazde'   => 0,
				'oaspeti'   => 'Viitorul Pietrari',
				'g_oaspeti' => 0,
			],[
				'data'      => '16-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 3,
				'gazde'     => 'Varcolacii Comisani',
				'g_gazde'   => 1,
				'oaspeti'   => 'Victoria Vacaresti 2018',
				'g_oaspeti' => 0,
			],[
				'data'      => '16-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 3,
				'gazde'     => 'Gloria 2018 Bucsani',
				'g_gazde'   => 7,
				'oaspeti'   => 'Vointa Valea Voievozilor',
				'g_oaspeti' => 1,
			],[
				'data'      => '16-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 3,
				'gazde'     => 'Victoria Vacaresti 2017',
				'g_gazde'   => 1,
				'oaspeti'   => 'Olimpicii Ulmi 3',
				'g_oaspeti' => 3,
			],[
				'data'      => '16-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 3,
				'gazde'     => 'Rapid Gemenea',
				'g_gazde'   => 2,
				'oaspeti'   => 'Unirea Ogrea',
				'g_oaspeti' => 3,
			],[
				'data'      => '16-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 3,
				'gazde'     => 'Muscelul Valeni',
				'g_gazde'   => 1,
				'oaspeti'   => 'Fortis Valea Lunga',
				'g_oaspeti' => 3,
			],[
				'data'      => '23-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 4,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Fortis Valea Lunga',
				'g_oaspeti' => null,
			],[
				'data'      => '23-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 4,
				'gazde'     => 'Unirea Ogrea',
				'g_gazde'   => 4,
				'oaspeti'   => 'Muscelul Valeni',
				'g_oaspeti' => 1,
			],[
				'data'      => '23-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 4,
				'gazde'     => 'Olimpicii Ulmi 3',
				'g_gazde'   => 4,
				'oaspeti'   => 'Rapid Gemenea',
				'g_oaspeti' => 2,
			],[
				'data'      => '23-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 4,
				'gazde'     => 'Vointa Valea Voievozilor',
				'g_gazde'   => 4,
				'oaspeti'   => 'Victoria Vacaresti 2017',
				'g_oaspeti' => 0,
			],[
				'data'      => '23-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 4,
				'gazde'     => 'Victoria Vacaresti 2018',
				'g_gazde'   => 2,
				'oaspeti'   => 'Gloria 2018 Bucsani',
				'g_oaspeti' => 5,
			],[
				'data'      => '23-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 4,
				'gazde'     => 'Viitorul Pietrari',
				'g_gazde'   => 2,
				'oaspeti'   => 'Varcolacii Comisani',
				'g_oaspeti' => 1,
			],[
				'data'      => '23-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 4,
				'gazde'     => 'Comertul 2014 Viisoara',
				'g_gazde'   => 3,
				'oaspeti'   => 'Gaz Metan Vladeni',
				'g_oaspeti' => 1,
			],[
				'data'      => '30-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 5,
				'gazde'     => 'Gaz Metan Vladeni',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '30-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 5,
				'gazde'     => 'Varcolacii Comisani',
				'g_gazde'   => 1,
				'oaspeti'   => 'Comertul 2014 Viisoara',
				'g_oaspeti' => 2,
			],[
				'data'      => '30-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 5,
				'gazde'     => 'Gloria 2018 Bucsani',
				'g_gazde'   => 3,
				'oaspeti'   => 'Viitorul Pietrari',
				'g_oaspeti' => 1,
			],[
				'data'      => '30-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 5,
				'gazde'     => 'Victoria Vacaresti 2017',
				'g_gazde'   => 1,
				'oaspeti'   => 'Victoria Vacaresti 2018',
				'g_oaspeti' => 2,
			],[
				'data'      => '30-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 5,
				'gazde'     => 'Rapid Gemenea',
				'g_gazde'   => 1,
				'oaspeti'   => 'Vointa Valea Voievozilor',
				'g_oaspeti' => 0,
			],[
				'data'      => '30-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 5,
				'gazde'     => 'Muscelul Valeni',
				'g_gazde'   => 1,
				'oaspeti'   => 'Olimpicii Ulmi 3',
				'g_oaspeti' => 3,
			],[
				'data'      => '30-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 5,
				'gazde'     => 'Fortis Valea Lunga',
				'g_gazde'   => 3,
				'oaspeti'   => 'Unirea Ogrea',
				'g_oaspeti' => 0,
			],[
				'data'      => '07-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 6,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Ogrea',
				'g_oaspeti' => null,
			],[
				'data'      => '07-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 6,
				'gazde'     => 'Olimpicii Ulmi 3',
				'g_gazde'   => 4,
				'oaspeti'   => 'Fortis Valea Lunga',
				'g_oaspeti' => 1,
			],[
				'data'      => '07-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 6,
				'gazde'     => 'Vointa Valea Voievozilor',
				'g_gazde'   => 5,
				'oaspeti'   => 'Muscelul Valeni',
				'g_oaspeti' => 2,
			],[
				'data'      => '07-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 6,
				'gazde'     => 'Victoria Vacaresti 2018',
				'g_gazde'   => 7,
				'oaspeti'   => 'Rapid Gemenea',
				'g_oaspeti' => 0,
			],[
				'data'      => '07-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 6,
				'gazde'     => 'Viitorul Pietrari',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2017',
				'g_oaspeti' => null,
			],[
				'data'      => '07-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 6,
				'gazde'     => 'Comertul 2014 Viisoara',
				'g_gazde'   => 2,
				'oaspeti'   => 'Gloria 2018 Bucsani',
				'g_oaspeti' => 4,
			],[
				'data'      => '07-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 6,
				'gazde'     => 'Gaz Metan Vladeni',
				'g_gazde'   => 1,
				'oaspeti'   => 'Varcolacii Comisani',
				'g_oaspeti' => 1,
			],[
				'data'      => '14-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 7,
				'gazde'     => 'Varcolacii Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '14-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 7,
				'gazde'     => 'Gloria 2018 Bucsani',
				'g_gazde'   => 6,
				'oaspeti'   => 'Gaz Metan Vladeni',
				'g_oaspeti' => 0,
			],[
				'data'      => '14-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 7,
				'gazde'     => 'Victoria Vacaresti 2017',
				'g_gazde'   => 2,
				'oaspeti'   => 'Comertul 2014 Viisoara',
				'g_oaspeti' => 2,
			],[
				'data'      => '14-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 7,
				'gazde'     => 'Rapid Gemenea',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Pietrari',
				'g_oaspeti' => null,
			],[
				'data'      => '14-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 7,
				'gazde'     => 'Muscelul Valeni',
				'g_gazde'   => 5,
				'oaspeti'   => 'Victoria Vacaresti 2018',
				'g_oaspeti' => 2,
			],[
				'data'      => '14-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 7,
				'gazde'     => 'Fortis Valea Lunga',
				'g_gazde'   => 2,
				'oaspeti'   => 'Vointa Valea Voievozilor',
				'g_oaspeti' => 1,
			],[
				'data'      => '14-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 7,
				'gazde'     => 'Unirea Ogrea',
				'g_gazde'   => 2,
				'oaspeti'   => 'Olimpicii Ulmi 3',
				'g_oaspeti' => 2,
			],[
				'data'      => '21-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 8,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii Ulmi 3',
				'g_oaspeti' => null,
			],[
				'data'      => '21-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 8,
				'gazde'     => 'Vointa Valea Voievozilor',
				'g_gazde'   => 2,
				'oaspeti'   => 'Unirea Ogrea',
				'g_oaspeti' => 1,
			],[
				'data'      => '21-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 8,
				'gazde'     => 'Victoria Vacaresti 2018',
				'g_gazde'   => 2,
				'oaspeti'   => 'Fortis Valea Lunga',
				'g_oaspeti' => 2,
			],[
				'data'      => '21-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 8,
				'gazde'     => 'Viitorul Pietrari',
				'g_gazde'   => 4,
				'oaspeti'   => 'Muscelul Valeni',
				'g_oaspeti' => 2,
			],[
				'data'      => '21-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 8,
				'gazde'     => 'Comertul 2014 Viisoara',
				'g_gazde'   => 6,
				'oaspeti'   => 'Rapid Gemenea',
				'g_oaspeti' => 2,
			],[
				'data'      => '21-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 8,
				'gazde'     => 'Gaz Metan Vladeni',
				'g_gazde'   => 2,
				'oaspeti'   => 'Victoria Vacaresti 2017',
				'g_oaspeti' => 0,
			],[
				'data'      => '21-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 8,
				'gazde'     => 'Varcolacii Comisani',
				'g_gazde'   => 2,
				'oaspeti'   => 'Gloria 2018 Bucsani',
				'g_oaspeti' => 4,
			],[
				'data'      => '28-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 9,
				'gazde'     => 'Gloria 2018 Bucsani',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 9,
				'gazde'     => 'Victoria Vacaresti 2017',
				'g_gazde'   => null,
				'oaspeti'   => 'Varcolacii Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 9,
				'gazde'     => 'Rapid Gemenea',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Vladeni',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 9,
				'gazde'     => 'Muscelul Valeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Comertul 2014 Viisoara',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 9,
				'gazde'     => 'Fortis Valea Lunga',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Pietrari',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 9,
				'gazde'     => 'Unirea Ogrea',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2018',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 9,
				'gazde'     => 'Olimpicii Ulmi 3',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Valea Voievozilor',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 10,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Valea Voievozilor',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 10,
				'gazde'     => 'Victoria Vacaresti 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii Ulmi 3',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 10,
				'gazde'     => 'Viitorul Pietrari',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Ogrea',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 10,
				'gazde'     => 'Comertul 2014 Viisoara',
				'g_gazde'   => null,
				'oaspeti'   => 'Fortis Valea Lunga',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 10,
				'gazde'     => 'Gaz Metan Vladeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Muscelul Valeni',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 10,
				'gazde'     => 'Varcolacii Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Rapid Gemenea',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 10,
				'gazde'     => 'Gloria 2018 Bucsani',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2017',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 11,
				'gazde'     => 'Victoria Vacaresti 2017',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 11,
				'gazde'     => 'Rapid Gemenea',
				'g_gazde'   => null,
				'oaspeti'   => 'Gloria 2018 Bucsani',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 11,
				'gazde'     => 'Muscelul Valeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Varcolacii Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 11,
				'gazde'     => 'Fortis Valea Lunga',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Vladeni',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 11,
				'gazde'     => 'Unirea Ogrea',
				'g_gazde'   => null,
				'oaspeti'   => 'Comertul 2014 Viisoara',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 11,
				'gazde'     => 'Olimpicii Ulmi 3',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Pietrari',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 11,
				'gazde'     => 'Vointa Valea Voievozilor',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2018',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 12,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2018',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 12,
				'gazde'     => 'Viitorul Pietrari',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Valea Voievozilor',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 12,
				'gazde'     => 'Comertul 2014 Viisoara',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii Ulmi 3',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 12,
				'gazde'     => 'Gaz Metan Vladeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Ogrea',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 12,
				'gazde'     => 'Varcolacii Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Fortis Valea Lunga',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 12,
				'gazde'     => 'Gloria 2018 Bucsani',
				'g_gazde'   => null,
				'oaspeti'   => 'Muscelul Valeni',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 12,
				'gazde'     => 'Victoria Vacaresti 2017',
				'g_gazde'   => null,
				'oaspeti'   => 'Rapid Gemenea',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 13,
				'gazde'     => 'Rapid Gemenea',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 13,
				'gazde'     => 'Muscelul Valeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2017',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 13,
				'gazde'     => 'Fortis Valea Lunga',
				'g_gazde'   => null,
				'oaspeti'   => 'Gloria 2018 Bucsani',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 13,
				'gazde'     => 'Unirea Ogrea',
				'g_gazde'   => null,
				'oaspeti'   => 'Varcolacii Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 13,
				'gazde'     => 'Olimpicii Ulmi 3',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Vladeni',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 13,
				'gazde'     => 'Vointa Valea Voievozilor',
				'g_gazde'   => null,
				'oaspeti'   => 'Comertul 2014 Viisoara',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 13,
				'gazde'     => 'Victoria Vacaresti 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Pietrari',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 14,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Pietrari',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 14,
				'gazde'     => 'Victoria Vacaresti 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'Comertul 2014 Viisoara',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 14,
				'gazde'     => 'Vointa Valea Voievozilor',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Vladeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 14,
				'gazde'     => 'Olimpicii Ulmi 3',
				'g_gazde'   => null,
				'oaspeti'   => 'Varcolacii Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 14,
				'gazde'     => 'Unirea Ogrea',
				'g_gazde'   => null,
				'oaspeti'   => 'Gloria 2018 Bucsani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 14,
				'gazde'     => 'Fortis Valea Lunga',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2017',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 14,
				'gazde'     => 'Muscelul Valeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Rapid Gemenea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 15,
				'gazde'     => 'Muscelul Valeni',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 15,
				'gazde'     => 'Rapid Gemenea',
				'g_gazde'   => null,
				'oaspeti'   => 'Fortis Valea Lunga',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 15,
				'gazde'     => 'Victoria Vacaresti 2017',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Ogrea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 15,
				'gazde'     => 'Gloria 2018 Bucsani',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii Ulmi 3',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 15,
				'gazde'     => 'Varcolacii Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Valea Voievozilor',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 15,
				'gazde'     => 'Gaz Metan Vladeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2018',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 15,
				'gazde'     => 'Comertul 2014 Viisoara',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Pietrari',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 16,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Comertul 2014 Viisoara',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 16,
				'gazde'     => 'Viitorul Pietrari',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Vladeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 16,
				'gazde'     => 'Victoria Vacaresti 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'Varcolacii Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 16,
				'gazde'     => 'Vointa Valea Voievozilor',
				'g_gazde'   => null,
				'oaspeti'   => 'Gloria 2018 Bucsani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 16,
				'gazde'     => 'Olimpicii Ulmi 3',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2017',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 16,
				'gazde'     => 'Unirea Ogrea',
				'g_gazde'   => null,
				'oaspeti'   => 'Rapid Gemenea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 16,
				'gazde'     => 'Fortis Valea Lunga',
				'g_gazde'   => null,
				'oaspeti'   => 'Muscelul Valeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 17,
				'gazde'     => 'Fortis Valea Lunga',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 17,
				'gazde'     => 'Muscelul Valeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Ogrea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 17,
				'gazde'     => 'Rapid Gemenea',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii Ulmi 3',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 17,
				'gazde'     => 'Victoria Vacaresti 2017',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Valea Voievozilor',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 17,
				'gazde'     => 'Gloria 2018 Bucsani',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2018',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 17,
				'gazde'     => 'Varcolacii Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Pietrari',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 17,
				'gazde'     => 'Gaz Metan Vladeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Comertul 2014 Viisoara',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 18,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Vladeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 18,
				'gazde'     => 'Comertul 2014 Viisoara',
				'g_gazde'   => null,
				'oaspeti'   => 'Varcolacii Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 18,
				'gazde'     => 'Viitorul Pietrari',
				'g_gazde'   => null,
				'oaspeti'   => 'Gloria 2018 Bucsani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 18,
				'gazde'     => 'Victoria Vacaresti 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2017',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 18,
				'gazde'     => 'Vointa Valea Voievozilor',
				'g_gazde'   => null,
				'oaspeti'   => 'Rapid Gemenea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 18,
				'gazde'     => 'Olimpicii Ulmi 3',
				'g_gazde'   => null,
				'oaspeti'   => 'Muscelul Valeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 18,
				'gazde'     => 'Unirea Ogrea',
				'g_gazde'   => null,
				'oaspeti'   => 'Fortis Valea Lunga',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 19,
				'gazde'     => 'Unirea Ogrea',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 19,
				'gazde'     => 'Fortis Valea Lunga',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii Ulmi 3',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 19,
				'gazde'     => 'Muscelul Valeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Valea Voievozilor',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 19,
				'gazde'     => 'Rapid Gemenea',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2018',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 19,
				'gazde'     => 'Victoria Vacaresti 2017',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Pietrari',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 19,
				'gazde'     => 'Gloria 2018 Bucsani',
				'g_gazde'   => null,
				'oaspeti'   => 'Comertul 2014 Viisoara',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 19,
				'gazde'     => 'Varcolacii Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Vladeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 20,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Varcolacii Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 20,
				'gazde'     => 'Gaz Metan Vladeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Gloria 2018 Bucsani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 20,
				'gazde'     => 'Comertul 2014 Viisoara',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2017',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 20,
				'gazde'     => 'Viitorul Pietrari',
				'g_gazde'   => null,
				'oaspeti'   => 'Rapid Gemenea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 20,
				'gazde'     => 'Victoria Vacaresti 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'Muscelul Valeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 20,
				'gazde'     => 'Vointa Valea Voievozilor',
				'g_gazde'   => null,
				'oaspeti'   => 'Fortis Valea Lunga',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 20,
				'gazde'     => 'Olimpicii Ulmi 3',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Ogrea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 21,
				'gazde'     => 'Olimpicii Ulmi 3',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 21,
				'gazde'     => 'Unirea Ogrea',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Valea Voievozilor',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 21,
				'gazde'     => 'Fortis Valea Lunga',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2018',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 21,
				'gazde'     => 'Muscelul Valeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Pietrari',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 21,
				'gazde'     => 'Rapid Gemenea',
				'g_gazde'   => null,
				'oaspeti'   => 'Comertul 2014 Viisoara',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 21,
				'gazde'     => 'Victoria Vacaresti 2017',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Vladeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 21,
				'gazde'     => 'Gloria 2018 Bucsani',
				'g_gazde'   => null,
				'oaspeti'   => 'Varcolacii Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 22,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Gloria 2018 Bucsani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 22,
				'gazde'     => 'Varcolacii Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2017',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 22,
				'gazde'     => 'Gaz Metan Vladeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Rapid Gemenea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 22,
				'gazde'     => 'Comertul 2014 Viisoara',
				'g_gazde'   => null,
				'oaspeti'   => 'Muscelul Valeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 22,
				'gazde'     => 'Viitorul Pietrari',
				'g_gazde'   => null,
				'oaspeti'   => 'Fortis Valea Lunga',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 22,
				'gazde'     => 'Victoria Vacaresti 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Ogrea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 22,
				'gazde'     => 'Vointa Valea Voievozilor',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii Ulmi 3',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 23,
				'gazde'     => 'Vointa Valea Voievozilor',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 23,
				'gazde'     => 'Olimpicii Ulmi 3',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2018',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 23,
				'gazde'     => 'Unirea Ogrea',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Pietrari',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 23,
				'gazde'     => 'Fortis Valea Lunga',
				'g_gazde'   => null,
				'oaspeti'   => 'Comertul 2014 Viisoara',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 23,
				'gazde'     => 'Muscelul Valeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Vladeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 23,
				'gazde'     => 'Rapid Gemenea',
				'g_gazde'   => null,
				'oaspeti'   => 'Varcolacii Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 23,
				'gazde'     => 'Victoria Vacaresti 2017',
				'g_gazde'   => null,
				'oaspeti'   => 'Gloria 2018 Bucsani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 24,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2017',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 24,
				'gazde'     => 'Gloria 2018 Bucsani',
				'g_gazde'   => null,
				'oaspeti'   => 'Rapid Gemenea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 24,
				'gazde'     => 'Varcolacii Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Muscelul Valeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 24,
				'gazde'     => 'Gaz Metan Vladeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Fortis Valea Lunga',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 24,
				'gazde'     => 'Comertul 2014 Viisoara',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Ogrea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 24,
				'gazde'     => 'Viitorul Pietrari',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii Ulmi 3',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 24,
				'gazde'     => 'Victoria Vacaresti 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Valea Voievozilor',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 25,
				'gazde'     => 'Victoria Vacaresti 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 25,
				'gazde'     => 'Vointa Valea Voievozilor',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Pietrari',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 25,
				'gazde'     => 'Olimpicii Ulmi 3',
				'g_gazde'   => null,
				'oaspeti'   => 'Comertul 2014 Viisoara',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 25,
				'gazde'     => 'Unirea Ogrea',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Vladeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 25,
				'gazde'     => 'Fortis Valea Lunga',
				'g_gazde'   => null,
				'oaspeti'   => 'Varcolacii Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 25,
				'gazde'     => 'Muscelul Valeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Gloria 2018 Bucsani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 25,
				'gazde'     => 'Rapid Gemenea',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2017',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 26,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Rapid Gemenea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 26,
				'gazde'     => 'Victoria Vacaresti 2017',
				'g_gazde'   => null,
				'oaspeti'   => 'Muscelul Valeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 26,
				'gazde'     => 'Gloria 2018 Bucsani',
				'g_gazde'   => null,
				'oaspeti'   => 'Fortis Valea Lunga',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 26,
				'gazde'     => 'Varcolacii Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Ogrea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 26,
				'gazde'     => 'Gaz Metan Vladeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii Ulmi 3',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 26,
				'gazde'     => 'Comertul 2014 Viisoara',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Valea Voievozilor',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'NORD',
				'etapa'     => 26,
				'gazde'     => 'Viitorul Pietrari',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Vacaresti 2018',
				'g_oaspeti' => null,
			]
		];

		Echipe::where('liga', 6)->where('serie', 'NORD')->delete();
		foreach ($echipe as $echipa) {
			$adauga = new Echipe;
			$adauga->echipa = trim($echipa['echipa']);
			$adauga->liga   = $echipa['liga'];
			$adauga->serie  = $echipa['serie'];
			$adauga->save();
		}

		Etape::where('liga', 6)->where('serie', 'NORD')->delete();
		foreach ($etape as $etapa) {
			$adauga = new Etape;
			$adauga->gazde     = trim($etapa['gazde']);
			$adauga->oaspeti   = trim($etapa['oaspeti']);
			$adauga->g_gazde   = $etapa['g_gazde'];
			$adauga->g_oaspeti = $etapa['g_oaspeti'];
			$adauga->liga      = $etapa['liga'];
			$adauga->serie     = $etapa['serie'];
			$adauga->etapa     = $etapa['etapa'];
			$adauga->data      = $etapa['data'] != NULL ? DateTime::createFromFormat('d-m-Y', ($etapa['data']))->format('Y-m-d') : NULL;
			$adauga->ora       = $etapa['ora'];
			$adauga->save();
		}
    }
}
