<?php

use Illuminate\Database\Seeder;
use App\Echipe;
use App\Etape;

class liga_3_seria_3_2019_2020 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $echipe = [	
			[
				'echipa' => 'CSM Slatina',
				'liga'   => 3,
				'serie'  => 3,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'AFC Progresul 1944 Spartac',
				'liga'   => 3,
				'serie'  => 3,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'ACS Vediţa Coloneşti M.S',
				'liga'   => 3,
				'serie'  => 3,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'CSM Alexandria',
				'liga'   => 3,
				'serie'  => 3,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'SC FC Voluntari SA 2',
				'liga'   => 3,
				'serie'  => 3,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'CS Sporting Roşiori 2008',
				'liga'   => 3,
				'serie'  => 3,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'ACS SR Municipal Braşov',
				'liga'   => 3,
				'serie'  => 3,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'ACS Unirea Bascov',
				'liga'   => 3,
				'serie'  => 3,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'Universitatea Craiova 2',
				'liga'   => 3,
				'serie'  => 3,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'CS Blejoi',
				'liga'   => 3,
				'serie'  => 3,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'ACS Olimpic Cetate Râşnov',
				'liga'   => 3,
				'serie'  => 3,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'CSM Flacăra Moreni',
				'liga'   => 3,
				'serie'  => 3,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'AFC Astra 2',
				'liga'   => 3,
				'serie'  => 3,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'CS Baloteşti',
				'liga'   => 3,
				'serie'  => 3,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'AS FC Pucioasa',
				'liga'   => 3,
				'serie'  => 3,
				'sezon'  => '2019/2020'
			],[
				'echipa' => 'ACS Tractorul Cetate',
				'liga'   => 3,
				'serie'  => 3,
				'sezon'  => '2019/2020'
			]
		];

		$etape = [
			[
				'data'      => '2019-08-23',
				'ora'       => '18:00',
				'gazde'     => 'CSM Slatina',
				'oaspeti'   => 'CS Sporting Roşiori 2008',
				'g_gazde'   => 1,
				'g_oaspeti' => 0,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 1,
			],[
				'data'      => '2019-08-23',
				'ora'       => '18:00',
				'gazde'     => 'CSM Flacăra Moreni',
				'oaspeti'   => 'ACS Olimpic Cetate Râşnov',
				'g_gazde'   => 1,
				'g_oaspeti' => 1,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 1,
			],[
				'data'      => '2019-08-23',
				'ora'       => '18:00',
				'gazde'     => 'SC FC Voluntari SA 2',
				'oaspeti'   => 'ACS Unirea Bascov',
				'g_gazde'   => 3,
				'g_oaspeti' => 3,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 1,
			],[
				'data'      => '2019-08-23',
				'ora'       => '18:00',
				'gazde'     => 'Universitatea Craiova 2',
				'oaspeti'   => 'CS Baloteşti',
				'g_gazde'   => 1,
				'g_oaspeti' => 1,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 1,
			],[
				'data'      => '2019-08-24',
				'ora'       => '18:00',
				'gazde'     => 'ACS SR Municipal Braşov',
				'oaspeti'   => 'AFC Progresul 1944 Spartac',
				'g_gazde'   => 0,
				'g_oaspeti' => 3,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 1,
			],[
				'data'      => '2019-08-24',
				'ora'       => '18:00',
				'gazde'     => 'AS FC Pucioasa',
				'oaspeti'   => 'CSM Alexandria',
				'g_gazde'   => 0,
				'g_oaspeti' => 2,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 1,
			],[
				'data'      => '2019-08-24',
				'ora'       => '18:00',
				'gazde'     => 'CS Blejoi',
				'oaspeti'   => 'AFC Astra 2',
				'g_gazde'   => 1,
				'g_oaspeti' => 1,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 1,
			],[
				'data'      => '2019-08-24',
				'ora'       => '18:00',
				'gazde'     => 'ACS Vediţa Coloneşti M.S',
				'oaspeti'   => 'ACS Tractorul Cetate',
				'g_gazde'   => 1,
				'g_oaspeti' => 0,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 1,
			],[
				'data'      => '2019-08-30',
				'ora'       => '18:00',
				'gazde'     => 'ACS Unirea Bascov',
				'oaspeti'   => 'Universitatea Craiova 2',
				'g_gazde'   => 2,
				'g_oaspeti' => 2,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 2,
			],[
				'data'      => '2019-08-30',
				'ora'       => '18:00',
				'gazde'     => 'AFC Astra 2',
				'oaspeti'   => 'ACS Vediţa Coloneşti M.S',
				'g_gazde'   => 0,
				'g_oaspeti' => 1,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 2,
			],[
				'data'      => '2019-08-30',
				'ora'       => '18:00',
				'gazde'     => 'CSM Alexandria',
				'oaspeti'   => 'CS Blejoi',
				'g_gazde'   => 0,
				'g_oaspeti' => 0,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 2,
			],[
				'data'      => '2019-08-31',
				'ora'       => '18:00',
				'gazde'     => 'AFC Progresul 1944 Spartac',
				'oaspeti'   => 'CS Baloteşti',
				'g_gazde'   => 2,
				'g_oaspeti' => 0,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 2,
			],[
				'data'      => '2019-08-31',
				'ora'       => '18:00',
				'gazde'     => 'ACS Olimpic Cetate Râşnov',
				'oaspeti'   => 'SC FC Voluntari SA 2',
				'g_gazde'   => 1,
				'g_oaspeti' => 2,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 2,
			],[
				'data'      => '2019-08-31',
				'ora'       => '18:00',
				'gazde'     => 'CS Sporting Roşiori 2008',
				'oaspeti'   => 'CSM Flacăra Moreni',
				'g_gazde'   => 1,
				'g_oaspeti' => 0,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 2,
			],[
				'data'      => '2019-08-31',
				'ora'       => '18:00',
				'gazde'     => 'ACS Tractorul Cetate',
				'oaspeti'   => 'CSM Slatina',
				'g_gazde'   => 0,
				'g_oaspeti' => 8,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 2,
			],[
				'data'      => '2019-08-31',
				'ora'       => '18:00',
				'gazde'     => 'ACS SR Municipal Braşov',
				'oaspeti'   => 'AS FC Pucioasa',
				'g_gazde'   => 1,
				'g_oaspeti' => 0,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 2,
			],[
				'data'      => '2019-09-07',
				'ora'       => '17:00',
				'gazde'     => 'AS FC Pucioasa',
				'oaspeti'   => 'AFC Progresul 1944 Spartac',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 3,
			],[
				'data'      => '2019-09-07',
				'ora'       => '17:00',
				'gazde'     => 'CS Blejoi',
				'oaspeti'   => 'ACS SR Municipal Braşov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 3,
			],[
				'data'      => '2019-09-07',
				'ora'       => '17:00',
				'gazde'     => 'ACS Vediţa Coloneşti M.S',
				'oaspeti'   => 'CSM Alexandria',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 3,
			],[
				'data'      => '2019-09-07',
				'ora'       => '17:00',
				'gazde'     => 'CSM Slatina',
				'oaspeti'   => 'AFC Astra 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 3,
			],[
				'data'      => '2019-09-07',
				'ora'       => '17:00',
				'gazde'     => 'CSM Flacăra Moreni',
				'oaspeti'   => 'ACS Tractorul Cetate',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 3,
			],[
				'data'      => '2019-09-07',
				'ora'       => '17:00',
				'gazde'     => 'SC FC Voluntari SA 2',
				'oaspeti'   => 'CS Sporting Roşiori 2008',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 3,
			],[
				'data'      => '2019-09-07',
				'ora'       => '17:00',
				'gazde'     => 'Universitatea Craiova 2',
				'oaspeti'   => 'ACS Olimpic Cetate Râşnov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 3,
			],[
				'data'      => '2019-09-07',
				'ora'       => '17:00',
				'gazde'     => 'CS Baloteşti',
				'oaspeti'   => 'ACS Unirea Bascov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 3,
			],[
				'data'      => '2019-09-14',
				'ora'       => '17:00',
				'gazde'     => 'AFC Progresul 1944 Spartac',
				'oaspeti'   => 'ACS Unirea Bascov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 4,
			],[
				'data'      => '2019-09-14',
				'ora'       => '17:00',
				'gazde'     => 'ACS Olimpic Cetate Râşnov',
				'oaspeti'   => 'CS Baloteşti',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 4,
			],[
				'data'      => '2019-09-14',
				'ora'       => '17:00',
				'gazde'     => 'CS Sporting Roşiori 2008',
				'oaspeti'   => 'Universitatea Craiova 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 4,
			],[
				'data'      => '2019-09-14',
				'ora'       => '17:00',
				'gazde'     => 'ACS Tractorul Cetate',
				'oaspeti'   => 'SC FC Voluntari SA 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 4,
			],[
				'data'      => '2019-09-14',
				'ora'       => '17:00',
				'gazde'     => 'AFC Astra 2',
				'oaspeti'   => 'CSM Flacăra Moreni',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 4,
			],[
				'data'      => '2019-09-14',
				'ora'       => '17:00',
				'gazde'     => 'CSM Alexandria',
				'oaspeti'   => 'CSM Slatina',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 4,
			],[
				'data'      => '2019-09-14',
				'ora'       => '17:00',
				'gazde'     => 'ACS SR Municipal Braşov',
				'oaspeti'   => 'ACS Vediţa Coloneşti M.S',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 4,
			],[
				'data'      => '2019-09-14',
				'ora'       => '17:00',
				'gazde'     => 'AS FC Pucioasa',
				'oaspeti'   => 'CS Blejoi',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 4,
			],[
				'data'      => '2019-09-21',
				'ora'       => '17:00',
				'gazde'     => 'CS Blejoi',
				'oaspeti'   => 'AFC Progresul 1944 Spartac',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 5,
			],[
				'data'      => '2019-09-21',
				'ora'       => '17:00',
				'gazde'     => 'ACS Vediţa Coloneşti M.S',
				'oaspeti'   => 'AS FC Pucioasa',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 5,
			],[
				'data'      => '2019-09-21',
				'ora'       => '17:00',
				'gazde'     => 'CSM Slatina',
				'oaspeti'   => 'ACS SR Municipal Braşov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 5,
			],[
				'data'      => '2019-09-21',
				'ora'       => '17:00',
				'gazde'     => 'CSM Flacăra Moreni',
				'oaspeti'   => 'CSM Alexandria',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 5,
			],[
				'data'      => '2019-09-21',
				'ora'       => '17:00',
				'gazde'     => 'SC FC Voluntari SA 2',
				'oaspeti'   => 'AFC Astra 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 5,
			],[
				'data'      => '2019-09-21',
				'ora'       => '17:00',
				'gazde'     => 'Universitatea Craiova 2',
				'oaspeti'   => 'ACS Tractorul Cetate',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 5,
			],[
				'data'      => '2019-09-21',
				'ora'       => '17:00',
				'gazde'     => 'CS Baloteşti',
				'oaspeti'   => 'CS Sporting Roşiori 2008',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 5,
			],[
				'data'      => '2019-09-21',
				'ora'       => '17:00',
				'gazde'     => 'ACS Unirea Bascov',
				'oaspeti'   => 'ACS Olimpic Cetate Râşnov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 5,
			],[
				'data'      => '2019-09-28',
				'ora'       => '17:00',
				'gazde'     => 'AFC Progresul 1944 Spartac',
				'oaspeti'   => 'ACS Olimpic Cetate Râşnov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 6,
			],[
				'data'      => '2019-09-28',
				'ora'       => '17:00',
				'gazde'     => 'CS Sporting Roşiori 2008',
				'oaspeti'   => 'ACS Unirea Bascov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 6,
			],[
				'data'      => '2019-09-28',
				'ora'       => '17:00',
				'gazde'     => 'ACS Tractorul Cetate',
				'oaspeti'   => 'CS Baloteşti',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 6,
			],[
				'data'      => '2019-09-28',
				'ora'       => '17:00',
				'gazde'     => 'AFC Astra 2',
				'oaspeti'   => 'Universitatea Craiova 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 6,
			],[
				'data'      => '2019-09-28',
				'ora'       => '17:00',
				'gazde'     => 'CSM Alexandria',
				'oaspeti'   => 'SC FC Voluntari SA 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 6,
			],[
				'data'      => '2019-09-28',
				'ora'       => '17:00',
				'gazde'     => 'ACS SR Municipal Braşov',
				'oaspeti'   => 'CSM Flacăra Moreni',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 6,
			],[
				'data'      => '2019-09-28',
				'ora'       => '17:00',
				'gazde'     => 'AS FC Pucioasa',
				'oaspeti'   => 'CSM Slatina',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 6,
			],[
				'data'      => '2019-09-28',
				'ora'       => '17:00',
				'gazde'     => 'CS Blejoi',
				'oaspeti'   => 'ACS Vediţa Coloneşti M.S',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 6,
			],[
				'data'      => '2019-10-05',
				'ora'       => '15:00',
				'gazde'     => 'ACS Vediţa Coloneşti M.S',
				'oaspeti'   => 'AFC Progresul 1944 Spartac',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 7,
			],[
				'data'      => '2019-10-05',
				'ora'       => '15:00',
				'gazde'     => 'CSM Slatina',
				'oaspeti'   => 'CS Blejoi',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 7,
			],[
				'data'      => '2019-10-05',
				'ora'       => '15:00',
				'gazde'     => 'CSM Flacăra Moreni',
				'oaspeti'   => 'AS FC Pucioasa',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 7,
			],[
				'data'      => '2019-10-05',
				'ora'       => '15:00',
				'gazde'     => 'SC FC Voluntari SA 2',
				'oaspeti'   => 'ACS SR Municipal Braşov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 7,
			],[
				'data'      => '2019-10-05',
				'ora'       => '15:00',
				'gazde'     => 'Universitatea Craiova 2',
				'oaspeti'   => 'CSM Alexandria',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 7,
			],[
				'data'      => '2019-10-05',
				'ora'       => '15:00',
				'gazde'     => 'CS Baloteşti',
				'oaspeti'   => 'AFC Astra 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 7,
			],[
				'data'      => '2019-10-05',
				'ora'       => '15:00',
				'gazde'     => 'ACS Unirea Bascov',
				'oaspeti'   => 'ACS Tractorul Cetate',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 7,
			],[
				'data'      => '2019-10-05',
				'ora'       => '15:00',
				'gazde'     => 'ACS Olimpic Cetate Râşnov',
				'oaspeti'   => 'CS Sporting Roşiori 2008',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 7,
			],[
				'data'      => '2019-10-12',
				'ora'       => '15:00',
				'gazde'     => 'AFC Progresul 1944 Spartac',
				'oaspeti'   => 'CS Sporting Roşiori 2008',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 8,
			],[
				'data'      => '2019-10-12',
				'ora'       => '15:00',
				'gazde'     => 'ACS Tractorul Cetate',
				'oaspeti'   => 'ACS Olimpic Cetate Râşnov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 8,
			],[
				'data'      => '2019-10-12',
				'ora'       => '15:00',
				'gazde'     => 'AFC Astra 2',
				'oaspeti'   => 'ACS Unirea Bascov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 8,
			],[
				'data'      => '2019-10-12',
				'ora'       => '15:00',
				'gazde'     => 'CSM Alexandria',
				'oaspeti'   => 'CS Baloteşti',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 8,
			],[
				'data'      => '2019-10-12',
				'ora'       => '15:00',
				'gazde'     => 'ACS SR Municipal Braşov',
				'oaspeti'   => 'Universitatea Craiova 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 8,
			],[
				'data'      => '2019-10-12',
				'ora'       => '15:00',
				'gazde'     => 'AS FC Pucioasa',
				'oaspeti'   => 'SC FC Voluntari SA 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 8,
			],[
				'data'      => '2019-10-12',
				'ora'       => '15:00',
				'gazde'     => 'CS Blejoi',
				'oaspeti'   => 'CSM Flacăra Moreni',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 8,
			],[
				'data'      => '2019-10-12',
				'ora'       => '15:00',
				'gazde'     => 'ACS Vediţa Coloneşti M.S',
				'oaspeti'   => 'CSM Slatina',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 8,
			],[
				'data'      => '2019-10-19',
				'ora'       => '15:00',
				'gazde'     => 'CSM Slatina',
				'oaspeti'   => 'AFC Progresul 1944 Spartac',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 9,
			],[
				'data'      => '2019-10-19',
				'ora'       => '15:00',
				'gazde'     => 'CSM Flacăra Moreni',
				'oaspeti'   => 'ACS Vediţa Coloneşti M.S',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 9,
			],[
				'data'      => '2019-10-19',
				'ora'       => '15:00',
				'gazde'     => 'SC FC Voluntari SA 2',
				'oaspeti'   => 'CS Blejoi',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 9,
			],[
				'data'      => '2019-10-19',
				'ora'       => '15:00',
				'gazde'     => 'Universitatea Craiova 2',
				'oaspeti'   => 'AS FC Pucioasa',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 9,
			],[
				'data'      => '2019-10-19',
				'ora'       => '15:00',
				'gazde'     => 'CS Baloteşti',
				'oaspeti'   => 'ACS SR Municipal Braşov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 9,
			],[
				'data'      => '2019-10-19',
				'ora'       => '15:00',
				'gazde'     => 'ACS Unirea Bascov',
				'oaspeti'   => 'CSM Alexandria',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 9,
			],[
				'data'      => '2019-10-19',
				'ora'       => '15:00',
				'gazde'     => 'ACS Olimpic Cetate Râşnov',
				'oaspeti'   => 'AFC Astra 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 9,
			],[
				'data'      => '2019-10-19',
				'ora'       => '15:00',
				'gazde'     => 'CS Sporting Roşiori 2008',
				'oaspeti'   => 'ACS Tractorul Cetate',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 9,
			],[
				'data'      => '2019-10-26',
				'ora'       => '15:00',
				'gazde'     => 'AFC Progresul 1944 Spartac',
				'oaspeti'   => 'ACS Tractorul Cetate',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 10,
			],[
				'data'      => '2019-10-26',
				'ora'       => '15:00',
				'gazde'     => 'AFC Astra 2',
				'oaspeti'   => 'CS Sporting Roşiori 2008',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 10,
			],[
				'data'      => '2019-10-26',
				'ora'       => '15:00',
				'gazde'     => 'CSM Alexandria',
				'oaspeti'   => 'ACS Olimpic Cetate Râşnov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 10,
			],[
				'data'      => '2019-10-26',
				'ora'       => '15:00',
				'gazde'     => 'ACS SR Municipal Braşov',
				'oaspeti'   => 'ACS Unirea Bascov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 10,
			],[
				'data'      => '2019-10-26',
				'ora'       => '15:00',
				'gazde'     => 'AS FC Pucioasa',
				'oaspeti'   => 'CS Baloteşti',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 10,
			],[
				'data'      => '2019-10-26',
				'ora'       => '15:00',
				'gazde'     => 'CS Blejoi',
				'oaspeti'   => 'Universitatea Craiova 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 10,
			],[
				'data'      => '2019-10-26',
				'ora'       => '15:00',
				'gazde'     => 'ACS Vediţa Coloneşti M.S',
				'oaspeti'   => 'SC FC Voluntari SA 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 10,
			],[
				'data'      => '2019-10-26',
				'ora'       => '15:00',
				'gazde'     => 'CSM Slatina',
				'oaspeti'   => 'CSM Flacăra Moreni',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 10,
			],[
				'data'      => '2019-11-02',
				'ora'       => '14:00',
				'gazde'     => 'CSM Flacăra Moreni',
				'oaspeti'   => 'AFC Progresul 1944 Spartac',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 11,
			],[
				'data'      => '2019-11-02',
				'ora'       => '14:00',
				'gazde'     => 'SC FC Voluntari SA 2',
				'oaspeti'   => 'CSM Slatina',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 11,
			],[
				'data'      => '2019-11-02',
				'ora'       => '14:00',
				'gazde'     => 'Universitatea Craiova 2',
				'oaspeti'   => 'ACS Vediţa Coloneşti M.S',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 11,
			],[
				'data'      => '2019-11-02',
				'ora'       => '14:00',
				'gazde'     => 'CS Baloteşti',
				'oaspeti'   => 'CS Blejoi',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 11,
			],[
				'data'      => '2019-11-02',
				'ora'       => '14:00',
				'gazde'     => 'ACS Unirea Bascov',
				'oaspeti'   => 'AS FC Pucioasa',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 11,
			],[
				'data'      => '2019-11-02',
				'ora'       => '14:00',
				'gazde'     => 'ACS Olimpic Cetate Râşnov',
				'oaspeti'   => 'ACS SR Municipal Braşov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 11,
			],[
				'data'      => '2019-11-02',
				'ora'       => '14:00',
				'gazde'     => 'CS Sporting Roşiori 2008',
				'oaspeti'   => 'CSM Alexandria',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 11,
			],[
				'data'      => '2019-11-02',
				'ora'       => '14:00',
				'gazde'     => 'ACS Tractorul Cetate',
				'oaspeti'   => 'AFC Astra 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 11,
			],[
				'data'      => '2019-11-09',
				'ora'       => '14:00',
				'gazde'     => 'AFC Progresul 1944 Spartac',
				'oaspeti'   => 'AFC Astra 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 12,
			],[
				'data'      => '2019-11-09',
				'ora'       => '14:00',
				'gazde'     => 'CSM Alexandria',
				'oaspeti'   => 'ACS Tractorul Cetate',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 12,
			],[
				'data'      => '2019-11-09',
				'ora'       => '14:00',
				'gazde'     => 'ACS SR Municipal Braşov',
				'oaspeti'   => 'CS Sporting Roşiori 2008',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 12,
			],[
				'data'      => '2019-11-09',
				'ora'       => '14:00',
				'gazde'     => 'AS FC Pucioasa',
				'oaspeti'   => 'ACS Olimpic Cetate Râşnov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 12,
			],[
				'data'      => '2019-11-09',
				'ora'       => '14:00',
				'gazde'     => 'CS Blejoi',
				'oaspeti'   => 'ACS Unirea Bascov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 12,
			],[
				'data'      => '2019-11-09',
				'ora'       => '14:00',
				'gazde'     => 'ACS Vediţa Coloneşti M.S',
				'oaspeti'   => 'CS Baloteşti',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 12,
			],[
				'data'      => '2019-11-09',
				'ora'       => '14:00',
				'gazde'     => 'CSM Slatina',
				'oaspeti'   => 'Universitatea Craiova 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 12,
			],[
				'data'      => '2019-11-09',
				'ora'       => '14:00',
				'gazde'     => 'CSM Flacăra Moreni',
				'oaspeti'   => 'SC FC Voluntari SA 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 12,
			],[
				'data'      => '2019-11-16',
				'ora'       => '14:00',
				'gazde'     => 'SC FC Voluntari SA 2',
				'oaspeti'   => 'AFC Progresul 1944 Spartac',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 13,
			],[
				'data'      => '2019-11-16',
				'ora'       => '14:00',
				'gazde'     => 'Universitatea Craiova 2',
				'oaspeti'   => 'CSM Flacăra Moreni',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 13,
			],[
				'data'      => '2019-11-16',
				'ora'       => '14:00',
				'gazde'     => 'CS Baloteşti',
				'oaspeti'   => 'CSM Slatina',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 13,
			],[
				'data'      => '2019-11-16',
				'ora'       => '14:00',
				'gazde'     => 'ACS Unirea Bascov',
				'oaspeti'   => 'ACS Vediţa Coloneşti M.S',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 13,
			],[
				'data'      => '2019-11-16',
				'ora'       => '14:00',
				'gazde'     => 'ACS Olimpic Cetate Râşnov',
				'oaspeti'   => 'CS Blejoi',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 13,
			],[
				'data'      => '2019-11-16',
				'ora'       => '14:00',
				'gazde'     => 'CS Sporting Roşiori 2008',
				'oaspeti'   => 'AS FC Pucioasa',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 13,
			],[
				'data'      => '2019-11-16',
				'ora'       => '14:00',
				'gazde'     => 'ACS Tractorul Cetate',
				'oaspeti'   => 'ACS SR Municipal Braşov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 13,
			],[
				'data'      => '2019-11-16',
				'ora'       => '14:00',
				'gazde'     => 'AFC Astra 2',
				'oaspeti'   => 'CSM Alexandria',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 13,
			],[
				'data'      => '2019-11-23',
				'ora'       => '14:00',
				'gazde'     => 'AFC Progresul 1944 Spartac',
				'oaspeti'   => 'CSM Alexandria',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 14,
			],[
				'data'      => '2019-11-23',
				'ora'       => '14:00',
				'gazde'     => 'ACS SR Municipal Braşov',
				'oaspeti'   => 'AFC Astra 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 14,
			],[
				'data'      => '2019-11-23',
				'ora'       => '14:00',
				'gazde'     => 'AS FC Pucioasa',
				'oaspeti'   => 'ACS Tractorul Cetate',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 14,
			],[
				'data'      => '2019-11-23',
				'ora'       => '14:00',
				'gazde'     => 'CS Blejoi',
				'oaspeti'   => 'CS Sporting Roşiori 2008',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 14,
			],[
				'data'      => '2019-11-23',
				'ora'       => '14:00',
				'gazde'     => 'ACS Vediţa Coloneşti M.S',
				'oaspeti'   => 'ACS Olimpic Cetate Râşnov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 14,
			],[
				'data'      => '2019-11-23',
				'ora'       => '14:00',
				'gazde'     => 'CSM Slatina',
				'oaspeti'   => 'ACS Unirea Bascov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 14,
			],[
				'data'      => '2019-11-23',
				'ora'       => '14:00',
				'gazde'     => 'CSM Flacăra Moreni',
				'oaspeti'   => 'CS Baloteşti',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 14,
			],[
				'data'      => '2019-11-23',
				'ora'       => '14:00',
				'gazde'     => 'SC FC Voluntari SA 2',
				'oaspeti'   => 'Universitatea Craiova 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 14,
			],[
				'data'      => '2019-11-30',
				'ora'       => '14:00',
				'gazde'     => 'Universitatea Craiova 2',
				'oaspeti'   => 'AFC Progresul 1944 Spartac',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 15,
			],[
				'data'      => '2019-11-30',
				'ora'       => '14:00',
				'gazde'     => 'CS Baloteşti',
				'oaspeti'   => 'SC FC Voluntari SA 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 15,
			],[
				'data'      => '2019-11-30',
				'ora'       => '14:00',
				'gazde'     => 'ACS Unirea Bascov',
				'oaspeti'   => 'CSM Flacăra Moreni',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 15,
			],[
				'data'      => '2019-11-30',
				'ora'       => '14:00',
				'gazde'     => 'ACS Olimpic Cetate Râşnov',
				'oaspeti'   => 'CSM Slatina',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 15,
			],[
				'data'      => '2019-11-30',
				'ora'       => '14:00',
				'gazde'     => 'CS Sporting Roşiori 2008',
				'oaspeti'   => 'ACS Vediţa Coloneşti M.S',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 15,
			],[
				'data'      => '2019-11-30',
				'ora'       => '14:00',
				'gazde'     => 'ACS Tractorul Cetate',
				'oaspeti'   => 'CS Blejoi',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 15,
			],[
				'data'      => '2019-11-30',
				'ora'       => '14:00',
				'gazde'     => 'AFC Astra 2',
				'oaspeti'   => 'AS FC Pucioasa',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 15,
			],[
				'data'      => '2019-11-30',
				'ora'       => '14:00',
				'gazde'     => 'CSM Alexandria',
				'oaspeti'   => 'ACS SR Municipal Braşov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 15,
			],[
				'data'      => '2020-03-07',
				'ora'       => '15:00',
				'gazde'     => 'AFC Progresul 1944 Spartac',
				'oaspeti'   => 'ACS SR Municipal Braşov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 16,
			],[
				'data'      => '2020-03-07',
				'ora'       => '15:00',
				'gazde'     => 'CSM Alexandria',
				'oaspeti'   => 'AS FC Pucioasa',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 16,
			],[
				'data'      => '2020-03-07',
				'ora'       => '15:00',
				'gazde'     => 'AFC Astra 2',
				'oaspeti'   => 'CS Blejoi',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 16,
			],[
				'data'      => '2020-03-07',
				'ora'       => '15:00',
				'gazde'     => 'ACS Tractorul Cetate',
				'oaspeti'   => 'ACS Vediţa Coloneşti M.S',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 16,
			],[
				'data'      => '2020-03-07',
				'ora'       => '15:00',
				'gazde'     => 'CS Sporting Roşiori 2008',
				'oaspeti'   => 'CSM Slatina',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 16,
			],[
				'data'      => '2020-03-07',
				'ora'       => '15:00',
				'gazde'     => 'ACS Olimpic Cetate Râşnov',
				'oaspeti'   => 'CSM Flacăra Moreni',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 16,
			],[
				'data'      => '2020-03-07',
				'ora'       => '15:00',
				'gazde'     => 'ACS Unirea Bascov',
				'oaspeti'   => 'SC FC Voluntari SA 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 16,
			],[
				'data'      => '2020-03-07',
				'ora'       => '15:00',
				'gazde'     => 'CS Baloteşti',
				'oaspeti'   => 'Universitatea Craiova 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 16,
			],[
				'data'      => '2020-03-14',
				'ora'       => '15:00',
				'gazde'     => 'CS Baloteşti',
				'oaspeti'   => 'AFC Progresul 1944 Spartac',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 17,
			],[
				'data'      => '2020-03-14',
				'ora'       => '15:00',
				'gazde'     => 'Universitatea Craiova 2',
				'oaspeti'   => 'ACS Unirea Bascov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 17,
			],[
				'data'      => '2020-03-14',
				'ora'       => '15:00',
				'gazde'     => 'SC FC Voluntari SA 2',
				'oaspeti'   => 'ACS Olimpic Cetate Râşnov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 17,
			],[
				'data'      => '2020-03-14',
				'ora'       => '15:00',
				'gazde'     => 'CSM Flacăra Moreni',
				'oaspeti'   => 'CS Sporting Roşiori 2008',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 17,
			],[
				'data'      => '2020-03-14',
				'ora'       => '15:00',
				'gazde'     => 'CSM Slatina',
				'oaspeti'   => 'ACS Tractorul Cetate',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 17,
			],[
				'data'      => '2020-03-14',
				'ora'       => '15:00',
				'gazde'     => 'ACS Vediţa Coloneşti M.S',
				'oaspeti'   => 'AFC Astra 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 17,
			],[
				'data'      => '2020-03-14',
				'ora'       => '15:00',
				'gazde'     => 'CS Blejoi',
				'oaspeti'   => 'CSM Alexandria',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 17,
			],[
				'data'      => '2020-03-14',
				'ora'       => '15:00',
				'gazde'     => 'AS FC Pucioasa',
				'oaspeti'   => 'ACS SR Municipal Braşov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 17,
			],[
				'data'      => '2020-03-21',
				'ora'       => '15:00',
				'gazde'     => 'AFC Progresul 1944 Spartac',
				'oaspeti'   => 'AS FC Pucioasa',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 18,
			],[
				'data'      => '2020-03-21',
				'ora'       => '15:00',
				'gazde'     => 'ACS SR Municipal Braşov',
				'oaspeti'   => 'CS Blejoi',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 18,
			],[
				'data'      => '2020-03-21',
				'ora'       => '15:00',
				'gazde'     => 'CSM Alexandria',
				'oaspeti'   => 'ACS Vediţa Coloneşti M.S',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 18,
			],[
				'data'      => '2020-03-21',
				'ora'       => '15:00',
				'gazde'     => 'AFC Astra 2',
				'oaspeti'   => 'CSM Slatina',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 18,
			],[
				'data'      => '2020-03-21',
				'ora'       => '15:00',
				'gazde'     => 'ACS Tractorul Cetate',
				'oaspeti'   => 'CSM Flacăra Moreni',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 18,
			],[
				'data'      => '2020-03-21',
				'ora'       => '15:00',
				'gazde'     => 'CS Sporting Roşiori 2008',
				'oaspeti'   => 'SC FC Voluntari SA 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 18,
			],[
				'data'      => '2020-03-21',
				'ora'       => '15:00',
				'gazde'     => 'ACS Olimpic Cetate Râşnov',
				'oaspeti'   => 'Universitatea Craiova 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 18,
			],[
				'data'      => '2020-03-21',
				'ora'       => '15:00',
				'gazde'     => 'ACS Unirea Bascov',
				'oaspeti'   => 'CS Baloteşti',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 18,
			],[
				'data'      => '2020-03-28',
				'ora'       => '15:00',
				'gazde'     => 'ACS Unirea Bascov',
				'oaspeti'   => 'AFC Progresul 1944 Spartac',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 19,
			],[
				'data'      => '2020-03-28',
				'ora'       => '15:00',
				'gazde'     => 'CS Baloteşti',
				'oaspeti'   => 'ACS Olimpic Cetate Râşnov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 19,
			],[
				'data'      => '2020-03-28',
				'ora'       => '15:00',
				'gazde'     => 'Universitatea Craiova 2',
				'oaspeti'   => 'CS Sporting Roşiori 2008',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 19,
			],[
				'data'      => '2020-03-28',
				'ora'       => '15:00',
				'gazde'     => 'SC FC Voluntari SA 2',
				'oaspeti'   => 'ACS Tractorul Cetate',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 19,
			],[
				'data'      => '2020-03-28',
				'ora'       => '15:00',
				'gazde'     => 'CSM Flacăra Moreni',
				'oaspeti'   => 'AFC Astra 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 19,
			],[
				'data'      => '2020-03-28',
				'ora'       => '15:00',
				'gazde'     => 'CSM Slatina',
				'oaspeti'   => 'CSM Alexandria',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 19,
			],[
				'data'      => '2020-03-28',
				'ora'       => '15:00',
				'gazde'     => 'ACS Vediţa Coloneşti M.S',
				'oaspeti'   => 'ACS SR Municipal Braşov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 19,
			],[
				'data'      => '2020-03-28',
				'ora'       => '15:00',
				'gazde'     => 'CS Blejoi',
				'oaspeti'   => 'AS FC Pucioasa',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 19,
			],[
				'data'      => '2020-04-04',
				'ora'       => '17:00',
				'gazde'     => 'AFC Progresul 1944 Spartac',
				'oaspeti'   => 'CS Blejoi',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 20,
			],[
				'data'      => '2020-04-04',
				'ora'       => '17:00',
				'gazde'     => 'AS FC Pucioasa',
				'oaspeti'   => 'ACS Vediţa Coloneşti M.S',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 20,
			],[
				'data'      => '2020-04-04',
				'ora'       => '17:00',
				'gazde'     => 'ACS SR Municipal Braşov',
				'oaspeti'   => 'CSM Slatina',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 20,
			],[
				'data'      => '2020-04-04',
				'ora'       => '17:00',
				'gazde'     => 'CSM Alexandria',
				'oaspeti'   => 'CSM Flacăra Moreni',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 20,
			],[
				'data'      => '2020-04-04',
				'ora'       => '17:00',
				'gazde'     => 'AFC Astra 2',
				'oaspeti'   => 'SC FC Voluntari SA 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 20,
			],[
				'data'      => '2020-04-04',
				'ora'       => '17:00',
				'gazde'     => 'ACS Tractorul Cetate',
				'oaspeti'   => 'Universitatea Craiova 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 20,
			],[
				'data'      => '2020-04-04',
				'ora'       => '17:00',
				'gazde'     => 'CS Sporting Roşiori 2008',
				'oaspeti'   => 'CS Baloteşti',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 20,
			],[
				'data'      => '2020-04-04',
				'ora'       => '17:00',
				'gazde'     => 'ACS Olimpic Cetate Râşnov',
				'oaspeti'   => 'ACS Unirea Bascov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 20,
			],[
				'data'      => '2020-04-08',
				'ora'       => '17:00',
				'gazde'     => 'ACS Olimpic Cetate Râşnov',
				'oaspeti'   => 'AFC Progresul 1944 Spartac',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 21,
			],[
				'data'      => '2020-04-08',
				'ora'       => '17:00',
				'gazde'     => 'ACS Unirea Bascov',
				'oaspeti'   => 'CS Sporting Roşiori 2008',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 21,
			],[
				'data'      => '2020-04-08',
				'ora'       => '17:00',
				'gazde'     => 'CS Baloteşti',
				'oaspeti'   => 'ACS Tractorul Cetate',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 21,
			],[
				'data'      => '2020-04-08',
				'ora'       => '17:00',
				'gazde'     => 'Universitatea Craiova 2',
				'oaspeti'   => 'AFC Astra 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 21,
			],[
				'data'      => '2020-04-08',
				'ora'       => '17:00',
				'gazde'     => 'SC FC Voluntari SA 2',
				'oaspeti'   => 'CSM Alexandria',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 21,
			],[
				'data'      => '2020-04-08',
				'ora'       => '17:00',
				'gazde'     => 'CSM Flacăra Moreni',
				'oaspeti'   => 'ACS SR Municipal Braşov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 21,
			],[
				'data'      => '2020-04-08',
				'ora'       => '17:00',
				'gazde'     => 'CSM Slatina',
				'oaspeti'   => 'AS FC Pucioasa',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 21,
			],[
				'data'      => '2020-04-08',
				'ora'       => '17:00',
				'gazde'     => 'ACS Vediţa Coloneşti M.S',
				'oaspeti'   => 'CS Blejoi',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 21,
			],[
				'data'      => '2020-04-11',
				'ora'       => '17:00',
				'gazde'     => 'AFC Progresul 1944 Spartac',
				'oaspeti'   => 'ACS Vediţa Coloneşti M.S',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 22,
			],[
				'data'      => '2020-04-11',
				'ora'       => '17:00',
				'gazde'     => 'CS Blejoi',
				'oaspeti'   => 'CSM Slatina',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 22,
			],[
				'data'      => '2020-04-11',
				'ora'       => '17:00',
				'gazde'     => 'AS FC Pucioasa',
				'oaspeti'   => 'CSM Flacăra Moreni',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 22,
			],[
				'data'      => '2020-04-11',
				'ora'       => '17:00',
				'gazde'     => 'ACS SR Municipal Braşov',
				'oaspeti'   => 'SC FC Voluntari SA 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 22,
			],[
				'data'      => '2020-04-11',
				'ora'       => '17:00',
				'gazde'     => 'CSM Alexandria',
				'oaspeti'   => 'Universitatea Craiova 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 22,
			],[
				'data'      => '2020-04-11',
				'ora'       => '17:00',
				'gazde'     => 'AFC Astra 2',
				'oaspeti'   => 'CS Baloteşti',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 22,
			],[
				'data'      => '2020-04-11',
				'ora'       => '17:00',
				'gazde'     => 'ACS Tractorul Cetate',
				'oaspeti'   => 'ACS Unirea Bascov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 22,
			],[
				'data'      => '2020-04-11',
				'ora'       => '17:00',
				'gazde'     => 'CS Sporting Roşiori 2008',
				'oaspeti'   => 'ACS Olimpic Cetate Râşnov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 22,
			],[
				'data'      => '2020-04-17',
				'ora'       => '17:00',
				'gazde'     => 'CS Sporting Roşiori 2008',
				'oaspeti'   => 'AFC Progresul 1944 Spartac',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 23,
			],[
				'data'      => '2020-04-17',
				'ora'       => '17:00',
				'gazde'     => 'ACS Olimpic Cetate Râşnov',
				'oaspeti'   => 'ACS Tractorul Cetate',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 23,
			],[
				'data'      => '2020-04-17',
				'ora'       => '17:00',
				'gazde'     => 'ACS Unirea Bascov',
				'oaspeti'   => 'AFC Astra 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 23,
			],[
				'data'      => '2020-04-17',
				'ora'       => '17:00',
				'gazde'     => 'CS Baloteşti',
				'oaspeti'   => 'CSM Alexandria',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 23,
			],[
				'data'      => '2020-04-17',
				'ora'       => '17:00',
				'gazde'     => 'Universitatea Craiova 2',
				'oaspeti'   => 'ACS SR Municipal Braşov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 23,
			],[
				'data'      => '2020-04-17',
				'ora'       => '17:00',
				'gazde'     => 'SC FC Voluntari SA 2',
				'oaspeti'   => 'AS FC Pucioasa',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 23,
			],[
				'data'      => '2020-04-17',
				'ora'       => '17:00',
				'gazde'     => 'CSM Flacăra Moreni',
				'oaspeti'   => 'CS Blejoi',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 23,
			],[
				'data'      => '2020-04-17',
				'ora'       => '17:00',
				'gazde'     => 'CSM Slatina',
				'oaspeti'   => 'ACS Vediţa Coloneşti M.S',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 23,
			],[
				'data'      => '2020-04-25',
				'ora'       => '17:00',
				'gazde'     => 'AFC Progresul 1944 Spartac',
				'oaspeti'   => 'CSM Slatina',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 24,
			],[
				'data'      => '2020-04-25',
				'ora'       => '17:00',
				'gazde'     => 'ACS Vediţa Coloneşti M.S',
				'oaspeti'   => 'CSM Flacăra Moreni',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 24,
			],[
				'data'      => '2020-04-25',
				'ora'       => '17:00',
				'gazde'     => 'CS Blejoi',
				'oaspeti'   => 'SC FC Voluntari SA 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 24,
			],[
				'data'      => '2020-04-25',
				'ora'       => '17:00',
				'gazde'     => 'AS FC Pucioasa',
				'oaspeti'   => 'Universitatea Craiova 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 24,
			],[
				'data'      => '2020-04-25',
				'ora'       => '17:00',
				'gazde'     => 'ACS SR Municipal Braşov',
				'oaspeti'   => 'CS Baloteşti',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 24,
			],[
				'data'      => '2020-04-25',
				'ora'       => '17:00',
				'gazde'     => 'CSM Alexandria',
				'oaspeti'   => 'ACS Unirea Bascov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 24,
			],[
				'data'      => '2020-04-25',
				'ora'       => '17:00',
				'gazde'     => 'AFC Astra 2',
				'oaspeti'   => 'ACS Olimpic Cetate Râşnov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 24,
			],[
				'data'      => '2020-04-25',
				'ora'       => '17:00',
				'gazde'     => 'ACS Tractorul Cetate',
				'oaspeti'   => 'CS Sporting Roşiori 2008',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 24,
			],[
				'data'      => '2020-05-02',
				'ora'       => '18:00',
				'gazde'     => 'ACS Tractorul Cetate',
				'oaspeti'   => 'AFC Progresul 1944 Spartac',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 25,
			],[
				'data'      => '2020-05-02',
				'ora'       => '18:00',
				'gazde'     => 'CS Sporting Roşiori 2008',
				'oaspeti'   => 'AFC Astra 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 25,
			],[
				'data'      => '2020-05-02',
				'ora'       => '18:00',
				'gazde'     => 'ACS Olimpic Cetate Râşnov',
				'oaspeti'   => 'CSM Alexandria',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 25,
			],[
				'data'      => '2020-05-02',
				'ora'       => '18:00',
				'gazde'     => 'ACS Unirea Bascov',
				'oaspeti'   => 'ACS SR Municipal Braşov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 25,
			],[
				'data'      => '2020-05-02',
				'ora'       => '18:00',
				'gazde'     => 'CS Baloteşti',
				'oaspeti'   => 'AS FC Pucioasa',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 25,
			],[
				'data'      => '2020-05-02',
				'ora'       => '18:00',
				'gazde'     => 'Universitatea Craiova 2',
				'oaspeti'   => 'CS Blejoi',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 25,
			],[
				'data'      => '2020-05-02',
				'ora'       => '18:00',
				'gazde'     => 'SC FC Voluntari SA 2',
				'oaspeti'   => 'ACS Vediţa Coloneşti M.S',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 25,
			],[
				'data'      => '2020-05-02',
				'ora'       => '18:00',
				'gazde'     => 'CSM Flacăra Moreni',
				'oaspeti'   => 'CSM Slatina',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 25,
			],[
				'data'      => '2020-05-06',
				'ora'       => '18:00',
				'gazde'     => 'AFC Progresul 1944 Spartac',
				'oaspeti'   => 'CSM Flacăra Moreni',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 26,
			],[
				'data'      => '2020-05-06',
				'ora'       => '18:00',
				'gazde'     => 'CSM Slatina',
				'oaspeti'   => 'SC FC Voluntari SA 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 26,
			],[
				'data'      => '2020-05-06',
				'ora'       => '18:00',
				'gazde'     => 'ACS Vediţa Coloneşti M.S',
				'oaspeti'   => 'Universitatea Craiova 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 26,
			],[
				'data'      => '2020-05-06',
				'ora'       => '18:00',
				'gazde'     => 'CS Blejoi',
				'oaspeti'   => 'CS Baloteşti',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 26,
			],[
				'data'      => '2020-05-06',
				'ora'       => '18:00',
				'gazde'     => 'AS FC Pucioasa',
				'oaspeti'   => 'ACS Unirea Bascov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 26,
			],[
				'data'      => '2020-05-06',
				'ora'       => '18:00',
				'gazde'     => 'ACS SR Municipal Braşov',
				'oaspeti'   => 'ACS Olimpic Cetate Râşnov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 26,
			],[
				'data'      => '2020-05-06',
				'ora'       => '18:00',
				'gazde'     => 'CSM Alexandria',
				'oaspeti'   => 'CS Sporting Roşiori 2008',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 26,
			],[
				'data'      => '2020-05-06',
				'ora'       => '18:00',
				'gazde'     => 'AFC Astra 2',
				'oaspeti'   => 'ACS Tractorul Cetate',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 26,
			],[
				'data'      => '2020-05-09',
				'ora'       => '18:00',
				'gazde'     => 'AFC Astra 2',
				'oaspeti'   => 'AFC Progresul 1944 Spartac',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 27,
			],[
				'data'      => '2020-05-09',
				'ora'       => '18:00',
				'gazde'     => 'ACS Tractorul Cetate',
				'oaspeti'   => 'CSM Alexandria',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 27,
			],[
				'data'      => '2020-05-09',
				'ora'       => '18:00',
				'gazde'     => 'CS Sporting Roşiori 2008',
				'oaspeti'   => 'ACS SR Municipal Braşov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 27,
			],[
				'data'      => '2020-05-09',
				'ora'       => '18:00',
				'gazde'     => 'ACS Olimpic Cetate Râşnov',
				'oaspeti'   => 'AS FC Pucioasa',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 27,
			],[
				'data'      => '2020-05-09',
				'ora'       => '18:00',
				'gazde'     => 'ACS Unirea Bascov',
				'oaspeti'   => 'CS Blejoi',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 27,
			],[
				'data'      => '2020-05-09',
				'ora'       => '18:00',
				'gazde'     => 'CS Baloteşti',
				'oaspeti'   => 'ACS Vediţa Coloneşti M.S',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 27,
			],[
				'data'      => '2020-05-09',
				'ora'       => '18:00',
				'gazde'     => 'Universitatea Craiova 2',
				'oaspeti'   => 'CSM Slatina',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 27,
			],[
				'data'      => '2020-05-09',
				'ora'       => '18:00',
				'gazde'     => 'SC FC Voluntari SA 2',
				'oaspeti'   => 'CSM Flacăra Moreni',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 27,
			],[
				'data'      => '2020-05-16',
				'ora'       => '18:00',
				'gazde'     => 'AFC Progresul 1944 Spartac',
				'oaspeti'   => 'SC FC Voluntari SA 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 28,
			],[
				'data'      => '2020-05-16',
				'ora'       => '18:00',
				'gazde'     => 'CSM Flacăra Moreni',
				'oaspeti'   => 'Universitatea Craiova 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 28,
			],[
				'data'      => '2020-05-16',
				'ora'       => '18:00',
				'gazde'     => 'CSM Slatina',
				'oaspeti'   => 'CS Baloteşti',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 28,
			],[
				'data'      => '2020-05-16',
				'ora'       => '18:00',
				'gazde'     => 'ACS Vediţa Coloneşti M.S',
				'oaspeti'   => 'ACS Unirea Bascov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 28,
			],[
				'data'      => '2020-05-16',
				'ora'       => '18:00',
				'gazde'     => 'CS Blejoi',
				'oaspeti'   => 'ACS Olimpic Cetate Râşnov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 28,
			],[
				'data'      => '2020-05-16',
				'ora'       => '18:00',
				'gazde'     => 'AS FC Pucioasa',
				'oaspeti'   => 'CS Sporting Roşiori 2008',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 28,
			],[
				'data'      => '2020-05-16',
				'ora'       => '18:00',
				'gazde'     => 'ACS SR Municipal Braşov',
				'oaspeti'   => 'ACS Tractorul Cetate',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 28,
			],[
				'data'      => '2020-05-16',
				'ora'       => '18:00',
				'gazde'     => 'CSM Alexandria',
				'oaspeti'   => 'AFC Astra 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 28,
			],[
				'data'      => '2020-05-23',
				'ora'       => '18:00',
				'gazde'     => 'CSM Alexandria',
				'oaspeti'   => 'AFC Progresul 1944 Spartac',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 29,
			],[
				'data'      => '2020-05-23',
				'ora'       => '18:00',
				'gazde'     => 'AFC Astra 2',
				'oaspeti'   => 'ACS SR Municipal Braşov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 29,
			],[
				'data'      => '2020-05-23',
				'ora'       => '18:00',
				'gazde'     => 'ACS Tractorul Cetate',
				'oaspeti'   => 'AS FC Pucioasa',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 29,
			],[
				'data'      => '2020-05-23',
				'ora'       => '18:00',
				'gazde'     => 'CS Sporting Roşiori 2008',
				'oaspeti'   => 'CS Blejoi',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 29,
			],[
				'data'      => '2020-05-23',
				'ora'       => '18:00',
				'gazde'     => 'ACS Olimpic Cetate Râşnov',
				'oaspeti'   => 'ACS Vediţa Coloneşti M.S',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 29,
			],[
				'data'      => '2020-05-23',
				'ora'       => '18:00',
				'gazde'     => 'ACS Unirea Bascov',
				'oaspeti'   => 'CSM Slatina',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 29,
			],[
				'data'      => '2020-05-23',
				'ora'       => '18:00',
				'gazde'     => 'CS Baloteşti',
				'oaspeti'   => 'CSM Flacăra Moreni',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 29,
			],[
				'data'      => '2020-05-23',
				'ora'       => '18:00',
				'gazde'     => 'Universitatea Craiova 2',
				'oaspeti'   => 'SC FC Voluntari SA 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 29,
			],[
				'data'      => '2020-05-30',
				'ora'       => '18:00',
				'gazde'     => 'AFC Progresul 1944 Spartac',
				'oaspeti'   => 'Universitatea Craiova 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 30,
			],[
				'data'      => '2020-05-30',
				'ora'       => '18:00',
				'gazde'     => 'SC FC Voluntari SA 2',
				'oaspeti'   => 'CS Baloteşti',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 30,
			],[
				'data'      => '2020-05-30',
				'ora'       => '18:00',
				'gazde'     => 'CSM Flacăra Moreni',
				'oaspeti'   => 'ACS Unirea Bascov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 30,
			],[
				'data'      => '2020-05-30',
				'ora'       => '18:00',
				'gazde'     => 'CSM Slatina',
				'oaspeti'   => 'ACS Olimpic Cetate Râşnov',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 30,
			],[
				'data'      => '2020-05-30',
				'ora'       => '18:00',
				'gazde'     => 'ACS Vediţa Coloneşti M.S',
				'oaspeti'   => 'CS Sporting Roşiori 2008',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 30,
			],[
				'data'      => '2020-05-30',
				'ora'       => '18:00',
				'gazde'     => 'CS Blejoi',
				'oaspeti'   => 'ACS Tractorul Cetate',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 30,
			],[
				'data'      => '2020-05-30',
				'ora'       => '18:00',
				'gazde'     => 'AS FC Pucioasa',
				'oaspeti'   => 'AFC Astra 2',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 30,
			],[
				'data'      => '2020-05-30',
				'ora'       => '18:00',
				'gazde'     => 'ACS SR Municipal Braşov',
				'oaspeti'   => 'CSM Alexandria',
				'g_gazde'   => null,
				'g_oaspeti' => null,
				'liga'      => 3,
				'serie'     => 3,
				'sezon'     => '2019/2020',
				'etapa'     => 30,
			]
		];

		foreach ($echipe as $echipa) {
			$adauga = new Echipe;
			$adauga->echipa = trim($echipa['echipa']);
			$adauga->liga   = $echipa['liga'];
			$adauga->serie  = $echipa['serie'];
			$adauga->sezon  = $echipa['sezon'];
			$adauga->save();
		}

		/*Etape::where('liga', 5)->where('serie', 'NORD')
								->where('sezon', '2019/2020')
								->delete();*/
		foreach ($etape as $etapa) {
			$adauga = new Etape;
			$adauga->gazde     = trim($etapa['gazde']);
			$adauga->oaspeti   = trim($etapa['oaspeti']);
			$adauga->g_gazde   = $etapa['g_gazde'];
			$adauga->g_oaspeti = $etapa['g_oaspeti'];
			$adauga->liga      = $etapa['liga'];
			$adauga->serie     = $etapa['serie'];
			$adauga->etapa     = $etapa['etapa'];
			$adauga->data      = $etapa['data']/* != NULL ? DateTime::createFromFormat('d-m-Y', ($etapa['data']))->format('Y-m-d') : NULL*/;
			$adauga->ora       = $etapa['ora'];
			$adauga->sezon     = $etapa['sezon'];
			$adauga->save();
		}
    }
}
