<?php

use Illuminate\Database\Seeder;
use App\Echipe;
use App\Etape;

class liga_5_vest extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$echipe = [
			[
				'echipa' => 'Petrolul Rascaieti',
				'liga'   => 5,
				'serie'  => 'VEST',
			], [
				'echipa' => 'Olimpia Morteni',
				'liga'   => 5,
				'serie'  => 'VEST',
			], [
				'echipa' => 'Spicul Jugureni',
				'liga'   => 5,
				'serie'  => 'VEST',
			], [
				'echipa' => 'Dinamo Odaia Turcului',
				'liga'   => 5,
				'serie'  => 'VEST',
			], [
				'echipa' => 'Flacara Zavoiu',
				'liga'   => 5,
				'serie'  => 'VEST',
			], [
				'echipa' => 'Viitorul Straosti',
				'liga'   => 5,
				'serie'  => 'VEST',
			], [
				'echipa' => 'PCM Ungureni',
				'liga'   => 5,
				'serie'  => 'VEST',
			], [
				'echipa' => 'Unirea Cobia',
				'liga'   => 5,
				'serie'  => 'VEST',
			], [
				'echipa' => 'Viitorul Tomsani',
				'liga'   => 5,
				'serie'  => 'VEST',
			], [
				'echipa' => 'Corbii Mari',
				'liga'   => 5,
				'serie'  => 'VEST',
			], [
				'echipa' => 'Viitorul Gaesti',
				'liga'   => 5,
				'serie'  => 'VEST',
			], [
				'echipa' => 'Sportul Mogosani',
				'liga'   => 5,
				'serie'  => 'VEST',
			], [
				'echipa' => 'Flacara Valea Mare',
				'liga'   => 5,
				'serie'  => 'VEST',
			], [
				'echipa' => 'Vointa Ionesti',
				'liga'   => 5,
				'serie'  => 'VEST',
			], [
				'echipa' => 'Olimpia Picior de Munte',
				'liga'   => 5,
				'serie'  => 'VEST',
			], [
				'echipa' => 'Viitorul Odobesti Ziduri',
				'liga'   => 5,
				'serie'  => 'VEST',
			], [
				'echipa' => 'Viitorul Burduca',
				'liga'   => 5,
				'serie'  => 'VEST',
			], [
				'echipa' => 'ACS Urban Titu',
				'liga'   => 5,
				'serie'  => 'VEST',
			]
		];

		$etape = [
			[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 1,
				'gazde'     => 'Petrolul Rascaieti',
				'g_gazde'   => 4,
				'oaspeti'   => 'Olimpia Morteni',
				'g_oaspeti' => 1,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 1,
				'gazde'     => 'Spicul Jugureni',
				'g_gazde'   => 3,
				'oaspeti'   => 'Dinamo Odaia Turcului',
				'g_oaspeti' => 2,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 1,
				'gazde'     => 'Flacara Zavoiu',
				'g_gazde'   => 5,
				'oaspeti'   => 'Viitorul Straosti',
				'g_oaspeti' => 4,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 1,
				'gazde'     => 'PCM Ungureni',
				'g_gazde'   => 5,
				'oaspeti'   => 'Unirea Cobia',
				'g_oaspeti' => 3,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 1,
				'gazde'     => 'Viitorul Tomsani',
				'g_gazde'   => 0,
				'oaspeti'   => 'Corbii Mari',
				'g_oaspeti' => 3,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 1,
				'gazde'     => 'Viitorul Gaesti',
				'g_gazde'   => 2,
				'oaspeti'   => 'Sportul Mogosani',
				'g_oaspeti' => 6,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 1,
				'gazde'     => 'Flacara Valea Mare',
				'g_gazde'   => 8,
				'oaspeti'   => 'Vointa Ionesti',
				'g_oaspeti' => 3,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 1,
				'gazde'     => 'Olimpia Picior de Munte',
				'g_gazde'   => 5,
				'oaspeti'   => 'Viitorul Odobesti Ziduri',
				'g_oaspeti' => 3,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 1,
				'gazde'     => 'Viitorul Burduca',
				'g_gazde'   => 2,
				'oaspeti'   => 'ACS Urban Titu',
				'g_oaspeti' => 5,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 2,
				'gazde'     => 'Olimpia Morteni',
				'g_gazde'   => 1,
				'oaspeti'   => 'ACS Urban Titu',
				'g_oaspeti' => 4,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 2,
				'gazde'     => 'Viitorul Odobesti Ziduri',
				'g_gazde'   => 3,
				'oaspeti'   => 'Viitorul Burduca',
				'g_oaspeti' => 0,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 2,
				'gazde'     => 'Vointa Ionesti',
				'g_gazde'   => 3,
				'oaspeti'   => 'Olimpia Picior de Munte',
				'g_oaspeti' => 0,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 2,
				'gazde'     => 'Sportul Mogosani',
				'g_gazde'   => 4,
				'oaspeti'   => 'Flacara Valea Mare',
				'g_oaspeti' => 2,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 2,
				'gazde'     => 'Corbii Mari',
				'g_gazde'   => 10,
				'oaspeti'   => 'Viitorul Gaesti',
				'g_oaspeti' => 3,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 2,
				'gazde'     => 'Unirea Cobia',
				'g_gazde'   => 9,
				'oaspeti'   => 'Viitorul Tomsani',
				'g_oaspeti' => 3,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 2,
				'gazde'     => 'Viitorul Straosti',
				'g_gazde'   => 3,
				'oaspeti'   => 'PCM Ungureni',
				'g_oaspeti' => 4,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 2,
				'gazde'     => 'Dinamo Odaia Turcului',
				'g_gazde'   => 4,
				'oaspeti'   => 'Flacara Zavoiu',
				'g_oaspeti' => 1,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 2,
				'gazde'     => 'Petrolul Rascaieti',
				'g_gazde'   => 0,
				'oaspeti'   => 'Spicul Jugureni',
				'g_oaspeti' => 0,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 3,
				'gazde'     => 'Spicul Jugureni',
				'g_gazde'   => 5,
				'oaspeti'   => 'Olimpia Morteni',
				'g_oaspeti' => 1,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 3,
				'gazde'     => 'Flacara Zavoiu',
				'g_gazde'   => 6,
				'oaspeti'   => 'Petrolul Rascaieti',
				'g_oaspeti' => 3,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 3,
				'gazde'     => 'PCM Ungureni',
				'g_gazde'   => 4,
				'oaspeti'   => 'Dinamo Odaia Turcului',
				'g_oaspeti' => 3,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 3,
				'gazde'     => 'Viitorul Tomsani',
				'g_gazde'   => 2,
				'oaspeti'   => 'Viitorul Straosti',
				'g_oaspeti' => 3,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 3,
				'gazde'     => 'Viitorul Gaesti',
				'g_gazde'   => 1,
				'oaspeti'   => 'Unirea Cobia',
				'g_oaspeti' => 1,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 3,
				'gazde'     => 'Flacara Valea Mare',
				'g_gazde'   => 5,
				'oaspeti'   => 'Corbii Mari',
				'g_oaspeti' => 1,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 3,
				'gazde'     => 'Olimpia Picior de Munte',
				'g_gazde'   => 2,
				'oaspeti'   => 'Sportul Mogosani',
				'g_oaspeti' => 0,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 3,
				'gazde'     => 'Viitorul Burduca',
				'g_gazde'   => 4,
				'oaspeti'   => 'Vointa Ionesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 3,
				'gazde'     => 'ACS Urban Titu',
				'g_gazde'   => 7,
				'oaspeti'   => 'Viitorul Odobesti Ziduri',
				'g_oaspeti' => 0,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 4,
				'gazde'     => 'Olimpia Morteni',
				'g_gazde'   => 0,
				'oaspeti'   => 'Viitorul Odobesti Ziduri',
				'g_oaspeti' => 1,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 4,
				'gazde'     => 'Vointa Ionesti',
				'g_gazde'   => 1,
				'oaspeti'   => 'ACS Urban Titu',
				'g_oaspeti' => 5,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 4,
				'gazde'     => 'Sportul Mogosani',
				'g_gazde'   => 4,
				'oaspeti'   => 'Viitorul Burduca',
				'g_oaspeti' => 1,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 4,
				'gazde'     => 'Corbii Mari',
				'g_gazde'   => 4,
				'oaspeti'   => 'Olimpia Picior de Munte',
				'g_oaspeti' => 2,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 4,
				'gazde'     => 'Unirea Cobia',
				'g_gazde'   => 0,
				'oaspeti'   => 'Flacara Valea Mare',
				'g_oaspeti' => 7,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 4,
				'gazde'     => 'Viitorul Straosti',
				'g_gazde'   => 3,
				'oaspeti'   => 'Viitorul Gaesti',
				'g_oaspeti' => 2,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 4,
				'gazde'     => 'Dinamo Odaia Turcului',
				'g_gazde'   => 7,
				'oaspeti'   => 'Viitorul Tomsani',
				'g_oaspeti' => 2,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 4,
				'gazde'     => 'Petrolul Rascaieti',
				'g_gazde'   => 1,
				'oaspeti'   => 'PCM Ungureni',
				'g_oaspeti' => 0,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 4,
				'gazde'     => 'Spicul Jugureni',
				'g_gazde'   => 1,
				'oaspeti'   => 'Flacara Zavoiu',
				'g_oaspeti' => 0,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 5,
				'gazde'     => 'Flacara Zavoiu',
				'g_gazde'   => 7,
				'oaspeti'   => 'Olimpia Morteni',
				'g_oaspeti' => 0,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 5,
				'gazde'     => 'PCM Ungureni',
				'g_gazde'   => 1,
				'oaspeti'   => 'Spicul Jugureni',
				'g_oaspeti' => 0,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 5,
				'gazde'     => 'Viitorul Tomsani',
				'g_gazde'   => 1,
				'oaspeti'   => 'Petrolul Rascaieti',
				'g_oaspeti' => 0,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 5,
				'gazde'     => 'Viitorul Gaesti',
				'g_gazde'   => 2,
				'oaspeti'   => 'Dinamo Odaia Turcului',
				'g_oaspeti' => 3,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 5,
				'gazde'     => 'Flacara Valea Mare',
				'g_gazde'   => 2,
				'oaspeti'   => 'Viitorul Straosti',
				'g_oaspeti' => 1,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 5,
				'gazde'     => 'Olimpia Picior de Munte',
				'g_gazde'   => 1,
				'oaspeti'   => 'Unirea Cobia',
				'g_oaspeti' => 3,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 5,
				'gazde'     => 'Viitorul Burduca',
				'g_gazde'   => 2,
				'oaspeti'   => 'Corbii Mari',
				'g_oaspeti' => 5,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 5,
				'gazde'     => 'ACS Urban Titu',
				'g_gazde'   => 4,
				'oaspeti'   => 'Sportul Mogosani',
				'g_oaspeti' => 1,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 5,
				'gazde'     => 'Viitorul Odobesti Ziduri',
				'g_gazde'   => 4,
				'oaspeti'   => 'Vointa Ionesti',
				'g_oaspeti' => 2,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 6,
				'gazde'     => 'Olimpia Morteni',
				'g_gazde'   => 2,
				'oaspeti'   => 'Vointa Ionesti',
				'g_oaspeti' => 0,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 6,
				'gazde'     => 'Sportul Mogosani',
				'g_gazde'   => 7,
				'oaspeti'   => 'Viitorul Odobesti Ziduri',
				'g_oaspeti' => 1,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 6,
				'gazde'     => 'Corbii Mari',
				'g_gazde'   => 1,
				'oaspeti'   => 'ACS Urban Titu',
				'g_oaspeti' => 1,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 6,
				'gazde'     => 'Unirea Cobia',
				'g_gazde'   => 4,
				'oaspeti'   => 'Viitorul Burduca',
				'g_oaspeti' => 1,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 6,
				'gazde'     => 'Viitorul Straosti',
				'g_gazde'   => 4,
				'oaspeti'   => 'Olimpia Picior de Munte',
				'g_oaspeti' => 2,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 6,
				'gazde'     => 'Dinamo Odaia Turcului',
				'g_gazde'   => 1,
				'oaspeti'   => 'Flacara Valea Mare',
				'g_oaspeti' => 2,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 6,
				'gazde'     => 'Petrolul Rascaieti',
				'g_gazde'   => 2,
				'oaspeti'   => 'Viitorul Gaesti',
				'g_oaspeti' => 2,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 6,
				'gazde'     => 'Spicul Jugureni',
				'g_gazde'   => 7,
				'oaspeti'   => 'Viitorul Tomsani',
				'g_oaspeti' => 3,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 6,
				'gazde'     => 'Flacara Zavoiu',
				'g_gazde'   => 0,
				'oaspeti'   => 'PCM Ungureni',
				'g_oaspeti' => 2,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 7,
				'gazde'     => 'PCM Ungureni',
				'g_gazde'   => 7,
				'oaspeti'   => 'Olimpia Morteni',
				'g_oaspeti' => 3,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 7,
				'gazde'     => 'Viitorul Tomsani',
				'g_gazde'   => 1,
				'oaspeti'   => 'Flacara Zavoiu',
				'g_oaspeti' => 7,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 7,
				'gazde'     => 'Viitorul Gaesti',
				'g_gazde'   => 1,
				'oaspeti'   => 'Spicul Jugureni',
				'g_oaspeti' => 8,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 7,
				'gazde'     => 'Flacara Valea Mare',
				'g_gazde'   => 4,
				'oaspeti'   => 'Petrolul Rascaieti',
				'g_oaspeti' => 1,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 7,
				'gazde'     => 'Olimpia Picior de Munte',
				'g_gazde'   => 1,
				'oaspeti'   => 'Dinamo Odaia Turcului',
				'g_oaspeti' => 3,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 7,
				'gazde'     => 'Viitorul Burduca',
				'g_gazde'   => 4,
				'oaspeti'   => 'Viitorul Straosti',
				'g_oaspeti' => 3,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 7,
				'gazde'     => 'ACS Urban Titu',
				'g_gazde'   => 5,
				'oaspeti'   => 'Unirea Cobia',
				'g_oaspeti' => 1,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 7,
				'gazde'     => 'Viitorul Odobesti Ziduri',
				'g_gazde'   => 0,
				'oaspeti'   => 'Corbii Mari',
				'g_oaspeti' => 3,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 7,
				'gazde'     => 'Vointa Ionesti',
				'g_gazde'   => 1,
				'oaspeti'   => 'Sportul Mogosani',
				'g_oaspeti' => 5,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 8,
				'gazde'     => 'Olimpia Morteni',
				'g_gazde'   => 1,
				'oaspeti'   => 'Sportul Mogosani',
				'g_oaspeti' => 2,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 8,
				'gazde'     => 'Corbii Mari',
				'g_gazde'   => 9,
				'oaspeti'   => 'Vointa Ionesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 8,
				'gazde'     => 'Unirea Cobia',
				'g_gazde'   => 8,
				'oaspeti'   => 'Viitorul Odobesti Ziduri',
				'g_oaspeti' => 2,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 8,
				'gazde'     => 'Viitorul Straosti',
				'g_gazde'   => 2,
				'oaspeti'   => 'ACS Urban Titu',
				'g_oaspeti' => 6,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 8,
				'gazde'     => 'Dinamo Odaia Turcului',
				'g_gazde'   => 1,
				'oaspeti'   => 'Viitorul Burduca',
				'g_oaspeti' => 0,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 8,
				'gazde'     => 'Petrolul Rascaieti',
				'g_gazde'   => 3,
				'oaspeti'   => 'Olimpia Picior de Munte',
				'g_oaspeti' => 2,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 8,
				'gazde'     => 'Spicul Jugureni',
				'g_gazde'   => 1,
				'oaspeti'   => 'Flacara Valea Mare',
				'g_oaspeti' => 2,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 8,
				'gazde'     => 'Flacara Zavoiu',
				'g_gazde'   => 9,
				'oaspeti'   => 'Viitorul Gaesti',
				'g_oaspeti' => 0,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 8,
				'gazde'     => 'PCM Ungureni',
				'g_gazde'   => 8,
				'oaspeti'   => 'Viitorul Tomsani',
				'g_oaspeti' => 0,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 9,
				'gazde'     => 'Viitorul Tomsani',
				'g_gazde'   => 4,
				'oaspeti'   => 'Olimpia Morteni',
				'g_oaspeti' => 2,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 9,
				'gazde'     => 'Viitorul Gaesti',
				'g_gazde'   => 1,
				'oaspeti'   => 'PCM Ungureni',
				'g_oaspeti' => 12,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 9,
				'gazde'     => 'Flacara Valea Mare',
				'g_gazde'   => 4,
				'oaspeti'   => 'Flacara Zavoiu',
				'g_oaspeti' => 1,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 9,
				'gazde'     => 'Olimpia Picior de Munte',
				'g_gazde'   => 0,
				'oaspeti'   => 'Spicul Jugureni',
				'g_oaspeti' => 0,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 9,
				'gazde'     => 'Viitorul Burduca',
				'g_gazde'   => 4,
				'oaspeti'   => 'Petrolul Rascaieti',
				'g_oaspeti' => 3,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 9,
				'gazde'     => 'ACS Urban Titu',
				'g_gazde'   => 4,
				'oaspeti'   => 'Dinamo Odaia Turcului',
				'g_oaspeti' => 0,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 9,
				'gazde'     => 'Viitorul Odobesti Ziduri',
				'g_gazde'   => 0,
				'oaspeti'   => 'Viitorul Straosti',
				'g_oaspeti' => 7,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 9,
				'gazde'     => 'Vointa Ionesti',
				'g_gazde'   => 2,
				'oaspeti'   => 'Unirea Cobia',
				'g_oaspeti' => 0,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 9,
				'gazde'     => 'Sportul Mogosani',
				'g_gazde'   => 2,
				'oaspeti'   => 'Corbii Mari',
				'g_oaspeti' => 2,
			], [
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 10,
				'gazde'     => 'Olimpia Morteni',
				'g_gazde'   => 1,
				'oaspeti'   => 'Corbii Mari',
				'g_oaspeti' => 8,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 10,
				'gazde'     => 'Unirea Cobia',
				'g_gazde'   => 0,
				'oaspeti'   => 'Sportul Mogosani',
				'g_oaspeti' => 2,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 10,
				'gazde'     => 'Viitorul Straosti',
				'g_gazde'   => 8,
				'oaspeti'   => 'Vointa Ionesti',
				'g_oaspeti' => 3,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 10,
				'gazde'     => 'Dinamo Odaia Turcului',
				'g_gazde'   => 12,
				'oaspeti'   => 'Viitorul Odobesti Ziduri',
				'g_oaspeti' => 0,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 10,
				'gazde'     => 'Petrolul Rascaieti',
				'g_gazde'   => 2,
				'oaspeti'   => 'ACS Urban Titu',
				'g_oaspeti' => 6,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 10,
				'gazde'     => 'Spicul Jugureni',
				'g_gazde'   => 6,
				'oaspeti'   => 'Viitorul Burduca',
				'g_oaspeti' => 2,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 10,
				'gazde'     => 'Flacara Zavoiu',
				'g_gazde'   => 5,
				'oaspeti'   => 'Olimpia Picior de Munte',
				'g_oaspeti' => 0,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 10,
				'gazde'     => 'PCM Ungureni',
				'g_gazde'   => 1,
				'oaspeti'   => 'Flacara Valea Mare',
				'g_oaspeti' => 2,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 10,
				'gazde'     => 'Viitorul Tomsani',
				'g_gazde'   => 5,
				'oaspeti'   => 'Viitorul Gaesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 11,
				'gazde'     => 'Viitorul Gaesti',
				'g_gazde'   => 1,
				'oaspeti'   => 'Olimpia Morteni',
				'g_oaspeti' => 7,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 11,
				'gazde'     => 'Flacara Valea Mare',
				'g_gazde'   => 6,
				'oaspeti'   => 'Viitorul Tomsani',
				'g_oaspeti' => 0,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 11,
				'gazde'     => 'Olimpia Picior de Munte',
				'g_gazde'   => 3,
				'oaspeti'   => 'PCM Ungureni',
				'g_oaspeti' => 3,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 11,
				'gazde'     => 'Viitorul Burduca',
				'g_gazde'   => 4,
				'oaspeti'   => 'Flacara Zavoiu',
				'g_oaspeti' => 3,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 11,
				'gazde'     => 'ACS Urban Titu',
				'g_gazde'   => 5,
				'oaspeti'   => 'Spicul Jugureni',
				'g_oaspeti' => 2,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 11,
				'gazde'     => 'Viitorul Odobesti Ziduri',
				'g_gazde'   => 2,
				'oaspeti'   => 'Petrolul Rascaieti',
				'g_oaspeti' => 6,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 11,
				'gazde'     => 'Vointa Ionesti',
				'g_gazde'   => 1,
				'oaspeti'   => 'Dinamo Odaia Turcului',
				'g_oaspeti' => 3,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 11,
				'gazde'     => 'Sportul Mogosani',
				'g_gazde'   => 2,
				'oaspeti'   => 'Viitorul Straosti',
				'g_oaspeti' => 0,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 11,
				'gazde'     => 'Corbii Mari',
				'g_gazde'   => 5,
				'oaspeti'   => 'Unirea Cobia',
				'g_oaspeti' => 1,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 12,
				'gazde'     => 'Olimpia Morteni',
				'g_gazde'   => 3,
				'oaspeti'   => 'Unirea Cobia',
				'g_oaspeti' => 1,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 12,
				'gazde'     => 'Viitorul Straosti',
				'g_gazde'   => 4,
				'oaspeti'   => 'Corbii Mari',
				'g_oaspeti' => 2,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 12,
				'gazde'     => 'Dinamo Odaia Turcului',
				'g_gazde'   => 4,
				'oaspeti'   => 'Sportul Mogosani',
				'g_oaspeti' => 1,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 12,
				'gazde'     => 'Petrolul Rascaieti',
				'g_gazde'   => 4,
				'oaspeti'   => 'Vointa Ionesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 12,
				'gazde'     => 'Spicul Jugureni',
				'g_gazde'   => 8,
				'oaspeti'   => 'Viitorul Odobesti Ziduri',
				'g_oaspeti' => 7,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 12,
				'gazde'     => 'Flacara Zavoiu',
				'g_gazde'   => 5,
				'oaspeti'   => 'ACS Urban Titu',
				'g_oaspeti' => 1,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 12,
				'gazde'     => 'PCM Ungureni',
				'g_gazde'   => 3,
				'oaspeti'   => 'Viitorul Burduca',
				'g_oaspeti' => 2,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 12,
				'gazde'     => 'Viitorul Tomsani',
				'g_gazde'   => 2,
				'oaspeti'   => 'Olimpia Picior de Munte',
				'g_oaspeti' => 2,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 12,
				'gazde'     => 'Viitorul Gaesti',
				'g_gazde'   => 2,
				'oaspeti'   => 'Flacara Valea Mare',
				'g_oaspeti' => 9,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 13,
				'gazde'     => 'Flacara Valea Mare',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Morteni',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 13,
				'gazde'     => 'Olimpia Picior de Munte',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gaesti',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 13,
				'gazde'     => 'Viitorul Burduca',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Tomsani',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 13,
				'gazde'     => 'ACS Urban Titu',
				'g_gazde'   => null,
				'oaspeti'   => 'PCM Ungureni',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 13,
				'gazde'     => 'Viitorul Odobesti Ziduri',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Zavoiu',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 13,
				'gazde'     => 'Vointa Ionesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Spicul Jugureni',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 13,
				'gazde'     => 'Sportul Mogosani',
				'g_gazde'   => null,
				'oaspeti'   => 'Petrolul Rascaieti',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 13,
				'gazde'     => 'Corbii Mari',
				'g_gazde'   => null,
				'oaspeti'   => 'Dinamo Odaia Turcului',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 13,
				'gazde'     => 'Unirea Cobia',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Straosti',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 14,
				'gazde'     => 'Olimpia Morteni',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Straosti',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 14,
				'gazde'     => 'Dinamo Odaia Turcului',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Cobia',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 14,
				'gazde'     => 'Petrolul Rascaieti',
				'g_gazde'   => null,
				'oaspeti'   => 'Corbii Mari',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 14,
				'gazde'     => 'Spicul Jugureni',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Mogosani',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 14,
				'gazde'     => 'Flacara Zavoiu',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Ionesti',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 14,
				'gazde'     => 'PCM Ungureni',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Odobesti Ziduri',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 14,
				'gazde'     => 'Viitorul Tomsani',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Urban Titu',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 14,
				'gazde'     => 'Viitorul Gaesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Burduca',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 14,
				'gazde'     => 'Flacara Valea Mare',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Picior de Munte',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 15,
				'gazde'     => 'Olimpia Picior de Munte',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Morteni',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 15,
				'gazde'     => 'Viitorul Burduca',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Valea Mare',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 15,
				'gazde'     => 'ACS Urban Titu',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gaesti',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 15,
				'gazde'     => 'Viitorul Odobesti Ziduri',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Tomsani',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 15,
				'gazde'     => 'Vointa Ionesti',
				'g_gazde'   => null,
				'oaspeti'   => 'PCM Ungureni',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 15,
				'gazde'     => 'Sportul Mogosani',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Zavoiu',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 15,
				'gazde'     => 'Corbii Mari',
				'g_gazde'   => null,
				'oaspeti'   => 'Spicul Jugureni',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 15,
				'gazde'     => 'Unirea Cobia',
				'g_gazde'   => null,
				'oaspeti'   => 'Petrolul Rascaieti',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 15,
				'gazde'     => 'Viitorul Straosti',
				'g_gazde'   => null,
				'oaspeti'   => 'Dinamo Odaia Turcului',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 16,
				'gazde'     => 'Olimpia Morteni',
				'g_gazde'   => null,
				'oaspeti'   => 'Dinamo Odaia Turcului',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 16,
				'gazde'     => 'Petrolul Rascaieti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Straosti',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 16,
				'gazde'     => 'Spicul Jugureni',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Cobia',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 16,
				'gazde'     => 'Flacara Zavoiu',
				'g_gazde'   => null,
				'oaspeti'   => 'Corbii Mari',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 16,
				'gazde'     => 'PCM Ungureni',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Mogosani',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 16,
				'gazde'     => 'Viitorul Tomsani',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Ionesti',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 16,
				'gazde'     => 'Viitorul Gaesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Odobesti Ziduri',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 16,
				'gazde'     => 'Flacara Valea Mare',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Urban Titu',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 16,
				'gazde'     => 'Olimpia Picior de Munte',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Burduca',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 17,
				'gazde'     => 'Viitorul Burduca',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Morteni',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 17,
				'gazde'     => 'ACS Urban Titu',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Picior de Munte',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 17,
				'gazde'     => 'Viitorul Odobesti Ziduri',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Valea Mare',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 17,
				'gazde'     => 'Vointa Ionesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gaesti',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 17,
				'gazde'     => 'Sportul Mogosani',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Tomsani',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 17,
				'gazde'     => 'Corbii Mari',
				'g_gazde'   => null,
				'oaspeti'   => 'PCM Ungureni',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 17,
				'gazde'     => 'Unirea Cobia',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Zavoiu',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 17,
				'gazde'     => 'Viitorul Straosti',
				'g_gazde'   => null,
				'oaspeti'   => 'Spicul Jugureni',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 17,
				'gazde'     => 'Dinamo Odaia Turcului',
				'g_gazde'   => null,
				'oaspeti'   => 'Petrolul Rascaieti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 18,
				'gazde'     => 'Olimpia Morteni',
				'g_gazde'   => null,
				'oaspeti'   => 'Petrolul Rascaieti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 18,
				'gazde'     => 'Dinamo Odaia Turcului',
				'g_gazde'   => null,
				'oaspeti'   => 'Spicul Jugureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 18,
				'gazde'     => 'Viitorul Straosti',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Zavoiu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 18,
				'gazde'     => 'Unirea Cobia',
				'g_gazde'   => null,
				'oaspeti'   => 'PCM Ungureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 18,
				'gazde'     => 'Corbii Mari',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Tomsani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 18,
				'gazde'     => 'Sportul Mogosani',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gaesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 18,
				'gazde'     => 'Vointa Ionesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Valea Mare',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 18,
				'gazde'     => 'Viitorul Odobesti Ziduri',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Picior de Munte',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 18,
				'gazde'     => 'ACS Urban Titu',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Burduca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 19,
				'gazde'     => 'ACS Urban Titu',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Morteni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 19,
				'gazde'     => 'Viitorul Burduca',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Odobesti Ziduri',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 19,
				'gazde'     => 'Olimpia Picior de Munte',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Ionesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 19,
				'gazde'     => 'Flacara Valea Mare',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Mogosani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 19,
				'gazde'     => 'Viitorul Gaesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Corbii Mari',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 19,
				'gazde'     => 'Viitorul Tomsani',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Cobia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 19,
				'gazde'     => 'PCM Ungureni',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Straosti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 19,
				'gazde'     => 'Flacara Zavoiu',
				'g_gazde'   => null,
				'oaspeti'   => 'Dinamo Odaia Turcului',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 19,
				'gazde'     => 'Spicul Jugureni',
				'g_gazde'   => null,
				'oaspeti'   => 'Petrolul Rascaieti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 20,
				'gazde'     => 'Olimpia Morteni',
				'g_gazde'   => null,
				'oaspeti'   => 'Spicul Jugureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 20,
				'gazde'     => 'Petrolul Rascaieti',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Zavoiu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 20,
				'gazde'     => 'Dinamo Odaia Turcului',
				'g_gazde'   => null,
				'oaspeti'   => 'PCM Ungureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 20,
				'gazde'     => 'Viitorul Straosti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Tomsani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 20,
				'gazde'     => 'Unirea Cobia',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gaesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 20,
				'gazde'     => 'Corbii Mari',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Valea Mare',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 20,
				'gazde'     => 'Sportul Mogosani',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Picior de Munte',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 20,
				'gazde'     => 'Vointa Ionesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Burduca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 20,
				'gazde'     => 'Viitorul Odobesti Ziduri',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Urban Titu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 21,
				'gazde'     => 'Viitorul Odobesti Ziduri',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Morteni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 21,
				'gazde'     => 'ACS Urban Titu',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Ionesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 21,
				'gazde'     => 'Viitorul Burduca',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Mogosani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 21,
				'gazde'     => 'Olimpia Picior de Munte',
				'g_gazde'   => null,
				'oaspeti'   => 'Corbii Mari',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 21,
				'gazde'     => 'Flacara Valea Mare',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Cobia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 21,
				'gazde'     => 'Viitorul Gaesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Straosti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 21,
				'gazde'     => 'Viitorul Tomsani',
				'g_gazde'   => null,
				'oaspeti'   => 'Dinamo Odaia Turcului',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 21,
				'gazde'     => 'PCM Ungureni',
				'g_gazde'   => null,
				'oaspeti'   => 'Petrolul Rascaieti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 21,
				'gazde'     => 'Flacara Zavoiu',
				'g_gazde'   => null,
				'oaspeti'   => 'Spicul Jugureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 22,
				'gazde'     => 'Olimpia Morteni',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Zavoiu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 22,
				'gazde'     => 'Spicul Jugureni',
				'g_gazde'   => null,
				'oaspeti'   => 'PCM Ungureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 22,
				'gazde'     => 'Petrolul Rascaieti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Tomsani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 22,
				'gazde'     => 'Dinamo Odaia Turcului',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gaesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 22,
				'gazde'     => 'Viitorul Straosti',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Valea Mare',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 22,
				'gazde'     => 'Unirea Cobia',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Picior de Munte',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 22,
				'gazde'     => 'Corbii Mari',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Burduca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 22,
				'gazde'     => 'Sportul Mogosani',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Urban Titu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 22,
				'gazde'     => 'Vointa Ionesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Odobesti Ziduri',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 23,
				'gazde'     => 'Vointa Ionesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Morteni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 23,
				'gazde'     => 'Viitorul Odobesti Ziduri',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Mogosani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 23,
				'gazde'     => 'ACS Urban Titu',
				'g_gazde'   => null,
				'oaspeti'   => 'Corbii Mari',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 23,
				'gazde'     => 'Viitorul Burduca',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Cobia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 23,
				'gazde'     => 'Olimpia Picior de Munte',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Straosti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 23,
				'gazde'     => 'Flacara Valea Mare',
				'g_gazde'   => null,
				'oaspeti'   => 'Dinamo Odaia Turcului',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 23,
				'gazde'     => 'Viitorul Gaesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Petrolul Rascaieti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 23,
				'gazde'     => 'Viitorul Tomsani',
				'g_gazde'   => null,
				'oaspeti'   => 'Spicul Jugureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 23,
				'gazde'     => 'PCM Ungureni',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Zavoiu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 24,
				'gazde'     => 'Olimpia Morteni',
				'g_gazde'   => null,
				'oaspeti'   => 'PCM Ungureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 24,
				'gazde'     => 'Flacara Zavoiu',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Tomsani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 24,
				'gazde'     => 'Spicul Jugureni',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gaesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 24,
				'gazde'     => 'Petrolul Rascaieti',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Valea Mare',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 24,
				'gazde'     => 'Dinamo Odaia Turcului',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Picior de Munte',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 24,
				'gazde'     => 'Viitorul Straosti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Burduca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 24,
				'gazde'     => 'Unirea Cobia',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Urban Titu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 24,
				'gazde'     => 'Corbii Mari',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Odobesti Ziduri',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 24,
				'gazde'     => 'Sportul Mogosani',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Ionesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 25,
				'gazde'     => 'Sportul Mogosani',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Morteni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 25,
				'gazde'     => 'Vointa Ionesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Corbii Mari',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 25,
				'gazde'     => 'Viitorul Odobesti Ziduri',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Cobia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 25,
				'gazde'     => 'ACS Urban Titu',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Straosti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 25,
				'gazde'     => 'Viitorul Burduca',
				'g_gazde'   => null,
				'oaspeti'   => 'Dinamo Odaia Turcului',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 25,
				'gazde'     => 'Olimpia Picior de Munte',
				'g_gazde'   => null,
				'oaspeti'   => 'Petrolul Rascaieti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 25,
				'gazde'     => 'Flacara Valea Mare',
				'g_gazde'   => null,
				'oaspeti'   => 'Spicul Jugureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 25,
				'gazde'     => 'Viitorul Gaesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Zavoiu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 25,
				'gazde'     => 'Viitorul Tomsani',
				'g_gazde'   => null,
				'oaspeti'   => 'PCM Ungureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 26,
				'gazde'     => 'Olimpia Morteni',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Tomsani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 26,
				'gazde'     => 'PCM Ungureni',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gaesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 26,
				'gazde'     => 'Flacara Zavoiu',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Valea Mare',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 26,
				'gazde'     => 'Spicul Jugureni',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Picior de Munte',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 26,
				'gazde'     => 'Petrolul Rascaieti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Burduca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 26,
				'gazde'     => 'Dinamo Odaia Turcului',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Urban Titu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 26,
				'gazde'     => 'Viitorul Straosti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Odobesti Ziduri',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 26,
				'gazde'     => 'Unirea Cobia',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Ionesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 26,
				'gazde'     => 'Corbii Mari',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Mogosani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 27,
				'gazde'     => 'Corbii Mari',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Morteni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 27,
				'gazde'     => 'Sportul Mogosani',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Cobia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 27,
				'gazde'     => 'Vointa Ionesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Straosti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 27,
				'gazde'     => 'Viitorul Odobesti Ziduri',
				'g_gazde'   => null,
				'oaspeti'   => 'Dinamo Odaia Turcului',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 27,
				'gazde'     => 'ACS Urban Titu',
				'g_gazde'   => null,
				'oaspeti'   => 'Petrolul Rascaieti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 27,
				'gazde'     => 'Viitorul Burduca',
				'g_gazde'   => null,
				'oaspeti'   => 'Spicul Jugureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 27,
				'gazde'     => 'Olimpia Picior de Munte',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Zavoiu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 27,
				'gazde'     => 'Flacara Valea Mare',
				'g_gazde'   => null,
				'oaspeti'   => 'PCM Ungureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 27,
				'gazde'     => 'Viitorul Gaesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Tomsani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 28,
				'gazde'     => 'Olimpia Morteni',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gaesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 28,
				'gazde'     => 'Viitorul Tomsani',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Valea Mare',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 28,
				'gazde'     => 'PCM Ungureni',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Picior de Munte',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 28,
				'gazde'     => 'Flacara Zavoiu',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Burduca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 28,
				'gazde'     => 'Spicul Jugureni',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Urban Titu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 28,
				'gazde'     => 'Petrolul Rascaieti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Odobesti Ziduri',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 28,
				'gazde'     => 'Dinamo Odaia Turcului',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Ionesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 28,
				'gazde'     => 'Viitorul Straosti',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Mogosani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 28,
				'gazde'     => 'Unirea Cobia',
				'g_gazde'   => null,
				'oaspeti'   => 'Corbii Mari',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 29,
				'gazde'     => 'Unirea Cobia',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Morteni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 29,
				'gazde'     => 'Corbii Mari',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Straosti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 29,
				'gazde'     => 'Sportul Mogosani',
				'g_gazde'   => null,
				'oaspeti'   => 'Dinamo Odaia Turcului',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 29,
				'gazde'     => 'Vointa Ionesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Petrolul Rascaieti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 29,
				'gazde'     => 'Viitorul Odobesti Ziduri',
				'g_gazde'   => null,
				'oaspeti'   => 'Spicul Jugureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 29,
				'gazde'     => 'ACS Urban Titu',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Zavoiu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 29,
				'gazde'     => 'Viitorul Burduca',
				'g_gazde'   => null,
				'oaspeti'   => 'PCM Ungureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 29,
				'gazde'     => 'Olimpia Picior de Munte',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Tomsani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 29,
				'gazde'     => 'Flacara Valea Mare',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gaesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 30,
				'gazde'     => 'Olimpia Morteni',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Valea Mare',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 30,
				'gazde'     => 'Viitorul Gaesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Picior de Munte',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 30,
				'gazde'     => 'Viitorul Tomsani',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Burduca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 30,
				'gazde'     => 'PCM Ungureni',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Urban Titu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 30,
				'gazde'     => 'Flacara Zavoiu',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Odobesti Ziduri',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 30,
				'gazde'     => 'Spicul Jugureni',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Ionesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 30,
				'gazde'     => 'Petrolul Rascaieti',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Mogosani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 30,
				'gazde'     => 'Dinamo Odaia Turcului',
				'g_gazde'   => null,
				'oaspeti'   => 'Corbii Mari',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 30,
				'gazde'     => 'Viitorul Straosti',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Cobia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 31,
				'gazde'     => 'Viitorul Straosti',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Morteni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 31,
				'gazde'     => 'Unirea Cobia',
				'g_gazde'   => null,
				'oaspeti'   => 'Dinamo Odaia Turcului',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 31,
				'gazde'     => 'Corbii Mari',
				'g_gazde'   => null,
				'oaspeti'   => 'Petrolul Rascaieti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 31,
				'gazde'     => 'Sportul Mogosani',
				'g_gazde'   => null,
				'oaspeti'   => 'Spicul Jugureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 31,
				'gazde'     => 'Vointa Ionesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Zavoiu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 31,
				'gazde'     => 'Viitorul Odobesti Ziduri',
				'g_gazde'   => null,
				'oaspeti'   => 'PCM Ungureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 31,
				'gazde'     => 'ACS Urban Titu',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Tomsani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 31,
				'gazde'     => 'Viitorul Burduca',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gaesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 31,
				'gazde'     => 'Olimpia Picior de Munte',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Valea Mare',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 32,
				'gazde'     => 'Olimpia Morteni',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Picior de Munte',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 32,
				'gazde'     => 'Flacara Valea Mare',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Burduca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 32,
				'gazde'     => 'Viitorul Gaesti',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Urban Titu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 32,
				'gazde'     => 'Viitorul Tomsani',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Odobesti Ziduri',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 32,
				'gazde'     => 'PCM Ungureni',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Ionesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 32,
				'gazde'     => 'Flacara Zavoiu',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Mogosani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 32,
				'gazde'     => 'Spicul Jugureni',
				'g_gazde'   => null,
				'oaspeti'   => 'Corbii Mari',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 32,
				'gazde'     => 'Petrolul Rascaieti',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Cobia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 32,
				'gazde'     => 'Dinamo Odaia Turcului',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Straosti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 33,
				'gazde'     => 'Dinamo Odaia Turcului',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Morteni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 33,
				'gazde'     => 'Viitorul Straosti',
				'g_gazde'   => null,
				'oaspeti'   => 'Petrolul Rascaieti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 33,
				'gazde'     => 'Unirea Cobia',
				'g_gazde'   => null,
				'oaspeti'   => 'Spicul Jugureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 33,
				'gazde'     => 'Corbii Mari',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Zavoiu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 33,
				'gazde'     => 'Sportul Mogosani',
				'g_gazde'   => null,
				'oaspeti'   => 'PCM Ungureni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 33,
				'gazde'     => 'Vointa Ionesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Tomsani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 33,
				'gazde'     => 'Viitorul Odobesti Ziduri',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gaesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 33,
				'gazde'     => 'ACS Urban Titu',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Valea Mare',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 33,
				'gazde'     => 'Viitorul Burduca',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Picior de Munte',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 34,
				'gazde'     => 'Olimpia Morteni',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Burduca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 34,
				'gazde'     => 'Olimpia Picior de Munte',
				'g_gazde'   => null,
				'oaspeti'   => 'ACS Urban Titu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 34,
				'gazde'     => 'Flacara Valea Mare',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Odobesti Ziduri',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 34,
				'gazde'     => 'Viitorul Gaesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Ionesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 34,
				'gazde'     => 'Viitorul Tomsani',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Mogosani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 34,
				'gazde'     => 'PCM Ungureni',
				'g_gazde'   => null,
				'oaspeti'   => 'Corbii Mari',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 34,
				'gazde'     => 'Flacara Zavoiu',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Cobia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 34,
				'gazde'     => 'Spicul Jugureni',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Straosti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'VEST',
				'etapa'     => 34,
				'gazde'     => 'Petrolul Rascaieti',
				'g_gazde'   => null,
				'oaspeti'   => 'Dinamo Odaia Turcului',
				'g_oaspeti' => null,
			]
		];

        Echipe::where('liga', 5)->where('serie', 'VEST')->delete();
		foreach ($echipe as $echipa) {
			$adauga = new Echipe;
			$adauga->echipa = trim($echipa['echipa']);
			$adauga->liga   = $echipa['liga'];
			$adauga->serie  = $echipa['serie'];
			$adauga->save();
		}

		Etape::where('liga', 5)->where('serie', 'VEST')->delete();
		foreach ($etape as $etapa) {
			$adauga = new Etape;
			$adauga->gazde     = trim($etapa['gazde']);
			$adauga->oaspeti   = trim($etapa['oaspeti']);
			$adauga->g_gazde   = $etapa['g_gazde'];
			$adauga->g_oaspeti = $etapa['g_oaspeti'];
			$adauga->liga      = $etapa['liga'];
			$adauga->serie     = $etapa['serie'];
			$adauga->etapa     = $etapa['etapa'];
			$adauga->data      = $etapa['data'] != NULL ? DateTime::createFromFormat('d-m-Y', ($etapa['data']))->format('Y-m-d') : NULL;
			$adauga->ora       = $etapa['ora'];
			$adauga->save();
		}
    }
}
