<?php

use Illuminate\Database\Seeder;
use App\Echipe;
use App\Etape;

class liga_5_nord extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $echipe = [	
			[
				'echipa' => 'Cetatea 1396 Targoviste',
				'liga'   => 5,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Luceafarul Darmanesti',
				'liga'   => 5,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Flacara Suta Seaca',
				'liga'   => 5,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Sageata Gura Ocnitei',
				'liga'   => 5,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Vointa Sacuieni',
				'liga'   => 5,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Vointa Tatarani',
				'liga'   => 5,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Vointa Steaua Pietrosita',
				'liga'   => 5,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Sportul Runcu',
				'liga'   => 5,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Viitorul Razvad',
				'liga'   => 5,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Viitorul Ocnita',
				'liga'   => 5,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Pomicola Raciu',
				'liga'   => 5,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Victoria Comisani',
				'liga'   => 5,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Vointa Adanca',
				'liga'   => 5,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Olimpicii 2 Ulmi',
				'liga'   => 5,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Vointa Buciumeni',
				'liga'   => 5,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Doicesti',
				'liga'   => 5,
				'serie'  => 'NORD',
			],[
				'echipa' => 'Unirea Lucieni',
				'liga'   => 5,
				'serie'  => 'NORD',
			],[
				'echipa' => 'STA',
				'liga'   => 5,
				'serie'  => 'NORD',
			]
		];

		$etape = [
	        [
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 1,
				'gazde'     => 'Sportul Runcu',
				'g_gazde'   => 2,
				'oaspeti'   => 'Luceafarul Darmanesti',
				'g_oaspeti' => 3,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 1,
				'gazde'     => 'Unirea Lucieni',
				'g_gazde'   => 0,
				'oaspeti'   => 'Pomicola Raciu',
				'g_oaspeti' => 3,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 1,
				'gazde'     => 'Vointa Adanca',
				'g_gazde'   => 1,
				'oaspeti'   => 'Sageata Gura Ocnitei',
				'g_oaspeti' => 1,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 1,
				'gazde'     => 'Vointa Buciumeni',
				'g_gazde'   => 2,
				'oaspeti'   => 'Vointa Tatarani',
				'g_oaspeti' => 3,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 1,
				'gazde'     => 'Viitorul Ocnita',
				'g_gazde'   => 1,
				'oaspeti'   => 'Viitorul Razvad',
				'g_oaspeti' => 2,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 1,
				'gazde'     => 'Olimpicii 2 Ulmi',
				'g_gazde'   => 10,
				'oaspeti'   => 'Doicesti',
				'g_oaspeti' => 0,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 1,
				'gazde'     => 'Vointa Sacuieni',
				'g_gazde'   => 4,
				'oaspeti'   => 'Vointa Steaua Pietrosita',
				'g_oaspeti' => 1,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 1,
				'gazde'     => 'Cetatea 1396 Targoviste',
				'g_gazde'   => 6,
				'oaspeti'   => 'STA',
				'g_oaspeti' => 3,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 1,
				'gazde'     => 'Flacara Suta Seaca',
				'g_gazde'   => 3,
				'oaspeti'   => 'STA',
				'g_oaspeti' => 0,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 2,
				'gazde'     => 'Luceafarul Darmanesti',
				'g_gazde'   => 4,
				'oaspeti'   => 'Victoria Comisani',
				'g_oaspeti' => 0,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 2,
				'gazde'     => 'STA',
				'g_gazde'   => 0,
				'oaspeti'   => 'Flacara Suta Seaca',
				'g_oaspeti' => 3,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 2,
				'gazde'     => 'Vointa Steaua Pietrosita',
				'g_gazde'   => 2,
				'oaspeti'   => 'Cetatea 1396 Targoviste',
				'g_oaspeti' => 1,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 2,
				'gazde'     => 'Doicesti',
				'g_gazde'   => 1,
				'oaspeti'   => 'Vointa Sacuieni',
				'g_oaspeti' => 3,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 2,
				'gazde'     => 'Viitorul Razvad',
				'g_gazde'   => 5,
				'oaspeti'   => 'Olimpicii 2 Ulmi',
				'g_oaspeti' => 0,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 2,
				'gazde'     => 'Vointa Tatarani',
				'g_gazde'   => 2,
				'oaspeti'   => 'Viitorul Ocnita',
				'g_oaspeti' => 2,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 2,
				'gazde'     => 'Sageata Gura Ocnitei',
				'g_gazde'   => 3,
				'oaspeti'   => 'Vointa Buciumeni',
				'g_oaspeti' => 1,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 2,
				'gazde'     => 'Pomicola Raciu',
				'g_gazde'   => 9,
				'oaspeti'   => 'Vointa Adanca',
				'g_oaspeti' => 4,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 2,
				'gazde'     => 'Sportul Runcu',
				'g_gazde'   => 5,
				'oaspeti'   => 'Unirea Lucieni',
				'g_oaspeti' => 2,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 3,
				'gazde'     => 'Unirea Lucieni',
				'g_gazde'   => 0,
				'oaspeti'   => 'Luceafarul Darmanesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 3,
				'gazde'     => 'Vointa Adanca',
				'g_gazde'   => 2,
				'oaspeti'   => 'Sportul Runcu',
				'g_oaspeti' => 6,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 3,
				'gazde'     => 'Vointa Buciumeni',
				'g_gazde'   => 2,
				'oaspeti'   => 'Pomicola Raciu',
				'g_oaspeti' => 3,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 3,
				'gazde'     => 'Viitorul Ocnita',
				'g_gazde'   => 1,
				'oaspeti'   => 'Sageata Gura Ocnitei',
				'g_oaspeti' => 1,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 3,
				'gazde'     => 'Olimpicii 2 Ulmi',
				'g_gazde'   => 0,
				'oaspeti'   => 'Vointa Tatarani',
				'g_oaspeti' => 3,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 3,
				'gazde'     => 'Vointa Sacuieni',
				'g_gazde'   => 1,
				'oaspeti'   => 'Viitorul Razvad',
				'g_oaspeti' => 2,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 3,
				'gazde'     => 'Cetatea 1396 Targoviste',
				'g_gazde'   => 9,
				'oaspeti'   => 'Doicesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 3,
				'gazde'     => 'Flacara Suta Seaca',
				'g_gazde'   => 4,
				'oaspeti'   => 'Vointa Steaua Pietrosita',
				'g_oaspeti' => 2,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 3,
				'gazde'     => 'Victoria Comisani',
				'g_gazde'   => 3,
				'oaspeti'   => 'STA',
				'g_oaspeti' => 0,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 4,
				'gazde'     => 'Luceafarul Darmanesti',
				'g_gazde'   => 5,
				'oaspeti'   => 'STA',
				'g_oaspeti' => 0,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 4,
				'gazde'     => 'Vointa Steaua Pietrosita',
				'g_gazde'   => 3,
				'oaspeti'   => 'Victoria Comisani',
				'g_oaspeti' => 1,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 4,
				'gazde'     => 'Doicesti',
				'g_gazde'   => 0,
				'oaspeti'   => 'Flacara Suta Seaca',
				'g_oaspeti' => 3,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 4,
				'gazde'     => 'Viitorul Razvad',
				'g_gazde'   => 0,
				'oaspeti'   => 'Cetatea 1396 Targoviste',
				'g_oaspeti' => 3,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 4,
				'gazde'     => 'Vointa Tatarani',
				'g_gazde'   => 2,
				'oaspeti'   => 'Vointa Sacuieni',
				'g_oaspeti' => 5,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 4,
				'gazde'     => 'Sageata Gura Ocnitei',
				'g_gazde'   => 6,
				'oaspeti'   => 'Olimpicii 2 Ulmi',
				'g_oaspeti' => 2,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 4,
				'gazde'     => 'Pomicola Raciu',
				'g_gazde'   => 5,
				'oaspeti'   => 'Viitorul Ocnita',
				'g_oaspeti' => 3,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 4,
				'gazde'     => 'Sportul Runcu',
				'g_gazde'   => 3,
				'oaspeti'   => 'Vointa Buciumeni',
				'g_oaspeti' => 3,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 4,
				'gazde'     => 'Unirea Lucieni',
				'g_gazde'   => 1,
				'oaspeti'   => 'Vointa Adanca',
				'g_oaspeti' => 7,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 5,
				'gazde'     => 'Vointa Adanca',
				'g_gazde'   => 2,
				'oaspeti'   => 'Luceafarul Darmanesti',
				'g_oaspeti' => 3,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 5,
				'gazde'     => 'Vointa Buciumeni',
				'g_gazde'   => 8,
				'oaspeti'   => 'Unirea Lucieni',
				'g_oaspeti' => 0,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 5,
				'gazde'     => 'Viitorul Ocnita',
				'g_gazde'   => 4,
				'oaspeti'   => 'Sportul Runcu',
				'g_oaspeti' => 4,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 5,
				'gazde'     => 'Olimpicii 2 Ulmi',
				'g_gazde'   => 1,
				'oaspeti'   => 'Pomicola Raciu',
				'g_oaspeti' => 3,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 5,
				'gazde'     => 'Vointa Sacuieni',
				'g_gazde'   => 0,
				'oaspeti'   => 'Sageata Gura Ocnitei',
				'g_oaspeti' => 3,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 5,
				'gazde'     => 'Cetatea 1396 Targoviste',
				'g_gazde'   => 7,
				'oaspeti'   => 'Vointa Tatarani',
				'g_oaspeti' => 0,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 5,
				'gazde'     => 'Flacara Suta Seaca',
				'g_gazde'   => 3,
				'oaspeti'   => 'Viitorul Razvad',
				'g_oaspeti' => 1,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 5,
				'gazde'     => 'Victoria Comisani',
				'g_gazde'   => 6,
				'oaspeti'   => 'Doicesti',
				'g_oaspeti' => 0,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 5,
				'gazde'     => 'STA',
				'g_gazde'   => 0,
				'oaspeti'   => 'Vointa Steaua Pietrosita',
				'g_oaspeti' => 3,
			],[
				'data'      => '12-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 6,
				'gazde'     => 'Luceafarul Darmanesti',
				'g_gazde'   => 7,
				'oaspeti'   => 'Vointa Steaua Pietrosita',
				'g_oaspeti' => 2,
			],[
				'data'      => '12-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 6,
				'gazde'     => 'Doicesti',
				'g_gazde'   => 3,
				'oaspeti'   => 'STA',
				'g_oaspeti' => 0,
			],[
				'data'      => '12-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 6,
				'gazde'     => 'Viitorul Razvad',
				'g_gazde'   => 4,
				'oaspeti'   => 'Victoria Comisani',
				'g_oaspeti' => 1,
			],[
				'data'      => '12-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 6,
				'gazde'     => 'Vointa Tatarani',
				'g_gazde'   => 0,
				'oaspeti'   => 'Flacara Suta Seaca',
				'g_oaspeti' => 2,
			],[
				'data'      => '12-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 6,
				'gazde'     => 'Sageata Gura Ocnitei',
				'g_gazde'   => 2,
				'oaspeti'   => 'Cetatea 1396 Targoviste',
				'g_oaspeti' => 2,
			],[
				'data'      => '12-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 6,
				'gazde'     => 'Pomicola Raciu',
				'g_gazde'   => 5,
				'oaspeti'   => 'Vointa Sacuieni',
				'g_oaspeti' => 1,
			],[
				'data'      => '12-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 6,
				'gazde'     => 'Sportul Runcu',
				'g_gazde'   => 3,
				'oaspeti'   => 'Olimpicii 2 Ulmi',
				'g_oaspeti' => 0,
			],[
				'data'      => '12-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 6,
				'gazde'     => 'Unirea Lucieni',
				'g_gazde'   => 0,
				'oaspeti'   => 'Viitorul Ocnita',
				'g_oaspeti' => 3,
			],[
				'data'      => '12-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 6,
				'gazde'     => 'Vointa Adanca',
				'g_gazde'   => 6,
				'oaspeti'   => 'Vointa Buciumeni',
				'g_oaspeti' => 1,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 7,
				'gazde'     => 'Vointa Buciumeni',
				'g_gazde'   => 0,
				'oaspeti'   => 'Luceafarul Darmanesti',
				'g_oaspeti' => 4,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 7,
				'gazde'     => 'Viitorul Ocnita',
				'g_gazde'   => 4,
				'oaspeti'   => 'Vointa Adanca',
				'g_oaspeti' => 1,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 7,
				'gazde'     => 'Olimpicii 2 Ulmi',
				'g_gazde'   => 9,
				'oaspeti'   => 'Unirea Lucieni',
				'g_oaspeti' => 0,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 7,
				'gazde'     => 'Vointa Sacuieni',
				'g_gazde'   => 4,
				'oaspeti'   => 'Sportul Runcu',
				'g_oaspeti' => 1,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 7,
				'gazde'     => 'Cetatea 1396 Targoviste',
				'g_gazde'   => 2,
				'oaspeti'   => 'Pomicola Raciu',
				'g_oaspeti' => 0,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 7,
				'gazde'     => 'Flacara Suta Seaca',
				'g_gazde'   => 0,
				'oaspeti'   => 'Sageata Gura Ocnitei',
				'g_oaspeti' => 2,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 7,
				'gazde'     => 'Victoria Comisani',
				'g_gazde'   => 0,
				'oaspeti'   => 'Vointa Tatarani',
				'g_oaspeti' => 3,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 7,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Razvad',
				'g_oaspeti' => null,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 7,
				'gazde'     => 'Vointa Steaua Pietrosita',
				'g_gazde'   => 7,
				'oaspeti'   => 'Doicesti',
				'g_oaspeti' => 4,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 8,
				'gazde'     => 'Luceafarul Darmanesti',
				'g_gazde'   => 7,
				'oaspeti'   => 'Doicesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 8,
				'gazde'     => 'Viitorul Razvad',
				'g_gazde'   => 3,
				'oaspeti'   => 'Vointa Steaua Pietrosita',
				'g_oaspeti' => 5,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 8,
				'gazde'     => 'Vointa Tatarani',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 8,
				'gazde'     => 'Sageata Gura Ocnitei',
				'g_gazde'   => 4,
				'oaspeti'   => 'Victoria Comisani',
				'g_oaspeti' => 1,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 8,
				'gazde'     => 'Pomicola Raciu',
				'g_gazde'   => 2,
				'oaspeti'   => 'Flacara Suta Seaca',
				'g_oaspeti' => 2,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 8,
				'gazde'     => 'Sportul Runcu',
				'g_gazde'   => 4,
				'oaspeti'   => 'Cetatea 1396 Targoviste',
				'g_oaspeti' => 5,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 8,
				'gazde'     => 'Unirea Lucieni',
				'g_gazde'   => 1,
				'oaspeti'   => 'Vointa Sacuieni',
				'g_oaspeti' => 3,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 8,
				'gazde'     => 'Vointa Adanca',
				'g_gazde'   => 5,
				'oaspeti'   => 'Olimpicii 2 Ulmi',
				'g_oaspeti' => 5,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 8,
				'gazde'     => 'Vointa Buciumeni',
				'g_gazde'   => 1,
				'oaspeti'   => 'Viitorul Ocnita',
				'g_oaspeti' => 2,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 9,
				'gazde'     => 'Viitorul Ocnita',
				'g_gazde'   => 3,
				'oaspeti'   => 'Luceafarul Darmanesti',
				'g_oaspeti' => 2,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 9,
				'gazde'     => 'Olimpicii 2 Ulmi',
				'g_gazde'   => 7,
				'oaspeti'   => 'Vointa Buciumeni',
				'g_oaspeti' => 3,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 9,
				'gazde'     => 'Vointa Sacuieni',
				'g_gazde'   => 5,
				'oaspeti'   => 'Vointa Adanca',
				'g_oaspeti' => 3,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 9,
				'gazde'     => 'Cetatea 1396 Targoviste',
				'g_gazde'   => 10,
				'oaspeti'   => 'Unirea Lucieni',
				'g_oaspeti' => 1,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 9,
				'gazde'     => 'Flacara Suta Seaca',
				'g_gazde'   => 5,
				'oaspeti'   => 'Sportul Runcu',
				'g_oaspeti' => 3,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 9,
				'gazde'     => 'Victoria Comisani',
				'g_gazde'   => 4,
				'oaspeti'   => 'Pomicola Raciu',
				'g_oaspeti' => 2,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 9,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Gura Ocnitei',
				'g_oaspeti' => null,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 9,
				'gazde'     => 'Vointa Steaua Pietrosita',
				'g_gazde'   => 0,
				'oaspeti'   => 'Vointa Tatarani',
				'g_oaspeti' => 2,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 9,
				'gazde'     => 'Doicesti',
				'g_gazde'   => 1,
				'oaspeti'   => 'Viitorul Razvad',
				'g_oaspeti' => 5,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 10,
				'gazde'     => 'Luceafarul Darmanesti',
				'g_gazde'   => 2,
				'oaspeti'   => 'Viitorul Razvad',
				'g_oaspeti' => 1,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 10,
				'gazde'     => 'Vointa Tatarani',
				'g_gazde'   => 7,
				'oaspeti'   => 'Doicesti',
				'g_oaspeti' => 3,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 10,
				'gazde'     => 'Sageata Gura Ocnitei',
				'g_gazde'   => 5,
				'oaspeti'   => 'Vointa Steaua Pietrosita',
				'g_oaspeti' => 1,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 10,
				'gazde'     => 'Pomicola Raciu',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 10,
				'gazde'     => 'Sportul Runcu',
				'g_gazde'   => 5,
				'oaspeti'   => 'Victoria Comisani',
				'g_oaspeti' => 0,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 10,
				'gazde'     => 'Unirea Lucieni',
				'g_gazde'   => 1,
				'oaspeti'   => 'Flacara Suta Seaca',
				'g_oaspeti' => 4,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 10,
				'gazde'     => 'Vointa Adanca',
				'g_gazde'   => 0,
				'oaspeti'   => 'Cetatea 1396 Targoviste',
				'g_oaspeti' => 5,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 10,
				'gazde'     => 'Vointa Buciumeni',
				'g_gazde'   => 5,
				'oaspeti'   => 'Vointa Sacuieni',
				'g_oaspeti' => 6,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 10,
				'gazde'     => 'Viitorul Ocnita',
				'g_gazde'   => 6,
				'oaspeti'   => 'Olimpicii 2 Ulmi',
				'g_oaspeti' => 1,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 11,
				'gazde'     => 'Olimpicii 2 Ulmi',
				'g_gazde'   => 2,
				'oaspeti'   => 'Luceafarul Darmanesti',
				'g_oaspeti' => 3,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 11,
				'gazde'     => 'Vointa Sacuieni',
				'g_gazde'   => 2,
				'oaspeti'   => 'Viitorul Ocnita',
				'g_oaspeti' => 2,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 11,
				'gazde'     => 'Cetatea 1396 Targoviste',
				'g_gazde'   => 8,
				'oaspeti'   => 'Vointa Buciumeni',
				'g_oaspeti' => 1,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 11,
				'gazde'     => 'Flacara Suta Seaca',
				'g_gazde'   => 6,
				'oaspeti'   => 'Vointa Adanca',
				'g_oaspeti' => 3,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 11,
				'gazde'     => 'Victoria Comisani',
				'g_gazde'   => 7,
				'oaspeti'   => 'Unirea Lucieni',
				'g_oaspeti' => 2,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 11,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Runcu',
				'g_oaspeti' => null,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 11,
				'gazde'     => 'Vointa Steaua Pietrosita',
				'g_gazde'   => 3,
				'oaspeti'   => 'Pomicola Raciu',
				'g_oaspeti' => 0,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 11,
				'gazde'     => 'Doicesti',
				'g_gazde'   => 3,
				'oaspeti'   => 'Sageata Gura Ocnitei',
				'g_oaspeti' => 6,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 11,
				'gazde'     => 'Viitorul Razvad',
				'g_gazde'   => 1,
				'oaspeti'   => 'Vointa Tatarani',
				'g_oaspeti' => 2,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 12,
				'gazde'     => 'Luceafarul Darmanesti',
				'g_gazde'   => 1,
				'oaspeti'   => 'Vointa Tatarani',
				'g_oaspeti' => 0,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 12,
				'gazde'     => 'Sageata Gura Ocnitei',
				'g_gazde'   => 1,
				'oaspeti'   => 'Viitorul Razvad',
				'g_oaspeti' => 1,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 12,
				'gazde'     => 'Pomicola Raciu',
				'g_gazde'   => 3,
				'oaspeti'   => 'Doicesti',
				'g_oaspeti' => 0,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 12,
				'gazde'     => 'Sportul Runcu',
				'g_gazde'   => 2,
				'oaspeti'   => 'Vointa Steaua Pietrosita',
				'g_oaspeti' => 0,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 12,
				'gazde'     => 'Unirea Lucieni',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 12,
				'gazde'     => 'Vointa Adanca',
				'g_gazde'   => 6,
				'oaspeti'   => 'Victoria Comisani',
				'g_oaspeti' => 2,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 12,
				'gazde'     => 'Vointa Buciumeni',
				'g_gazde'   => 2,
				'oaspeti'   => 'Flacara Suta Seaca',
				'g_oaspeti' => 1,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 12,
				'gazde'     => 'Viitorul Ocnita',
				'g_gazde'   => 2,
				'oaspeti'   => 'Cetatea 1396 Targoviste',
				'g_oaspeti' => 4,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 12,
				'gazde'     => 'Olimpicii 2 Ulmi',
				'g_gazde'   => 5,
				'oaspeti'   => 'Vointa Sacuieni',
				'g_oaspeti' => 3,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 13,
				'gazde'     => 'Vointa Sacuieni',
				'g_gazde'   => 3,
				'oaspeti'   => 'Luceafarul Darmanesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 13,
				'gazde'     => 'Cetatea 1396 Targoviste',
				'g_gazde'   => 4,
				'oaspeti'   => 'Olimpicii 2 Ulmi',
				'g_oaspeti' => 0,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 13,
				'gazde'     => 'Flacara Suta Seaca',
				'g_gazde'   => 6,
				'oaspeti'   => 'Viitorul Ocnita',
				'g_oaspeti' => 0,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 13,
				'gazde'     => 'Victoria Comisani',
				'g_gazde'   => 1,
				'oaspeti'   => 'Vointa Buciumeni',
				'g_oaspeti' => 2,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 13,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Adanca',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 13,
				'gazde'     => 'Vointa Steaua Pietrosita',
				'g_gazde'   => 3,
				'oaspeti'   => 'Unirea Lucieni',
				'g_oaspeti' => 2,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 13,
				'gazde'     => 'Doicesti',
				'g_gazde'   => 0,
				'oaspeti'   => 'Sportul Runcu',
				'g_oaspeti' => 3,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 13,
				'gazde'     => 'Viitorul Razvad',
				'g_gazde'   => 3,
				'oaspeti'   => 'Pomicola Raciu',
				'g_oaspeti' => 0,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 13,
				'gazde'     => 'Vointa Tatarani',
				'g_gazde'   => 3,
				'oaspeti'   => 'Sageata Gura Ocnitei',
				'g_oaspeti' => 2,
			],[
				'data'      => '04-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 14,
				'gazde'     => 'Luceafarul Darmanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Gura Ocnitei',
				'g_oaspeti' => null,
			],[
				'data'      => '04-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 14,
				'gazde'     => 'Pomicola Raciu',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Tatarani',
				'g_oaspeti' => null,
			],[
				'data'      => '04-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 14,
				'gazde'     => 'Sportul Runcu',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Razvad',
				'g_oaspeti' => null,
			],[
				'data'      => '04-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 14,
				'gazde'     => 'Unirea Lucieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Doicesti',
				'g_oaspeti' => null,
			],[
				'data'      => '04-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 14,
				'gazde'     => 'Vointa Adanca',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Steaua Pietrosita',
				'g_oaspeti' => null,
			],[
				'data'      => '04-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 14,
				'gazde'     => 'Vointa Buciumeni',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '04-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 14,
				'gazde'     => 'Viitorul Ocnita',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => '04-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 14,
				'gazde'     => 'Olimpicii 2 Ulmi',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Suta Seaca',
				'g_oaspeti' => null,
			],[
				'data'      => '04-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 14,
				'gazde'     => 'Vointa Sacuieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Cetatea 1396 Targoviste',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 15,
				'gazde'     => 'Cetatea 1396 Targoviste',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Darmanesti',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 15,
				'gazde'     => 'Flacara Suta Seaca',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Sacuieni',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 15,
				'gazde'     => 'Victoria Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii 2 Ulmi',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 15,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Ocnita',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 15,
				'gazde'     => 'Vointa Steaua Pietrosita',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Buciumeni',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 15,
				'gazde'     => 'Doicesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Adanca',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 15,
				'gazde'     => 'Viitorul Razvad',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Lucieni',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 15,
				'gazde'     => 'Vointa Tatarani',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Runcu',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 15,
				'gazde'     => 'Sageata Gura Ocnitei',
				'g_gazde'   => null,
				'oaspeti'   => 'Pomicola Raciu',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 16,
				'gazde'     => 'Luceafarul Darmanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Pomicola Raciu',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 16,
				'gazde'     => 'Sportul Runcu',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Gura Ocnitei',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 16,
				'gazde'     => 'Unirea Lucieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Tatarani',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 16,
				'gazde'     => 'Vointa Adanca',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Razvad',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 16,
				'gazde'     => 'Vointa Buciumeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Doicesti',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 16,
				'gazde'     => 'Viitorul Ocnita',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Steaua Pietrosita',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 16,
				'gazde'     => 'Olimpicii 2 Ulmi',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 16,
				'gazde'     => 'Vointa Sacuieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 16,
				'gazde'     => 'Cetatea 1396 Targoviste',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Suta Seaca',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 17,
				'gazde'     => 'Flacara Suta Seaca',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Darmanesti',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 17,
				'gazde'     => 'Victoria Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Cetatea 1396 Targoviste',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 17,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Sacuieni',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 17,
				'gazde'     => 'Vointa Steaua Pietrosita',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii 2 Ulmi',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 17,
				'gazde'     => 'Doicesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Ocnita',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 17,
				'gazde'     => 'Viitorul Razvad',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Buciumeni',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 17,
				'gazde'     => 'Vointa Tatarani',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Adanca',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 17,
				'gazde'     => 'Sageata Gura Ocnitei',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Lucieni',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 17,
				'gazde'     => 'Pomicola Raciu',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Runcu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 18,
				'gazde'     => 'Luceafarul Darmanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Runcu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 18,
				'gazde'     => 'Pomicola Raciu',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Lucieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 18,
				'gazde'     => 'Sageata Gura Ocnitei',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Adanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 18,
				'gazde'     => 'Vointa Tatarani',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Buciumeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 18,
				'gazde'     => 'Viitorul Razvad',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Ocnita',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 18,
				'gazde'     => 'Doicesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii 2 Ulmi',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 18,
				'gazde'     => 'Vointa Steaua Pietrosita',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Sacuieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 18,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Cetatea 1396 Targoviste',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 18,
				'gazde'     => 'Victoria Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Suta Seaca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 19,
				'gazde'     => 'Victoria Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Darmanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 19,
				'gazde'     => 'Flacara Suta Seaca',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 19,
				'gazde'     => 'Cetatea 1396 Targoviste',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Steaua Pietrosita',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 19,
				'gazde'     => 'Vointa Sacuieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Doicesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 19,
				'gazde'     => 'Olimpicii 2 Ulmi',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Razvad',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 19,
				'gazde'     => 'Viitorul Ocnita',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Tatarani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 19,
				'gazde'     => 'Vointa Buciumeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Gura Ocnitei',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 19,
				'gazde'     => 'Vointa Adanca',
				'g_gazde'   => null,
				'oaspeti'   => 'Pomicola Raciu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 19,
				'gazde'     => 'Unirea Lucieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Runcu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 20,
				'gazde'     => 'Luceafarul Darmanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Lucieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 20,
				'gazde'     => 'Sportul Runcu',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Adanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 20,
				'gazde'     => 'Pomicola Raciu',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Buciumeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 20,
				'gazde'     => 'Sageata Gura Ocnitei',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Ocnita',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 20,
				'gazde'     => 'Vointa Tatarani',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii 2 Ulmi',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 20,
				'gazde'     => 'Viitorul Razvad',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Sacuieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 20,
				'gazde'     => 'Doicesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Cetatea 1396 Targoviste',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 20,
				'gazde'     => 'Vointa Steaua Pietrosita',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Suta Seaca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 20,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 21,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Darmanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 21,
				'gazde'     => 'Victoria Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Steaua Pietrosita',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 21,
				'gazde'     => 'Flacara Suta Seaca',
				'g_gazde'   => null,
				'oaspeti'   => 'Doicesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 21,
				'gazde'     => 'Cetatea 1396 Targoviste',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Razvad',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 21,
				'gazde'     => 'Vointa Sacuieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Tatarani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 21,
				'gazde'     => 'Olimpicii 2 Ulmi',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Gura Ocnitei',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 21,
				'gazde'     => 'Viitorul Ocnita',
				'g_gazde'   => null,
				'oaspeti'   => 'Pomicola Raciu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 21,
				'gazde'     => 'Vointa Buciumeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Runcu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 21,
				'gazde'     => 'Vointa Adanca',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Lucieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 22,
				'gazde'     => 'Luceafarul Darmanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Adanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 22,
				'gazde'     => 'Unirea Lucieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Buciumeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 22,
				'gazde'     => 'Sportul Runcu',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Ocnita',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 22,
				'gazde'     => 'Pomicola Raciu',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii 2 Ulmi',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 22,
				'gazde'     => 'Sageata Gura Ocnitei',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Sacuieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 22,
				'gazde'     => 'Vointa Tatarani',
				'g_gazde'   => null,
				'oaspeti'   => 'Cetatea 1396 Targoviste',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 22,
				'gazde'     => 'Viitorul Razvad',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Suta Seaca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 22,
				'gazde'     => 'Doicesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 22,
				'gazde'     => 'Vointa Steaua Pietrosita',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 23,
				'gazde'     => 'Vointa Steaua Pietrosita',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Darmanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 23,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Doicesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 23,
				'gazde'     => 'Victoria Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Razvad',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 23,
				'gazde'     => 'Flacara Suta Seaca',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Tatarani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 23,
				'gazde'     => 'Cetatea 1396 Targoviste',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Gura Ocnitei',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 23,
				'gazde'     => 'Vointa Sacuieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Pomicola Raciu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 23,
				'gazde'     => 'Olimpicii 2 Ulmi',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Runcu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 23,
				'gazde'     => 'Viitorul Ocnita',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Lucieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 23,
				'gazde'     => 'Vointa Buciumeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Adanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 24,
				'gazde'     => 'Luceafarul Darmanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Buciumeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 24,
				'gazde'     => 'Vointa Adanca',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Ocnita',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 24,
				'gazde'     => 'Unirea Lucieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii 2 Ulmi',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 24,
				'gazde'     => 'Sportul Runcu',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Sacuieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 24,
				'gazde'     => 'Pomicola Raciu',
				'g_gazde'   => null,
				'oaspeti'   => 'Cetatea 1396 Targoviste',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 24,
				'gazde'     => 'Sageata Gura Ocnitei',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Suta Seaca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 24,
				'gazde'     => 'Vointa Tatarani',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 24,
				'gazde'     => 'Viitorul Razvad',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 24,
				'gazde'     => 'Doicesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Steaua Pietrosita',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 25,
				'gazde'     => 'Doicesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Darmanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 25,
				'gazde'     => 'Vointa Steaua Pietrosita',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Razvad',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 25,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Tatarani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 25,
				'gazde'     => 'Victoria Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Gura Ocnitei',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 25,
				'gazde'     => 'Flacara Suta Seaca',
				'g_gazde'   => null,
				'oaspeti'   => 'Pomicola Raciu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 25,
				'gazde'     => 'Cetatea 1396 Targoviste',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Runcu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 25,
				'gazde'     => 'Vointa Sacuieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Lucieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 25,
				'gazde'     => 'Olimpicii 2 Ulmi',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Adanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 25,
				'gazde'     => 'Viitorul Ocnita',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Buciumeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 26,
				'gazde'     => 'Luceafarul Darmanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Ocnita',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 26,
				'gazde'     => 'Vointa Buciumeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii 2 Ulmi',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 26,
				'gazde'     => 'Vointa Adanca',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Sacuieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 26,
				'gazde'     => 'Unirea Lucieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Cetatea 1396 Targoviste',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 26,
				'gazde'     => 'Sportul Runcu',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Suta Seaca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 26,
				'gazde'     => 'Pomicola Raciu',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 26,
				'gazde'     => 'Sageata Gura Ocnitei',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 26,
				'gazde'     => 'Vointa Tatarani',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Steaua Pietrosita',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 26,
				'gazde'     => 'Viitorul Razvad',
				'g_gazde'   => null,
				'oaspeti'   => 'Doicesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 27,
				'gazde'     => 'Viitorul Razvad',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Darmanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 27,
				'gazde'     => 'Doicesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Tatarani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 27,
				'gazde'     => 'Vointa Steaua Pietrosita',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Gura Ocnitei',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 27,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Pomicola Raciu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 27,
				'gazde'     => 'Victoria Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Runcu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 27,
				'gazde'     => 'Flacara Suta Seaca',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Lucieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 27,
				'gazde'     => 'Cetatea 1396 Targoviste',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Adanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 27,
				'gazde'     => 'Vointa Sacuieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Buciumeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 27,
				'gazde'     => 'Olimpicii 2 Ulmi',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Ocnita',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 28,
				'gazde'     => 'Luceafarul Darmanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii 2 Ulmi',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 28,
				'gazde'     => 'Viitorul Ocnita',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Sacuieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 28,
				'gazde'     => 'Vointa Buciumeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Cetatea 1396 Targoviste',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 28,
				'gazde'     => 'Vointa Adanca',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Suta Seaca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 28,
				'gazde'     => 'Unirea Lucieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 28,
				'gazde'     => 'Sportul Runcu',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 28,
				'gazde'     => 'Pomicola Raciu',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Steaua Pietrosita',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 28,
				'gazde'     => 'Sageata Gura Ocnitei',
				'g_gazde'   => null,
				'oaspeti'   => 'Doicesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 28,
				'gazde'     => 'Vointa Tatarani',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Razvad',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 29,
				'gazde'     => 'Vointa Tatarani',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Darmanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 29,
				'gazde'     => 'Viitorul Razvad',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Gura Ocnitei',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 29,
				'gazde'     => 'Doicesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Pomicola Raciu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 29,
				'gazde'     => 'Vointa Steaua Pietrosita',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Runcu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 29,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Lucieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 29,
				'gazde'     => 'Victoria Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Adanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 29,
				'gazde'     => 'Flacara Suta Seaca',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Buciumeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 29,
				'gazde'     => 'Cetatea 1396 Targoviste',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Ocnita',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 29,
				'gazde'     => 'Vointa Sacuieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii 2 Ulmi',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 30,
				'gazde'     => 'Luceafarul Darmanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Sacuieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 30,
				'gazde'     => 'Olimpicii 2 Ulmi',
				'g_gazde'   => null,
				'oaspeti'   => 'Cetatea 1396 Targoviste',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 30,
				'gazde'     => 'Viitorul Ocnita',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Suta Seaca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 30,
				'gazde'     => 'Vointa Buciumeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 30,
				'gazde'     => 'Vointa Adanca',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 30,
				'gazde'     => 'Unirea Lucieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Steaua Pietrosita',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 30,
				'gazde'     => 'Sportul Runcu',
				'g_gazde'   => null,
				'oaspeti'   => 'Doicesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 30,
				'gazde'     => 'Pomicola Raciu',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Razvad',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 30,
				'gazde'     => 'Sageata Gura Ocnitei',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Tatarani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 31,
				'gazde'     => 'Sageata Gura Ocnitei',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Darmanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 31,
				'gazde'     => 'Vointa Tatarani',
				'g_gazde'   => null,
				'oaspeti'   => 'Pomicola Raciu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 31,
				'gazde'     => 'Viitorul Razvad',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Runcu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 31,
				'gazde'     => 'Doicesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Lucieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 31,
				'gazde'     => 'Vointa Steaua Pietrosita',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Adanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 31,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Buciumeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 31,
				'gazde'     => 'Victoria Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Ocnita',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 31,
				'gazde'     => 'Flacara Suta Seaca',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii 2 Ulmi',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 31,
				'gazde'     => 'Cetatea 1396 Targoviste',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Sacuieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 32,
				'gazde'     => 'Luceafarul Darmanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Cetatea 1396 Targoviste',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 32,
				'gazde'     => 'Vointa Sacuieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Suta Seaca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 32,
				'gazde'     => 'Olimpicii 2 Ulmi',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 32,
				'gazde'     => 'Viitorul Ocnita',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 32,
				'gazde'     => 'Vointa Buciumeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Steaua Pietrosita',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 32,
				'gazde'     => 'Vointa Adanca',
				'g_gazde'   => null,
				'oaspeti'   => 'Doicesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 32,
				'gazde'     => 'Unirea Lucieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Razvad',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 32,
				'gazde'     => 'Sportul Runcu',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Tatarani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 32,
				'gazde'     => 'Pomicola Raciu',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Gura Ocnitei',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 33,
				'gazde'     => 'Pomicola Raciu',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Darmanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 33,
				'gazde'     => 'Sageata Gura Ocnitei',
				'g_gazde'   => null,
				'oaspeti'   => 'Sportul Runcu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 33,
				'gazde'     => 'Vointa Tatarani',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Lucieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 33,
				'gazde'     => 'Viitorul Razvad',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Adanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 33,
				'gazde'     => 'Doicesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Buciumeni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 33,
				'gazde'     => 'Vointa Steaua Pietrosita',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Ocnita',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 33,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpicii 2 Ulmi',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 33,
				'gazde'     => 'Victoria Comisani',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Sacuieni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 33,
				'gazde'     => 'Flacara Suta Seaca',
				'g_gazde'   => null,
				'oaspeti'   => 'Cetatea 1396 Targoviste',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 34,
				'gazde'     => 'Luceafarul Darmanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Suta Seaca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 34,
				'gazde'     => 'Cetatea 1396 Targoviste',
				'g_gazde'   => null,
				'oaspeti'   => 'Victoria Comisani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 34,
				'gazde'     => 'Vointa Sacuieni',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 34,
				'gazde'     => 'Olimpicii 2 Ulmi',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Steaua Pietrosita',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 34,
				'gazde'     => 'Viitorul Ocnita',
				'g_gazde'   => null,
				'oaspeti'   => 'Doicesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 34,
				'gazde'     => 'Vointa Buciumeni',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Razvad',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 34,
				'gazde'     => 'Vointa Adanca',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Tatarani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 34,
				'gazde'     => 'Unirea Lucieni',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Gura Ocnitei',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'NORD',
				'etapa'     => 34,
				'gazde'     => 'Sportul Runcu',
				'g_gazde'   => null,
				'oaspeti'   => 'Pomicola Raciu',
				'g_oaspeti' => null,
			]
    	];

    	Echipe::where('liga', 5)->where('serie', 'NORD')->delete();
		foreach ($echipe as $echipa) {
			$adauga = new Echipe;
			$adauga->echipa = trim($echipa['echipa']);
			$adauga->liga   = $echipa['liga'];
			$adauga->serie  = $echipa['serie'];
			$adauga->save();
		}

		Etape::where('liga', 5)->where('serie', 'NORD')->delete();
		foreach ($etape as $etapa) {
			$adauga = new Etape;
			$adauga->gazde     = trim($etapa['gazde']);
			$adauga->oaspeti   = trim($etapa['oaspeti']);
			$adauga->g_gazde   = $etapa['g_gazde'];
			$adauga->g_oaspeti = $etapa['g_oaspeti'];
			$adauga->liga      = $etapa['liga'];
			$adauga->serie     = $etapa['serie'];
			$adauga->etapa     = $etapa['etapa'];
			$adauga->data      = $etapa['data'] != NULL ? DateTime::createFromFormat('d-m-Y', ($etapa['data']))->format('Y-m-d') : NULL;
			$adauga->ora       = $etapa['ora'];
			$adauga->save();
		}
    }
}
