<?php

use Illuminate\Database\Seeder;
use App\Echipe;
use App\Etape;

class liga_4 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        $echipe = [
			[
				'echipa' => 'Sportul Voinesti 2016',
				'liga'   => 4,
				'serie'  => NULL,
			], [
				'echipa' => 'C.S.M Fieni',
				'liga'   => 4,
				'serie'  => NULL,
			], [
				'echipa' => 'Viitorul I.L. Caragiale',
				'liga'   => 4,
				'serie'  => NULL,
			], [
				'echipa' => 'Recolta Gura Sutii',
				'liga'   => 4,
				'serie'  => NULL,
			], [
				'echipa' => 'Coada Izvorului',
				'liga'   => 4,
				'serie'  => NULL,
			], [
				'echipa' => 'FC Brezoaele',
				'liga'   => 4,
				'serie'  => NULL,
			], [
				'echipa' => 'Olimpicii Ulmi',
				'liga'   => 4,
				'serie'  => NULL,
			], [
				'echipa' => 'Progresul Matasaru',
				'liga'   => 4,
				'serie'  => NULL,
			], [
				'echipa' => 'Luceafarul Dragomiresti',
				'liga'   => 4,
				'serie'  => NULL,
			], [
				'echipa' => 'Petrolul Targoviste',
				'liga'   => 4,
				'serie'  => NULL,
			], [
				'echipa' => 'Unirea 2018 Racari',
				'liga'   => 4,
				'serie'  => NULL,
			], [
				'echipa' => 'Unirea Bucsani',
				'liga'   => 4,
				'serie'  => NULL,
			], [
				'echipa' => 'Vointa Visina',
				'liga'   => 4,
				'serie'  => NULL,
			], [
				'echipa' => 'Roberto Ziduri',
				'liga'   => 4,
				'serie'  => NULL,
			], [
				'echipa' => 'Unirea Colibasi',
				'liga'   => 4,
				'serie'  => NULL,
			], [
				'echipa' => 'Vointa Piersinari',
				'liga'   => 4,
				'serie'  => NULL,
			], [
				'echipa' => 'Unirea Ungureni',
				'liga'   => 4,
				'serie'  => NULL,
			], [
				'echipa' => 'Gloria 2015 Cornesti',
				'liga'   => 4,
				'serie'  => NULL,
			]
		];

        $etape = [
			[
				'data'     => '18-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 1,
				'gazde'    => 'Sportul Voinesti 2016',
				'g_gazde'  => 2,
				'oaspeti'  => 'C.S.M Fieni',
				'g_oaspeti'=> 8,
			],[
				'data'     => '18-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 1,
				'gazde'    => 'Viitorul I.L. Caragiale',
				'g_gazde'  => 3,
				'oaspeti'  => 'Recolta Gura Sutii',
				'g_oaspeti'=> 6,
			],[
				'data'     => '18-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 1,
				'gazde'    => 'Coada Izvorului',
				'g_gazde'  => 1,
				'oaspeti'  => 'FC Brezoaele',
				'g_oaspeti'=> 3,
			],[
				'data'     => '18-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 1,
				'gazde'    => 'Olimpicii Ulmi',
				'g_gazde'  => 5,
				'oaspeti'  => 'Progresul Matasaru',
				'g_oaspeti'=> 0,
			],[
				'data'     => '18-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 1,
				'gazde'    => 'Luceafarul Dragomiresti',
				'g_gazde'  => 2,
				'oaspeti'  => 'Petrolul Targoviste',
				'g_oaspeti'=> 0,
			],[
				'data'     => '18-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 1,
				'gazde'    => 'Unirea 2018 Racari',
				'g_gazde'  => 3,
				'oaspeti'  => 'Unirea Bucsani',
				'g_oaspeti'=> 0,
			],[
				'data'     => '18-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 1,
				'gazde'    => 'Vointa Visina',
				'g_gazde'  => 1,
				'oaspeti'  => 'Roberto Ziduri',
				'g_oaspeti'=> 1,
			],[
				'data'     => '18-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 1,
				'gazde'    => 'Unirea Colibasi',
				'g_gazde'  => 5,
				'oaspeti'  => 'Vointa Piersinari',
				'g_oaspeti'=> 3,
			],[
				'data'     => '18-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 1,
				'gazde'    => 'Unirea Ungureni',
				'g_gazde'  => 1,
				'oaspeti'  => 'Gloria 2015 Cornesti',
				'g_oaspeti'=> 6,
			],[
				'data'     => '25-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 2,
				'gazde'    => 'C.S.M Fieni',
				'g_gazde'  => 2,
				'oaspeti'  => 'Unirea Ungureni',
				'g_oaspeti'=> 1,
			],[
				'data'     => '25-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 2,
				'gazde'    => 'Gloria 2015 Cornesti',
				'g_gazde'  => 5,
				'oaspeti'  => 'Unirea Colibasi',
				'g_oaspeti'=> 1,
			],[
				'data'     => '25-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 2,
				'gazde'    => 'Vointa Piersinari',
				'g_gazde'  => 5,
				'oaspeti'  => 'Vointa Visina',
				'g_oaspeti'=> 2,
			],[
				'data'     => '25-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 2,
				'gazde'    => 'Roberto Ziduri',
				'g_gazde'  => 0,
				'oaspeti'  => 'Unirea 2018 Racari',
				'g_oaspeti'=> 1,
			],[
				'data'     => '25-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 2,
				'gazde'    => 'Unirea Bucsani',
				'g_gazde'  => 3,
				'oaspeti'  => 'Luceafarul Dragomiresti',
				'g_oaspeti'=> 0,
			],[
				'data'     => '25-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 2,
				'gazde'    => 'Petrolul Targoviste',
				'g_gazde'  => 1,
				'oaspeti'  => 'Olimpicii Ulmi',
				'g_oaspeti'=> 1,
			],[
				'data'     => '25-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 2,
				'gazde'    => 'Progresul Matasaru',
				'g_gazde'  => 9,
				'oaspeti'  => 'Coada Izvorului',
				'g_oaspeti'=> 0,
			],[
				'data'     => '25-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 2,
				'gazde'    => 'FC Brezoaele',
				'g_gazde'  => 4,
				'oaspeti'  => 'Viitorul I.L. Caragiale',
				'g_oaspeti'=> 0,
			],[
				'data'     => '25-08-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 2,
				'gazde'    => 'Recolta Gura Sutii',
				'g_gazde'  => 6,
				'oaspeti'  => 'Sportul Voinesti 2016',
				'g_oaspeti'=> 1,
			],[
				'data'     => '28-08-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 3,
				'gazde'    => 'C.S.M Fieni',
				'g_gazde'  => 1,
				'oaspeti'  => 'Recolta Gura Sutii',
				'g_oaspeti'=> 2,
			],[
				'data'     => '28-08-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 3,
				'gazde'    => 'Sportul Voinesti 2016',
				'g_gazde'  => 1,
				'oaspeti'  => 'FC Brezoaele',
				'g_oaspeti'=> 1,
			],[
				'data'     => '28-08-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 3,
				'gazde'    => 'Viitorul I.L. Caragiale',
				'g_gazde'  => 2,
				'oaspeti'  => 'Progresul Matasaru',
				'g_oaspeti'=> 1,
			],[
				'data'     => '28-08-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 3,
				'gazde'    => 'Coada Izvorului',
				'g_gazde'  => 0,
				'oaspeti'  => 'Petrolul Targoviste',
				'g_oaspeti'=> 0,
			],[
				'data'     => '28-08-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 3,
				'gazde'    => 'Olimpicii Ulmi',
				'g_gazde'  => 2,
				'oaspeti'  => 'Unirea Bucsani',
				'g_oaspeti'=> 0,
			],[
				'data'     => '28-08-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 3,
				'gazde'    => 'Luceafarul Dragomiresti',
				'g_gazde'  => 3,
				'oaspeti'  => 'Roberto Ziduri',
				'g_oaspeti'=> 5,
			],[
				'data'     => '28-08-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 3,
				'gazde'    => 'Unirea 2018 Racari',
				'g_gazde'  => 0,
				'oaspeti'  => 'Vointa Piersinari',
				'g_oaspeti'=> 2,
			],[
				'data'     => '28-08-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 3,
				'gazde'    => 'Vointa Visina',
				'g_gazde'  => 2,
				'oaspeti'  => 'Gloria 2015 Cornesti',
				'g_oaspeti'=> 8,
			],[
				'data'     => '28-08-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 3,
				'gazde'    => 'Unirea Colibasi',
				'g_gazde'  => 2,
				'oaspeti'  => 'Unirea Ungureni',
				'g_oaspeti'=> 0,
			],[
				'data'     => '01-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 4,
				'gazde'    => 'Unirea Colibasi',
				'g_gazde'  => 0,
				'oaspeti'  => 'C.S.M Fieni',
				'g_oaspeti'=> 5,
			],[
				'data'     => '01-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 4,
				'gazde'    => 'Unirea Ungureni',
				'g_gazde'  => 2,
				'oaspeti'  => 'Vointa Visina',
				'g_oaspeti'=> 4,
			],[
				'data'     => '01-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 4,
				'gazde'    => 'Gloria 2015 Cornesti',
				'g_gazde'  => 3,
				'oaspeti'  => 'Unirea 2018 Racari',
				'g_oaspeti'=> 0,
			],[
				'data'     => '01-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 4,
				'gazde'    => 'Vointa Piersinari',
				'g_gazde'  => 6,
				'oaspeti'  => 'Luceafarul Dragomiresti',
				'g_oaspeti'=> 4,
			],[
				'data'     => '01-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 4,
				'gazde'    => 'Roberto Ziduri',
				'g_gazde'  => 3,
				'oaspeti'  => 'Olimpicii Ulmi',
				'g_oaspeti'=> 0,
			],[
				'data'     => '01-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 4,
				'gazde'    => 'Unirea Bucsani',
				'g_gazde'  => 4,
				'oaspeti'  => 'Coada Izvorului',
				'g_oaspeti'=> 0,
			],[
				'data'     => '01-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 4,
				'gazde'    => 'Petrolul Targoviste',
				'g_gazde'  => 7,
				'oaspeti'  => 'Viitorul I.L. Caragiale',
				'g_oaspeti'=> 0,
			],[
				'data'     => '01-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 4,
				'gazde'    => 'Progresul Matasaru',
				'g_gazde'  => 6,
				'oaspeti'  => 'Sportul Voinesti 2016',
				'g_oaspeti'=> 4,
			],[
				'data'     => '01-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 4,
				'gazde'    => 'FC Brezoaele',
				'g_gazde'  => 0,
				'oaspeti'  => 'Recolta Gura Sutii',
				'g_oaspeti'=> 0,
			],[
				'data'     => '08-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 5,
				'gazde'    => 'C.S.M Fieni',
				'g_gazde'  => 1,
				'oaspeti'  => 'FC Brezoaele',
				'g_oaspeti'=> 2,
			],[
				'data'     => '08-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 5,
				'gazde'    => 'Recolta Gura Sutii',
				'g_gazde'  => 7,
				'oaspeti'  => 'Progresul Matasaru',
				'g_oaspeti'=> 0,
			],[
				'data'     => '08-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 5,
				'gazde'    => 'Sportul Voinesti 2016',
				'g_gazde'  => 2,
				'oaspeti'  => 'Petrolul Targoviste',
				'g_oaspeti'=> 0,
			],[
				'data'     => '08-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 5,
				'gazde'    => 'Viitorul I.L. Caragiale',
				'g_gazde'  => 3,
				'oaspeti'  => 'Unirea Bucsani',
				'g_oaspeti'=> 0,
			],[
				'data'     => '08-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 5,
				'gazde'    => 'Coada Izvorului',
				'g_gazde'  => 1,
				'oaspeti'  => 'Roberto Ziduri',
				'g_oaspeti'=> 3,
			],[
				'data'     => '08-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 5,
				'gazde'    => 'Olimpicii Ulmi',
				'g_gazde'  => 0,
				'oaspeti'  => 'Vointa Piersinari',
				'g_oaspeti'=> 3,
			],[
				'data'     => '08-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 5,
				'gazde'    => 'Luceafarul Dragomiresti',
				'g_gazde'  => 2,
				'oaspeti'  => 'Gloria 2015 Cornesti',
				'g_oaspeti'=> 7,
			],[
				'data'     => '08-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 5,
				'gazde'    => 'Unirea 2018 Racari',
				'g_gazde'  => 9,
				'oaspeti'  => 'Unirea Ungureni',
				'g_oaspeti'=> 2,
			],[
				'data'     => '08-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 5,
				'gazde'    => 'Vointa Visina',
				'g_gazde'  => 4,
				'oaspeti'  => 'Unirea Colibasi',
				'g_oaspeti'=> 1,
			],[
				'data'     => '11-09-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 6,
				'gazde'    => 'Vointa Visina',
				'g_gazde'  => 1,
				'oaspeti'  => 'C.S.M Fieni',
				'g_oaspeti'=> 0,
			],[
				'data'     => '11-09-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 6,
				'gazde'    => 'Unirea Colibasi',
				'g_gazde'  => 3,
				'oaspeti'  => 'Unirea 2018 Racari',
				'g_oaspeti'=> 5,
			],[
				'data'     => '11-09-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 6,
				'gazde'    => 'Unirea Ungureni',
				'g_gazde'  => 2,
				'oaspeti'  => 'Luceafarul Dragomiresti',
				'g_oaspeti'=> 0,
			],[
				'data'     => '11-09-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 6,
				'gazde'    => 'Gloria 2015 Cornesti',
				'g_gazde'  => 4,
				'oaspeti'  => 'Olimpicii Ulmi',
				'g_oaspeti'=> 2,
			],[
				'data'     => '11-09-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 6,
				'gazde'    => 'Vointa Piersinari',
				'g_gazde'  => 7,
				'oaspeti'  => 'Coada Izvorului',
				'g_oaspeti'=> 2,
			],[
				'data'     => '11-09-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 6,
				'gazde'    => 'Roberto Ziduri',
				'g_gazde'  => 3,
				'oaspeti'  => 'Viitorul I.L. Caragiale',
				'g_oaspeti'=> 0,
			],[
				'data'     => '11-09-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 6,
				'gazde'    => 'Unirea Bucsani',
				'g_gazde'  => 1,
				'oaspeti'  => 'Sportul Voinesti 2016',
				'g_oaspeti'=> 2,
			],[
				'data'     => '11-09-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 6,
				'gazde'    => 'Petrolul Targoviste',
				'g_gazde'  => 1,
				'oaspeti'  => 'Recolta Gura Sutii',
				'g_oaspeti'=> 2,
			],[
				'data'     => '11-09-2018',
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 6,
				'gazde'    => 'Progresul Matasaru',
				'g_gazde'  => 2,
				'oaspeti'  => 'FC Brezoaele',
				'g_oaspeti'=> 2,
			],[
				'data'     => '15-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 7,
				'gazde'    => 'C.S.M Fieni',
				'g_gazde'  => 5,
				'oaspeti'  => 'Progresul Matasaru',
				'g_oaspeti'=> 3,
			],[
				'data'     => '15-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    =>null,
				'etapa'    => 7,
				'gazde'    => 'FC Brezoaele',
				'g_gazde'  => 11,
				'oaspeti'  => 'Petrolul Targoviste',
				'g_oaspeti'=> 2,
			],[
				'data'     => '15-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 7,
				'gazde'    => 'Recolta Gura Sutii',
				'g_gazde'  => 6,
				'oaspeti'  => 'Unirea Bucsani',
				'g_oaspeti'=> 3,
			],[
				'data'     => '15-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 7,
				'gazde'    => 'Sportul Voinesti 2016',
				'g_gazde'  => 3,
				'oaspeti'  => 'Roberto Ziduri',
				'g_oaspeti'=> 6,
			],[
				'data'     => '15-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 7,
				'gazde'    => 'Viitorul I.L. Caragiale',
				'g_gazde'  => 3,
				'oaspeti'  => 'Vointa Piersinari',
				'g_oaspeti'=> 6,
			],[
				'data'     => '15-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 7,
				'gazde'    => 'Coada Izvorului',
				'g_gazde'  => 4,
				'oaspeti'  => 'Gloria 2015 Cornesti',
				'g_oaspeti'=> 5,
			],[
				'data'     => '15-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 7,
				'gazde'    => 'Olimpicii Ulmi',
				'g_gazde'  => 9,
				'oaspeti'  => 'Unirea Ungureni',
				'g_oaspeti'=> 3,
			],[
				'data'     => '15-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 7,
				'gazde'    => 'Luceafarul Dragomiresti',
				'g_gazde'  => 1,
				'oaspeti'  => 'Unirea Colibasi',
				'g_oaspeti'=> 4,
			],[
				'data'     => '15-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 7,
				'gazde'    => 'Unirea 2018 Racari',
				'g_gazde'  => 4,
				'oaspeti'  => 'Vointa Visina',
				'g_oaspeti'=> 3,
			],[
				'data'     => '22-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 8,
				'gazde'    => 'Unirea 2018 Racari',
				'g_gazde'  => 4,
				'oaspeti'  => 'C.S.M Fieni',
				'g_oaspeti'=> 0,
			],[
				'data'     => '22-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 8,
				'gazde'    => 'Vointa Visina',
				'g_gazde'  => 8,
				'oaspeti'  => 'Luceafarul Dragomiresti',
				'g_oaspeti'=> 2,
			],[
				'data'     => '22-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 8,
				'gazde'    => 'Unirea Colibasi',
				'g_gazde'  => 0,
				'oaspeti'  => 'Olimpicii Ulmi',
				'g_oaspeti'=> 2,
			],[
				'data'     => '22-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 8,
				'gazde'    => 'Unirea Ungureni',
				'g_gazde'  => 1,
				'oaspeti'  => 'Coada Izvorului',
				'g_oaspeti'=> 2,
			],[
				'data'     => '22-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 8,
				'gazde'    => 'Gloria 2015 Cornesti',
				'g_gazde'  => 9,
				'oaspeti'  => 'Viitorul I.L. Caragiale',
				'g_oaspeti'=> 1,
			],[
				'data'     => '22-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 8,
				'gazde'    => 'Vointa Piersinari',
				'g_gazde'  => 4,
				'oaspeti'  => 'Sportul Voinesti 2016',
				'g_oaspeti'=> 1,
			],[
				'data'     => '22-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 8,
				'gazde'    => 'Roberto Ziduri',
				'g_gazde'  => 1,
				'oaspeti'  => 'Recolta Gura Sutii',
				'g_oaspeti'=> 1,
			],[
				'data'     => '22-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 8,
				'gazde'    => 'Unirea Bucsani',
				'g_gazde'  => 2,
				'oaspeti'  => 'FC Brezoaele',
				'g_oaspeti'=> 2,
			],[
				'data'     => '22-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 8,
				'gazde'    => 'Petrolul Targoviste',
				'g_gazde'  => 3,
				'oaspeti'  => 'Progresul Matasaru',
				'g_oaspeti'=> 1,
			],[
				'data'     => '29-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 9,
				'gazde'    => 'C.S.M Fieni',
				'g_gazde'  => 1,
				'oaspeti'  => 'Petrolul Targoviste',
				'g_oaspeti'=> 3,
			],[
				'data'     => '29-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 9,
				'gazde'    => 'Progresul Matasaru',
				'g_gazde'  => 1,
				'oaspeti'  => 'Unirea Bucsani',
				'g_oaspeti'=> 5,
			],[
				'data'     => '29-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 9,
				'gazde'    => 'FC Brezoaele',
				'g_gazde'  => 1,
				'oaspeti'  => 'Roberto Ziduri',
				'g_oaspeti'=> 1,
			],[
				'data'     => '29-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 9,
				'gazde'    => 'Recolta Gura Sutii',
				'g_gazde'  => 3,
				'oaspeti'  => 'Vointa Piersinari',
				'g_oaspeti'=> 2,
			],[
				'data'     => '29-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 9,
				'gazde'    => 'Sportul Voinesti 2016',
				'g_gazde'  => 0,
				'oaspeti'  => 'Gloria 2015 Cornesti',
				'g_oaspeti'=> 4,
			],[
				'data'     => '29-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 9,
				'gazde'    => 'Viitorul I.L. Caragiale',
				'g_gazde'  => 3,
				'oaspeti'  => 'Unirea Ungureni',
				'g_oaspeti'=> 3,
			],[
				'data'     => '29-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 9,
				'gazde'    => 'Coada Izvorului',
				'g_gazde'  => 3,
				'oaspeti'  => 'Unirea Colibasi',
				'g_oaspeti'=> 7,
			],[
				'data'     => '29-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 9,
				'gazde'    => 'Olimpicii Ulmi',
				'g_gazde'  => 3,
				'oaspeti'  => 'Vointa Visina',
				'g_oaspeti'=> 2,
			],[
				'data'     => '29-09-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 9,
				'gazde'    => 'Luceafarul Dragomiresti',
				'g_gazde'  => 0,
				'oaspeti'  => 'Unirea 2018 Racari',
				'g_oaspeti'=> 6,
			],[
				'data'     => '06-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 10,
				'gazde'    => 'Luceafarul Dragomiresti',
				'g_gazde'  => 2,
				'oaspeti'  => 'C.S.M Fieni',
				'g_oaspeti'=> 4,
			],[
				'data'     => '06-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 10,
				'gazde'    => 'Unirea 2018 Racari',
				'g_gazde'  => 3,
				'oaspeti'  => 'Olimpicii Ulmi',
				'g_oaspeti'=> 0,
			],[
				'data'     => '06-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 10,
				'gazde'    => 'Vointa Visina',
				'g_gazde'  => 5,
				'oaspeti'  => 'Coada Izvorului',
				'g_oaspeti'=> 1,
			],[
				'data'     => '06-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 10,
				'gazde'    => 'Unirea Colibasi',
				'g_gazde'  => 8,
				'oaspeti'  => 'Viitorul I.L. Caragiale',
				'g_oaspeti'=> 1,
			],[
				'data'     => '06-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 10,
				'gazde'    => 'Unirea Ungureni',
				'g_gazde'  => 3,
				'oaspeti'  => 'Sportul Voinesti 2016',
				'g_oaspeti'=> 3,
			],[
				'data'     => '06-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 10,
				'gazde'    => 'Gloria 2015 Cornesti',
				'g_gazde'  => 1,
				'oaspeti'  => 'Recolta Gura Sutii',
				'g_oaspeti'=> 1,
			],[
				'data'     => '06-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 10,
				'gazde'    => 'Vointa Piersinari',
				'g_gazde'  => 5,
				'oaspeti'  => 'FC Brezoaele',
				'g_oaspeti'=> 3,
			],[
				'data'     => '06-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 10,
				'gazde'    => 'Roberto Ziduri',
				'g_gazde'  => 3,
				'oaspeti'  => 'Progresul Matasaru',
				'g_oaspeti'=> 2,
			],[
				'data'     => '06-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 10,
				'gazde'    => 'Unirea Bucsani',
				'g_gazde'  => 3,
				'oaspeti'  => 'Petrolul Targoviste',
				'g_oaspeti'=> 3,
			],[
				'data'     => '13-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 11,
				'gazde'    => 'C.S.M Fieni',
				'g_gazde'  => 6,
				'oaspeti'  => 'Unirea Bucsani',
				'g_oaspeti'=> 0,
			],[
				'data'     => '13-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 11,
				'gazde'    => 'Petrolul Targoviste',
				'g_gazde'  => 1,
				'oaspeti'  => 'Roberto Ziduri',
				'g_oaspeti'=> 7,
			],[
				'data'     => '13-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 11,
				'gazde'    => 'Progresul Matasaru',
				'g_gazde'  => 2,
				'oaspeti'  => 'Vointa Piersinari',
				'g_oaspeti'=> 6,
			],[
				'data'     => '13-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 11,
				'gazde'    => 'FC Brezoaele',
				'g_gazde'  => 2,
				'oaspeti'  => 'Gloria 2015 Cornesti',
				'g_oaspeti'=> 1,
			],[
				'data'     => '13-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 11,
				'gazde'    => 'Recolta Gura Sutii',
				'g_gazde'  => 4,
				'oaspeti'  => 'Unirea Ungureni',
				'g_oaspeti'=> 3,
			],[
				'data'     => '13-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 11,
				'gazde'    => 'Sportul Voinesti 2016',
				'g_gazde'  => 5,
				'oaspeti'  => 'Unirea Colibasi',
				'g_oaspeti'=> 2,
			],[
				'data'     => '13-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 11,
				'gazde'    => 'Viitorul I.L. Caragiale',
				'g_gazde'  => 1,
				'oaspeti'  => 'Vointa Visina',
				'g_oaspeti'=> 0,
			],[
				'data'     => '13-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 11,
				'gazde'    => 'Coada Izvorului',
				'g_gazde'  => 2,
				'oaspeti'  => 'Unirea 2018 Racari',
				'g_oaspeti'=> 5,
			],[
				'data'     => '13-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 11,
				'gazde'    => 'Olimpicii Ulmi',
				'g_gazde'  => 8,
				'oaspeti'  => 'Luceafarul Dragomiresti',
				'g_oaspeti'=> 1,
			],[
				'data'     => '20-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 12,
				'gazde'    => 'Olimpicii Ulmi',
				'g_gazde'  => null,
				'oaspeti'  => 'C.S.M Fieni',
				'g_oaspeti'=> null,
			],[
				'data'     => '20-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 12,
				'gazde'    => 'Luceafarul Dragomiresti',
				'g_gazde'  => null,
				'oaspeti'  => 'Coada Izvorului',
				'g_oaspeti'=> null,
			],[
				'data'     => '20-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 12,
				'gazde'    => 'Unirea 2018 Racari',
				'g_gazde'  => null,
				'oaspeti'  => 'Viitorul I.L. Caragiale',
				'g_oaspeti'=> null,
			],[
				'data'     => '20-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 12,
				'gazde'    => 'Vointa Visina',
				'g_gazde'  => null,
				'oaspeti'  => 'Sportul Voinesti 2016',
				'g_oaspeti'=> null,
			],[
				'data'     => '20-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 12,
				'gazde'    => 'Unirea Colibasi',
				'g_gazde'  => null,
				'oaspeti'  => 'Recolta Gura Sutii',
				'g_oaspeti'=> null,
			],[
				'data'     => '20-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 12,
				'gazde'    => 'Unirea Ungureni',
				'g_gazde'  => null,
				'oaspeti'  => 'FC Brezoaele',
				'g_oaspeti'=> null,
			],[
				'data'     => '20-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 12,
				'gazde'    => 'Gloria 2015 Cornesti',
				'g_gazde'  => null,
				'oaspeti'  => 'Progresul Matasaru',
				'g_oaspeti'=> null,
			],[
				'data'     => '20-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 12,
				'gazde'    => 'Vointa Piersinari',
				'g_gazde'  => null,
				'oaspeti'  => 'Petrolul Targoviste',
				'g_oaspeti'=> null,
			],[
				'data'     => '20-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 12,
				'gazde'    => 'Roberto Ziduri',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Bucsani',
				'g_oaspeti'=> null,
			],[
				'data'     => '27-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 13,
				'gazde'    => 'C.S.M Fieni',
				'g_gazde'  => null,
				'oaspeti'  => 'Roberto Ziduri',
				'g_oaspeti'=> null,
			],[
				'data'     => '27-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 13,
				'gazde'    => 'Unirea Bucsani',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Piersinari',
				'g_oaspeti'=> null,
			],[
				'data'     => '27-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 13,
				'gazde'    => 'Petrolul Targoviste',
				'g_gazde'  => null,
				'oaspeti'  => 'Gloria 2015 Cornesti',
				'g_oaspeti'=> null,
			],[
				'data'     => '27-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 13,
				'gazde'    => 'Progresul Matasaru',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Ungureni',
				'g_oaspeti'=> null,
			],[
				'data'     => '27-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 13,
				'gazde'    => 'FC Brezoaele',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Colibasi',
				'g_oaspeti'=> null,
			],[
				'data'     => '27-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 13,
				'gazde'    => 'Recolta Gura Sutii',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Visina',
				'g_oaspeti'=> null,
			],[
				'data'     => '27-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 13,
				'gazde'    => 'Sportul Voinesti 2016',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea 2018 Racari',
				'g_oaspeti'=> null,
			],[
				'data'     => '27-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 13,
				'gazde'    => 'Viitorul I.L. Caragiale',
				'g_gazde'  => null,
				'oaspeti'  => 'Luceafarul Dragomiresti',
				'g_oaspeti'=> null,
			],[
				'data'     => '27-10-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 13,
				'gazde'    => 'Coada Izvorului',
				'g_gazde'  => null,
				'oaspeti'  => 'Olimpicii Ulmi',
				'g_oaspeti'=> null,
			],[
				'data'     => '03-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 14,
				'gazde'    => 'Coada Izvorului',
				'g_gazde'  => null,
				'oaspeti'  => 'C.S.M Fieni',
				'g_oaspeti'=> null,
			],[
				'data'     => '03-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 14,
				'gazde'    => 'Olimpicii Ulmi',
				'g_gazde'  => null,
				'oaspeti'  => 'Viitorul I.L. Caragiale',
				'g_oaspeti'=> null,
			],[
				'data'     => '03-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 14,
				'gazde'    => 'Luceafarul Dragomiresti',
				'g_gazde'  => null,
				'oaspeti'  => 'Sportul Voinesti 2016',
				'g_oaspeti'=> null,
			],[
				'data'     => '03-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 14,
				'gazde'    => 'Unirea 2018 Racari',
				'g_gazde'  => null,
				'oaspeti'  => 'Recolta Gura Sutii',
				'g_oaspeti'=> null,
			],[
				'data'     => '03-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 14,
				'gazde'    => 'Vointa Visina',
				'g_gazde'  => null,
				'oaspeti'  => 'FC Brezoaele',
				'g_oaspeti'=> null,
			],[
				'data'     => '03-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 14,
				'gazde'    => 'Unirea Colibasi',
				'g_gazde'  => null,
				'oaspeti'  => 'Progresul Matasaru',
				'g_oaspeti'=> null,
			],[
				'data'     => '03-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 14,
				'gazde'    => 'Unirea Ungureni',
				'g_gazde'  => null,
				'oaspeti'  => 'Petrolul Targoviste',
				'g_oaspeti'=> null,
			],[
				'data'     => '03-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 14,
				'gazde'    => 'Gloria 2015 Cornesti',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Bucsani',
				'g_oaspeti'=> null,
			],[
				'data'     => '03-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 14,
				'gazde'    => 'Vointa Piersinari',
				'g_gazde'  => null,
				'oaspeti'  => 'Roberto Ziduri',
				'g_oaspeti'=> null,
			],[
				'data'     => '10-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 15,
				'gazde'    => 'C.S.M Fieni',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Piersinari',
				'g_oaspeti'=> null,
			],[
				'data'     => '10-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 15,
				'gazde'    => 'Roberto Ziduri',
				'g_gazde'  => null,
				'oaspeti'  => 'Gloria 2015 Cornesti',
				'g_oaspeti'=> null,
			],[
				'data'     => '10-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 15,
				'gazde'    => 'Unirea Bucsani',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Ungureni',
				'g_oaspeti'=> null,
			],[
				'data'     => '10-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 15,
				'gazde'    => 'Petrolul Targoviste',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Colibasi',
				'g_oaspeti'=> null,
			],[
				'data'     => '10-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 15,
				'gazde'    => 'Progresul Matasaru',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Visina',
				'g_oaspeti'=> null,
			],[
				'data'     => '10-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 15,
				'gazde'    => 'FC Brezoaele',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea 2018 Racari',
				'g_oaspeti'=> null,
			],[
				'data'     => '10-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 15,
				'gazde'    => 'Recolta Gura Sutii',
				'g_gazde'  => null,
				'oaspeti'  => 'Luceafarul Dragomiresti',
				'g_oaspeti'=> null,
			],[
				'data'     => '10-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 15,
				'gazde'    => 'Sportul Voinesti 2016',
				'g_gazde'  => null,
				'oaspeti'  => 'Olimpicii Ulmi',
				'g_oaspeti'=> null,
			],[
				'data'     => '10-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 15,
				'gazde'    => 'Viitorul I.L. Caragiale',
				'g_gazde'  => null,
				'oaspeti'  => 'Coada Izvorului',
				'g_oaspeti'=> null,
			],[
				'data'     => '17-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 16,
				'gazde'    => 'Viitorul I.L. Caragiale',
				'g_gazde'  => null,
				'oaspeti'  => 'C.S.M Fieni',
				'g_oaspeti'=> null,
			],[
				'data'     => '17-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 16,
				'gazde'    => 'Coada Izvorului',
				'g_gazde'  => null,
				'oaspeti'  => 'Sportul Voinesti 2016',
				'g_oaspeti'=> null,
			],[
				'data'     => '17-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 16,
				'gazde'    => 'Olimpicii Ulmi',
				'g_gazde'  => null,
				'oaspeti'  => 'Recolta Gura Sutii',
				'g_oaspeti'=> null,
			],[
				'data'     => '17-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 16,
				'gazde'    => 'Luceafarul Dragomiresti',
				'g_gazde'  => null,
				'oaspeti'  => 'FC Brezoaele',
				'g_oaspeti'=> null,
			],[
				'data'     => '17-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 16,
				'gazde'    => 'Unirea 2018 Racari',
				'g_gazde'  => null,
				'oaspeti'  => 'Progresul Matasaru',
				'g_oaspeti'=> null,
			],[
				'data'     => '17-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 16,
				'gazde'    => 'Vointa Visina',
				'g_gazde'  => null,
				'oaspeti'  => 'Petrolul Targoviste',
				'g_oaspeti'=> null,
			],[
				'data'     => '17-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 16,
				'gazde'    => 'Unirea Colibasi',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Bucsani',
				'g_oaspeti'=> null,
			],[
				'data'     => '17-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 16,
				'gazde'    => 'Unirea Ungureni',
				'g_gazde'  => null,
				'oaspeti'  => 'Roberto Ziduri',
				'g_oaspeti'=> null,
			],[
				'data'     => '17-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 16,
				'gazde'    => 'Gloria 2015 Cornesti',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Piersinari',
				'g_oaspeti'=> null,
			],[
				'data'     => '24-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 17,
				'gazde'    => 'C.S.M Fieni',
				'g_gazde'  => null,
				'oaspeti'  => 'Gloria 2015 Cornesti',
				'g_oaspeti'=> null,
			],[
				'data'     => '24-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 17,
				'gazde'    => 'Vointa Piersinari',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Ungureni',
				'g_oaspeti'=> null,
			],[
				'data'     => '24-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 17,
				'gazde'    => 'Roberto Ziduri',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Colibasi',
				'g_oaspeti'=> null,
			],[
				'data'     => '24-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 17,
				'gazde'    => 'Unirea Bucsani',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Visina',
				'g_oaspeti'=> null,
			],[
				'data'     => '24-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 17,
				'gazde'    => 'Petrolul Targoviste',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea 2018 Racari',
				'g_oaspeti'=> null,
			],[
				'data'     => '24-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 17,
				'gazde'    => 'Progresul Matasaru',
				'g_gazde'  => null,
				'oaspeti'  => 'Luceafarul Dragomiresti',
				'g_oaspeti'=> null,
			],[
				'data'     => '24-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 17,
				'gazde'    => 'FC Brezoaele',
				'g_gazde'  => null,
				'oaspeti'  => 'Olimpicii Ulmi',
				'g_oaspeti'=> null,
			],[
				'data'     => '24-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 17,
				'gazde'    => 'Recolta Gura Sutii',
				'g_gazde'  => null,
				'oaspeti'  => 'Coada Izvorului',
				'g_oaspeti'=> null,
			],[
				'data'     => '24-11-2018',
				'ora'      => '11:00',
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 17,
				'gazde'    => 'Sportul Voinesti 2016',
				'g_gazde'  => null,
				'oaspeti'  => 'Viitorul I.L. Caragiale',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 18,
				'gazde'    => 'C.S.M Fieni',
				'g_gazde'  => null,
				'oaspeti'  => 'Sportul Voinesti 2016',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 18,
				'gazde'    => 'Recolta Gura Sutii',
				'g_gazde'  => null,
				'oaspeti'  => 'Viitorul I.L. Caragiale',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 18,
				'gazde'    => 'FC Brezoaele',
				'g_gazde'  => null,
				'oaspeti'  => 'Coada Izvorului',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 18,
				'gazde'    => 'Progresul Matasaru',
				'g_gazde'  => null,
				'oaspeti'  => 'Olimpicii Ulmi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 18,
				'gazde'    => 'Petrolul Targoviste',
				'g_gazde'  => null,
				'oaspeti'  => 'Luceafarul Dragomiresti',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 18,
				'gazde'    => 'Unirea Bucsani',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea 2018 Racari',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 18,
				'gazde'    => 'Roberto Ziduri',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Visina',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 18,
				'gazde'    => 'Vointa Piersinari',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Colibasi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 18,
				'gazde'    => 'Gloria 2015 Cornesti',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Ungureni',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 19,
				'gazde'    => 'Unirea Ungureni',
				'g_gazde'  => null,
				'oaspeti'  => 'C.S.M Fieni',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 19,
				'gazde'    => 'Unirea Colibasi',
				'g_gazde'  => null,
				'oaspeti'  => 'Gloria 2015 Cornesti',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 19,
				'gazde'    => 'Vointa Visina',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Piersinari',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 19,
				'gazde'    => 'Unirea 2018 Racari',
				'g_gazde'  => null,
				'oaspeti'  => 'Roberto Ziduri',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 19,
				'gazde'    => 'Luceafarul Dragomiresti',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Bucsani',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 19,
				'gazde'    => 'Olimpicii Ulmi',
				'g_gazde'  => null,
				'oaspeti'  => 'Petrolul Targoviste',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 19,
				'gazde'    => 'Coada Izvorului',
				'g_gazde'  => null,
				'oaspeti'  => 'Progresul Matasaru',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 19,
				'gazde'    => 'Viitorul I.L. Caragiale',
				'g_gazde'  => null,
				'oaspeti'  => 'FC Brezoaele',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 19,
				'gazde'    => 'Sportul Voinesti 2016',
				'g_gazde'  => null,
				'oaspeti'  => 'Recolta Gura Sutii',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 20,
				'gazde'    => 'Recolta Gura Sutii',
				'g_gazde'  => null,
				'oaspeti'  => 'C.S.M Fieni',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 20,
				'gazde'    => 'FC Brezoaele',
				'g_gazde'  => null,
				'oaspeti'  => 'Sportul Voinesti 2016',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 20,
				'gazde'    => 'Progresul Matasaru',
				'g_gazde'  => null,
				'oaspeti'  => 'Viitorul I.L. Caragiale',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 20,
				'gazde'    => 'Petrolul Targoviste',
				'g_gazde'  => null,
				'oaspeti'  => 'Coada Izvorului',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 20,
				'gazde'    => 'Unirea Bucsani',
				'g_gazde'  => null,
				'oaspeti'  => 'Olimpicii Ulmi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 20,
				'gazde'    => 'Roberto Ziduri',
				'g_gazde'  => null,
				'oaspeti'  => 'Luceafarul Dragomiresti',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 20,
				'gazde'    => 'Vointa Piersinari',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea 2018 Racari',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 20,
				'gazde'    => 'Gloria 2015 Cornesti',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Visina',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 20,
				'gazde'    => 'Unirea Ungureni',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Colibasi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 21,
				'gazde'    => 'C.S.M Fieni',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Colibasi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 21,
				'gazde'    => 'Vointa Visina',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Ungureni',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 21,
				'gazde'    => 'Unirea 2018 Racari',
				'g_gazde'  => null,
				'oaspeti'  => 'Gloria 2015 Cornesti',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 21,
				'gazde'    => 'Luceafarul Dragomiresti',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Piersinari',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 21,
				'gazde'    => 'Olimpicii Ulmi',
				'g_gazde'  => null,
				'oaspeti'  => 'Roberto Ziduri',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 21,
				'gazde'    => 'Coada Izvorului',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Bucsani',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 21,
				'gazde'    => 'Viitorul I.L. Caragiale',
				'g_gazde'  => null,
				'oaspeti'  => 'Petrolul Targoviste',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 21,
				'gazde'    => 'Sportul Voinesti 2016',
				'g_gazde'  => null,
				'oaspeti'  => 'Progresul Matasaru',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 21,
				'gazde'    => 'Recolta Gura Sutii',
				'g_gazde'  => null,
				'oaspeti'  => 'FC Brezoaele',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 22,
				'gazde'    => 'FC Brezoaele',
				'g_gazde'  => null,
				'oaspeti'  => 'C.S.M Fieni',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 22,
				'gazde'    => 'Progresul Matasaru',
				'g_gazde'  => null,
				'oaspeti'  => 'Recolta Gura Sutii',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 22,
				'gazde'    => 'Petrolul Targoviste',
				'g_gazde'  => null,
				'oaspeti'  => 'Sportul Voinesti 2016',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 22,
				'gazde'    => 'Unirea Bucsani',
				'g_gazde'  => null,
				'oaspeti'  => 'Viitorul I.L. Caragiale',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 22,
				'gazde'    => 'Roberto Ziduri',
				'g_gazde'  => null,
				'oaspeti'  => 'Coada Izvorului',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 22,
				'gazde'    => 'Vointa Piersinari',
				'g_gazde'  => null,
				'oaspeti'  => 'Olimpicii Ulmi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 22,
				'gazde'    => 'Gloria 2015 Cornesti',
				'g_gazde'  => null,
				'oaspeti'  => 'Luceafarul Dragomiresti',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 22,
				'gazde'    => 'Unirea Ungureni',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea 2018 Racari',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 22,
				'gazde'    => 'Unirea Colibasi',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Visina',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 23,
				'gazde'    => 'C.S.M Fieni',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Visina',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 23,
				'gazde'    => 'Unirea 2018 Racari',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Colibasi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 23,
				'gazde'    => 'Luceafarul Dragomiresti',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Ungureni',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 23,
				'gazde'    => 'Olimpicii Ulmi',
				'g_gazde'  => null,
				'oaspeti'  => 'Gloria 2015 Cornesti',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 23,
				'gazde'    => 'Coada Izvorului',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Piersinari',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 23,
				'gazde'    => 'Viitorul I.L. Caragiale',
				'g_gazde'  => null,
				'oaspeti'  => 'Roberto Ziduri',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 23,
				'gazde'    => 'Sportul Voinesti 2016',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Bucsani',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 23,
				'gazde'    => 'Recolta Gura Sutii',
				'g_gazde'  => null,
				'oaspeti'  => 'Petrolul Targoviste',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 23,
				'gazde'    => 'FC Brezoaele',
				'g_gazde'  => null,
				'oaspeti'  => 'Progresul Matasaru',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 24,
				'gazde'    => 'Progresul Matasaru',
				'g_gazde'  => null,
				'oaspeti'  => 'C.S.M Fieni',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 24,
				'gazde'    => 'Petrolul Targoviste',
				'g_gazde'  => null,
				'oaspeti'  => 'FC Brezoaele',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 24,
				'gazde'    => 'Unirea Bucsani',
				'g_gazde'  => null,
				'oaspeti'  => 'Recolta Gura Sutii',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 24,
				'gazde'    => 'Roberto Ziduri',
				'g_gazde'  => null,
				'oaspeti'  => 'Sportul Voinesti 2016',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 24,
				'gazde'    => 'Vointa Piersinari',
				'g_gazde'  => null,
				'oaspeti'  => 'Viitorul I.L. Caragiale',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 24,
				'gazde'    => 'Gloria 2015 Cornesti',
				'g_gazde'  => null,
				'oaspeti'  => 'Coada Izvorului',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 24,
				'gazde'    => 'Unirea Ungureni',
				'g_gazde'  => null,
				'oaspeti'  => 'Olimpicii Ulmi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 24,
				'gazde'    => 'Unirea Colibasi',
				'g_gazde'  => null,
				'oaspeti'  => 'Luceafarul Dragomiresti',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 24,
				'gazde'    => 'Vointa Visina',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea 2018 Racari',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 25,
				'gazde'    => 'C.S.M Fieni',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea 2018 Racari',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 25,
				'gazde'    => 'Luceafarul Dragomiresti',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Visina',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 25,
				'gazde'    => 'Olimpicii Ulmi',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Colibasi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 25,
				'gazde'    => 'Coada Izvorului',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Ungureni',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 25,
				'gazde'    => 'Viitorul I.L. Caragiale',
				'g_gazde'  => null,
				'oaspeti'  => 'Gloria 2015 Cornesti',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 25,
				'gazde'    => 'Sportul Voinesti 2016',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Piersinari',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 25,
				'gazde'    => 'Recolta Gura Sutii',
				'g_gazde'  => null,
				'oaspeti'  => 'Roberto Ziduri',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 25,
				'gazde'    => 'FC Brezoaele',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Bucsani',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 25,
				'gazde'    => 'Progresul Matasaru',
				'g_gazde'  => null,
				'oaspeti'  => 'Petrolul Targoviste',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 26,
				'gazde'    => 'Petrolul Targoviste',
				'g_gazde'  => null,
				'oaspeti'  => 'C.S.M Fieni',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 26,
				'gazde'    => 'Unirea Bucsani',
				'g_gazde'  => null,
				'oaspeti'  => 'Progresul Matasaru',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 26,
				'gazde'    => 'Roberto Ziduri',
				'g_gazde'  => null,
				'oaspeti'  => 'FC Brezoaele',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 26,
				'gazde'    => 'Vointa Piersinari',
				'g_gazde'  => null,
				'oaspeti'  => 'Recolta Gura Sutii',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 26,
				'gazde'    => 'Gloria 2015 Cornesti',
				'g_gazde'  => null,
				'oaspeti'  => 'Sportul Voinesti 2016',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 26,
				'gazde'    => 'Unirea Ungureni',
				'g_gazde'  => null,
				'oaspeti'  => 'Viitorul I.L. Caragiale',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 26,
				'gazde'    => 'Unirea Colibasi',
				'g_gazde'  => null,
				'oaspeti'  => 'Coada Izvorului',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 26,
				'gazde'    => 'Vointa Visina',
				'g_gazde'  => null,
				'oaspeti'  => 'Olimpicii Ulmi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 26,
				'gazde'    => 'Unirea 2018 Racari',
				'g_gazde'  => null,
				'oaspeti'  => 'Luceafarul Dragomiresti',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 27,
				'gazde'    => 'C.S.M Fieni',
				'g_gazde'  => null,
				'oaspeti'  => 'Luceafarul Dragomiresti',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 27,
				'gazde'    => 'Olimpicii Ulmi',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea 2018 Racari',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 27,
				'gazde'    => 'Coada Izvorului',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Visina',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 27,
				'gazde'    => 'Viitorul I.L. Caragiale',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Colibasi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 27,
				'gazde'    => 'Sportul Voinesti 2016',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Ungureni',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 27,
				'gazde'    => 'Recolta Gura Sutii',
				'g_gazde'  => null,
				'oaspeti'  => 'Gloria 2015 Cornesti',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 27,
				'gazde'    => 'FC Brezoaele',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Piersinari',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 27,
				'gazde'    => 'Progresul Matasaru',
				'g_gazde'  => null,
				'oaspeti'  => 'Roberto Ziduri',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 27,
				'gazde'    => 'Petrolul Targoviste',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Bucsani',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 28,
				'gazde'    => 'Unirea Bucsani',
				'g_gazde'  => null,
				'oaspeti'  => 'C.S.M Fieni',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 28,
				'gazde'    => 'Roberto Ziduri',
				'g_gazde'  => null,
				'oaspeti'  => 'Petrolul Targoviste',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 28,
				'gazde'    => 'Vointa Piersinari',
				'g_gazde'  => null,
				'oaspeti'  => 'Progresul Matasaru',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 28,
				'gazde'    => 'Gloria 2015 Cornesti',
				'g_gazde'  => null,
				'oaspeti'  => 'FC Brezoaele',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 28,
				'gazde'    => 'Unirea Ungureni',
				'g_gazde'  => null,
				'oaspeti'  => 'Recolta Gura Sutii',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 28,
				'gazde'    => 'Unirea Colibasi',
				'g_gazde'  => null,
				'oaspeti'  => 'Sportul Voinesti 2016',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 28,
				'gazde'    => 'Vointa Visina',
				'g_gazde'  => null,
				'oaspeti'  => 'Viitorul I.L. Caragiale',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 28,
				'gazde'    => 'Unirea 2018 Racari',
				'g_gazde'  => null,
				'oaspeti'  => 'Coada Izvorului',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 28,
				'gazde'    => 'Luceafarul Dragomiresti',
				'g_gazde'  => null,
				'oaspeti'  => 'Olimpicii Ulmi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 29,
				'gazde'    => 'C.S.M Fieni',
				'g_gazde'  => null,
				'oaspeti'  => 'Olimpicii Ulmi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 29,
				'gazde'    => 'Coada Izvorului',
				'g_gazde'  => null,
				'oaspeti'  => 'Luceafarul Dragomiresti',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 29,
				'gazde'    => 'Viitorul I.L. Caragiale',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea 2018 Racari',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 29,
				'gazde'    => 'Sportul Voinesti 2016',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Visina',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 29,
				'gazde'    => 'Recolta Gura Sutii',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Colibasi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 29,
				'gazde'    => 'FC Brezoaele',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Ungureni',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 29,
				'gazde'    => 'Progresul Matasaru',
				'g_gazde'  => null,
				'oaspeti'  => 'Gloria 2015 Cornesti',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 29,
				'gazde'    => 'Petrolul Targoviste',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Piersinari',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 29,
				'gazde'    => 'Unirea Bucsani',
				'g_gazde'  => null,
				'oaspeti'  => 'Roberto Ziduri',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 30,
				'gazde'    => 'Roberto Ziduri',
				'g_gazde'  => null,
				'oaspeti'  => 'C.S.M Fieni',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 30,
				'gazde'    => 'Vointa Piersinari',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Bucsani',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 30,
				'gazde'    => 'Gloria 2015 Cornesti',
				'g_gazde'  => null,
				'oaspeti'  => 'Petrolul Targoviste',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 30,
				'gazde'    => 'Unirea Ungureni',
				'g_gazde'  => null,
				'oaspeti'  => 'Progresul Matasaru',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 30,
				'gazde'    => 'Unirea Colibasi',
				'g_gazde'  => null,
				'oaspeti'  => 'FC Brezoaele',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 30,
				'gazde'    => 'Vointa Visina',
				'g_gazde'  => null,
				'oaspeti'  => 'Recolta Gura Sutii',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 30,
				'gazde'    => 'Unirea 2018 Racari',
				'g_gazde'  => null,
				'oaspeti'  => 'Sportul Voinesti 2016',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 30,
				'gazde'    => 'Luceafarul Dragomiresti',
				'g_gazde'  => null,
				'oaspeti'  => 'Viitorul I.L. Caragiale',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 30,
				'gazde'    => 'Olimpicii Ulmi',
				'g_gazde'  => null,
				'oaspeti'  => 'Coada Izvorului',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 31,
				'gazde'    => 'C.S.M Fieni',
				'g_gazde'  => null,
				'oaspeti'  => 'Coada Izvorului',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 31,
				'gazde'    => 'Viitorul I.L. Caragiale',
				'g_gazde'  => null,
				'oaspeti'  => 'Olimpicii Ulmi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 31,
				'gazde'    => 'Sportul Voinesti 2016',
				'g_gazde'  => null,
				'oaspeti'  => 'Luceafarul Dragomiresti',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 31,
				'gazde'    => 'Recolta Gura Sutii',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea 2018 Racari',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 31,
				'gazde'    => 'FC Brezoaele',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Visina',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 31,
				'gazde'    => 'Progresul Matasaru',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Colibasi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 31,
				'gazde'    => 'Petrolul Targoviste',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Ungureni',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 31,
				'gazde'    => 'Unirea Bucsani',
				'g_gazde'  => null,
				'oaspeti'  => 'Gloria 2015 Cornesti',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 31,
				'gazde'    => 'Roberto Ziduri',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Piersinari',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 32,
				'gazde'    => 'Vointa Piersinari',
				'g_gazde'  => null,
				'oaspeti'  => 'C.S.M Fieni',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 32,
				'gazde'    => 'Gloria 2015 Cornesti',
				'g_gazde'  => null,
				'oaspeti'  => 'Roberto Ziduri',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 32,
				'gazde'    => 'Unirea Ungureni',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Bucsani',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 32,
				'gazde'    => 'Unirea Colibasi',
				'g_gazde'  => null,
				'oaspeti'  => 'Petrolul Targoviste',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 32,
				'gazde'    => 'Vointa Visina',
				'g_gazde'  => null,
				'oaspeti'  => 'Progresul Matasaru',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 32,
				'gazde'    => 'Unirea 2018 Racari',
				'g_gazde'  => null,
				'oaspeti'  => 'FC Brezoaele',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 32,
				'gazde'    => 'Luceafarul Dragomiresti',
				'g_gazde'  => null,
				'oaspeti'  => 'Recolta Gura Sutii',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 32,
				'gazde'    => 'Olimpicii Ulmi',
				'g_gazde'  => null,
				'oaspeti'  => 'Sportul Voinesti 2016',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 32,
				'gazde'    => 'Coada Izvorului',
				'g_gazde'  => null,
				'oaspeti'  => 'Viitorul I.L. Caragiale',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 33,
				'gazde'    => 'C.S.M Fieni',
				'g_gazde'  => null,
				'oaspeti'  => 'Viitorul I.L. Caragiale',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 33,
				'gazde'    => 'Sportul Voinesti 2016',
				'g_gazde'  => null,
				'oaspeti'  => 'Coada Izvorului',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 33,
				'gazde'    => 'Recolta Gura Sutii',
				'g_gazde'  => null,
				'oaspeti'  => 'Olimpicii Ulmi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 33,
				'gazde'    => 'FC Brezoaele',
				'g_gazde'  => null,
				'oaspeti'  => 'Luceafarul Dragomiresti',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 33,
				'gazde'    => 'Progresul Matasaru',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea 2018 Racari',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 33,
				'gazde'    => 'Petrolul Targoviste',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Visina',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 33,
				'gazde'    => 'Unirea Bucsani',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Colibasi',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 33,
				'gazde'    => 'Roberto Ziduri',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Ungureni',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 33,
				'gazde'    => 'Vointa Piersinari',
				'g_gazde'  => null,
				'oaspeti'  => 'Gloria 2015 Cornesti',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 34,
				'gazde'    => 'Gloria 2015 Cornesti',
				'g_gazde'  => null,
				'oaspeti'  => 'C.S.M Fieni',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 34,
				'gazde'    => 'Unirea Ungureni',
				'g_gazde'  => null,
				'oaspeti'  => 'Vointa Piersinari',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 34,
				'gazde'    => 'Unirea Colibasi',
				'g_gazde'  => null,
				'oaspeti'  => 'Roberto Ziduri',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 34,
				'gazde'    => 'Vointa Visina',
				'g_gazde'  => null,
				'oaspeti'  => 'Unirea Bucsani',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 34,
				'gazde'    => 'Unirea 2018 Racari',
				'g_gazde'  => null,
				'oaspeti'  => 'Petrolul Targoviste',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 34,
				'gazde'    => 'Luceafarul Dragomiresti',
				'g_gazde'  => null,
				'oaspeti'  => 'Progresul Matasaru',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 34,
				'gazde'    => 'Olimpicii Ulmi',
				'g_gazde'  => null,
				'oaspeti'  => 'FC Brezoaele',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 34,
				'gazde'    => 'Coada Izvorului',
				'g_gazde'  => null,
				'oaspeti'  => 'Recolta Gura Sutii',
				'g_oaspeti'=> null,
			],[
				'data'     => null,
				'ora'      => null,
				'liga'     => 4,
				'serie'    => null,
				'etapa'    => 34,
				'gazde'    => 'Viitorul I.L. Caragiale',
				'g_gazde'  => null,
				'oaspeti'  => 'Sportul Voinesti 2016',
				'g_oaspeti'=> null,
			]
		];

		Echipe::where('liga', 4)->where('serie', null)->delete();
		foreach ($echipe as $echipa) {
			$adauga = new Echipe;
			$adauga->echipa = trim($echipa['echipa']);
			$adauga->liga   = $echipa['liga'];
			$adauga->serie  = $echipa['serie'];
			$adauga->save();
		}

		Etape::where('liga', 4)->where('serie', null)->delete();
		foreach ($etape as $etapa) {
			$adauga = new Etape;
			$adauga->gazde     = trim($etapa['gazde']);
			$adauga->oaspeti   = trim($etapa['oaspeti']);
			$adauga->g_gazde   = $etapa['g_gazde'];
			$adauga->g_oaspeti = $etapa['g_oaspeti'];
			$adauga->liga      = $etapa['liga'];
			$adauga->serie     = $etapa['serie'];
			$adauga->etapa     = $etapa['etapa'];
			$adauga->data      = $etapa['data'] != NULL ? DateTime::createFromFormat('d-m-Y', ($etapa['data']))->format('Y-m-d') : NULL;
			$adauga->ora       = $etapa['ora'];
			$adauga->save();
		}
    }
}
