<?php

use Illuminate\Database\Seeder;
use App\Echipe;
use App\Etape;
use App\ToateEchipele;

class liga_3_serie_4_2019_2020 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $echipe = [  
		   [
		      'echipa' => 'U Craiova 1948 SA'
		   ],[
		      'echipa' => 'ACS Flacăra Horezu'
		   ],[
		      'echipa' => 'CSC Ghiroda şi Giarmata Vii'
		   ],[
		      'echipa' => 'AS Fortuna Becicherecu Mic'
		   ],[
		      'echipa' => 'CS Viitorul Dăeşti'
		   ],[
		      'echipa' => 'ACS Progresul Pecica'
		   ],[
		      'echipa' => 'CS Crişul Chişineu Criş'
		   ],[
		      'echipa' => 'CSC Dumbrăvița'
		   ],[
		      'echipa' => 'CS Şoimii Lipova'
		   ],[
		      'echipa' => 'CS Hunedoara'
		   ],[
		      'echipa' => 'ACSO Filiaşi'
		   ],[
		      'echipa' => 'CS Gloria Lunca-Teuz Cermei'
		   ],[
		      'echipa' => 'CS Naţional Sebiş'
		   ],[
		      'echipa' => 'LPS Cetate Deva'
		   ],[
		      'echipa' => 'ACS Poli Timişoara'
		   ],[
		      'echipa' => 'CS Gilortul Târgu Cărbuneşti'
		   ]
		];

		$etape = [ 
		   [ 
		      "data" => "2019-08-23",
		      "ora" => "18:00",
		      "gazde" => "CSC Dumbrăvița",
		      "oaspeti" => "LPS Cetate Deva",
		      "g_gazde" => 1,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-23",
		      "ora" => "18:00",
		      "gazde" => "CS Şoimii Lipova",
		      "oaspeti" => "U Craiova 1948 SA",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "AS Fortuna Becicherecu Mic",
		      "oaspeti" => "ACS Poli Timişoara",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "ACS Progresul Pecica",
		      "oaspeti" => "CS Crişul Chişineu Criş",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "CSC Ghiroda şi Giarmata Vii",
		      "oaspeti" => "CS Gloria Lunca-Teuz Cermei",
		      "g_gazde" => 3,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "CS Viitorul Dăeşti",
		      "oaspeti" => "CS Hunedoara",
		      "g_gazde" => 4,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "CS Naţional Sebiş",
		      "oaspeti" => "ACS Flacăra Horezu",
		      "g_gazde" => 0,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "CS Gilortul Târgu Cărbuneşti",
		      "oaspeti" => "ACSO Filiaşi",
		      "g_gazde" => 1,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-30",
		      "ora" => "18:00",
		      "gazde" => "ACS Poli Timişoara",
		      "oaspeti" => "ACSO Filiaşi",
		      "g_gazde" => 1,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-30",
		      "ora" => "18:00",
		      "gazde" => "LPS Cetate Deva",
		      "oaspeti" => "CSC Ghiroda şi Giarmata Vii",
		      "g_gazde" => 0,
		      "g_oaspeti" => 4,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "U Craiova 1948 SA",
		      "oaspeti" => "CS Gilortul Târgu Cărbuneşti",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "ACS Flacăra Horezu",
		      "oaspeti" => "CS Şoimii Lipova",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "CS Hunedoara",
		      "oaspeti" => "CS Naţional Sebiş",
		      "g_gazde" => 4,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "CS Gloria Lunca-Teuz Cermei",
		      "oaspeti" => "CS Viitorul Dăeşti",
		      "g_gazde" => 2,
		      "g_oaspeti" => 4,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "CS Crişul Chişineu Criş",
		      "oaspeti" => "CSC Dumbrăvița",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "AS Fortuna Becicherecu Mic",
		      "oaspeti" => "ACS Progresul Pecica",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-09-06",
		      "ora" => "17:00",
		      "gazde" => "CSC Dumbrăvița",
		      "oaspeti" => "AS Fortuna Becicherecu Mic",
		      "g_gazde" => 0,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-06",
		      "ora" => "17:00",
		      "gazde" => "CS Şoimii Lipova",
		      "oaspeti" => "CS Hunedoara",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-06",
		      "ora" => "17:00",
		      "gazde" => "ACSO Filiaşi",
		      "oaspeti" => "U Craiova 1948 SA",
		      "g_gazde" => 2,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "ACS Progresul Pecica",
		      "oaspeti" => "ACS Poli Timişoara",
		      "g_gazde" => 3,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "CSC Ghiroda şi Giarmata Vii",
		      "oaspeti" => "CS Crişul Chişineu Criş",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "CS Viitorul Dăeşti",
		      "oaspeti" => "LPS Cetate Deva",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "CS Naţional Sebiş",
		      "oaspeti" => "CS Gloria Lunca-Teuz Cermei",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "CS Gilortul Târgu Cărbuneşti",
		      "oaspeti" => "ACS Flacăra Horezu",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-13",
		      "ora" => "17:00",
		      "gazde" => "LPS Cetate Deva",
		      "oaspeti" => "CS Naţional Sebiş",
		      "g_gazde" => 1,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "ACS Poli Timişoara",
		      "oaspeti" => "U Craiova 1948 SA",
		      "g_gazde" => 0,
		      "g_oaspeti" => 5,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "ACS Flacăra Horezu",
		      "oaspeti" => "ACSO Filiaşi",
		      "g_gazde" => 3,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "CS Hunedoara",
		      "oaspeti" => "CS Gilortul Târgu Cărbuneşti",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "CS Gloria Lunca-Teuz Cermei",
		      "oaspeti" => "CS Şoimii Lipova",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "CS Crişul Chişineu Criş",
		      "oaspeti" => "CS Viitorul Dăeşti",
		      "g_gazde" => 3,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "AS Fortuna Becicherecu Mic",
		      "oaspeti" => "CSC Ghiroda şi Giarmata Vii",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "ACS Progresul Pecica",
		      "oaspeti" => "CSC Dumbrăvița",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-20",
		      "ora" => "17:00",
		      "gazde" => "CSC Dumbrăvița",
		      "oaspeti" => "ACS Poli Timişoara",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-20",
		      "ora" => "17:00",
		      "gazde" => "CS Şoimii Lipova",
		      "oaspeti" => "LPS Cetate Deva",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-20",
		      "ora" => "18:00",
		      "gazde" => "U Craiova 1948 SA",
		      "oaspeti" => "ACS Flacăra Horezu",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "CSC Ghiroda şi Giarmata Vii",
		      "oaspeti" => "ACS Progresul Pecica",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "CS Viitorul Dăeşti",
		      "oaspeti" => "AS Fortuna Becicherecu Mic",
		      "g_gazde" => 2,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "CS Naţional Sebiş",
		      "oaspeti" => "CS Crişul Chişineu Criş",
		      "g_gazde" => 3,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "CS Gilortul Târgu Cărbuneşti",
		      "oaspeti" => "CS Gloria Lunca-Teuz Cermei",
		      "g_gazde" => 1,
		      "g_oaspeti" => 5,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "ACSO Filiaşi",
		      "oaspeti" => "CS Hunedoara",
		      "g_gazde" => 1,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-27",
		      "ora" => "17:00",
		      "gazde" => "ACS Poli Timişoara",
		      "oaspeti" => "ACS Flacăra Horezu",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-27",
		      "ora" => "17:00",
		      "gazde" => "LPS Cetate Deva",
		      "oaspeti" => "CS Gilortul Târgu Cărbuneşti",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-27",
		      "ora" => "17:00",
		      "gazde" => "CS Crişul Chişineu Criş",
		      "oaspeti" => "CS Şoimii Lipova",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-27",
		      "ora" => "17:00",
		      "gazde" => "CSC Dumbrăvița",
		      "oaspeti" => "CSC Ghiroda şi Giarmata Vii",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-28",
		      "ora" => "17:00",
		      "gazde" => "CS Gloria Lunca-Teuz Cermei",
		      "oaspeti" => "ACSO Filiaşi",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-28",
		      "ora" => "17:00",
		      "gazde" => "AS Fortuna Becicherecu Mic",
		      "oaspeti" => "CS Naţional Sebiş",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-28",
		      "ora" => "17:00",
		      "gazde" => "ACS Progresul Pecica",
		      "oaspeti" => "CS Viitorul Dăeşti",
		      "g_gazde" => 5,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-29",
		      "ora" => "11:00",
		      "gazde" => "CS Hunedoara",
		      "oaspeti" => "U Craiova 1948 SA",
		      "g_gazde" => 2,
		      "g_oaspeti" => 4,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-10-04",
		      "ora" => "15:00",
		      "gazde" => "CS Şoimii Lipova",
		      "oaspeti" => "AS Fortuna Becicherecu Mic",
		      "g_gazde" => 2,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-04",
		      "ora" => "16:00",
		      "gazde" => "ACSO Filiaşi",
		      "oaspeti" => "LPS Cetate Deva",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "CSC Ghiroda şi Giarmata Vii",
		      "oaspeti" => "ACS Poli Timişoara",
		      "g_gazde" => 5,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "CS Viitorul Dăeşti",
		      "oaspeti" => "CSC Dumbrăvița",
		      "g_gazde" => 3,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "CS Naţional Sebiş",
		      "oaspeti" => "ACS Progresul Pecica",
		      "g_gazde" => 1,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "CS Gilortul Târgu Cărbuneşti",
		      "oaspeti" => "CS Crişul Chişineu Criş",
		      "g_gazde" => 0,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "U Craiova 1948 SA",
		      "oaspeti" => "CS Gloria Lunca-Teuz Cermei",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "ACS Flacăra Horezu",
		      "oaspeti" => "CS Hunedoara",
		      "g_gazde" => 3,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-11",
		      "ora" => "15:00",
		      "gazde" => "ACS Poli Timişoara",
		      "oaspeti" => "CS Hunedoara",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-11",
		      "ora" => "15:00",
		      "gazde" => "LPS Cetate Deva",
		      "oaspeti" => "U Craiova 1948 SA",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-11",
		      "ora" => "15:00",
		      "gazde" => "CSC Dumbrăvița",
		      "oaspeti" => "CS Naţional Sebiş",
		      "g_gazde" => 3,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-11",
		      "ora" => "15:00",
		      "gazde" => "CSC Ghiroda şi Giarmata Vii",
		      "oaspeti" => "CS Viitorul Dăeşti",
		      "g_gazde" => 2,
		      "g_oaspeti" => 4,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-12",
		      "ora" => "15:00",
		      "gazde" => "CS Gloria Lunca-Teuz Cermei",
		      "oaspeti" => "ACS Flacăra Horezu",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-12",
		      "ora" => "15:00",
		      "gazde" => "CS Crişul Chişineu Criş",
		      "oaspeti" => "ACSO Filiaşi",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-12",
		      "ora" => "15:00",
		      "gazde" => "AS Fortuna Becicherecu Mic",
		      "oaspeti" => "CS Gilortul Târgu Cărbuneşti",
		      "g_gazde" => 3,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-12",
		      "ora" => "15:00",
		      "gazde" => "ACS Progresul Pecica",
		      "oaspeti" => "CS Şoimii Lipova",
		      "g_gazde" => 1,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-18",
		      "ora" => "15:00",
		      "gazde" => "CS Şoimii Lipova",
		      "oaspeti" => "CSC Dumbrăvița",
		      "g_gazde" => 3,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-18",
		      "ora" => "15:00",
		      "gazde" => "ACSO Filiaşi",
		      "oaspeti" => "AS Fortuna Becicherecu Mic",
		      "g_gazde" => 3,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "CS Viitorul Dăeşti",
		      "oaspeti" => "ACS Poli Timişoara",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "CS Naţional Sebiş",
		      "oaspeti" => "CSC Ghiroda şi Giarmata Vii",
		      "g_gazde" => 0,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "CS Gilortul Târgu Cărbuneşti",
		      "oaspeti" => "ACS Progresul Pecica",
		      "g_gazde" => 0,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "U Craiova 1948 SA",
		      "oaspeti" => "CS Crişul Chişineu Criş",
		      "g_gazde" => 5,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "ACS Flacăra Horezu",
		      "oaspeti" => "LPS Cetate Deva",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "CS Hunedoara",
		      "oaspeti" => "CS Gloria Lunca-Teuz Cermei",
		      "g_gazde" => 3,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-25",
		      "ora" => "15:00",
		      "gazde" => "ACS Poli Timişoara",
		      "oaspeti" => "CS Gloria Lunca-Teuz Cermei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-25",
		      "ora" => "15:00",
		      "gazde" => "LPS Cetate Deva",
		      "oaspeti" => "CS Hunedoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-25",
		      "ora" => "15:00",
		      "gazde" => "CSC Dumbrăvița",
		      "oaspeti" => "CS Gilortul Târgu Cărbuneşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "CS Crişul Chişineu Criş",
		      "oaspeti" => "ACS Flacăra Horezu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "AS Fortuna Becicherecu Mic",
		      "oaspeti" => "U Craiova 1948 SA",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "ACS Progresul Pecica",
		      "oaspeti" => "ACSO Filiaşi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "CSC Ghiroda şi Giarmata Vii",
		      "oaspeti" => "CS Şoimii Lipova",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "CS Viitorul Dăeşti",
		      "oaspeti" => "CS Naţional Sebiş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-11-01",
		      "ora" => "14:00",
		      "gazde" => "CS Şoimii Lipova",
		      "oaspeti" => "CS Viitorul Dăeşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-01",
		      "ora" => "14:00",
		      "gazde" => "ACSO Filiaşi",
		      "oaspeti" => "CSC Dumbrăvița",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "CS Naţional Sebiş",
		      "oaspeti" => "ACS Poli Timişoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "CS Gilortul Târgu Cărbuneşti",
		      "oaspeti" => "CSC Ghiroda şi Giarmata Vii",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "U Craiova 1948 SA",
		      "oaspeti" => "ACS Progresul Pecica",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "ACS Flacăra Horezu",
		      "oaspeti" => "AS Fortuna Becicherecu Mic",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "CS Hunedoara",
		      "oaspeti" => "CS Crişul Chişineu Criş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "CS Gloria Lunca-Teuz Cermei",
		      "oaspeti" => "LPS Cetate Deva",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "ACS Poli Timişoara",
		      "oaspeti" => "LPS Cetate Deva",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "CS Crişul Chişineu Criş",
		      "oaspeti" => "CS Gloria Lunca-Teuz Cermei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "AS Fortuna Becicherecu Mic",
		      "oaspeti" => "CS Hunedoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "ACS Progresul Pecica",
		      "oaspeti" => "ACS Flacăra Horezu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "CSC Dumbrăvița",
		      "oaspeti" => "U Craiova 1948 SA",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "CSC Ghiroda şi Giarmata Vii",
		      "oaspeti" => "ACSO Filiaşi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "CS Viitorul Dăeşti",
		      "oaspeti" => "CS Gilortul Târgu Cărbuneşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "CS Naţional Sebiş",
		      "oaspeti" => "CS Şoimii Lipova",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "CS Şoimii Lipova",
		      "oaspeti" => "ACS Poli Timişoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "CS Gilortul Târgu Cărbuneşti",
		      "oaspeti" => "CS Naţional Sebiş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "ACSO Filiaşi",
		      "oaspeti" => "CS Viitorul Dăeşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "U Craiova 1948 SA",
		      "oaspeti" => "CSC Ghiroda şi Giarmata Vii",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "ACS Flacăra Horezu",
		      "oaspeti" => "CSC Dumbrăvița",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "CS Hunedoara",
		      "oaspeti" => "ACS Progresul Pecica",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "CS Gloria Lunca-Teuz Cermei",
		      "oaspeti" => "AS Fortuna Becicherecu Mic",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "LPS Cetate Deva",
		      "oaspeti" => "CS Crişul Chişineu Criş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "ACS Poli Timişoara",
		      "oaspeti" => "CS Crişul Chişineu Criş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "AS Fortuna Becicherecu Mic",
		      "oaspeti" => "LPS Cetate Deva",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "ACS Progresul Pecica",
		      "oaspeti" => "CS Gloria Lunca-Teuz Cermei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "CSC Dumbrăvița",
		      "oaspeti" => "CS Hunedoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "CSC Ghiroda şi Giarmata Vii",
		      "oaspeti" => "ACS Flacăra Horezu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "CS Viitorul Dăeşti",
		      "oaspeti" => "U Craiova 1948 SA",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "CS Naţional Sebiş",
		      "oaspeti" => "ACSO Filiaşi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "CS Şoimii Lipova",
		      "oaspeti" => "CS Gilortul Târgu Cărbuneşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "CS Gilortul Târgu Cărbuneşti",
		      "oaspeti" => "ACS Poli Timişoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "ACSO Filiaşi",
		      "oaspeti" => "CS Şoimii Lipova",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "U Craiova 1948 SA",
		      "oaspeti" => "CS Naţional Sebiş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "ACS Flacăra Horezu",
		      "oaspeti" => "CS Viitorul Dăeşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "CS Hunedoara",
		      "oaspeti" => "CSC Ghiroda şi Giarmata Vii",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "CS Gloria Lunca-Teuz Cermei",
		      "oaspeti" => "CSC Dumbrăvița",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "LPS Cetate Deva",
		      "oaspeti" => "ACS Progresul Pecica",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "CS Crişul Chişineu Criş",
		      "oaspeti" => "AS Fortuna Becicherecu Mic",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "ACS Poli Timişoara",
		      "oaspeti" => "AS Fortuna Becicherecu Mic",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "CS Crişul Chişineu Criş",
		      "oaspeti" => "ACS Progresul Pecica",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "LPS Cetate Deva",
		      "oaspeti" => "CSC Dumbrăvița",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "CS Gloria Lunca-Teuz Cermei",
		      "oaspeti" => "CSC Ghiroda şi Giarmata Vii",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "CS Hunedoara",
		      "oaspeti" => "CS Viitorul Dăeşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "ACS Flacăra Horezu",
		      "oaspeti" => "CS Naţional Sebiş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "U Craiova 1948 SA",
		      "oaspeti" => "CS Şoimii Lipova",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "ACSO Filiaşi",
		      "oaspeti" => "CS Gilortul Târgu Cărbuneşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "ACSO Filiaşi",
		      "oaspeti" => "ACS Poli Timişoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "CS Gilortul Târgu Cărbuneşti",
		      "oaspeti" => "U Craiova 1948 SA",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "CS Şoimii Lipova",
		      "oaspeti" => "ACS Flacăra Horezu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "CS Naţional Sebiş",
		      "oaspeti" => "CS Hunedoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "CS Viitorul Dăeşti",
		      "oaspeti" => "CS Gloria Lunca-Teuz Cermei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "CSC Ghiroda şi Giarmata Vii",
		      "oaspeti" => "LPS Cetate Deva",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "CSC Dumbrăvița",
		      "oaspeti" => "CS Crişul Chişineu Criş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "ACS Progresul Pecica",
		      "oaspeti" => "AS Fortuna Becicherecu Mic",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "ACS Poli Timişoara",
		      "oaspeti" => "ACS Progresul Pecica",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "AS Fortuna Becicherecu Mic",
		      "oaspeti" => "CSC Dumbrăvița",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "CS Crişul Chişineu Criş",
		      "oaspeti" => "CSC Ghiroda şi Giarmata Vii",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "LPS Cetate Deva",
		      "oaspeti" => "CS Viitorul Dăeşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "CS Gloria Lunca-Teuz Cermei",
		      "oaspeti" => "CS Naţional Sebiş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "CS Hunedoara",
		      "oaspeti" => "CS Şoimii Lipova",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "ACS Flacăra Horezu",
		      "oaspeti" => "CS Gilortul Târgu Cărbuneşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "U Craiova 1948 SA",
		      "oaspeti" => "ACSO Filiaşi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "U Craiova 1948 SA",
		      "oaspeti" => "ACS Poli Timişoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "ACSO Filiaşi",
		      "oaspeti" => "ACS Flacăra Horezu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "CS Gilortul Târgu Cărbuneşti",
		      "oaspeti" => "CS Hunedoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "CS Şoimii Lipova",
		      "oaspeti" => "CS Gloria Lunca-Teuz Cermei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "CS Naţional Sebiş",
		      "oaspeti" => "LPS Cetate Deva",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "CS Viitorul Dăeşti",
		      "oaspeti" => "CS Crişul Chişineu Criş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "CSC Ghiroda şi Giarmata Vii",
		      "oaspeti" => "AS Fortuna Becicherecu Mic",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "CSC Dumbrăvița",
		      "oaspeti" => "ACS Progresul Pecica",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "ACS Poli Timişoara",
		      "oaspeti" => "CSC Dumbrăvița",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "ACS Progresul Pecica",
		      "oaspeti" => "CSC Ghiroda şi Giarmata Vii",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "AS Fortuna Becicherecu Mic",
		      "oaspeti" => "CS Viitorul Dăeşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "CS Crişul Chişineu Criş",
		      "oaspeti" => "CS Naţional Sebiş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "LPS Cetate Deva",
		      "oaspeti" => "CS Şoimii Lipova",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "CS Gloria Lunca-Teuz Cermei",
		      "oaspeti" => "CS Gilortul Târgu Cărbuneşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "CS Hunedoara",
		      "oaspeti" => "ACSO Filiaşi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "ACS Flacăra Horezu",
		      "oaspeti" => "U Craiova 1948 SA",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "ACS Flacăra Horezu",
		      "oaspeti" => "ACS Poli Timişoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "U Craiova 1948 SA",
		      "oaspeti" => "CS Hunedoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "ACSO Filiaşi",
		      "oaspeti" => "CS Gloria Lunca-Teuz Cermei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "CS Gilortul Târgu Cărbuneşti",
		      "oaspeti" => "LPS Cetate Deva",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "CS Şoimii Lipova",
		      "oaspeti" => "CS Crişul Chişineu Criş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "CS Naţional Sebiş",
		      "oaspeti" => "AS Fortuna Becicherecu Mic",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "CS Viitorul Dăeşti",
		      "oaspeti" => "ACS Progresul Pecica",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "CSC Ghiroda şi Giarmata Vii",
		      "oaspeti" => "CSC Dumbrăvița",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "ACS Poli Timişoara",
		      "oaspeti" => "CSC Ghiroda şi Giarmata Vii",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "CSC Dumbrăvița",
		      "oaspeti" => "CS Viitorul Dăeşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "ACS Progresul Pecica",
		      "oaspeti" => "CS Naţional Sebiş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "AS Fortuna Becicherecu Mic",
		      "oaspeti" => "CS Şoimii Lipova",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "CS Crişul Chişineu Criş",
		      "oaspeti" => "CS Gilortul Târgu Cărbuneşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "LPS Cetate Deva",
		      "oaspeti" => "ACSO Filiaşi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "CS Gloria Lunca-Teuz Cermei",
		      "oaspeti" => "U Craiova 1948 SA",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "CS Hunedoara",
		      "oaspeti" => "ACS Flacăra Horezu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "CS Hunedoara",
		      "oaspeti" => "ACS Poli Timişoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "ACS Flacăra Horezu",
		      "oaspeti" => "CS Gloria Lunca-Teuz Cermei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "U Craiova 1948 SA",
		      "oaspeti" => "LPS Cetate Deva",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "ACSO Filiaşi",
		      "oaspeti" => "CS Crişul Chişineu Criş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "CS Gilortul Târgu Cărbuneşti",
		      "oaspeti" => "AS Fortuna Becicherecu Mic",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "CS Şoimii Lipova",
		      "oaspeti" => "ACS Progresul Pecica",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "CS Naţional Sebiş",
		      "oaspeti" => "CSC Dumbrăvița",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "CS Viitorul Dăeşti",
		      "oaspeti" => "CSC Ghiroda şi Giarmata Vii",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "ACS Poli Timişoara",
		      "oaspeti" => "CS Viitorul Dăeşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "CSC Ghiroda şi Giarmata Vii",
		      "oaspeti" => "CS Naţional Sebiş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "CSC Dumbrăvița",
		      "oaspeti" => "CS Şoimii Lipova",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "ACS Progresul Pecica",
		      "oaspeti" => "CS Gilortul Târgu Cărbuneşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "AS Fortuna Becicherecu Mic",
		      "oaspeti" => "ACSO Filiaşi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "CS Crişul Chişineu Criş",
		      "oaspeti" => "U Craiova 1948 SA",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "LPS Cetate Deva",
		      "oaspeti" => "ACS Flacăra Horezu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "CS Gloria Lunca-Teuz Cermei",
		      "oaspeti" => "CS Hunedoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "CS Gloria Lunca-Teuz Cermei",
		      "oaspeti" => "ACS Poli Timişoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "CS Hunedoara",
		      "oaspeti" => "LPS Cetate Deva",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "ACS Flacăra Horezu",
		      "oaspeti" => "CS Crişul Chişineu Criş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "U Craiova 1948 SA",
		      "oaspeti" => "AS Fortuna Becicherecu Mic",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "ACSO Filiaşi",
		      "oaspeti" => "ACS Progresul Pecica",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "CS Gilortul Târgu Cărbuneşti",
		      "oaspeti" => "CSC Dumbrăvița",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "CS Şoimii Lipova",
		      "oaspeti" => "CSC Ghiroda şi Giarmata Vii",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "CS Naţional Sebiş",
		      "oaspeti" => "CS Viitorul Dăeşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "ACS Poli Timişoara",
		      "oaspeti" => "CS Naţional Sebiş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "CS Viitorul Dăeşti",
		      "oaspeti" => "CS Şoimii Lipova",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "CSC Ghiroda şi Giarmata Vii",
		      "oaspeti" => "CS Gilortul Târgu Cărbuneşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "CSC Dumbrăvița",
		      "oaspeti" => "ACSO Filiaşi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "ACS Progresul Pecica",
		      "oaspeti" => "U Craiova 1948 SA",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "AS Fortuna Becicherecu Mic",
		      "oaspeti" => "ACS Flacăra Horezu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "CS Crişul Chişineu Criş",
		      "oaspeti" => "CS Hunedoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "LPS Cetate Deva",
		      "oaspeti" => "CS Gloria Lunca-Teuz Cermei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "LPS Cetate Deva",
		      "oaspeti" => "ACS Poli Timişoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "CS Gloria Lunca-Teuz Cermei",
		      "oaspeti" => "CS Crişul Chişineu Criş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "CS Hunedoara",
		      "oaspeti" => "AS Fortuna Becicherecu Mic",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "ACS Flacăra Horezu",
		      "oaspeti" => "ACS Progresul Pecica",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "U Craiova 1948 SA",
		      "oaspeti" => "CSC Dumbrăvița",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "ACSO Filiaşi",
		      "oaspeti" => "CSC Ghiroda şi Giarmata Vii",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "CS Gilortul Târgu Cărbuneşti",
		      "oaspeti" => "CS Viitorul Dăeşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "CS Şoimii Lipova",
		      "oaspeti" => "CS Naţional Sebiş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "ACS Poli Timişoara",
		      "oaspeti" => "CS Şoimii Lipova",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "CS Naţional Sebiş",
		      "oaspeti" => "CS Gilortul Târgu Cărbuneşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "CS Viitorul Dăeşti",
		      "oaspeti" => "ACSO Filiaşi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "CSC Ghiroda şi Giarmata Vii",
		      "oaspeti" => "U Craiova 1948 SA",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "CSC Dumbrăvița",
		      "oaspeti" => "ACS Flacăra Horezu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "ACS Progresul Pecica",
		      "oaspeti" => "CS Hunedoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "AS Fortuna Becicherecu Mic",
		      "oaspeti" => "CS Gloria Lunca-Teuz Cermei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "CS Crişul Chişineu Criş",
		      "oaspeti" => "LPS Cetate Deva",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "CS Crişul Chişineu Criş",
		      "oaspeti" => "ACS Poli Timişoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "LPS Cetate Deva",
		      "oaspeti" => "AS Fortuna Becicherecu Mic",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "CS Gloria Lunca-Teuz Cermei",
		      "oaspeti" => "ACS Progresul Pecica",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "CS Hunedoara",
		      "oaspeti" => "CSC Dumbrăvița",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "ACS Flacăra Horezu",
		      "oaspeti" => "CSC Ghiroda şi Giarmata Vii",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "U Craiova 1948 SA",
		      "oaspeti" => "CS Viitorul Dăeşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "ACSO Filiaşi",
		      "oaspeti" => "CS Naţional Sebiş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "CS Gilortul Târgu Cărbuneşti",
		      "oaspeti" => "CS Şoimii Lipova",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "ACS Poli Timişoara",
		      "oaspeti" => "CS Gilortul Târgu Cărbuneşti",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "CS Şoimii Lipova",
		      "oaspeti" => "ACSO Filiaşi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "CS Naţional Sebiş",
		      "oaspeti" => "U Craiova 1948 SA",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "CS Viitorul Dăeşti",
		      "oaspeti" => "ACS Flacăra Horezu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "CSC Ghiroda şi Giarmata Vii",
		      "oaspeti" => "CS Hunedoara",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "CSC Dumbrăvița",
		      "oaspeti" => "CS Gloria Lunca-Teuz Cermei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "ACS Progresul Pecica",
		      "oaspeti" => "LPS Cetate Deva",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "AS Fortuna Becicherecu Mic",
		      "oaspeti" => "CS Crişul Chişineu Criş",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 4,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ]
		];

		foreach ($echipe as $echipa) {
			$adauga = new ToateEchipele;
			$adauga->team = trim($echipa['echipa']);
			$adauga->save();

			// Echipe::where('echipa_id', $e->id)->delete();
			$clasament = new Echipe;
			$clasament->echipa_id = $adauga->id;
			$clasament->liga = 3;
			$clasament->serie = 4;
			$clasament->sezon = '2019/2020';
			$clasament->save();
		}


		Etape::where('liga', 3)->where('serie', 4)->where('sezon', '2019/2020')->delete();

		foreach ($etape as $etapa) {
			$gazde = ToateEchipele::where('team', trim($etapa['gazde']))->first();
			$oaspeti = ToateEchipele::where('team', trim($etapa['oaspeti']))->first();

			$adauga = new Etape;
			$adauga->gazde_id   = $gazde['id'];
			$adauga->oaspeti_id = $oaspeti['id'];
			$adauga->g_gazde    = $etapa['g_gazde'];
			$adauga->g_oaspeti  = $etapa['g_oaspeti'];
			$adauga->liga       = $etapa['liga'];
			$adauga->serie      = $etapa['serie'];
			$adauga->etapa      = $etapa['etapa'];
			$adauga->data       = $etapa['data'];
			$adauga->ora        = $etapa['ora'];
			$adauga->sezon      = $etapa['sezon'];
			$adauga->save();
		}
    }
}
