<?php

use Illuminate\Database\Seeder;
use App\Echipe;
use App\Etape;

class liga_5_sud extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $echipe = [
			[
				'echipa' => 'Spic de Grau Ghimpati',
				'liga'   => 5,
				'serie'  => 'SUD',
			], [
				'echipa' => 'Viitorul Gheboaia',
				'liga'   => 5,
				'serie'  => 'SUD',
			], [
				'echipa' => 'Unirea Slobozia Moara',
				'liga'   => 5,
				'serie'  => 'SUD',
			], [
				'echipa' => 'Luceafarul Bolovani',
				'liga'   => 5,
				'serie'  => 'SUD',
			], [
				'echipa' => 'Unirea Nucet',
				'liga'   => 5,
				'serie'  => 'SUD',
			], [
				'echipa' => 'F.C. Potlogi',
				'liga'   => 5,
				'serie'  => 'SUD',
			], [
				'echipa' => 'Sageata Branistea',
				'liga'   => 5,
				'serie'  => 'SUD',
			], [
				'echipa' => 'Flacara Ghinesti',
				'liga'   => 5,
				'serie'  => 'SUD',
			], [
				'echipa' => 'Viitorul Mircea Voda',
				'liga'   => 5,
				'serie'  => 'SUD',
			], [
				'echipa' => 'Olimpia Marcesti',
				'liga'   => 5,
				'serie'  => 'SUD',
			], [
				'echipa' => 'Libertatea Urziceanca',
				'liga'   => 5,
				'serie'  => 'SUD',
			], [
				'echipa' => 'Publirex Ciocanesti',
				'liga'   => 5,
				'serie'  => 'SUD',
			], [
				'echipa' => 'Vanatorul 2015 Ratoaia',
				'liga'   => 5,
				'serie'  => 'SUD',
			], [
				'echipa' => 'F.C Dentas  Tartasesti',
				'liga'   => 5,
				'serie'  => 'SUD',
			], [
				'echipa' => 'C.S. Fulgerul Lunguletu',
				'liga'   => 5,
				'serie'  => 'SUD',
			], [
				'echipa' => 'Gaz Metan Finta',
				'liga'   => 5,
				'serie'  => 'SUD',
			], [
				'echipa' => 'Viitorul Dobra',
				'liga'   => 5,
				'serie'  => 'SUD',
			], [
				'echipa' => 'Vointa Podu Rizii',
				'liga'   => 5,
				'serie'  => 'SUD',
			]
		];

		$etape = [
			[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 1,
				'gazde'     => 'Spic de Grau Ghimpati',
				'g_gazde'   => 2,
				'oaspeti'   => 'Viitorul Gheboaia',
				'g_oaspeti' => 1,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 1,
				'gazde'     => 'Unirea Slobozia Moara',
				'g_gazde'   => 4,
				'oaspeti'   => 'Luceafarul Bolovani',
				'g_oaspeti' => 3,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 1,
				'gazde'     => 'Unirea Nucet',
				'g_gazde'   => 7,
				'oaspeti'   => 'F.C. Potlogi',
				'g_oaspeti' => 3,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 1,
				'gazde'     => 'Sageata Branistea',
				'g_gazde'   => 7,
				'oaspeti'   => 'Flacara Ghinesti',
				'g_oaspeti' => 3,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 1,
				'gazde'     => 'Viitorul Mircea Voda',
				'g_gazde'   => 2,
				'oaspeti'   => 'Olimpia Marcesti',
				'g_oaspeti' => 2,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 1,
				'gazde'     => 'Libertatea Urziceanca',
				'g_gazde'   => 12,
				'oaspeti'   => 'Publirex Ciocanesti',
				'g_oaspeti' => 2,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 1,
				'gazde'     => 'Vanatorul 2015 Ratoaia',
				'g_gazde'   => 3,
				'oaspeti'   => 'F.C Dentas  Tartasesti',
				'g_oaspeti' => 3,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 1,
				'gazde'     => 'C.S. Fulgerul Lunguletu',
				'g_gazde'   => 5,
				'oaspeti'   => 'Gaz Metan Finta',
				'g_oaspeti' => 7,
			],[
				'data'      => '19-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 1,
				'gazde'     => 'Viitorul Dobra',
				'g_gazde'   => 2,
				'oaspeti'   => 'Vointa Podu Rizii',
				'g_oaspeti' => 1,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 2,
				'gazde'     => 'Viitorul Gheboaia',
				'g_gazde'   => 3,
				'oaspeti'   => 'Vointa Podu Rizii',
				'g_oaspeti' => 1,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 2,
				'gazde'     => 'Gaz Metan Finta',
				'g_gazde'   => 5,
				'oaspeti'   => 'Viitorul Dobra',
				'g_oaspeti' => 2,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 2,
				'gazde'     => 'F.C Dentas  Tartasesti',
				'g_gazde'   => 7,
				'oaspeti'   => 'C.S. Fulgerul Lunguletu',
				'g_oaspeti' => 1,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 2,
				'gazde'     => 'Publirex Ciocanesti',
				'g_gazde'   => 2,
				'oaspeti'   => 'Vanatorul 2015 Ratoaia',
				'g_oaspeti' => 0,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 2,
				'gazde'     => 'Olimpia Marcesti',
				'g_gazde'   => 3,
				'oaspeti'   => 'Libertatea Urziceanca',
				'g_oaspeti' => 5,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 2,
				'gazde'     => 'Flacara Ghinesti',
				'g_gazde'   => 1,
				'oaspeti'   => 'Viitorul Mircea Voda',
				'g_oaspeti' => 2,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 2,
				'gazde'     => 'F.C. Potlogi',
				'g_gazde'   => 5,
				'oaspeti'   => 'Sageata Branistea',
				'g_oaspeti' => 0,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 2,
				'gazde'     => 'Luceafarul Bolovani',
				'g_gazde'   => 2,
				'oaspeti'   => 'Unirea Nucet',
				'g_oaspeti' => 2,
			],[
				'data'      => '26-08-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 2,
				'gazde'     => 'Spic de Grau Ghimpati',
				'g_gazde'   => 5,
				'oaspeti'   => 'Unirea Slobozia Moara',
				'g_oaspeti' => 6,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 3,
				'gazde'     => 'Unirea Slobozia Moara',
				'g_gazde'   => 2,
				'oaspeti'   => 'Viitorul Gheboaia',
				'g_oaspeti' => 0,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 3,
				'gazde'     => 'Unirea Nucet',
				'g_gazde'   => 7,
				'oaspeti'   => 'Spic de Grau Ghimpati',
				'g_oaspeti' => 1,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 3,
				'gazde'     => 'Sageata Branistea',
				'g_gazde'   => 9,
				'oaspeti'   => 'Luceafarul Bolovani',
				'g_oaspeti' => 1,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 3,
				'gazde'     => 'Viitorul Mircea Voda',
				'g_gazde'   => 3,
				'oaspeti'   => 'F.C. Potlogi',
				'g_oaspeti' => 1,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 3,
				'gazde'     => 'Libertatea Urziceanca',
				'g_gazde'   => 3,
				'oaspeti'   => 'Flacara Ghinesti',
				'g_oaspeti' => 0,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 3,
				'gazde'     => 'Vanatorul 2015 Ratoaia',
				'g_gazde'   => 6,
				'oaspeti'   => 'Olimpia Marcesti',
				'g_oaspeti' => 0,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 3,
				'gazde'     => 'C.S. Fulgerul Lunguletu',
				'g_gazde'   => 6,
				'oaspeti'   => 'Publirex Ciocanesti',
				'g_oaspeti' => 5,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 3,
				'gazde'     => 'Viitorul Dobra',
				'g_gazde'   => 2,
				'oaspeti'   => 'F.C Dentas  Tartasesti',
				'g_oaspeti' => 3,
			],[
				'data'      => '29-08-2018',
				'ora'       => '18:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 3,
				'gazde'     => 'Vointa Podu Rizii',
				'g_gazde'   => 1,
				'oaspeti'   => 'Gaz Metan Finta',
				'g_oaspeti' => 4,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 4,
				'gazde'     => 'Viitorul Gheboaia',
				'g_gazde'   => 0,
				'oaspeti'   => 'Gaz Metan Finta',
				'g_oaspeti' => 4,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 4,
				'gazde'     => 'F.C Dentas  Tartasesti',
				'g_gazde'   => 5,
				'oaspeti'   => 'Vointa Podu Rizii',
				'g_oaspeti' => 2,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 4,
				'gazde'     => 'Publirex Ciocanesti',
				'g_gazde'   => 2,
				'oaspeti'   => 'Viitorul Dobra',
				'g_oaspeti' => 2,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 4,
				'gazde'     => 'Olimpia Marcesti',
				'g_gazde'   => 1,
				'oaspeti'   => 'C.S. Fulgerul Lunguletu',
				'g_oaspeti' => 2,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 4,
				'gazde'     => 'Flacara Ghinesti',
				'g_gazde'   => 1,
				'oaspeti'   => 'Vanatorul 2015 Ratoaia',
				'g_oaspeti' => 0,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 4,
				'gazde'     => 'F.C. Potlogi',
				'g_gazde'   => 3,
				'oaspeti'   => 'Libertatea Urziceanca',
				'g_oaspeti' => 3,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 4,
				'gazde'     => 'Luceafarul Bolovani',
				'g_gazde'   => 2,
				'oaspeti'   => 'Viitorul Mircea Voda',
				'g_oaspeti' => 1,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 4,
				'gazde'     => 'Spic de Grau Ghimpati',
				'g_gazde'   => 1,
				'oaspeti'   => 'Sageata Branistea',
				'g_oaspeti' => 2,
			],[
				'data'      => '02-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 4,
				'gazde'     => 'Unirea Slobozia Moara',
				'g_gazde'   => 1,
				'oaspeti'   => 'Unirea Nucet',
				'g_oaspeti' => 3,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 5,
				'gazde'     => 'Unirea Nucet',
				'g_gazde'   => 4,
				'oaspeti'   => 'Viitorul Gheboaia',
				'g_oaspeti' => 0,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 5,
				'gazde'     => 'Sageata Branistea',
				'g_gazde'   => 5,
				'oaspeti'   => 'Unirea Slobozia Moara',
				'g_oaspeti' => 1,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 5,
				'gazde'     => 'Viitorul Mircea Voda',
				'g_gazde'   => 2,
				'oaspeti'   => 'Spic de Grau Ghimpati',
				'g_oaspeti' => 2,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 5,
				'gazde'     => 'Libertatea Urziceanca',
				'g_gazde'   => 4,
				'oaspeti'   => 'Luceafarul Bolovani',
				'g_oaspeti' => 3,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 5,
				'gazde'     => 'Vanatorul 2015 Ratoaia',
				'g_gazde'   => 3,
				'oaspeti'   => 'F.C. Potlogi',
				'g_oaspeti' => 3,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 5,
				'gazde'     => 'C.S. Fulgerul Lunguletu',
				'g_gazde'   => 2,
				'oaspeti'   => 'Flacara Ghinesti',
				'g_oaspeti' => 2,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 5,
				'gazde'     => 'Viitorul Dobra',
				'g_gazde'   => 9,
				'oaspeti'   => 'Olimpia Marcesti',
				'g_oaspeti' => 3,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 5,
				'gazde'     => 'Vointa Podu Rizii',
				'g_gazde'   => 9,
				'oaspeti'   => 'Publirex Ciocanesti',
				'g_oaspeti' => 0,
			],[
				'data'      => '09-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 5,
				'gazde'     => 'Gaz Metan Finta',
				'g_gazde'   => 7,
				'oaspeti'   => 'F.C Dentas  Tartasesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 6,
				'gazde'     => 'Viitorul Gheboaia',
				'g_gazde'   => 3,
				'oaspeti'   => 'F.C Dentas  Tartasesti',
				'g_oaspeti' => 4,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 6,
				'gazde'     => 'Publirex Ciocanesti',
				'g_gazde'   => 2,
				'oaspeti'   => 'Gaz Metan Finta',
				'g_oaspeti' => 7,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 6,
				'gazde'     => 'Olimpia Marcesti',
				'g_gazde'   => 1,
				'oaspeti'   => 'Vointa Podu Rizii',
				'g_oaspeti' => 2,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 6,
				'gazde'     => 'Flacara Ghinesti',
				'g_gazde'   => 3,
				'oaspeti'   => 'Viitorul Dobra',
				'g_oaspeti' => 5,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 6,
				'gazde'     => 'F.C. Potlogi',
				'g_gazde'   => 8,
				'oaspeti'   => 'C.S. Fulgerul Lunguletu',
				'g_oaspeti' => 2,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 6,
				'gazde'     => 'Luceafarul Bolovani',
				'g_gazde'   => 3,
				'oaspeti'   => 'Vanatorul 2015 Ratoaia',
				'g_oaspeti' => 1,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 6,
				'gazde'     => 'Spic de Grau Ghimpati',
				'g_gazde'   => 2,
				'oaspeti'   => 'Libertatea Urziceanca',
				'g_oaspeti' => 3,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 6,
				'gazde'     => 'Unirea Slobozia Moara',
				'g_gazde'   => 4,
				'oaspeti'   => 'Viitorul Mircea Voda',
				'g_oaspeti' => 2,
			],[
				'data'      => '12-09-2018',
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 6,
				'gazde'     => 'Unirea Nucet',
				'g_gazde'   => 2,
				'oaspeti'   => 'Sageata Branistea',
				'g_oaspeti' => 1,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 7,
				'gazde'     => 'Sageata Branistea',
				'g_gazde'   => 1,
				'oaspeti'   => 'Viitorul Gheboaia',
				'g_oaspeti' => 1,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 7,
				'gazde'     => 'Viitorul Mircea Voda',
				'g_gazde'   => 3,
				'oaspeti'   => 'Unirea Nucet',
				'g_oaspeti' => 0,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 7,
				'gazde'     => 'Libertatea Urziceanca',
				'g_gazde'   => 9,
				'oaspeti'   => 'Unirea Slobozia Moara',
				'g_oaspeti' => 3,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 7,
				'gazde'     => 'Vanatorul 2015 Ratoaia',
				'g_gazde'   => 2,
				'oaspeti'   => 'Spic de Grau Ghimpati',
				'g_oaspeti' => 2,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 7,
				'gazde'     => 'C.S. Fulgerul Lunguletu',
				'g_gazde'   => 0,
				'oaspeti'   => 'Luceafarul Bolovani',
				'g_oaspeti' => 3,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 7,
				'gazde'     => 'Viitorul Dobra',
				'g_gazde'   => 3,
				'oaspeti'   => 'F.C. Potlogi',
				'g_oaspeti' => 1,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 7,
				'gazde'     => 'Vointa Podu Rizii',
				'g_gazde'   => 3,
				'oaspeti'   => 'Flacara Ghinesti',
				'g_oaspeti' => 0,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 7,
				'gazde'     => 'Gaz Metan Finta',
				'g_gazde'   => 15,
				'oaspeti'   => 'Olimpia Marcesti',
				'g_oaspeti' => 2,
			],[
				'data'      => '16-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 7,
				'gazde'     => 'F.C Dentas  Tartasesti',
				'g_gazde'   => 3,
				'oaspeti'   => 'Publirex Ciocanesti',
				'g_oaspeti' => 0,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 8,
				'gazde'     => 'Viitorul Gheboaia',
				'g_gazde'   => 5,
				'oaspeti'   => 'Publirex Ciocanesti',
				'g_oaspeti' => 2,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 8,
				'gazde'     => 'Olimpia Marcesti',
				'g_gazde'   => 0,
				'oaspeti'   => 'F.C Dentas  Tartasesti',
				'g_oaspeti' => 2,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 8,
				'gazde'     => 'Flacara Ghinesti',
				'g_gazde'   => 3,
				'oaspeti'   => 'Gaz Metan Finta',
				'g_oaspeti' => 6,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 8,
				'gazde'     => 'F.C. Potlogi',
				'g_gazde'   => 6,
				'oaspeti'   => 'Vointa Podu Rizii',
				'g_oaspeti' => 2,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 8,
				'gazde'     => 'Luceafarul Bolovani',
				'g_gazde'   => 1,
				'oaspeti'   => 'Viitorul Dobra',
				'g_oaspeti' => 3,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 8,
				'gazde'     => 'Spic de Grau Ghimpati',
				'g_gazde'   => 3,
				'oaspeti'   => 'C.S. Fulgerul Lunguletu',
				'g_oaspeti' => 4,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 8,
				'gazde'     => 'Unirea Slobozia Moara',
				'g_gazde'   => 0,
				'oaspeti'   => 'Vanatorul 2015 Ratoaia',
				'g_oaspeti' => 3,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 8,
				'gazde'     => 'Unirea Nucet',
				'g_gazde'   => 2,
				'oaspeti'   => 'Libertatea Urziceanca',
				'g_oaspeti' => 1,
			],[
				'data'      => '23-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 8,
				'gazde'     => 'Sageata Branistea',
				'g_gazde'   => 5,
				'oaspeti'   => 'Viitorul Mircea Voda',
				'g_oaspeti' => 3,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 9,
				'gazde'     => 'Viitorul Mircea Voda',
				'g_gazde'   => 2,
				'oaspeti'   => 'Viitorul Gheboaia',
				'g_oaspeti' => 3,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 9,
				'gazde'     => 'Libertatea Urziceanca',
				'g_gazde'   => 3,
				'oaspeti'   => 'Sageata Branistea',
				'g_oaspeti' => 1,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 9,
				'gazde'     => 'Vanatorul 2015 Ratoaia',
				'g_gazde'   => 4,
				'oaspeti'   => 'Unirea Nucet',
				'g_oaspeti' => 1,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 9,
				'gazde'     => 'C.S. Fulgerul Lunguletu',
				'g_gazde'   => 7,
				'oaspeti'   => 'Unirea Slobozia Moara',
				'g_oaspeti' => 1,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 9,
				'gazde'     => 'Viitorul Dobra',
				'g_gazde'   => 7,
				'oaspeti'   => 'Spic de Grau Ghimpati',
				'g_oaspeti' => 1,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 9,
				'gazde'     => 'Vointa Podu Rizii',
				'g_gazde'   => 4,
				'oaspeti'   => 'Luceafarul Bolovani',
				'g_oaspeti' => 1,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 9,
				'gazde'     => 'Gaz Metan Finta',
				'g_gazde'   => 3,
				'oaspeti'   => 'F.C. Potlogi',
				'g_oaspeti' => 0,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 9,
				'gazde'     => 'F.C Dentas  Tartasesti',
				'g_gazde'   => 8,
				'oaspeti'   => 'Flacara Ghinesti',
				'g_oaspeti' => 0,
			],[
				'data'      => '30-09-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 9,
				'gazde'     => 'Publirex Ciocanesti',
				'g_gazde'   => 2,
				'oaspeti'   => 'Olimpia Marcesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 10,
				'gazde'     => 'Viitorul Gheboaia',
				'g_gazde'   => 3,
				'oaspeti'   => 'Olimpia Marcesti',
				'g_oaspeti' => 0,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 10,
				'gazde'     => 'Flacara Ghinesti',
				'g_gazde'   => 5,
				'oaspeti'   => 'Publirex Ciocanesti',
				'g_oaspeti' => 2,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 10,
				'gazde'     => 'F.C. Potlogi',
				'g_gazde'   => 4,
				'oaspeti'   => 'F.C Dentas  Tartasesti',
				'g_oaspeti' => 0,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 10,
				'gazde'     => 'Luceafarul Bolovani',
				'g_gazde'   => 1,
				'oaspeti'   => 'Gaz Metan Finta',
				'g_oaspeti' => 4,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 10,
				'gazde'     => 'Spic de Grau Ghimpati',
				'g_gazde'   => 0,
				'oaspeti'   => 'Vointa Podu Rizii',
				'g_oaspeti' => 0,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 10,
				'gazde'     => 'Unirea Slobozia Moara',
				'g_gazde'   => 4,
				'oaspeti'   => 'Viitorul Dobra',
				'g_oaspeti' => 3,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 10,
				'gazde'     => 'Unirea Nucet',
				'g_gazde'   => 2,
				'oaspeti'   => 'C.S. Fulgerul Lunguletu',
				'g_oaspeti' => 3,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 10,
				'gazde'     => 'Sageata Branistea',
				'g_gazde'   => 6,
				'oaspeti'   => 'Vanatorul 2015 Ratoaia',
				'g_oaspeti' => 3,
			],[
				'data'      => '07-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 10,
				'gazde'     => 'Viitorul Mircea Voda',
				'g_gazde'   => 3,
				'oaspeti'   => 'Libertatea Urziceanca',
				'g_oaspeti' => 3,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 11,
				'gazde'     => 'Libertatea Urziceanca',
				'g_gazde'   => 5,
				'oaspeti'   => 'Viitorul Gheboaia',
				'g_oaspeti' => 3,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 11,
				'gazde'     => 'Vanatorul 2015 Ratoaia',
				'g_gazde'   => 5,
				'oaspeti'   => 'Viitorul Mircea Voda',
				'g_oaspeti' => 1,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 11,
				'gazde'     => 'C.S. Fulgerul Lunguletu',
				'g_gazde'   => 5,
				'oaspeti'   => 'Sageata Branistea',
				'g_oaspeti' => 4,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 11,
				'gazde'     => 'Viitorul Dobra',
				'g_gazde'   => 1,
				'oaspeti'   => 'Unirea Nucet',
				'g_oaspeti' => 4,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 11,
				'gazde'     => 'Vointa Podu Rizii',
				'g_gazde'   => 1,
				'oaspeti'   => 'Unirea Slobozia Moara',
				'g_oaspeti' => 0,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 11,
				'gazde'     => 'Gaz Metan Finta',
				'g_gazde'   => 11,
				'oaspeti'   => 'Spic de Grau Ghimpati',
				'g_oaspeti' => 1,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 11,
				'gazde'     => 'F.C Dentas  Tartasesti',
				'g_gazde'   => 2,
				'oaspeti'   => 'Luceafarul Bolovani',
				'g_oaspeti' => 2,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 11,
				'gazde'     => 'Publirex Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C. Potlogi',
				'g_oaspeti' => null,
			],[
				'data'      => '14-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 11,
				'gazde'     => 'Olimpia Marcesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Ghinesti',
				'g_oaspeti' => null,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 12,
				'gazde'     => 'Viitorul Gheboaia',
				'g_gazde'   => 2,
				'oaspeti'   => 'Flacara Ghinesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 12,
				'gazde'     => 'F.C. Potlogi',
				'g_gazde'   => 4,
				'oaspeti'   => 'Olimpia Marcesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 12,
				'gazde'     => 'Luceafarul Bolovani',
				'g_gazde'   => 1,
				'oaspeti'   => 'Publirex Ciocanesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 12,
				'gazde'     => 'Spic de Grau Ghimpati',
				'g_gazde'   => 1,
				'oaspeti'   => 'F.C Dentas  Tartasesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 12,
				'gazde'     => 'Unirea Slobozia Moara',
				'g_gazde'   => 0,
				'oaspeti'   => 'Gaz Metan Finta',
				'g_oaspeti' => 5,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 12,
				'gazde'     => 'Unirea Nucet',
				'g_gazde'   => 3,
				'oaspeti'   => 'Vointa Podu Rizii',
				'g_oaspeti' => 0,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 12,
				'gazde'     => 'Sageata Branistea',
				'g_gazde'   => 3,
				'oaspeti'   => 'Viitorul Dobra',
				'g_oaspeti' => 4,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 12,
				'gazde'     => 'Viitorul Mircea Voda',
				'g_gazde'   => 1,
				'oaspeti'   => 'C.S. Fulgerul Lunguletu',
				'g_oaspeti' => 4,
			],[
				'data'      => '21-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 12,
				'gazde'     => 'Libertatea Urziceanca',
				'g_gazde'   => 6,
				'oaspeti'   => 'Vanatorul 2015 Ratoaia',
				'g_oaspeti' => 6,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 13,
				'gazde'     => 'Vanatorul 2015 Ratoaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gheboaia',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 13,
				'gazde'     => 'C.S. Fulgerul Lunguletu',
				'g_gazde'   => null,
				'oaspeti'   => 'Libertatea Urziceanca',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 13,
				'gazde'     => 'Viitorul Dobra',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Mircea Voda',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 13,
				'gazde'     => 'Vointa Podu Rizii',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Branistea',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 13,
				'gazde'     => 'Gaz Metan Finta',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Nucet',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 13,
				'gazde'     => 'F.C Dentas  Tartasesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Slobozia Moara',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 13,
				'gazde'     => 'Publirex Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Spic de Grau Ghimpati',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 13,
				'gazde'     => 'Olimpia Marcesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Bolovani',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 13,
				'gazde'     => 'Flacara Ghinesti',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C. Potlogi',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 14,
				'gazde'     => 'Viitorul Gheboaia',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C. Potlogi',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 14,
				'gazde'     => 'Luceafarul Bolovani',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Ghinesti',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 14,
				'gazde'     => 'Spic de Grau Ghimpati',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Marcesti',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 14,
				'gazde'     => 'Unirea Slobozia Moara',
				'g_gazde'   => null,
				'oaspeti'   => 'Publirex Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 14,
				'gazde'     => 'Unirea Nucet',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C Dentas  Tartasesti',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 14,
				'gazde'     => 'Sageata Branistea',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Finta',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 14,
				'gazde'     => 'Viitorul Mircea Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Podu Rizii',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 14,
				'gazde'     => 'Libertatea Urziceanca',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Dobra',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 14,
				'gazde'     => 'Vanatorul 2015 Ratoaia',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S. Fulgerul Lunguletu',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 15,
				'gazde'     => 'C.S. Fulgerul Lunguletu',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gheboaia',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 15,
				'gazde'     => 'Viitorul Dobra',
				'g_gazde'   => null,
				'oaspeti'   => 'Vanatorul 2015 Ratoaia',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 15,
				'gazde'     => 'Vointa Podu Rizii',
				'g_gazde'   => null,
				'oaspeti'   => 'Libertatea Urziceanca',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 15,
				'gazde'     => 'Gaz Metan Finta',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Mircea Voda',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 15,
				'gazde'     => 'F.C Dentas  Tartasesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Branistea',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 15,
				'gazde'     => 'Publirex Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Nucet',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 15,
				'gazde'     => 'Olimpia Marcesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Slobozia Moara',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 15,
				'gazde'     => 'Flacara Ghinesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Spic de Grau Ghimpati',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 15,
				'gazde'     => 'F.C. Potlogi',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Bolovani',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 16,
				'gazde'     => 'Viitorul Gheboaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Bolovani',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 16,
				'gazde'     => 'Spic de Grau Ghimpati',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C. Potlogi',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 16,
				'gazde'     => 'Unirea Slobozia Moara',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Ghinesti',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 16,
				'gazde'     => 'Unirea Nucet',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Marcesti',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 16,
				'gazde'     => 'Sageata Branistea',
				'g_gazde'   => null,
				'oaspeti'   => 'Publirex Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 16,
				'gazde'     => 'Viitorul Mircea Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C Dentas  Tartasesti',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 16,
				'gazde'     => 'Libertatea Urziceanca',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Finta',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 16,
				'gazde'     => 'Vanatorul 2015 Ratoaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Podu Rizii',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 16,
				'gazde'     => 'C.S. Fulgerul Lunguletu',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Dobra',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 17,
				'gazde'     => 'Viitorul Dobra',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gheboaia',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 17,
				'gazde'     => 'Vointa Podu Rizii',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S. Fulgerul Lunguletu',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 17,
				'gazde'     => 'Gaz Metan Finta',
				'g_gazde'   => null,
				'oaspeti'   => 'Vanatorul 2015 Ratoaia',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 17,
				'gazde'     => 'F.C Dentas  Tartasesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Libertatea Urziceanca',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 17,
				'gazde'     => 'Publirex Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Mircea Voda',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 17,
				'gazde'     => 'Olimpia Marcesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Branistea',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 17,
				'gazde'     => 'Flacara Ghinesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Nucet',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 17,
				'gazde'     => 'F.C. Potlogi',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Slobozia Moara',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '11:00',
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 17,
				'gazde'     => 'Luceafarul Bolovani',
				'g_gazde'   => null,
				'oaspeti'   => 'Spic de Grau Ghimpati',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 18,
				'gazde'     => 'Viitorul Gheboaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Spic de Grau Ghimpati',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 18,
				'gazde'     => 'Luceafarul Bolovani',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Slobozia Moara',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 18,
				'gazde'     => 'F.C. Potlogi',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Nucet',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 18,
				'gazde'     => 'Flacara Ghinesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Branistea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 18,
				'gazde'     => 'Olimpia Marcesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Mircea Voda',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 18,
				'gazde'     => 'Publirex Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Libertatea Urziceanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 18,
				'gazde'     => 'F.C Dentas  Tartasesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Vanatorul 2015 Ratoaia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 18,
				'gazde'     => 'Gaz Metan Finta',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S. Fulgerul Lunguletu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 18,
				'gazde'     => 'Vointa Podu Rizii',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Dobra',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 19,
				'gazde'     => 'Vointa Podu Rizii',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gheboaia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 19,
				'gazde'     => 'Viitorul Dobra',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Finta',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 19,
				'gazde'     => 'C.S. Fulgerul Lunguletu',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C Dentas  Tartasesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 19,
				'gazde'     => 'Vanatorul 2015 Ratoaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Publirex Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 19,
				'gazde'     => 'Libertatea Urziceanca',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Marcesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 19,
				'gazde'     => 'Viitorul Mircea Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Ghinesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 19,
				'gazde'     => 'Sageata Branistea',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C. Potlogi',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 19,
				'gazde'     => 'Unirea Nucet',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Bolovani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 19,
				'gazde'     => 'Unirea Slobozia Moara',
				'g_gazde'   => null,
				'oaspeti'   => 'Spic de Grau Ghimpati',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 20,
				'gazde'     => 'Viitorul Gheboaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Slobozia Moara',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 20,
				'gazde'     => 'Spic de Grau Ghimpati',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Nucet',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 20,
				'gazde'     => 'Luceafarul Bolovani',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Branistea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 20,
				'gazde'     => 'F.C. Potlogi',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Mircea Voda',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 20,
				'gazde'     => 'Flacara Ghinesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Libertatea Urziceanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 20,
				'gazde'     => 'Olimpia Marcesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Vanatorul 2015 Ratoaia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 20,
				'gazde'     => 'Publirex Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S. Fulgerul Lunguletu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 20,
				'gazde'     => 'F.C Dentas  Tartasesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Dobra',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 20,
				'gazde'     => 'Gaz Metan Finta',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Podu Rizii',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 21,
				'gazde'     => 'Gaz Metan Finta',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gheboaia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 21,
				'gazde'     => 'Vointa Podu Rizii',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C Dentas  Tartasesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 21,
				'gazde'     => 'Viitorul Dobra',
				'g_gazde'   => null,
				'oaspeti'   => 'Publirex Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 21,
				'gazde'     => 'C.S. Fulgerul Lunguletu',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Marcesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 21,
				'gazde'     => 'Vanatorul 2015 Ratoaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Ghinesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 21,
				'gazde'     => 'Libertatea Urziceanca',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C. Potlogi',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 21,
				'gazde'     => 'Viitorul Mircea Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Bolovani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 21,
				'gazde'     => 'Sageata Branistea',
				'g_gazde'   => null,
				'oaspeti'   => 'Spic de Grau Ghimpati',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 21,
				'gazde'     => 'Unirea Nucet',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Slobozia Moara',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 22,
				'gazde'     => 'Viitorul Gheboaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Nucet',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 22,
				'gazde'     => 'Unirea Slobozia Moara',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Branistea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 22,
				'gazde'     => 'Spic de Grau Ghimpati',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Mircea Voda',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 22,
				'gazde'     => 'Luceafarul Bolovani',
				'g_gazde'   => null,
				'oaspeti'   => 'Libertatea Urziceanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 22,
				'gazde'     => 'F.C. Potlogi',
				'g_gazde'   => null,
				'oaspeti'   => 'Vanatorul 2015 Ratoaia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 22,
				'gazde'     => 'Flacara Ghinesti',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S. Fulgerul Lunguletu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 22,
				'gazde'     => 'Olimpia Marcesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Dobra',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 22,
				'gazde'     => 'Publirex Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Podu Rizii',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 22,
				'gazde'     => 'F.C Dentas  Tartasesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Finta',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 23,
				'gazde'     => 'F.C Dentas  Tartasesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gheboaia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 23,
				'gazde'     => 'Gaz Metan Finta',
				'g_gazde'   => null,
				'oaspeti'   => 'Publirex Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 23,
				'gazde'     => 'Vointa Podu Rizii',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Marcesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 23,
				'gazde'     => 'Viitorul Dobra',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Ghinesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 23,
				'gazde'     => 'C.S. Fulgerul Lunguletu',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C. Potlogi',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 23,
				'gazde'     => 'Vanatorul 2015 Ratoaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Bolovani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 23,
				'gazde'     => 'Libertatea Urziceanca',
				'g_gazde'   => null,
				'oaspeti'   => 'Spic de Grau Ghimpati',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 23,
				'gazde'     => 'Viitorul Mircea Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Slobozia Moara',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 23,
				'gazde'     => 'Sageata Branistea',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Nucet',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 24,
				'gazde'     => 'Viitorul Gheboaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Branistea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 24,
				'gazde'     => 'Unirea Nucet',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Mircea Voda',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 24,
				'gazde'     => 'Unirea Slobozia Moara',
				'g_gazde'   => null,
				'oaspeti'   => 'Libertatea Urziceanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 24,
				'gazde'     => 'Spic de Grau Ghimpati',
				'g_gazde'   => null,
				'oaspeti'   => 'Vanatorul 2015 Ratoaia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 24,
				'gazde'     => 'Luceafarul Bolovani',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S. Fulgerul Lunguletu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 24,
				'gazde'     => 'F.C. Potlogi',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Dobra',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 24,
				'gazde'     => 'Flacara Ghinesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Podu Rizii',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 24,
				'gazde'     => 'Olimpia Marcesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Finta',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 24,
				'gazde'     => 'Publirex Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C Dentas  Tartasesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 25,
				'gazde'     => 'Publirex Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gheboaia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 25,
				'gazde'     => 'F.C Dentas  Tartasesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Marcesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 25,
				'gazde'     => 'Gaz Metan Finta',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Ghinesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 25,
				'gazde'     => 'Vointa Podu Rizii',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C. Potlogi',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 25,
				'gazde'     => 'Viitorul Dobra',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Bolovani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 25,
				'gazde'     => 'C.S. Fulgerul Lunguletu',
				'g_gazde'   => null,
				'oaspeti'   => 'Spic de Grau Ghimpati',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 25,
				'gazde'     => 'Vanatorul 2015 Ratoaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Slobozia Moara',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 25,
				'gazde'     => 'Libertatea Urziceanca',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Nucet',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 25,
				'gazde'     => 'Viitorul Mircea Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Branistea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 26,
				'gazde'     => 'Viitorul Gheboaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Mircea Voda',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 26,
				'gazde'     => 'Sageata Branistea',
				'g_gazde'   => null,
				'oaspeti'   => 'Libertatea Urziceanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 26,
				'gazde'     => 'Unirea Nucet',
				'g_gazde'   => null,
				'oaspeti'   => 'Vanatorul 2015 Ratoaia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 26,
				'gazde'     => 'Unirea Slobozia Moara',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S. Fulgerul Lunguletu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 26,
				'gazde'     => 'Spic de Grau Ghimpati',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Dobra',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 26,
				'gazde'     => 'Luceafarul Bolovani',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Podu Rizii',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 26,
				'gazde'     => 'F.C. Potlogi',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Finta',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 26,
				'gazde'     => 'Flacara Ghinesti',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C Dentas  Tartasesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 26,
				'gazde'     => 'Olimpia Marcesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Publirex Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 27,
				'gazde'     => 'Olimpia Marcesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gheboaia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 27,
				'gazde'     => 'Publirex Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Ghinesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 27,
				'gazde'     => 'F.C Dentas  Tartasesti',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C. Potlogi',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 27,
				'gazde'     => 'Gaz Metan Finta',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Bolovani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 27,
				'gazde'     => 'Vointa Podu Rizii',
				'g_gazde'   => null,
				'oaspeti'   => 'Spic de Grau Ghimpati',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 27,
				'gazde'     => 'Viitorul Dobra',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Slobozia Moara',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 27,
				'gazde'     => 'C.S. Fulgerul Lunguletu',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Nucet',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 27,
				'gazde'     => 'Vanatorul 2015 Ratoaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Branistea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 27,
				'gazde'     => 'Libertatea Urziceanca',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Mircea Voda',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 28,
				'gazde'     => 'Viitorul Gheboaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Libertatea Urziceanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 28,
				'gazde'     => 'Viitorul Mircea Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'Vanatorul 2015 Ratoaia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 28,
				'gazde'     => 'Sageata Branistea',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S. Fulgerul Lunguletu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 28,
				'gazde'     => 'Unirea Nucet',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Dobra',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 28,
				'gazde'     => 'Unirea Slobozia Moara',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Podu Rizii',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 28,
				'gazde'     => 'Spic de Grau Ghimpati',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Finta',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 28,
				'gazde'     => 'Luceafarul Bolovani',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C Dentas  Tartasesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 28,
				'gazde'     => 'F.C. Potlogi',
				'g_gazde'   => null,
				'oaspeti'   => 'Publirex Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 28,
				'gazde'     => 'Flacara Ghinesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Marcesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 29,
				'gazde'     => 'Flacara Ghinesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gheboaia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 29,
				'gazde'     => 'Olimpia Marcesti',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C. Potlogi',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 29,
				'gazde'     => 'Publirex Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Bolovani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 29,
				'gazde'     => 'F.C Dentas  Tartasesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Spic de Grau Ghimpati',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 29,
				'gazde'     => 'Gaz Metan Finta',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Slobozia Moara',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 29,
				'gazde'     => 'Vointa Podu Rizii',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Nucet',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 29,
				'gazde'     => 'Viitorul Dobra',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Branistea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 29,
				'gazde'     => 'C.S. Fulgerul Lunguletu',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Mircea Voda',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 29,
				'gazde'     => 'Vanatorul 2015 Ratoaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Libertatea Urziceanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 30,
				'gazde'     => 'Viitorul Gheboaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Vanatorul 2015 Ratoaia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 30,
				'gazde'     => 'Libertatea Urziceanca',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S. Fulgerul Lunguletu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 30,
				'gazde'     => 'Viitorul Mircea Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Dobra',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 30,
				'gazde'     => 'Sageata Branistea',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Podu Rizii',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 30,
				'gazde'     => 'Unirea Nucet',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Finta',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 30,
				'gazde'     => 'Unirea Slobozia Moara',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C Dentas  Tartasesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 30,
				'gazde'     => 'Spic de Grau Ghimpati',
				'g_gazde'   => null,
				'oaspeti'   => 'Publirex Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 30,
				'gazde'     => 'Luceafarul Bolovani',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Marcesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 30,
				'gazde'     => 'F.C. Potlogi',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Ghinesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 31,
				'gazde'     => 'F.C. Potlogi',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gheboaia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 31,
				'gazde'     => 'Flacara Ghinesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Bolovani',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 31,
				'gazde'     => 'Olimpia Marcesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Spic de Grau Ghimpati',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 31,
				'gazde'     => 'Publirex Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Slobozia Moara',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 31,
				'gazde'     => 'F.C Dentas  Tartasesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Nucet',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 31,
				'gazde'     => 'Gaz Metan Finta',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Branistea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 31,
				'gazde'     => 'Vointa Podu Rizii',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Mircea Voda',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 31,
				'gazde'     => 'Viitorul Dobra',
				'g_gazde'   => null,
				'oaspeti'   => 'Libertatea Urziceanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 31,
				'gazde'     => 'C.S. Fulgerul Lunguletu',
				'g_gazde'   => null,
				'oaspeti'   => 'Vanatorul 2015 Ratoaia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 32,
				'gazde'     => 'Viitorul Gheboaia',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S. Fulgerul Lunguletu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 32,
				'gazde'     => 'Vanatorul 2015 Ratoaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Dobra',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 32,
				'gazde'     => 'Libertatea Urziceanca',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Podu Rizii',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 32,
				'gazde'     => 'Viitorul Mircea Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Finta',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 32,
				'gazde'     => 'Sageata Branistea',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C Dentas  Tartasesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 32,
				'gazde'     => 'Unirea Nucet',
				'g_gazde'   => null,
				'oaspeti'   => 'Publirex Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 32,
				'gazde'     => 'Unirea Slobozia Moara',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Marcesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 32,
				'gazde'     => 'Spic de Grau Ghimpati',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Ghinesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 32,
				'gazde'     => 'Luceafarul Bolovani',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C. Potlogi',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 33,
				'gazde'     => 'Luceafarul Bolovani',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gheboaia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 33,
				'gazde'     => 'F.C. Potlogi',
				'g_gazde'   => null,
				'oaspeti'   => 'Spic de Grau Ghimpati',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 33,
				'gazde'     => 'Flacara Ghinesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Slobozia Moara',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 33,
				'gazde'     => 'Olimpia Marcesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Unirea Nucet',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 33,
				'gazde'     => 'Publirex Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Branistea',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 33,
				'gazde'     => 'F.C Dentas  Tartasesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Mircea Voda',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 33,
				'gazde'     => 'Gaz Metan Finta',
				'g_gazde'   => null,
				'oaspeti'   => 'Libertatea Urziceanca',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 33,
				'gazde'     => 'Vointa Podu Rizii',
				'g_gazde'   => null,
				'oaspeti'   => 'Vanatorul 2015 Ratoaia',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 33,
				'gazde'     => 'Viitorul Dobra',
				'g_gazde'   => null,
				'oaspeti'   => 'C.S. Fulgerul Lunguletu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 34,
				'gazde'     => 'Viitorul Gheboaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Dobra',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 34,
				'gazde'     => 'C.S. Fulgerul Lunguletu',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Podu Rizii',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 34,
				'gazde'     => 'Vanatorul 2015 Ratoaia',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaz Metan Finta',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 34,
				'gazde'     => 'Libertatea Urziceanca',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C Dentas  Tartasesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 34,
				'gazde'     => 'Viitorul Mircea Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'Publirex Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 34,
				'gazde'     => 'Sageata Branistea',
				'g_gazde'   => null,
				'oaspeti'   => 'Olimpia Marcesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 34,
				'gazde'     => 'Unirea Nucet',
				'g_gazde'   => null,
				'oaspeti'   => 'Flacara Ghinesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 34,
				'gazde'     => 'Unirea Slobozia Moara',
				'g_gazde'   => null,
				'oaspeti'   => 'F.C. Potlogi',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 5,
				'serie'     => 'SUD',
				'etapa'     => 34,
				'gazde'     => 'Spic de Grau Ghimpati',
				'g_gazde'   => null,
				'oaspeti'   => 'Luceafarul Bolovani',
				'g_oaspeti' => null,
			]
		];

		Echipe::where('liga', 5)->where('serie', 'SUD')->delete();
		foreach ($echipe as $echipa) {
			$adauga = new Echipe;
			$adauga->echipa = trim($echipa['echipa']);
			$adauga->liga   = $echipa['liga'];
			$adauga->serie  = $echipa['serie'];
			$adauga->save();
		}

		Etape::where('liga', 5)->where('serie', 'SUD')->delete();
		foreach ($etape as $etapa) {
			$adauga = new Etape;
			$adauga->gazde     = trim($etapa['gazde']);
			$adauga->oaspeti   = trim($etapa['oaspeti']);
			$adauga->g_gazde   = $etapa['g_gazde'];
			$adauga->g_oaspeti = $etapa['g_oaspeti'];
			$adauga->liga      = $etapa['liga'];
			$adauga->serie     = $etapa['serie'];
			$adauga->etapa     = $etapa['etapa'];
			$adauga->data      = $etapa['data'] != NULL ? DateTime::createFromFormat('d-m-Y', ($etapa['data']))->format('Y-m-d') : NULL;
			$adauga->ora       = $etapa['ora'];
			$adauga->save();
		}
    }
}
