<?php

use Illuminate\Database\Seeder;
use App\Echipe;
use App\Etape;

class liga_6_sud extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$echipe = [
			[
				'echipa' => 'Vointa Cretu',
				'liga'   => 6,
				'serie'  => 'SUD',
			],[
				'echipa' => 'Neajlovul Puntea de Greci',
				'liga'   => 6,
				'serie'  => 'SUD',
			],[
				'echipa' => 'Vointa Crevedia 2010',
				'liga'   => 6,
				'serie'  => 'SUD',
			],[
				'echipa' => 'Sageata Catunu 1975',
				'liga'   => 6,
				'serie'  => 'SUD',
			],[
				'echipa' => 'Cojasca 2018',
				'liga'   => 6,
				'serie'  => 'SUD',
			],[
				'echipa' => 'Viitorul Gura Foii',
				'liga'   => 6,
				'serie'  => 'SUD',
			],[
				'echipa' => 'Steagu Rosu Colacu',
				'liga'   => 6,
				'serie'  => 'SUD',
			],[
				'echipa' => 'Gaita Bilciuresti',
				'liga'   => 6,
				'serie'  => 'SUD',
			],[
				'echipa' => 'Dacia Hulubesti',
				'liga'   => 6,
				'serie'  => 'SUD',
			],[
				'echipa' => 'Juniorul Ciocanesti',
				'liga'   => 6,
				'serie'  => 'SUD',
			],[
				'echipa' => 'Avantul Produlesti',
				'liga'   => 6,
				'serie'  => 'SUD',
			],[
				'echipa' => 'Viitorul Cuza Voda',
				'liga'   => 6,
				'serie'  => 'SUD',
			],[
				'echipa' => 'Universitatea Baleni',
				'liga'   => 6,
				'serie'  => 'SUD',
			],[
				'echipa' => 'STA',
				'liga'   => 6,
				'serie'  => 'SUD',
			]
		];

        $etape = [
			[
				'data'      => '02-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 1,
				'gazde'     => 'Steagu Rosu Colacu',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata Catunu',
				'g_oaspeti' => null,
			],[
				'data'      => '02-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 1,
				'gazde'     => 'Neajlovul Puntea de Greci',
				'g_gazde'   => 3,
				'oaspeti'   => 'Dacia Hulubesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '02-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 1,
				'gazde'     => 'Gaita Bilciuresti',
				'g_gazde'   => 1,
				'oaspeti'   => 'Vointa Crevedia 2010',
				'g_oaspeti' => 1,
			],[
				'data'      => '02-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 1,
				'gazde'     => 'Cojasca 2018',
				'g_gazde'   => 0,
				'oaspeti'   => 'Viitorul Gura Foii',
				'g_oaspeti' => 4,
			],[
				'data'      => '02-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 1,
				'gazde'     => 'Viitorul Cuza Voda',
				'g_gazde'   => 2,
				'oaspeti'   => 'Universitatea Baleni',
				'g_oaspeti' => 2,
			],[
				'data'      => '02-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 1,
				'gazde'     => 'Sageata  Catunu 1975',
				'g_gazde'   => 7,
				'oaspeti'   => 'Avantul Produlesti',
				'g_oaspeti' => 0,
			],[
				'data'      => '02-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 1,
				'gazde'     => 'Vointa Cretu',
				'g_gazde'   => 2,
				'oaspeti'   => 'Juniorul Ciocanesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '09-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 2,
				'gazde'     => 'Sageata Catunu',
				'g_gazde'   => null,
				'oaspeti'   => 'Juniorul Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => '09-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 2,
				'gazde'     => 'Avantul Produlesti',
				'g_gazde'   => 3,
				'oaspeti'   => 'Vointa Cretu',
				'g_oaspeti' => 7,
			],[
				'data'      => '09-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 2,
				'gazde'     => 'Universitatea Baleni',
				'g_gazde'   => 0,
				'oaspeti'   => 'Sageata  Catunu 1975',
				'g_oaspeti' => 3,
			],[
				'data'      => '09-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 2,
				'gazde'     => 'Viitorul Gura Foii',
				'g_gazde'   => 3,
				'oaspeti'   => 'Viitorul Cuza Voda',
				'g_oaspeti' => 0,
			],[
				'data'      => '09-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 2,
				'gazde'     => 'Vointa Crevedia 2010',
				'g_gazde'   => 0,
				'oaspeti'   => 'Cojasca 2018',
				'g_oaspeti' => 3,
			],[
				'data'      => '09-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 2,
				'gazde'     => 'Dacia Hulubesti',
				'g_gazde'   => 6,
				'oaspeti'   => 'Gaita Bilciuresti',
				'g_oaspeti' => 2,
			],[
				'data'      => '09-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 2,
				'gazde'     => 'Steagu Rosu Colacu',
				'g_gazde'   => 0,
				'oaspeti'   => 'Neajlovul Puntea de Greci',
				'g_oaspeti' => 1,
			],[
				'data'      => '16-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 3,
				'gazde'     => 'Neajlovul Puntea de Greci',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '16-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 3,
				'gazde'     => 'Gaita Bilciuresti',
				'g_gazde'   => 4,
				'oaspeti'   => 'Steagu Rosu Colacu',
				'g_oaspeti' => 2,
			],[
				'data'      => '16-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 3,
				'gazde'     => 'Cojasca 2018',
				'g_gazde'   => 7,
				'oaspeti'   => 'Dacia Hulubesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '16-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 3,
				'gazde'     => 'Viitorul Cuza Voda',
				'g_gazde'   => 0,
				'oaspeti'   => 'Vointa Crevedia 2010',
				'g_oaspeti' => 3,
			],[
				'data'      => '16-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 3,
				'gazde'     => 'Sageata  Catunu 1975',
				'g_gazde'   => 1,
				'oaspeti'   => 'Viitorul Gura Foii',
				'g_oaspeti' => 1,
			],[
				'data'      => '16-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 3,
				'gazde'     => 'Vointa Cretu',
				'g_gazde'   => 7,
				'oaspeti'   => 'Universitatea Baleni',
				'g_oaspeti' => 2,
			],[
				'data'      => '16-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 3,
				'gazde'     => 'Juniorul Ciocanesti',
				'g_gazde'   => 4,
				'oaspeti'   => 'Avantul Produlesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '23-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 4,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Avantul Produlesti',
				'g_oaspeti' => null,
			],[
				'data'      => '23-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 4,
				'gazde'     => 'Universitatea Baleni',
				'g_gazde'   => 4,
				'oaspeti'   => 'Juniorul Ciocanesti',
				'g_oaspeti' => 4,
			],[
				'data'      => '23-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 4,
				'gazde'     => 'Viitorul Gura Foii',
				'g_gazde'   => 0,
				'oaspeti'   => 'Vointa Cretu',
				'g_oaspeti' => 3,
			],[
				'data'      => '23-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 4,
				'gazde'     => 'Vointa Crevedia 2010',
				'g_gazde'   => 5,
				'oaspeti'   => 'Sageata  Catunu 1975',
				'g_oaspeti' => 1,
			],[
				'data'      => '23-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 4,
				'gazde'     => 'Dacia Hulubesti',
				'g_gazde'   => 0,
				'oaspeti'   => 'Viitorul Cuza Voda',
				'g_oaspeti' => 3,
			],[
				'data'      => '23-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 4,
				'gazde'     => 'Steagu Rosu Colacu',
				'g_gazde'   => 3,
				'oaspeti'   => 'Cojasca 2018',
				'g_oaspeti' => 4,
			],[
				'data'      => '23-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 4,
				'gazde'     => 'Neajlovul Puntea de Greci',
				'g_gazde'   => 7,
				'oaspeti'   => 'Gaita Bilciuresti',
				'g_oaspeti' => 1,
			],[
				'data'      => '30-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 5,
				'gazde'     => 'Gaita Bilciuresti',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '30-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 5,
				'gazde'     => 'Cojasca 2018',
				'g_gazde'   => 3,
				'oaspeti'   => 'Neajlovul Puntea de Greci',
				'g_oaspeti' => 0,
			],[
				'data'      => '30-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 5,
				'gazde'     => 'Viitorul Cuza Voda',
				'g_gazde'   => 5,
				'oaspeti'   => 'Steagu Rosu Colacu',
				'g_oaspeti' => 5,
			],[
				'data'      => '30-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 5,
				'gazde'     => 'Sageata  Catunu 1975',
				'g_gazde'   => 6,
				'oaspeti'   => 'Dacia Hulubesti',
				'g_oaspeti' => 5,
			],[
				'data'      => '30-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 5,
				'gazde'     => 'Vointa Cretu',
				'g_gazde'   => 1,
				'oaspeti'   => 'Vointa Crevedia 2010',
				'g_oaspeti' => 0,
			],[
				'data'      => '30-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 5,
				'gazde'     => 'Juniorul Ciocanesti',
				'g_gazde'   => 1,
				'oaspeti'   => 'Viitorul Gura Foii',
				'g_oaspeti' => 2,
			],[
				'data'      => '30-09-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 5,
				'gazde'     => 'Avantul Produlesti',
				'g_gazde'   => 2,
				'oaspeti'   => 'Universitatea Baleni',
				'g_oaspeti' => 2,
			],[
				'data'      => '07-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 6,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Universitatea Baleni',
				'g_oaspeti' => null,
			],[
				'data'      => '07-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 6,
				'gazde'     => 'Viitorul Gura Foii',
				'g_gazde'   => 7,
				'oaspeti'   => 'Avantul Produlesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '07-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 6,
				'gazde'     => 'Vointa Crevedia 2010',
				'g_gazde'   => 5,
				'oaspeti'   => 'Juniorul Ciocanesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '07-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 6,
				'gazde'     => 'Dacia Hulubesti',
				'g_gazde'   => 0,
				'oaspeti'   => 'Vointa Cretu',
				'g_oaspeti' => 4,
			],[
				'data'      => '07-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 6,
				'gazde'     => 'Steagu Rosu Colacu',
				'g_gazde'   => 2,
				'oaspeti'   => 'Sageata  Catunu 1975',
				'g_oaspeti' => 0,
			],[
				'data'      => '07-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 6,
				'gazde'     => 'Neajlovul Puntea de Greci',
				'g_gazde'   => 9,
				'oaspeti'   => 'Viitorul Cuza Voda',
				'g_oaspeti' => 0,
			],[
				'data'      => '07-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 6,
				'gazde'     => 'Gaita Bilciuresti',
				'g_gazde'   => 5,
				'oaspeti'   => 'Cojasca 2018',
				'g_oaspeti' => 3,
			],[
				'data'      => '14-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 7,
				'gazde'     => 'Cojasca 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '14-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 7,
				'gazde'     => 'Viitorul Cuza Voda',
				'g_gazde'   => 4,
				'oaspeti'   => 'Gaita Bilciuresti',
				'g_oaspeti' => 2,
			],[
				'data'      => '14-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 7,
				'gazde'     => 'Sageata  Catunu 1975',
				'g_gazde'   => 1,
				'oaspeti'   => 'Neajlovul Puntea de Greci',
				'g_oaspeti' => 3,
			],[
				'data'      => '14-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 7,
				'gazde'     => 'Vointa Cretu',
				'g_gazde'   => 3,
				'oaspeti'   => 'Steagu Rosu Colacu',
				'g_oaspeti' => 0,
			],[
				'data'      => '14-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 7,
				'gazde'     => 'Juniorul Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Dacia Hulubesti',
				'g_oaspeti' => null,
			],[
				'data'      => '14-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 7,
				'gazde'     => 'Avantul Produlesti',
				'g_gazde'   => 1,
				'oaspeti'   => 'Vointa Crevedia 2010',
				'g_oaspeti' => 5,
			],[
				'data'      => '14-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 7,
				'gazde'     => 'Universitatea Baleni',
				'g_gazde'   => 0,
				'oaspeti'   => 'Viitorul Gura Foii',
				'g_oaspeti' => 3,
			],[
				'data'      => '21-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 8,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gura Foii',
				'g_oaspeti' => null,
			],[
				'data'      => '21-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 8,
				'gazde'     => 'Vointa Crevedia 2010',
				'g_gazde'   => 3,
				'oaspeti'   => 'Universitatea Baleni',
				'g_oaspeti' => 1,
			],[
				'data'      => '21-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 8,
				'gazde'     => 'Dacia Hulubesti',
				'g_gazde'   => 4,
				'oaspeti'   => 'Avantul Produlesti',
				'g_oaspeti' => 1,
			],[
				'data'      => '21-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 8,
				'gazde'     => 'Steagu Rosu Colacu',
				'g_gazde'   => 6,
				'oaspeti'   => 'Juniorul Ciocanesti',
				'g_oaspeti' => 5,
			],[
				'data'      => '21-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 8,
				'gazde'     => 'Neajlovul Puntea de Greci',
				'g_gazde'   => 2,
				'oaspeti'   => 'Vointa Cretu',
				'g_oaspeti' => 1,
			],[
				'data'      => '21-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 8,
				'gazde'     => 'Gaita Bilciuresti',
				'g_gazde'   => 0,
				'oaspeti'   => 'Sageata  Catunu 1975',
				'g_oaspeti' => 3,
			],[
				'data'      => '21-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 8,
				'gazde'     => 'Cojasca 2018',
				'g_gazde'   => 2,
				'oaspeti'   => 'Viitorul Cuza Voda',
				'g_oaspeti' => 3,
			],[
				'data'      => '28-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 9,
				'gazde'     => 'Viitorul Cuza Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 9,
				'gazde'     => 'Sageata  Catunu 1975',
				'g_gazde'   => null,
				'oaspeti'   => 'Cojasca 2018',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 9,
				'gazde'     => 'Vointa Cretu',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaita Bilciuresti',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 9,
				'gazde'     => 'Juniorul Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Neajlovul Puntea de Greci',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 9,
				'gazde'     => 'Avantul Produlesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Steagu Rosu Colacu',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 9,
				'gazde'     => 'Universitatea Baleni',
				'g_gazde'   => null,
				'oaspeti'   => 'Dacia Hulubesti',
				'g_oaspeti' => null,
			],[
				'data'      => '28-10-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 9,
				'gazde'     => 'Viitorul Gura Foii',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Crevedia 2010',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 10,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Crevedia 2010',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 10,
				'gazde'     => 'Dacia Hulubesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gura Foii',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 10,
				'gazde'     => 'Steagu Rosu Colacu',
				'g_gazde'   => null,
				'oaspeti'   => 'Universitatea Baleni',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 10,
				'gazde'     => 'Neajlovul Puntea de Greci',
				'g_gazde'   => null,
				'oaspeti'   => 'Avantul Produlesti',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 10,
				'gazde'     => 'Gaita Bilciuresti',
				'g_gazde'   => null,
				'oaspeti'   => 'Juniorul Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 10,
				'gazde'     => 'Cojasca 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Cretu',
				'g_oaspeti' => null,
			],[
				'data'      => '04-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 10,
				'gazde'     => 'Viitorul Cuza Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata  Catunu 1975',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 11,
				'gazde'     => 'Sageata  Catunu 1975',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 11,
				'gazde'     => 'Vointa Cretu',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Cuza Voda',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 11,
				'gazde'     => 'Juniorul Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Cojasca 2018',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 11,
				'gazde'     => 'Avantul Produlesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaita Bilciuresti',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 11,
				'gazde'     => 'Universitatea Baleni',
				'g_gazde'   => null,
				'oaspeti'   => 'Neajlovul Puntea de Greci',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 11,
				'gazde'     => 'Viitorul Gura Foii',
				'g_gazde'   => null,
				'oaspeti'   => 'Steagu Rosu Colacu',
				'g_oaspeti' => null,
			],[
				'data'      => '11-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 11,
				'gazde'     => 'Vointa Crevedia 2010',
				'g_gazde'   => null,
				'oaspeti'   => 'Dacia Hulubesti',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 12,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Dacia Hulubesti',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 12,
				'gazde'     => 'Steagu Rosu Colacu',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Crevedia 2010',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 12,
				'gazde'     => 'Neajlovul Puntea de Greci',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gura Foii',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 12,
				'gazde'     => 'Gaita Bilciuresti',
				'g_gazde'   => null,
				'oaspeti'   => 'Universitatea Baleni',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 12,
				'gazde'     => 'Cojasca 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'Avantul Produlesti',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 12,
				'gazde'     => 'Viitorul Cuza Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'Juniorul Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => '18-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 12,
				'gazde'     => 'Sageata  Catunu 1975',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Cretu',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 13,
				'gazde'     => 'Vointa Cretu',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 13,
				'gazde'     => 'Juniorul Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata  Catunu 1975',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 13,
				'gazde'     => 'Avantul Produlesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Cuza Voda',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 13,
				'gazde'     => 'Universitatea Baleni',
				'g_gazde'   => null,
				'oaspeti'   => 'Cojasca 2018',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 13,
				'gazde'     => 'Viitorul Gura Foii',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaita Bilciuresti',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 13,
				'gazde'     => 'Vointa Crevedia 2010',
				'g_gazde'   => null,
				'oaspeti'   => 'Neajlovul Puntea de Greci',
				'g_oaspeti' => null,
			],[
				'data'      => '25-11-2018',
				'ora'       => '14:30',
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 13,
				'gazde'     => 'Dacia Hulubesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Steagu Rosu Colacu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 14,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Steagu Rosu Colacu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 14,
				'gazde'     => 'Dacia Hulubesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Neajlovul Puntea de Greci',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 14,
				'gazde'     => 'Vointa Crevedia 2010',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaita Bilciuresti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 14,
				'gazde'     => 'Viitorul Gura Foii',
				'g_gazde'   => null,
				'oaspeti'   => 'Cojasca 2018',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 14,
				'gazde'     => 'Universitatea Baleni',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Cuza Voda',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 14,
				'gazde'     => 'Avantul Produlesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata  Catunu 1975',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 14,
				'gazde'     => 'Juniorul Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Cretu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 15,
				'gazde'     => 'Juniorul Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 15,
				'gazde'     => 'Vointa Cretu',
				'g_gazde'   => null,
				'oaspeti'   => 'Avantul Produlesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 15,
				'gazde'     => 'Sageata  Catunu 1975',
				'g_gazde'   => null,
				'oaspeti'   => 'Universitatea Baleni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 15,
				'gazde'     => 'Viitorul Cuza Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gura Foii',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 15,
				'gazde'     => 'Cojasca 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Crevedia 2010',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 15,
				'gazde'     => 'Gaita Bilciuresti',
				'g_gazde'   => null,
				'oaspeti'   => 'Dacia Hulubesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 15,
				'gazde'     => 'Neajlovul Puntea de Greci',
				'g_gazde'   => null,
				'oaspeti'   => 'Steagu Rosu Colacu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 16,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Neajlovul Puntea de Greci',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 16,
				'gazde'     => 'Steagu Rosu Colacu',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaita Bilciuresti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 16,
				'gazde'     => 'Dacia Hulubesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Cojasca 2018',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 16,
				'gazde'     => 'Vointa Crevedia 2010',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Cuza Voda',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 16,
				'gazde'     => 'Viitorul Gura Foii',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata  Catunu 1975',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 16,
				'gazde'     => 'Universitatea Baleni',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Cretu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 16,
				'gazde'     => 'Avantul Produlesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Juniorul Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 17,
				'gazde'     => 'Avantul Produlesti',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 17,
				'gazde'     => 'Juniorul Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Universitatea Baleni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 17,
				'gazde'     => 'Vointa Cretu',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gura Foii',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 17,
				'gazde'     => 'Sageata  Catunu 1975',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Crevedia 2010',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 17,
				'gazde'     => 'Viitorul Cuza Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'Dacia Hulubesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 17,
				'gazde'     => 'Cojasca 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'Steagu Rosu Colacu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 17,
				'gazde'     => 'Gaita Bilciuresti',
				'g_gazde'   => null,
				'oaspeti'   => 'Neajlovul Puntea de Greci',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 18,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaita Bilciuresti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 18,
				'gazde'     => 'Neajlovul Puntea de Greci',
				'g_gazde'   => null,
				'oaspeti'   => 'Cojasca 2018',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 18,
				'gazde'     => 'Steagu Rosu Colacu',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Cuza Voda',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 18,
				'gazde'     => 'Dacia Hulubesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata  Catunu 1975',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 18,
				'gazde'     => 'Vointa Crevedia 2010',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Cretu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 18,
				'gazde'     => 'Viitorul Gura Foii',
				'g_gazde'   => null,
				'oaspeti'   => 'Juniorul Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 18,
				'gazde'     => 'Universitatea Baleni',
				'g_gazde'   => null,
				'oaspeti'   => 'Avantul Produlesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 19,
				'gazde'     => 'Universitatea Baleni',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 19,
				'gazde'     => 'Avantul Produlesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gura Foii',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 19,
				'gazde'     => 'Juniorul Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Crevedia 2010',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 19,
				'gazde'     => 'Vointa Cretu',
				'g_gazde'   => null,
				'oaspeti'   => 'Dacia Hulubesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 19,
				'gazde'     => 'Sageata  Catunu 1975',
				'g_gazde'   => null,
				'oaspeti'   => 'Steagu Rosu Colacu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 19,
				'gazde'     => 'Viitorul Cuza Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'Neajlovul Puntea de Greci',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 19,
				'gazde'     => 'Cojasca 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaita Bilciuresti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 20,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Cojasca 2018',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 20,
				'gazde'     => 'Gaita Bilciuresti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Cuza Voda',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 20,
				'gazde'     => 'Neajlovul Puntea de Greci',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata  Catunu 1975',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 20,
				'gazde'     => 'Steagu Rosu Colacu',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Cretu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 20,
				'gazde'     => 'Dacia Hulubesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Juniorul Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 20,
				'gazde'     => 'Vointa Crevedia 2010',
				'g_gazde'   => null,
				'oaspeti'   => 'Avantul Produlesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 20,
				'gazde'     => 'Viitorul Gura Foii',
				'g_gazde'   => null,
				'oaspeti'   => 'Universitatea Baleni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 21,
				'gazde'     => 'Viitorul Gura Foii',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 21,
				'gazde'     => 'Universitatea Baleni',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Crevedia 2010',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 21,
				'gazde'     => 'Avantul Produlesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Dacia Hulubesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 21,
				'gazde'     => 'Juniorul Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Steagu Rosu Colacu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 21,
				'gazde'     => 'Vointa Cretu',
				'g_gazde'   => null,
				'oaspeti'   => 'Neajlovul Puntea de Greci',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 21,
				'gazde'     => 'Sageata  Catunu 1975',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaita Bilciuresti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 21,
				'gazde'     => 'Viitorul Cuza Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'Cojasca 2018',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 22,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Cuza Voda',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 22,
				'gazde'     => 'Cojasca 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata  Catunu 1975',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 22,
				'gazde'     => 'Gaita Bilciuresti',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Cretu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 22,
				'gazde'     => 'Neajlovul Puntea de Greci',
				'g_gazde'   => null,
				'oaspeti'   => 'Juniorul Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 22,
				'gazde'     => 'Steagu Rosu Colacu',
				'g_gazde'   => null,
				'oaspeti'   => 'Avantul Produlesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 22,
				'gazde'     => 'Dacia Hulubesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Universitatea Baleni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 22,
				'gazde'     => 'Vointa Crevedia 2010',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gura Foii',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 23,
				'gazde'     => 'Vointa Crevedia 2010',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 23,
				'gazde'     => 'Viitorul Gura Foii',
				'g_gazde'   => null,
				'oaspeti'   => 'Dacia Hulubesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 23,
				'gazde'     => 'Universitatea Baleni',
				'g_gazde'   => null,
				'oaspeti'   => 'Steagu Rosu Colacu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 23,
				'gazde'     => 'Avantul Produlesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Neajlovul Puntea de Greci',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 23,
				'gazde'     => 'Juniorul Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaita Bilciuresti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 23,
				'gazde'     => 'Vointa Cretu',
				'g_gazde'   => null,
				'oaspeti'   => 'Cojasca 2018',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 23,
				'gazde'     => 'Sageata  Catunu 1975',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Cuza Voda',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 24,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata  Catunu 1975',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 24,
				'gazde'     => 'Viitorul Cuza Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Cretu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 24,
				'gazde'     => 'Cojasca 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'Juniorul Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 24,
				'gazde'     => 'Gaita Bilciuresti',
				'g_gazde'   => null,
				'oaspeti'   => 'Avantul Produlesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 24,
				'gazde'     => 'Neajlovul Puntea de Greci',
				'g_gazde'   => null,
				'oaspeti'   => 'Universitatea Baleni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 24,
				'gazde'     => 'Steagu Rosu Colacu',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gura Foii',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 24,
				'gazde'     => 'Dacia Hulubesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Crevedia 2010',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 25,
				'gazde'     => 'Dacia Hulubesti',
				'g_gazde'   => null,
				'oaspeti'   => 'STA',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 25,
				'gazde'     => 'Vointa Crevedia 2010',
				'g_gazde'   => null,
				'oaspeti'   => 'Steagu Rosu Colacu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 25,
				'gazde'     => 'Viitorul Gura Foii',
				'g_gazde'   => null,
				'oaspeti'   => 'Neajlovul Puntea de Greci',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 25,
				'gazde'     => 'Universitatea Baleni',
				'g_gazde'   => null,
				'oaspeti'   => 'Gaita Bilciuresti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 25,
				'gazde'     => 'Avantul Produlesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Cojasca 2018',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 25,
				'gazde'     => 'Juniorul Ciocanesti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Cuza Voda',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 25,
				'gazde'     => 'Vointa Cretu',
				'g_gazde'   => null,
				'oaspeti'   => 'Sageata  Catunu 1975',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 26,
				'gazde'     => 'STA',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Cretu',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 26,
				'gazde'     => 'Sageata  Catunu 1975',
				'g_gazde'   => null,
				'oaspeti'   => 'Juniorul Ciocanesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 26,
				'gazde'     => 'Viitorul Cuza Voda',
				'g_gazde'   => null,
				'oaspeti'   => 'Avantul Produlesti',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 26,
				'gazde'     => 'Cojasca 2018',
				'g_gazde'   => null,
				'oaspeti'   => 'Universitatea Baleni',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 26,
				'gazde'     => 'Gaita Bilciuresti',
				'g_gazde'   => null,
				'oaspeti'   => 'Viitorul Gura Foii',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 26,
				'gazde'     => 'Neajlovul Puntea de Greci',
				'g_gazde'   => null,
				'oaspeti'   => 'Vointa Crevedia 2010',
				'g_oaspeti' => null,
			],[
				'data'      => null,
				'ora'       => null,
				'liga'      => 6,
				'serie'     => 'SUD',
				'etapa'     => 26,
				'gazde'     => 'Steagu Rosu Colacu',
				'g_gazde'   => null,
				'oaspeti'   => 'Dacia Hulubesti',
				'g_oaspeti' => null,
			]
		];

		Echipe::where('liga', 6)->where('serie', 'SUD')->delete();
		foreach ($echipe as $echipa) {
			$adauga = new Echipe;
			$adauga->echipa = trim($echipa['echipa']);
			$adauga->liga   = $echipa['liga'];
			$adauga->serie  = $echipa['serie'];
			$adauga->save();
		}

		Etape::where('liga', 6)->where('serie', 'SUD')->delete();
		foreach ($etape as $etapa) {
			$adauga = new Etape;
			$adauga->gazde     = trim($etapa['gazde']);
			$adauga->oaspeti   = trim($etapa['oaspeti']);
			$adauga->g_gazde   = $etapa['g_gazde'];
			$adauga->g_oaspeti = $etapa['g_oaspeti'];
			$adauga->liga      = $etapa['liga'];
			$adauga->serie     = $etapa['serie'];
			$adauga->etapa     = $etapa['etapa'];
			$adauga->data      = $etapa['data'] != NULL ? DateTime::createFromFormat('d-m-Y', ($etapa['data']))->format('Y-m-d') : NULL;
			$adauga->ora       = $etapa['ora'];
			$adauga->save();
		}
    }
}
