<?php

use Illuminate\Database\Seeder;
use App\Echipe;
use App\Etape;
use App\ToateEchipele;

class liga_3_serie_2_2019_2020 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $echipe = [  
		   [
		      'echipa' => 'AFC Unirea 04 Slobozia'
		   ],[
		      'echipa' => 'CS Afumaţi'
		   ],[
		      'echipa' => 'ACS Mostiştea Ulmu'
		   ],[
		      'echipa' => 'ACS Înainte Modelu'
		   ],[
		      'echipa' => 'AFC Metalul Buzău'
		   ],[
		      'echipa' => 'CS Tunari'
		   ],[
		      'echipa' => 'CS Viitorul Ianca'
		   ],[
		      'echipa' => 'SC Popeşti-Leordeni'
		   ],[
		      'echipa' => 'CS Poseidon Limanu-2 Mai'
		   ],[
		      'echipa' => 'CS Medgidia'
		   ],[
		      'echipa' => 'FCSB 2'
		   ],[
		      'echipa' => 'CS Făurei'
		   ],[
		      'echipa' => 'ACS Dacia Unirea Brăila'
		   ],[
		      'echipa' => 'AS FC Agricola Borcea'
		   ],[
		      'echipa' => 'CSA Axiopolis Sport Cernavodă'
		   ],[
		      'echipa' => 'ACS Recolta Gheorghe Doja'
		   ]
		];

		$etape =
		[ 
		   [ 
		      "data" => "2019-08-23",
		      "ora" => "18:00",
		      "gazde" => "FCSB 2",
		      "oaspeti" => "AS FC Agricola Borcea",
		      "g_gazde" => 2,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-23",
		      "ora" => "18:00",
		      "gazde" => "ACS Înainte Modelu",
		      "oaspeti" => "CSA Axiopolis Sport Cernavodă",
		      "g_gazde" => 3,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "CS Viitorul Ianca",
		      "oaspeti" => "CS Tunari",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "AFC Metalul Buzău",
		      "oaspeti" => "ACS Dacia Unirea Brăila",
		      "g_gazde" => 5,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "ACS Recolta Gheorghe Doja",
		      "oaspeti" => "CS Medgidia",
		      "g_gazde" => 0,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "ACS Mostiştea Ulmu",
		      "oaspeti" => "CS Afumaţi",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "CS Poseidon Limanu-2 Mai",
		      "oaspeti" => "AFC Unirea 04 Slobozia",
		      "g_gazde" => 1,
		      "g_oaspeti" => 4,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "SC Popeşti-Leordeni",
		      "oaspeti" => "CS Făurei",
		      "g_gazde" => 3,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [ 
		      "data" => "2019-08-30",
		      "ora" => "18:00",
		      "gazde" => "ACS Dacia Unirea Brăila",
		      "oaspeti" => "ACS Recolta Gheorghe Doja",
		      "g_gazde" => 3,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "CS Tunari",
		      "oaspeti" => "CS Făurei",
		      "g_gazde" => 3,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "CSA Axiopolis Sport Cernavodă",
		      "oaspeti" => "SC Popeşti-Leordeni",
		      "g_gazde" => 1,
		      "g_oaspeti" => 4,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "AFC Unirea 04 Slobozia",
		      "oaspeti" => "ACS Înainte Modelu",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "CS Afumaţi",
		      "oaspeti" => "CS Poseidon Limanu-2 Mai",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "AS FC Agricola Borcea",
		      "oaspeti" => "ACS Mostiştea Ulmu",
		      "g_gazde" => 2,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "CS Medgidia",
		      "oaspeti" => "FCSB 2",
		      "g_gazde" => 0,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "CS Viitorul Ianca",
		      "oaspeti" => "AFC Metalul Buzău",
		      "g_gazde" => 1,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [ 
		      "data" => "2019-09-06",
		      "ora" => "17:00",
		      "gazde" => "FCSB 2",
		      "oaspeti" => "ACS Dacia Unirea Brăila",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-06",
		      "ora" => "17:00",
		      "gazde" => "ACS Înainte Modelu",
		      "oaspeti" => "CS Afumaţi",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "AFC Metalul Buzău",
		      "oaspeti" => "CS Tunari",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "ACS Recolta Gheorghe Doja",
		      "oaspeti" => "CS Viitorul Ianca",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "ACS Mostiştea Ulmu",
		      "oaspeti" => "CS Medgidia",
		      "g_gazde" => 4,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "SC Popeşti-Leordeni",
		      "oaspeti" => "AFC Unirea 04 Slobozia",
		      "g_gazde" => 0,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "CS Făurei",
		      "oaspeti" => "CSA Axiopolis Sport Cernavodă",
		      "g_gazde" => 3,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-25",
		      "ora" => "17:00",
		      "gazde" => "CS Poseidon Limanu-2 Mai",
		      "oaspeti" => "AS FC Agricola Borcea",
		      "g_gazde" => 4,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [ 
		      "data" => "2019-09-13",
		      "ora" => "17:00",
		      "gazde" => "ACS Dacia Unirea Brăila",
		      "oaspeti" => "ACS Mostiştea Ulmu",
		      "g_gazde" => 0,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "CS Tunari",
		      "oaspeti" => "CSA Axiopolis Sport Cernavodă",
		      "g_gazde" => 5,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "AFC Unirea 04 Slobozia",
		      "oaspeti" => "CS Făurei",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "CS Afumaţi",
		      "oaspeti" => "SC Popeşti-Leordeni",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "AS FC Agricola Borcea",
		      "oaspeti" => "ACS Înainte Modelu",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "CS Medgidia",
		      "oaspeti" => "CS Poseidon Limanu-2 Mai",
		      "g_gazde" => 3,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "CS Viitorul Ianca",
		      "oaspeti" => "FCSB 2",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "AFC Metalul Buzău",
		      "oaspeti" => "ACS Recolta Gheorghe Doja",
		      "g_gazde" => 3,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [ 
		      "data" => "2019-09-20",
		      "ora" => "17:00",
		      "gazde" => "FCSB 2",
		      "oaspeti" => "AFC Metalul Buzău",
		      "g_gazde" => 0,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-20",
		      "ora" => "17:00",
		      "gazde" => "ACS Înainte Modelu",
		      "oaspeti" => "CS Medgidia",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "ACS Recolta Gheorghe Doja",
		      "oaspeti" => "CS Tunari",
		      "g_gazde" => 2,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "ACS Mostiştea Ulmu",
		      "oaspeti" => "CS Viitorul Ianca",
		      "g_gazde" => 3,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "CS Poseidon Limanu-2 Mai",
		      "oaspeti" => "ACS Dacia Unirea Brăila",
		      "g_gazde" => 4,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "SC Popeşti-Leordeni",
		      "oaspeti" => "AS FC Agricola Borcea",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "CS Făurei",
		      "oaspeti" => "CS Afumaţi",
		      "g_gazde" => 1,
		      "g_oaspeti" => 4,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "CSA Axiopolis Sport Cernavodă",
		      "oaspeti" => "AFC Unirea 04 Slobozia",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [ 
		      "data" => "2019-09-27",
		      "ora" => "17:00",
		      "gazde" => "ACS Dacia Unirea Brăila",
		      "oaspeti" => "ACS Înainte Modelu",
		      "g_gazde" => 2,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-28",
		      "ora" => "17:00",
		      "gazde" => "CS Tunari",
		      "oaspeti" => "AFC Unirea 04 Slobozia",
		      "g_gazde" => 3,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-28",
		      "ora" => "17:00",
		      "gazde" => "CS Afumaţi",
		      "oaspeti" => "CSA Axiopolis Sport Cernavodă",
		      "g_gazde" => 8,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-28",
		      "ora" => "17:00",
		      "gazde" => "AS FC Agricola Borcea",
		      "oaspeti" => "CS Făurei",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-28",
		      "ora" => "17:00",
		      "gazde" => "CS Medgidia",
		      "oaspeti" => "SC Popeşti-Leordeni",
		      "g_gazde" => 0,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-28",
		      "ora" => "17:00",
		      "gazde" => "CS Viitorul Ianca",
		      "oaspeti" => "CS Poseidon Limanu-2 Mai",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-28",
		      "ora" => "17:00",
		      "gazde" => "AFC Metalul Buzău",
		      "oaspeti" => "ACS Mostiştea Ulmu",
		      "g_gazde" => 0,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-09-28",
		      "ora" => "17:00",
		      "gazde" => "ACS Recolta Gheorghe Doja",
		      "oaspeti" => "FCSB 2",
		      "g_gazde" => 1,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [ 
		      "data" => "2019-10-04",
		      "ora" => "15:00",
		      "gazde" => "FCSB 2",
		      "oaspeti" => "CS Tunari",
		      "g_gazde" => 2,
		      "g_oaspeti" => 4,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-04",
		      "ora" => "15:00",
		      "gazde" => "ACS Înainte Modelu",
		      "oaspeti" => "CS Viitorul Ianca",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "ACS Mostiştea Ulmu",
		      "oaspeti" => "ACS Recolta Gheorghe Doja",
		      "g_gazde" => 3,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "CS Poseidon Limanu-2 Mai",
		      "oaspeti" => "AFC Metalul Buzău",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "SC Popeşti-Leordeni",
		      "oaspeti" => "ACS Dacia Unirea Brăila",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "CS Făurei",
		      "oaspeti" => "CS Medgidia",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "CSA Axiopolis Sport Cernavodă",
		      "oaspeti" => "AS FC Agricola Borcea",
		      "g_gazde" => 5,
		      "g_oaspeti" => 4,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "AFC Unirea 04 Slobozia",
		      "oaspeti" => "CS Afumaţi",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [ 
		      "data" => "2019-10-11",
		      "ora" => "15:00",
		      "gazde" => "ACS Dacia Unirea Brăila",
		      "oaspeti" => "CS Făurei",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-11",
		      "ora" => "15:00",
		      "gazde" => "AFC Metalul Buzău",
		      "oaspeti" => "ACS Înainte Modelu",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-11",
		      "ora" => "15:00",
		      "gazde" => "FCSB 2",
		      "oaspeti" => "ACS Mostiştea Ulmu",
		      "g_gazde" => 1,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-12",
		      "ora" => "15:00",
		      "gazde" => "CS Tunari",
		      "oaspeti" => "CS Afumaţi",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-12",
		      "ora" => "15:00",
		      "gazde" => "AS FC Agricola Borcea",
		      "oaspeti" => "AFC Unirea 04 Slobozia",
		      "g_gazde" => 0,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-12",
		      "ora" => "15:00",
		      "gazde" => "CS Medgidia",
		      "oaspeti" => "CSA Axiopolis Sport Cernavodă",
		      "g_gazde" => 4,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-12",
		      "ora" => "15:00",
		      "gazde" => "CS Viitorul Ianca",
		      "oaspeti" => "SC Popeşti-Leordeni",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-12",
		      "ora" => "15:00",
		      "gazde" => "ACS Recolta Gheorghe Doja",
		      "oaspeti" => "CS Poseidon Limanu-2 Mai",
		      "g_gazde" => 1,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [ 
		      "data" => "2019-10-18",
		      "ora" => "15:00",
		      "gazde" => "ACS Înainte Modelu",
		      "oaspeti" => "ACS Recolta Gheorghe Doja",
		      "g_gazde" => 3,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "ACS Mostiştea Ulmu",
		      "oaspeti" => "CS Tunari",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "CS Poseidon Limanu-2 Mai",
		      "oaspeti" => "FCSB 2",
		      "g_gazde" => 3,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "SC Popeşti-Leordeni",
		      "oaspeti" => "AFC Metalul Buzău",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "CS Făurei",
		      "oaspeti" => "CS Viitorul Ianca",
		      "g_gazde" => 3,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "CSA Axiopolis Sport Cernavodă",
		      "oaspeti" => "ACS Dacia Unirea Brăila",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "AFC Unirea 04 Slobozia",
		      "oaspeti" => "CS Medgidia",
		      "g_gazde" => 4,
		      "g_oaspeti" => 4,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "CS Afumaţi",
		      "oaspeti" => "AS FC Agricola Borcea",
		      "g_gazde" => 8,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [ 
		      "data" => "2019-10-25",
		      "ora" => "15:00",
		      "gazde" => "ACS Dacia Unirea Brăila",
		      "oaspeti" => "AFC Unirea 04 Slobozia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-25",
		      "ora" => "15:00",
		      "gazde" => "FCSB 2",
		      "oaspeti" => "ACS Înainte Modelu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "CS Tunari",
		      "oaspeti" => "AS FC Agricola Borcea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "CS Medgidia",
		      "oaspeti" => "CS Afumaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "CS Viitorul Ianca",
		      "oaspeti" => "CSA Axiopolis Sport Cernavodă",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "AFC Metalul Buzău",
		      "oaspeti" => "CS Făurei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "ACS Recolta Gheorghe Doja",
		      "oaspeti" => "SC Popeşti-Leordeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "ACS Mostiştea Ulmu",
		      "oaspeti" => "CS Poseidon Limanu-2 Mai",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [ 
		      "data" => "2019-11-01",
		      "ora" => "14:00",
		      "gazde" => "ACS Înainte Modelu",
		      "oaspeti" => "ACS Mostiştea Ulmu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "CS Poseidon Limanu-2 Mai",
		      "oaspeti" => "CS Tunari",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "SC Popeşti-Leordeni",
		      "oaspeti" => "FCSB 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "CS Făurei",
		      "oaspeti" => "ACS Recolta Gheorghe Doja",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "AFC Unirea 04 Slobozia",
		      "oaspeti" => "CS Viitorul Ianca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "CS Afumaţi",
		      "oaspeti" => "ACS Dacia Unirea Brăila",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "AS FC Agricola Borcea",
		      "oaspeti" => "CS Medgidia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-03",
		      "ora" => "14:00",
		      "gazde" => "CSA Axiopolis Sport Cernavodă",
		      "oaspeti" => "AFC Metalul Buzău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "CS Tunari",
		      "oaspeti" => "CS Medgidia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "ACS Dacia Unirea Brăila",
		      "oaspeti" => "AS FC Agricola Borcea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "CS Viitorul Ianca",
		      "oaspeti" => "CS Afumaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "AFC Metalul Buzău",
		      "oaspeti" => "AFC Unirea 04 Slobozia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "ACS Recolta Gheorghe Doja",
		      "oaspeti" => "CSA Axiopolis Sport Cernavodă",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "FCSB 2",
		      "oaspeti" => "CS Făurei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "ACS Mostiştea Ulmu",
		      "oaspeti" => "SC Popeşti-Leordeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "CS Poseidon Limanu-2 Mai",
		      "oaspeti" => "ACS Înainte Modelu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "ACS Înainte Modelu",
		      "oaspeti" => "CS Tunari",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "SC Popeşti-Leordeni",
		      "oaspeti" => "CS Poseidon Limanu-2 Mai",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "CS Făurei",
		      "oaspeti" => "ACS Mostiştea Ulmu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "CSA Axiopolis Sport Cernavodă",
		      "oaspeti" => "FCSB 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "AFC Unirea 04 Slobozia",
		      "oaspeti" => "ACS Recolta Gheorghe Doja",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "CS Afumaţi",
		      "oaspeti" => "AFC Metalul Buzău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "AS FC Agricola Borcea",
		      "oaspeti" => "CS Viitorul Ianca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "CS Medgidia",
		      "oaspeti" => "ACS Dacia Unirea Brăila",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "CS Tunari",
		      "oaspeti" => "ACS Dacia Unirea Brăila",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "CS Viitorul Ianca",
		      "oaspeti" => "CS Medgidia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "AFC Metalul Buzău",
		      "oaspeti" => "AS FC Agricola Borcea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "ACS Recolta Gheorghe Doja",
		      "oaspeti" => "CS Afumaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "FCSB 2",
		      "oaspeti" => "AFC Unirea 04 Slobozia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "ACS Mostiştea Ulmu",
		      "oaspeti" => "CSA Axiopolis Sport Cernavodă",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "CS Poseidon Limanu-2 Mai",
		      "oaspeti" => "CS Făurei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "ACS Înainte Modelu",
		      "oaspeti" => "SC Popeşti-Leordeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "SC Popeşti-Leordeni",
		      "oaspeti" => "CS Tunari",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "CS Făurei",
		      "oaspeti" => "ACS Înainte Modelu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "CSA Axiopolis Sport Cernavodă",
		      "oaspeti" => "CS Poseidon Limanu-2 Mai",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "AFC Unirea 04 Slobozia",
		      "oaspeti" => "ACS Mostiştea Ulmu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "CS Afumaţi",
		      "oaspeti" => "FCSB 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "AS FC Agricola Borcea",
		      "oaspeti" => "ACS Recolta Gheorghe Doja",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "CS Medgidia",
		      "oaspeti" => "AFC Metalul Buzău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "ACS Dacia Unirea Brăila",
		      "oaspeti" => "CS Viitorul Ianca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "CS Tunari",
		      "oaspeti" => "CS Viitorul Ianca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "ACS Dacia Unirea Brăila",
		      "oaspeti" => "AFC Metalul Buzău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "CS Medgidia",
		      "oaspeti" => "ACS Recolta Gheorghe Doja",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "AS FC Agricola Borcea",
		      "oaspeti" => "FCSB 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "CS Afumaţi",
		      "oaspeti" => "ACS Mostiştea Ulmu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "AFC Unirea 04 Slobozia",
		      "oaspeti" => "CS Poseidon Limanu-2 Mai",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "CSA Axiopolis Sport Cernavodă",
		      "oaspeti" => "ACS Înainte Modelu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "CS Făurei",
		      "oaspeti" => "SC Popeşti-Leordeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "CS Făurei",
		      "oaspeti" => "CS Tunari",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "SC Popeşti-Leordeni",
		      "oaspeti" => "CSA Axiopolis Sport Cernavodă",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "ACS Înainte Modelu",
		      "oaspeti" => "AFC Unirea 04 Slobozia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "CS Poseidon Limanu-2 Mai",
		      "oaspeti" => "CS Afumaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "ACS Mostiştea Ulmu",
		      "oaspeti" => "AS FC Agricola Borcea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "FCSB 2",
		      "oaspeti" => "CS Medgidia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "ACS Recolta Gheorghe Doja",
		      "oaspeti" => "ACS Dacia Unirea Brăila",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "AFC Metalul Buzău",
		      "oaspeti" => "CS Viitorul Ianca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "CS Tunari",
		      "oaspeti" => "AFC Metalul Buzău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "CS Viitorul Ianca",
		      "oaspeti" => "ACS Recolta Gheorghe Doja",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "ACS Dacia Unirea Brăila",
		      "oaspeti" => "FCSB 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "CS Medgidia",
		      "oaspeti" => "ACS Mostiştea Ulmu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "AS FC Agricola Borcea",
		      "oaspeti" => "CS Poseidon Limanu-2 Mai",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "CS Afumaţi",
		      "oaspeti" => "ACS Înainte Modelu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "AFC Unirea 04 Slobozia",
		      "oaspeti" => "SC Popeşti-Leordeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "CSA Axiopolis Sport Cernavodă",
		      "oaspeti" => "CS Făurei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "CSA Axiopolis Sport Cernavodă",
		      "oaspeti" => "CS Tunari",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "CS Făurei",
		      "oaspeti" => "AFC Unirea 04 Slobozia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "SC Popeşti-Leordeni",
		      "oaspeti" => "CS Afumaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "ACS Înainte Modelu",
		      "oaspeti" => "AS FC Agricola Borcea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "CS Poseidon Limanu-2 Mai",
		      "oaspeti" => "CS Medgidia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "ACS Mostiştea Ulmu",
		      "oaspeti" => "ACS Dacia Unirea Brăila",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "FCSB 2",
		      "oaspeti" => "CS Viitorul Ianca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "ACS Recolta Gheorghe Doja",
		      "oaspeti" => "AFC Metalul Buzău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "CS Tunari",
		      "oaspeti" => "ACS Recolta Gheorghe Doja",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "AFC Metalul Buzău",
		      "oaspeti" => "FCSB 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "CS Viitorul Ianca",
		      "oaspeti" => "ACS Mostiştea Ulmu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "ACS Dacia Unirea Brăila",
		      "oaspeti" => "CS Poseidon Limanu-2 Mai",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "CS Medgidia",
		      "oaspeti" => "ACS Înainte Modelu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "AS FC Agricola Borcea",
		      "oaspeti" => "SC Popeşti-Leordeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "CS Afumaţi",
		      "oaspeti" => "CS Făurei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "AFC Unirea 04 Slobozia",
		      "oaspeti" => "CSA Axiopolis Sport Cernavodă",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "AFC Unirea 04 Slobozia",
		      "oaspeti" => "CS Tunari",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "CSA Axiopolis Sport Cernavodă",
		      "oaspeti" => "CS Afumaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "CS Făurei",
		      "oaspeti" => "AS FC Agricola Borcea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "SC Popeşti-Leordeni",
		      "oaspeti" => "CS Medgidia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "ACS Înainte Modelu",
		      "oaspeti" => "ACS Dacia Unirea Brăila",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "CS Poseidon Limanu-2 Mai",
		      "oaspeti" => "CS Viitorul Ianca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "ACS Mostiştea Ulmu",
		      "oaspeti" => "AFC Metalul Buzău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "FCSB 2",
		      "oaspeti" => "ACS Recolta Gheorghe Doja",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "CS Tunari",
		      "oaspeti" => "FCSB 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "ACS Recolta Gheorghe Doja",
		      "oaspeti" => "ACS Mostiştea Ulmu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "AFC Metalul Buzău",
		      "oaspeti" => "CS Poseidon Limanu-2 Mai",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "CS Viitorul Ianca",
		      "oaspeti" => "ACS Înainte Modelu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "ACS Dacia Unirea Brăila",
		      "oaspeti" => "SC Popeşti-Leordeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "CS Medgidia",
		      "oaspeti" => "CS Făurei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "AS FC Agricola Borcea",
		      "oaspeti" => "CSA Axiopolis Sport Cernavodă",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "CS Afumaţi",
		      "oaspeti" => "AFC Unirea 04 Slobozia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "CS Afumaţi",
		      "oaspeti" => "CS Tunari",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "AFC Unirea 04 Slobozia",
		      "oaspeti" => "AS FC Agricola Borcea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "CSA Axiopolis Sport Cernavodă",
		      "oaspeti" => "CS Medgidia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "CS Făurei",
		      "oaspeti" => "ACS Dacia Unirea Brăila",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "SC Popeşti-Leordeni",
		      "oaspeti" => "CS Viitorul Ianca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "ACS Înainte Modelu",
		      "oaspeti" => "AFC Metalul Buzău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "CS Poseidon Limanu-2 Mai",
		      "oaspeti" => "ACS Recolta Gheorghe Doja",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "ACS Mostiştea Ulmu",
		      "oaspeti" => "FCSB 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "CS Tunari",
		      "oaspeti" => "ACS Mostiştea Ulmu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "FCSB 2",
		      "oaspeti" => "CS Poseidon Limanu-2 Mai",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "ACS Recolta Gheorghe Doja",
		      "oaspeti" => "ACS Înainte Modelu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "AFC Metalul Buzău",
		      "oaspeti" => "SC Popeşti-Leordeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "CS Viitorul Ianca",
		      "oaspeti" => "CS Făurei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "ACS Dacia Unirea Brăila",
		      "oaspeti" => "CSA Axiopolis Sport Cernavodă",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "CS Medgidia",
		      "oaspeti" => "AFC Unirea 04 Slobozia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "AS FC Agricola Borcea",
		      "oaspeti" => "CS Afumaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "AS FC Agricola Borcea",
		      "oaspeti" => "CS Tunari",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "CS Afumaţi",
		      "oaspeti" => "CS Medgidia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "AFC Unirea 04 Slobozia",
		      "oaspeti" => "ACS Dacia Unirea Brăila",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "CSA Axiopolis Sport Cernavodă",
		      "oaspeti" => "CS Viitorul Ianca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "CS Făurei",
		      "oaspeti" => "AFC Metalul Buzău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "SC Popeşti-Leordeni",
		      "oaspeti" => "ACS Recolta Gheorghe Doja",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "ACS Înainte Modelu",
		      "oaspeti" => "FCSB 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "CS Poseidon Limanu-2 Mai",
		      "oaspeti" => "ACS Mostiştea Ulmu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "CS Tunari",
		      "oaspeti" => "CS Poseidon Limanu-2 Mai",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "ACS Mostiştea Ulmu",
		      "oaspeti" => "ACS Înainte Modelu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "FCSB 2",
		      "oaspeti" => "SC Popeşti-Leordeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "ACS Recolta Gheorghe Doja",
		      "oaspeti" => "CS Făurei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "AFC Metalul Buzău",
		      "oaspeti" => "CSA Axiopolis Sport Cernavodă",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "CS Viitorul Ianca",
		      "oaspeti" => "AFC Unirea 04 Slobozia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "ACS Dacia Unirea Brăila",
		      "oaspeti" => "CS Afumaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "CS Medgidia",
		      "oaspeti" => "AS FC Agricola Borcea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "CS Medgidia",
		      "oaspeti" => "CS Tunari",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "AS FC Agricola Borcea",
		      "oaspeti" => "ACS Dacia Unirea Brăila",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "CS Afumaţi",
		      "oaspeti" => "CS Viitorul Ianca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "AFC Unirea 04 Slobozia",
		      "oaspeti" => "AFC Metalul Buzău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "CSA Axiopolis Sport Cernavodă",
		      "oaspeti" => "ACS Recolta Gheorghe Doja",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "CS Făurei",
		      "oaspeti" => "FCSB 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "SC Popeşti-Leordeni",
		      "oaspeti" => "ACS Mostiştea Ulmu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "ACS Înainte Modelu",
		      "oaspeti" => "CS Poseidon Limanu-2 Mai",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "CS Tunari",
		      "oaspeti" => "ACS Înainte Modelu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "CS Poseidon Limanu-2 Mai",
		      "oaspeti" => "SC Popeşti-Leordeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "ACS Mostiştea Ulmu",
		      "oaspeti" => "CS Făurei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "FCSB 2",
		      "oaspeti" => "CSA Axiopolis Sport Cernavodă",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "ACS Recolta Gheorghe Doja",
		      "oaspeti" => "AFC Unirea 04 Slobozia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "AFC Metalul Buzău",
		      "oaspeti" => "CS Afumaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "CS Viitorul Ianca",
		      "oaspeti" => "AS FC Agricola Borcea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "ACS Dacia Unirea Brăila",
		      "oaspeti" => "CS Medgidia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "ACS Dacia Unirea Brăila",
		      "oaspeti" => "CS Tunari",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "CS Medgidia",
		      "oaspeti" => "CS Viitorul Ianca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "AS FC Agricola Borcea",
		      "oaspeti" => "AFC Metalul Buzău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "CS Afumaţi",
		      "oaspeti" => "ACS Recolta Gheorghe Doja",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "AFC Unirea 04 Slobozia",
		      "oaspeti" => "FCSB 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "CSA Axiopolis Sport Cernavodă",
		      "oaspeti" => "ACS Mostiştea Ulmu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "CS Făurei",
		      "oaspeti" => "CS Poseidon Limanu-2 Mai",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "SC Popeşti-Leordeni",
		      "oaspeti" => "ACS Înainte Modelu",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "CS Tunari",
		      "oaspeti" => "SC Popeşti-Leordeni",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "ACS Înainte Modelu",
		      "oaspeti" => "CS Făurei",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "CS Poseidon Limanu-2 Mai",
		      "oaspeti" => "CSA Axiopolis Sport Cernavodă",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "ACS Mostiştea Ulmu",
		      "oaspeti" => "AFC Unirea 04 Slobozia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "FCSB 2",
		      "oaspeti" => "CS Afumaţi",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "ACS Recolta Gheorghe Doja",
		      "oaspeti" => "AS FC Agricola Borcea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "AFC Metalul Buzău",
		      "oaspeti" => "CS Medgidia",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [ 
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "CS Viitorul Ianca",
		      "oaspeti" => "ACS Dacia Unirea Brăila",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 2,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ]
		];

		foreach ($echipe as $echipa) {
			$adauga = new ToateEchipele;
			$adauga->team = trim($echipa['echipa']);
			// $adauga->save();

			$e = ToateEchipele::where('team', trim($echipa['echipa']))->first();

			// Echipe::where('echipa_id', $e->id)->delete();
			// $clasament = new Echipe;
			// $clasament->echipa_id = $e->id;
			// $clasament->liga = 3;
			// $clasament->serie = 2;
			// $clasament->sezon = '2019/2020';
			// $clasament->save();
		}


		Etape::where('liga', 3)->where('serie', 2)->where('sezon', '2019/2020')->delete();

		foreach ($etape as $etapa) {
			$gazde = ToateEchipele::where('team', trim($etapa['gazde']))->first();
			$oaspeti = ToateEchipele::where('team', trim($etapa['oaspeti']))->first();

			$adauga = new Etape;
			$adauga->gazde_id   = $gazde['id'];
			$adauga->oaspeti_id = $oaspeti['id'];
			$adauga->g_gazde    = $etapa['g_gazde'];
			$adauga->g_oaspeti  = $etapa['g_oaspeti'];
			$adauga->liga       = $etapa['liga'];
			$adauga->serie      = $etapa['serie'];
			$adauga->etapa      = $etapa['etapa'];
			$adauga->data       = $etapa['data'];
			$adauga->ora        = $etapa['ora'];
			$adauga->sezon      = $etapa['sezon'];
			$adauga->save();
		}
    }
}
