<?php

use Illuminate\Database\Seeder;
use App\Echipe;
use App\Etape;
use App\ToateEchipele;

class liga_3_serie_5_2019_2020 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $echipe = [  
		   [
		      'echipa' => 'CS Luceafărul Oradea'
		   ],[
		      'echipa' => 'ACS Fotbal Comuna Recea'
		   ],[
		      'echipa' => 'CSC Sânmartin'
		   ],[
		      'echipa' => 'ACS Viitorul Şelimbăr'
		   ],[
		      'echipa' => 'CS Minaur Baia Mare'
		   ],[
		      'echipa' => 'ACS Sticla Arieşul Turda'
		   ],[
		      'echipa' => 'FC CFR 1907 Cluj SA 2'
		   ],[
		      'echipa' => 'CS Sănătatea Servicii Publice Cluj-Napoca'
		   ],[
		      'echipa' => 'ACS Unu Fotbal Club Gloria'
		   ],[
		      'echipa' => 'CSM Avântul Reghin'
		   ],[
		      'echipa' => 'AFC Metalurgistul Cugir 1939'
		   ],[
		      'echipa' => 'FC Unirea Dej'
		   ],[
		      'echipa' => 'AFC Unirea 1924'
		   ],[
		      'echipa' => 'AFC Odorheiu Secuiesc'
		   ],[
		      'echipa' => 'ACS Industria Galda'
		   ],[
		      'echipa' => 'SCM Zalău'
		   ]
		];
		$etape =
		[ 
		   [
		      "data" => "2019-08-23",
		      "ora" => "18:00",
		      "gazde" => "ACS Viitorul Şelimbăr",
		      "oaspeti" => "AFC Unirea 1924",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [
		      "data" => "2019-08-23",
		      "ora" => "18:00",
		      "gazde" => "CSM Avântul Reghin",
		      "oaspeti" => "AFC Odorheiu Secuiesc",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [
		      "data" => "2019-08-23",
		      "ora" => "18:00",
		      "gazde" => "CSC Sânmartin",
		      "oaspeti" => "CS Luceafărul Oradea",
		      "g_gazde" => 3,
		      "g_oaspeti" => 6,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [
		      "data" => "2019-08-23",
		      "ora" => "18:00",
		      "gazde" => "FC CFR 1907 Cluj SA 2",
		      "oaspeti" => "ACS Industria Galda",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [
		      "data" => "2019-08-23",
		      "ora" => "18:00",
		      "gazde" => "ACS Sticla Arieşul Turda",
		      "oaspeti" => "CS Minaur Baia Mare",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "SCM Zalău",
		      "oaspeti" => "FC Unirea Dej",
		      "g_gazde" => 0,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "ACS Unu Fotbal Club Gloria",
		      "oaspeti" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "g_gazde" => 0,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [
		      "data" => "2019-08-24",
		      "ora" => "18:00",
		      "gazde" => "ACS Fotbal Comuna Recea",
		      "oaspeti" => "AFC Metalurgistul Cugir 1939",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 1
		   ],
		   [
		      "data" => "2019-08-30",
		      "ora" => "18:00",
		      "gazde" => "FC Unirea Dej",
		      "oaspeti" => "AFC Metalurgistul Cugir 1939",
		      "g_gazde" => 0,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [
		      "data" => "2019-08-30",
		      "ora" => "18:00",
		      "gazde" => "AFC Odorheiu Secuiesc",
		      "oaspeti" => "CSC Sânmartin",
		      "g_gazde" => 3,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [
		      "data" => "2019-08-30",
		      "ora" => "18:00",
		      "gazde" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "oaspeti" => "CSM Avântul Reghin",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "CS Minaur Baia Mare",
		      "oaspeti" => "ACS Fotbal Comuna Recea",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "ACS Industria Galda",
		      "oaspeti" => "ACS Sticla Arieşul Turda",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "CS Luceafărul Oradea",
		      "oaspeti" => "FC CFR 1907 Cluj SA 2",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "AFC Unirea 1924",
		      "oaspeti" => "ACS Unu Fotbal Club Gloria",
		      "g_gazde" => 4,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [
		      "data" => "2019-08-31",
		      "ora" => "18:00",
		      "gazde" => "SCM Zalău",
		      "oaspeti" => "ACS Viitorul Şelimbăr",
		      "g_gazde" => 2,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 2
		   ],
		   [
		      "data" => "2019-09-06",
		      "ora" => "17:00",
		      "gazde" => "ACS Viitorul Şelimbăr",
		      "oaspeti" => "FC Unirea Dej",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [
		      "data" => "2019-09-06",
		      "ora" => "17:00",
		      "gazde" => "CSM Avântul Reghin",
		      "oaspeti" => "AFC Unirea 1924",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [
		      "data" => "2019-09-06",
		      "ora" => "17:00",
		      "gazde" => "CSC Sânmartin",
		      "oaspeti" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "g_gazde" => 3,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [
		      "data" => "2019-09-06",
		      "ora" => "17:00",
		      "gazde" => "FC CFR 1907 Cluj SA 2",
		      "oaspeti" => "AFC Odorheiu Secuiesc",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [
		      "data" => "2019-09-06",
		      "ora" => "17:00",
		      "gazde" => "ACS Sticla Arieşul Turda",
		      "oaspeti" => "CS Luceafărul Oradea",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "ACS Unu Fotbal Club Gloria",
		      "oaspeti" => "SCM Zalău",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "ACS Fotbal Comuna Recea",
		      "oaspeti" => "ACS Industria Galda",
		      "g_gazde" => 8,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [
		      "data" => "2019-09-07",
		      "ora" => "17:00",
		      "gazde" => "AFC Metalurgistul Cugir 1939",
		      "oaspeti" => "CS Minaur Baia Mare",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 3
		   ],
		   [
		      "data" => "2019-09-13",
		      "ora" => "17:00",
		      "gazde" => "FC Unirea Dej",
		      "oaspeti" => "CS Minaur Baia Mare",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [
		      "data" => "2019-09-13",
		      "ora" => "17:00",
		      "gazde" => "AFC Odorheiu Secuiesc",
		      "oaspeti" => "ACS Sticla Arieşul Turda",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [
		      "data" => "2019-09-13",
		      "ora" => "17:00",
		      "gazde" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "oaspeti" => "FC CFR 1907 Cluj SA 2",
		      "g_gazde" => 2,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [
		      "data" => "2019-09-13",
		      "ora" => "17:00",
		      "gazde" => "ACS Viitorul Şelimbăr",
		      "oaspeti" => "ACS Unu Fotbal Club Gloria",
		      "g_gazde" => 0,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "ACS Industria Galda",
		      "oaspeti" => "AFC Metalurgistul Cugir 1939",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "CS Luceafărul Oradea",
		      "oaspeti" => "ACS Fotbal Comuna Recea",
		      "g_gazde" => 3,
		      "g_oaspeti" => 4,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "AFC Unirea 1924",
		      "oaspeti" => "CSC Sânmartin",
		      "g_gazde" => 3,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [
		      "data" => "2019-09-14",
		      "ora" => "17:00",
		      "gazde" => "SCM Zalău",
		      "oaspeti" => "CSM Avântul Reghin",
		      "g_gazde" => 3,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 4
		   ],
		   [
		      "data" => "2019-09-20",
		      "ora" => "17:00",
		      "gazde" => "CSM Avântul Reghin",
		      "oaspeti" => "ACS Viitorul Şelimbăr",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [
		      "data" => "2019-09-20",
		      "ora" => "17:00",
		      "gazde" => "CSC Sânmartin",
		      "oaspeti" => "SCM Zalău",
		      "g_gazde" => 3,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [
		      "data" => "2019-09-20",
		      "ora" => "17:00",
		      "gazde" => "FC CFR 1907 Cluj SA 2",
		      "oaspeti" => "AFC Unirea 1924",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [
		      "data" => "2019-09-20",
		      "ora" => "17:00",
		      "gazde" => "ACS Sticla Arieşul Turda",
		      "oaspeti" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [
		      "data" => "2019-09-20",
		      "ora" => "17:00",
		      "gazde" => "ACS Fotbal Comuna Recea",
		      "oaspeti" => "AFC Odorheiu Secuiesc",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [
		      "data" => "2019-09-20",
		      "ora" => "17:00",
		      "gazde" => "AFC Metalurgistul Cugir 1939",
		      "oaspeti" => "CS Luceafărul Oradea",
		      "g_gazde" => 0,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "ACS Unu Fotbal Club Gloria",
		      "oaspeti" => "FC Unirea Dej",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [
		      "data" => "2019-09-21",
		      "ora" => "17:00",
		      "gazde" => "CS Minaur Baia Mare",
		      "oaspeti" => "ACS Industria Galda",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 5
		   ],
		   [
		      "data" => "2019-09-27",
		      "ora" => "17:00",
		      "gazde" => "AFC Odorheiu Secuiesc",
		      "oaspeti" => "AFC Metalurgistul Cugir 1939",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [
		      "data" => "2019-09-27",
		      "ora" => "17:00",
		      "gazde" => "ACS Viitorul Şelimbăr",
		      "oaspeti" => "CSC Sânmartin",
		      "g_gazde" => 3,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [
		      "data" => "2019-09-28",
		      "ora" => "14:00",
		      "gazde" => "FC Unirea Dej",
		      "oaspeti" => "ACS Industria Galda",
		      "g_gazde" => 3,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [
		      "data" => "2019-09-28",
		      "ora" => "17:00",
		      "gazde" => "CS Luceafărul Oradea",
		      "oaspeti" => "CS Minaur Baia Mare",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [
		      "data" => "2019-09-28",
		      "ora" => "17:00",
		      "gazde" => "AFC Unirea 1924",
		      "oaspeti" => "ACS Sticla Arieşul Turda",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [
		      "data" => "2019-09-28",
		      "ora" => "17:00",
		      "gazde" => "SCM Zalău",
		      "oaspeti" => "FC CFR 1907 Cluj SA 2",
		      "g_gazde" => 3,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [
		      "data" => "2019-09-28",
		      "ora" => "17:00",
		      "gazde" => "ACS Unu Fotbal Club Gloria",
		      "oaspeti" => "CSM Avântul Reghin",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [
		      "data" => "2019-09-30",
		      "ora" => "17:00",
		      "gazde" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "oaspeti" => "ACS Fotbal Comuna Recea",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 6
		   ],
		   [
		      "data" => "2019-10-04",
		      "ora" => "15:00",
		      "gazde" => "CSM Avântul Reghin",
		      "oaspeti" => "FC Unirea Dej",
		      "g_gazde" => 3,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [
		      "data" => "2019-10-04",
		      "ora" => "15:00",
		      "gazde" => "CSC Sânmartin",
		      "oaspeti" => "ACS Unu Fotbal Club Gloria",
		      "g_gazde" => 3,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [
		      "data" => "2019-10-04",
		      "ora" => "15:00",
		      "gazde" => "FC CFR 1907 Cluj SA 2",
		      "oaspeti" => "ACS Viitorul Şelimbăr",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [
		      "data" => "2019-10-04",
		      "ora" => "15:00",
		      "gazde" => "ACS Sticla Arieşul Turda",
		      "oaspeti" => "SCM Zalău",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "ACS Fotbal Comuna Recea",
		      "oaspeti" => "AFC Unirea 1924",
		      "g_gazde" => 2,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "AFC Metalurgistul Cugir 1939",
		      "oaspeti" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "g_gazde" => 0,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "CS Minaur Baia Mare",
		      "oaspeti" => "AFC Odorheiu Secuiesc",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [
		      "data" => "2019-10-05",
		      "ora" => "15:00",
		      "gazde" => "ACS Industria Galda",
		      "oaspeti" => "CS Luceafărul Oradea",
		      "g_gazde" => 2,
		      "g_oaspeti" => 6,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 7
		   ],
		   [
		      "data" => "2019-10-11",
		      "ora" => "15:00",
		      "gazde" => "FC Unirea Dej",
		      "oaspeti" => "CS Luceafărul Oradea",
		      "g_gazde" => 2,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [
		      "data" => "2019-10-11",
		      "ora" => "15:00",
		      "gazde" => "AFC Odorheiu Secuiesc",
		      "oaspeti" => "ACS Industria Galda",
		      "g_gazde" => 1,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [
		      "data" => "2019-10-11",
		      "ora" => "15:00",
		      "gazde" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "oaspeti" => "CS Minaur Baia Mare",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [
		      "data" => "2019-10-11",
		      "ora" => "15:00",
		      "gazde" => "ACS Viitorul Şelimbăr",
		      "oaspeti" => "ACS Sticla Arieşul Turda",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [
		      "data" => "2019-10-11",
		      "ora" => "15:00",
		      "gazde" => "CSM Avântul Reghin",
		      "oaspeti" => "CSC Sânmartin",
		      "g_gazde" => 0,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [
		      "data" => "2019-10-12",
		      "ora" => "15:00",
		      "gazde" => "AFC Unirea 1924",
		      "oaspeti" => "AFC Metalurgistul Cugir 1939",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [
		      "data" => "2019-10-12",
		      "ora" => "15:00",
		      "gazde" => "SCM Zalău",
		      "oaspeti" => "ACS Fotbal Comuna Recea",
		      "g_gazde" => 0,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [
		      "data" => "2019-10-12",
		      "ora" => "15:00",
		      "gazde" => "ACS Unu Fotbal Club Gloria",
		      "oaspeti" => "FC CFR 1907 Cluj SA 2",
		      "g_gazde" => 3,
		      "g_oaspeti" => 2,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 8
		   ],
		   [
		      "data" => "2019-10-18",
		      "ora" => "15:00",
		      "gazde" => "CSC Sânmartin",
		      "oaspeti" => "FC Unirea Dej",
		      "g_gazde" => 5,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [
		      "data" => "2019-10-18",
		      "ora" => "15:00",
		      "gazde" => "FC CFR 1907 Cluj SA 2",
		      "oaspeti" => "CSM Avântul Reghin",
		      "g_gazde" => 3,
		      "g_oaspeti" => 3,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [
		      "data" => "2019-10-18",
		      "ora" => "15:00",
		      "gazde" => "ACS Sticla Arieşul Turda",
		      "oaspeti" => "ACS Unu Fotbal Club Gloria",
		      "g_gazde" => 1,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "ACS Fotbal Comuna Recea",
		      "oaspeti" => "ACS Viitorul Şelimbăr",
		      "g_gazde" => 2,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "AFC Metalurgistul Cugir 1939",
		      "oaspeti" => "SCM Zalău",
		      "g_gazde" => 3,
		      "g_oaspeti" => 1,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "CS Minaur Baia Mare",
		      "oaspeti" => "AFC Unirea 1924",
		      "g_gazde" => 1,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "ACS Industria Galda",
		      "oaspeti" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "g_gazde" => 0,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [
		      "data" => "2019-10-19",
		      "ora" => "15:00",
		      "gazde" => "CS Luceafărul Oradea",
		      "oaspeti" => "AFC Odorheiu Secuiesc",
		      "g_gazde" => 3,
		      "g_oaspeti" => 0,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 9
		   ],
		   [
		      "data" => "2019-10-25",
		      "ora" => "15:00",
		      "gazde" => "FC Unirea Dej",
		      "oaspeti" => "AFC Odorheiu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [
		      "data" => "2019-10-25",
		      "ora" => "15:00",
		      "gazde" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "oaspeti" => "CS Luceafărul Oradea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [
		      "data" => "2019-10-25",
		      "ora" => "15:00",
		      "gazde" => "ACS Viitorul Şelimbăr",
		      "oaspeti" => "AFC Metalurgistul Cugir 1939",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [
		      "data" => "2019-10-25",
		      "ora" => "15:00",
		      "gazde" => "CSM Avântul Reghin",
		      "oaspeti" => "ACS Sticla Arieşul Turda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [
		      "data" => "2019-10-25",
		      "ora" => "15:00",
		      "gazde" => "CSC Sânmartin",
		      "oaspeti" => "FC CFR 1907 Cluj SA 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "AFC Unirea 1924",
		      "oaspeti" => "ACS Industria Galda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "SCM Zalău",
		      "oaspeti" => "CS Minaur Baia Mare",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [
		      "data" => "2019-10-26",
		      "ora" => "15:00",
		      "gazde" => "ACS Unu Fotbal Club Gloria",
		      "oaspeti" => "ACS Fotbal Comuna Recea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 10
		   ],
		   [
		      "data" => "2019-11-01",
		      "ora" => "14:00",
		      "gazde" => "FC CFR 1907 Cluj SA 2",
		      "oaspeti" => "FC Unirea Dej",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [
		      "data" => "2019-11-01",
		      "ora" => "14:00",
		      "gazde" => "ACS Sticla Arieşul Turda",
		      "oaspeti" => "CSC Sânmartin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "ACS Fotbal Comuna Recea",
		      "oaspeti" => "CSM Avântul Reghin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "AFC Metalurgistul Cugir 1939",
		      "oaspeti" => "ACS Unu Fotbal Club Gloria",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "CS Minaur Baia Mare",
		      "oaspeti" => "ACS Viitorul Şelimbăr",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "ACS Industria Galda",
		      "oaspeti" => "SCM Zalău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "CS Luceafărul Oradea",
		      "oaspeti" => "AFC Unirea 1924",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [
		      "data" => "2019-11-02",
		      "ora" => "14:00",
		      "gazde" => "AFC Odorheiu Secuiesc",
		      "oaspeti" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 11
		   ],
		   [
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "FC Unirea Dej",
		      "oaspeti" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "AFC Unirea 1924",
		      "oaspeti" => "AFC Odorheiu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "SCM Zalău",
		      "oaspeti" => "CS Luceafărul Oradea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "ACS Viitorul Şelimbăr",
		      "oaspeti" => "ACS Industria Galda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "ACS Unu Fotbal Club Gloria",
		      "oaspeti" => "CS Minaur Baia Mare",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "CSM Avântul Reghin",
		      "oaspeti" => "AFC Metalurgistul Cugir 1939",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "CSC Sânmartin",
		      "oaspeti" => "ACS Fotbal Comuna Recea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [
		      "data" => "2019-11-09",
		      "ora" => "14:00",
		      "gazde" => "FC CFR 1907 Cluj SA 2",
		      "oaspeti" => "ACS Sticla Arieşul Turda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 12
		   ],
		   [
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "ACS Sticla Arieşul Turda",
		      "oaspeti" => "FC Unirea Dej",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "ACS Fotbal Comuna Recea",
		      "oaspeti" => "FC CFR 1907 Cluj SA 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "AFC Metalurgistul Cugir 1939",
		      "oaspeti" => "CSC Sânmartin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "CS Minaur Baia Mare",
		      "oaspeti" => "CSM Avântul Reghin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "ACS Industria Galda",
		      "oaspeti" => "ACS Unu Fotbal Club Gloria",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "CS Luceafărul Oradea",
		      "oaspeti" => "ACS Viitorul Şelimbăr",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "AFC Odorheiu Secuiesc",
		      "oaspeti" => "SCM Zalău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [
		      "data" => "2019-11-16",
		      "ora" => "14:00",
		      "gazde" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "oaspeti" => "AFC Unirea 1924",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 13
		   ],
		   [
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "FC Unirea Dej",
		      "oaspeti" => "AFC Unirea 1924",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "SCM Zalău",
		      "oaspeti" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "ACS Viitorul Şelimbăr",
		      "oaspeti" => "AFC Odorheiu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "ACS Unu Fotbal Club Gloria",
		      "oaspeti" => "CS Luceafărul Oradea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "CSM Avântul Reghin",
		      "oaspeti" => "ACS Industria Galda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "CSC Sânmartin",
		      "oaspeti" => "CS Minaur Baia Mare",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "FC CFR 1907 Cluj SA 2",
		      "oaspeti" => "AFC Metalurgistul Cugir 1939",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [
		      "data" => "2019-11-23",
		      "ora" => "14:00",
		      "gazde" => "ACS Sticla Arieşul Turda",
		      "oaspeti" => "ACS Fotbal Comuna Recea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 14
		   ],
		   [
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "ACS Fotbal Comuna Recea",
		      "oaspeti" => "FC Unirea Dej",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "AFC Metalurgistul Cugir 1939",
		      "oaspeti" => "ACS Sticla Arieşul Turda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "CS Minaur Baia Mare",
		      "oaspeti" => "FC CFR 1907 Cluj SA 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "ACS Industria Galda",
		      "oaspeti" => "CSC Sânmartin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "CS Luceafărul Oradea",
		      "oaspeti" => "CSM Avântul Reghin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "AFC Odorheiu Secuiesc",
		      "oaspeti" => "ACS Unu Fotbal Club Gloria",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "oaspeti" => "ACS Viitorul Şelimbăr",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [
		      "data" => "2019-11-30",
		      "ora" => "14:00",
		      "gazde" => "AFC Unirea 1924",
		      "oaspeti" => "SCM Zalău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 15
		   ],
		   [
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "FC Unirea Dej",
		      "oaspeti" => "SCM Zalău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "AFC Unirea 1924",
		      "oaspeti" => "ACS Viitorul Şelimbăr",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "oaspeti" => "ACS Unu Fotbal Club Gloria",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "AFC Odorheiu Secuiesc",
		      "oaspeti" => "CSM Avântul Reghin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "CS Luceafărul Oradea",
		      "oaspeti" => "CSC Sânmartin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "ACS Industria Galda",
		      "oaspeti" => "FC CFR 1907 Cluj SA 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "CS Minaur Baia Mare",
		      "oaspeti" => "ACS Sticla Arieşul Turda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [
		      "data" => "2020-03-07",
		      "ora" => "15:00",
		      "gazde" => "AFC Metalurgistul Cugir 1939",
		      "oaspeti" => "ACS Fotbal Comuna Recea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 16
		   ],
		   [
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "AFC Metalurgistul Cugir 1939",
		      "oaspeti" => "FC Unirea Dej",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "ACS Fotbal Comuna Recea",
		      "oaspeti" => "CS Minaur Baia Mare",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "ACS Sticla Arieşul Turda",
		      "oaspeti" => "ACS Industria Galda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "FC CFR 1907 Cluj SA 2",
		      "oaspeti" => "CS Luceafărul Oradea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "CSC Sânmartin",
		      "oaspeti" => "AFC Odorheiu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "CSM Avântul Reghin",
		      "oaspeti" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "ACS Unu Fotbal Club Gloria",
		      "oaspeti" => "AFC Unirea 1924",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [
		      "data" => "2020-03-14",
		      "ora" => "15:00",
		      "gazde" => "ACS Viitorul Şelimbăr",
		      "oaspeti" => "SCM Zalău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 17
		   ],
		   [
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "FC Unirea Dej",
		      "oaspeti" => "ACS Viitorul Şelimbăr",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "SCM Zalău",
		      "oaspeti" => "ACS Unu Fotbal Club Gloria",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "AFC Unirea 1924",
		      "oaspeti" => "CSM Avântul Reghin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "oaspeti" => "CSC Sânmartin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "AFC Odorheiu Secuiesc",
		      "oaspeti" => "FC CFR 1907 Cluj SA 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "CS Luceafărul Oradea",
		      "oaspeti" => "ACS Sticla Arieşul Turda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "ACS Industria Galda",
		      "oaspeti" => "ACS Fotbal Comuna Recea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [
		      "data" => "2020-03-21",
		      "ora" => "15:00",
		      "gazde" => "CS Minaur Baia Mare",
		      "oaspeti" => "AFC Metalurgistul Cugir 1939",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 18
		   ],
		   [
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "CS Minaur Baia Mare",
		      "oaspeti" => "FC Unirea Dej",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "AFC Metalurgistul Cugir 1939",
		      "oaspeti" => "ACS Industria Galda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "ACS Fotbal Comuna Recea",
		      "oaspeti" => "CS Luceafărul Oradea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "ACS Sticla Arieşul Turda",
		      "oaspeti" => "AFC Odorheiu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "FC CFR 1907 Cluj SA 2",
		      "oaspeti" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "CSC Sânmartin",
		      "oaspeti" => "AFC Unirea 1924",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "CSM Avântul Reghin",
		      "oaspeti" => "SCM Zalău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [
		      "data" => "2020-03-28",
		      "ora" => "15:00",
		      "gazde" => "ACS Unu Fotbal Club Gloria",
		      "oaspeti" => "ACS Viitorul Şelimbăr",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 19
		   ],
		   [
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "FC Unirea Dej",
		      "oaspeti" => "ACS Unu Fotbal Club Gloria",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "ACS Viitorul Şelimbăr",
		      "oaspeti" => "CSM Avântul Reghin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "SCM Zalău",
		      "oaspeti" => "CSC Sânmartin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "AFC Unirea 1924",
		      "oaspeti" => "FC CFR 1907 Cluj SA 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "oaspeti" => "ACS Sticla Arieşul Turda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "AFC Odorheiu Secuiesc",
		      "oaspeti" => "ACS Fotbal Comuna Recea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "CS Luceafărul Oradea",
		      "oaspeti" => "AFC Metalurgistul Cugir 1939",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [
		      "data" => "2020-04-04",
		      "ora" => "17:00",
		      "gazde" => "ACS Industria Galda",
		      "oaspeti" => "CS Minaur Baia Mare",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 20
		   ],
		   [
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "ACS Industria Galda",
		      "oaspeti" => "FC Unirea Dej",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "CS Minaur Baia Mare",
		      "oaspeti" => "CS Luceafărul Oradea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "AFC Metalurgistul Cugir 1939",
		      "oaspeti" => "AFC Odorheiu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "ACS Fotbal Comuna Recea",
		      "oaspeti" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "ACS Sticla Arieşul Turda",
		      "oaspeti" => "AFC Unirea 1924",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "FC CFR 1907 Cluj SA 2",
		      "oaspeti" => "SCM Zalău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "CSC Sânmartin",
		      "oaspeti" => "ACS Viitorul Şelimbăr",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [
		      "data" => "2020-04-08",
		      "ora" => "17:00",
		      "gazde" => "CSM Avântul Reghin",
		      "oaspeti" => "ACS Unu Fotbal Club Gloria",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 21
		   ],
		   [
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "FC Unirea Dej",
		      "oaspeti" => "CSM Avântul Reghin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "ACS Unu Fotbal Club Gloria",
		      "oaspeti" => "CSC Sânmartin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "ACS Viitorul Şelimbăr",
		      "oaspeti" => "FC CFR 1907 Cluj SA 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "SCM Zalău",
		      "oaspeti" => "ACS Sticla Arieşul Turda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "AFC Unirea 1924",
		      "oaspeti" => "ACS Fotbal Comuna Recea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "oaspeti" => "AFC Metalurgistul Cugir 1939",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "AFC Odorheiu Secuiesc",
		      "oaspeti" => "CS Minaur Baia Mare",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [
		      "data" => "2020-04-11",
		      "ora" => "17:00",
		      "gazde" => "CS Luceafărul Oradea",
		      "oaspeti" => "ACS Industria Galda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 22
		   ],
		   [
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "CS Luceafărul Oradea",
		      "oaspeti" => "FC Unirea Dej",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "ACS Industria Galda",
		      "oaspeti" => "AFC Odorheiu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "CS Minaur Baia Mare",
		      "oaspeti" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "AFC Metalurgistul Cugir 1939",
		      "oaspeti" => "AFC Unirea 1924",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "ACS Fotbal Comuna Recea",
		      "oaspeti" => "SCM Zalău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "ACS Sticla Arieşul Turda",
		      "oaspeti" => "ACS Viitorul Şelimbăr",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "FC CFR 1907 Cluj SA 2",
		      "oaspeti" => "ACS Unu Fotbal Club Gloria",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [
		      "data" => "2020-04-17",
		      "ora" => "17:00",
		      "gazde" => "CSC Sânmartin",
		      "oaspeti" => "CSM Avântul Reghin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 23
		   ],
		   [
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "FC Unirea Dej",
		      "oaspeti" => "CSC Sânmartin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "CSM Avântul Reghin",
		      "oaspeti" => "FC CFR 1907 Cluj SA 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "ACS Unu Fotbal Club Gloria",
		      "oaspeti" => "ACS Sticla Arieşul Turda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "ACS Viitorul Şelimbăr",
		      "oaspeti" => "ACS Fotbal Comuna Recea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "SCM Zalău",
		      "oaspeti" => "AFC Metalurgistul Cugir 1939",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "AFC Unirea 1924",
		      "oaspeti" => "CS Minaur Baia Mare",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "oaspeti" => "ACS Industria Galda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [
		      "data" => "2020-04-25",
		      "ora" => "17:00",
		      "gazde" => "AFC Odorheiu Secuiesc",
		      "oaspeti" => "CS Luceafărul Oradea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 24
		   ],
		   [
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "AFC Odorheiu Secuiesc",
		      "oaspeti" => "FC Unirea Dej",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "CS Luceafărul Oradea",
		      "oaspeti" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "ACS Industria Galda",
		      "oaspeti" => "AFC Unirea 1924",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "CS Minaur Baia Mare",
		      "oaspeti" => "SCM Zalău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "AFC Metalurgistul Cugir 1939",
		      "oaspeti" => "ACS Viitorul Şelimbăr",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "ACS Fotbal Comuna Recea",
		      "oaspeti" => "ACS Unu Fotbal Club Gloria",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "ACS Sticla Arieşul Turda",
		      "oaspeti" => "CSM Avântul Reghin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [
		      "data" => "2020-05-02",
		      "ora" => "18:00",
		      "gazde" => "FC CFR 1907 Cluj SA 2",
		      "oaspeti" => "CSC Sânmartin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 25
		   ],
		   [
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "FC Unirea Dej",
		      "oaspeti" => "FC CFR 1907 Cluj SA 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "CSC Sânmartin",
		      "oaspeti" => "ACS Sticla Arieşul Turda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "CSM Avântul Reghin",
		      "oaspeti" => "ACS Fotbal Comuna Recea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "ACS Unu Fotbal Club Gloria",
		      "oaspeti" => "AFC Metalurgistul Cugir 1939",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "ACS Viitorul Şelimbăr",
		      "oaspeti" => "CS Minaur Baia Mare",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "SCM Zalău",
		      "oaspeti" => "ACS Industria Galda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "AFC Unirea 1924",
		      "oaspeti" => "CS Luceafărul Oradea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [
		      "data" => "2020-05-06",
		      "ora" => "18:00",
		      "gazde" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "oaspeti" => "AFC Odorheiu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 26
		   ],
		   [
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "oaspeti" => "FC Unirea Dej",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "AFC Odorheiu Secuiesc",
		      "oaspeti" => "AFC Unirea 1924",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "CS Luceafărul Oradea",
		      "oaspeti" => "SCM Zalău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "ACS Industria Galda",
		      "oaspeti" => "ACS Viitorul Şelimbăr",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "CS Minaur Baia Mare",
		      "oaspeti" => "ACS Unu Fotbal Club Gloria",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "AFC Metalurgistul Cugir 1939",
		      "oaspeti" => "CSM Avântul Reghin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "ACS Fotbal Comuna Recea",
		      "oaspeti" => "CSC Sânmartin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [
		      "data" => "2020-05-09",
		      "ora" => "18:00",
		      "gazde" => "ACS Sticla Arieşul Turda",
		      "oaspeti" => "FC CFR 1907 Cluj SA 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 27
		   ],
		   [
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "FC Unirea Dej",
		      "oaspeti" => "ACS Sticla Arieşul Turda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "FC CFR 1907 Cluj SA 2",
		      "oaspeti" => "ACS Fotbal Comuna Recea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "CSC Sânmartin",
		      "oaspeti" => "AFC Metalurgistul Cugir 1939",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "CSM Avântul Reghin",
		      "oaspeti" => "CS Minaur Baia Mare",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "ACS Unu Fotbal Club Gloria",
		      "oaspeti" => "ACS Industria Galda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "ACS Viitorul Şelimbăr",
		      "oaspeti" => "CS Luceafărul Oradea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "SCM Zalău",
		      "oaspeti" => "AFC Odorheiu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [
		      "data" => "2020-05-16",
		      "ora" => "18:00",
		      "gazde" => "AFC Unirea 1924",
		      "oaspeti" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 28
		   ],
		   [
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "AFC Unirea 1924",
		      "oaspeti" => "FC Unirea Dej",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "oaspeti" => "SCM Zalău",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "AFC Odorheiu Secuiesc",
		      "oaspeti" => "ACS Viitorul Şelimbăr",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "CS Luceafărul Oradea",
		      "oaspeti" => "ACS Unu Fotbal Club Gloria",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "ACS Industria Galda",
		      "oaspeti" => "CSM Avântul Reghin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "CS Minaur Baia Mare",
		      "oaspeti" => "CSC Sânmartin",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "AFC Metalurgistul Cugir 1939",
		      "oaspeti" => "FC CFR 1907 Cluj SA 2",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [
		      "data" => "2020-05-23",
		      "ora" => "18:00",
		      "gazde" => "ACS Fotbal Comuna Recea",
		      "oaspeti" => "ACS Sticla Arieşul Turda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 29
		   ],
		   [
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "FC Unirea Dej",
		      "oaspeti" => "ACS Fotbal Comuna Recea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "ACS Sticla Arieşul Turda",
		      "oaspeti" => "AFC Metalurgistul Cugir 1939",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "FC CFR 1907 Cluj SA 2",
		      "oaspeti" => "CS Minaur Baia Mare",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "CSC Sânmartin",
		      "oaspeti" => "ACS Industria Galda",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "CSM Avântul Reghin",
		      "oaspeti" => "CS Luceafărul Oradea",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "ACS Unu Fotbal Club Gloria",
		      "oaspeti" => "AFC Odorheiu Secuiesc",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "ACS Viitorul Şelimbăr",
		      "oaspeti" => "CS Sănătatea Servicii Publice Cluj-Napoca",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ],
		   [
		      "data" => "2020-05-30",
		      "ora" => "18:00",
		      "gazde" => "SCM Zalău",
		      "oaspeti" => "AFC Unirea 1924",
		      "g_gazde" => null,
		      "g_oaspeti" => null,
		      "liga" => 3,
		      "serie" => 5,
		      "sezon" => "2019/2020",
		      "etapa" => 30
		   ]
		];

		foreach ($echipe as $echipa) {
			$adauga = new ToateEchipele;
			$adauga->team = trim($echipa['echipa']);
			$adauga->save();

			// Echipe::where('echipa_id', $e->id)->delete();
			$clasament = new Echipe;
			$clasament->echipa_id = $adauga->id;
			$clasament->liga = 3;
			$clasament->serie = 5;
			$clasament->sezon = '2019/2020';
			$clasament->save();
		}


		Etape::where('liga', 3)->where('serie', 5)->where('sezon', '2019/2020')->delete();

		foreach ($etape as $etapa) {
			$gazde = ToateEchipele::where('team', trim($etapa['gazde']))->first();
			$oaspeti = ToateEchipele::where('team', trim($etapa['oaspeti']))->first();

			$adauga = new Etape;
			$adauga->gazde_id   = $gazde['id'];
			$adauga->oaspeti_id = $oaspeti['id'];
			$adauga->g_gazde    = $etapa['g_gazde'];
			$adauga->g_oaspeti  = $etapa['g_oaspeti'];
			$adauga->liga       = $etapa['liga'];
			$adauga->serie      = $etapa['serie'];
			$adauga->etapa      = $etapa['etapa'];
			$adauga->data       = $etapa['data'];
			$adauga->ora        = $etapa['ora'];
			$adauga->sezon      = $etapa['sezon'];
			$adauga->save();
		}
    }
}
