<?php

use Illuminate\Database\Seeder;
use App\Echipe;
use App\Etape;

class liga_1 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $echipe = [
			[
			'echipa' => 'CFR Cluj',
			'liga'   => 1,
			'serie'  => NULL,
			],[
			'echipa' => 'FCSB',
			'liga'   => 1,
			'serie'  => NULL,
			],[
			'echipa' => 'Astra Giurgiu',
			'liga'   => 1,
			'serie'  => NULL,
			],[
			'echipa' => 'FC Viitorul',
			'liga'   => 1,
			'serie'  => NULL,
			],[
			'echipa' => 'FC Hermannstadt',
			'liga'   => 1,
			'serie'  => NULL,
			],[
			'echipa' => 'Sepsi',
			'liga'   => 1,
			'serie'  => NULL,
			],[
			'echipa' => 'Dinamo București',
			'liga'   => 1,
			'serie'  => NULL,
			],[
			'echipa' => 'Gaz Metan Mediaș',
			'liga'   => 1,
			'serie'  => NULL,
			],[
			'echipa' => 'Concordia Chiajna',
			'liga'   => 1,
			'serie'  => NULL,
			],[
			'echipa' => 'FC Botoșani',
			'liga'   => 1,
			'serie'  => NULL,
			],[
			'echipa' => 'Dunărea Călărași',
			'liga'   => 1,
			'serie'  => NULL,
			],[
			'echipa' => 'U Craiova 1948 CS',
			'liga'   => 1,
			'serie'  => NULL,
			],[
			'echipa' => 'Poli Iași',
			'liga'   => 1,
			'serie'  => NULL,
			],[
			'echipa' => 'FC Voluntari',
			'liga'   => 1,
			'serie'  => NULL,
			]
		];

		$etape = [
		    [
				'gazde'     => 'Concordia Chiajna',
				'oaspeti'   => 'Astra Giurgiu',
				'g_gazde'   => 0,
				'g_oaspeti' => 3,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 6,
				'data'      => '2018-08-24',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'U Craiova 1948 CS',
				'oaspeti'   => 'Concordia Chiajna',
				'g_gazde'   => 0,
				'g_oaspeti' => 1,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 5,
				'data'      => '2018-08-20',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'FC Hermannstadt',
				'oaspeti'   => 'FC Voluntari',
				'g_gazde'   => 4,
				'g_oaspeti' => 0,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 5,
				'data'      => '2018-08-20',
				'ora'       => '18:00',
		    ], [
				'gazde'     => 'CFR Cluj',
				'oaspeti'   => 'Dinamo București',
				'g_gazde'   => 3,
				'g_oaspeti' => 1,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 5,
				'data'      => '2018-08-19',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'FCSB',
				'oaspeti'   => 'Sepsi',
				'g_gazde'   => 2,
				'g_oaspeti' => 0,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 5,
				'data'      => '2018-08-19',
				'ora'       => '18:00',
		    ], [
				'gazde'     => 'FC Viitorul',
				'oaspeti'   => 'Gaz Metan Mediaș',
				'g_gazde'   => 2,
				'g_oaspeti' => 0,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 5,
				'data'      => '2018-08-18',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'Astra Giurgiu',
				'oaspeti'   => 'Dunărea Călărași',
				'g_gazde'   => 1,
				'g_oaspeti' => 1,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 5,
				'data'      => '2018-08-18',
				'ora'       => '18:00',
		    ], [
				'gazde'     => 'Poli Iași',
				'oaspeti'   => 'FC Botoșani',
				'g_gazde'   => 2,
				'g_oaspeti' => 1,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 5,
				'data'      => '2018-08-17',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'Dinamo București',
				'oaspeti'   => 'FC Viitorul',
				'g_gazde'   => 1,
				'g_oaspeti' => 0,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 4,
				'data'      => '2018-08-13',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'Gaz Metan Mediaș',
				'oaspeti'   => 'FCSB',
				'g_gazde'   => 1,
				'g_oaspeti' => 3,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 4,
				'data'      => '2018-08-12',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'FC Voluntari',
				'oaspeti'   => 'CFR Cluj',
				'g_gazde'   => 1,
				'g_oaspeti' => 2,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 4,
				'data'      => '2018-08-12',
				'ora'       => '18:00',
		    ], [
				'gazde'     => 'Dunărea Călărași',
				'oaspeti'   => 'U Craiova 1948 CS',
				'g_gazde'   => 1,
				'g_oaspeti' => 3,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 4,
				'data'      => '2018-08-12',
				'ora'       => '15:30',
		    ], [
				'gazde'     => 'Sepsi',
				'oaspeti'   => 'Poli Iași',
				'g_gazde'   => 3,
				'g_oaspeti' => 0,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 4,
				'data'      => '2018-08-11',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'Concordia Chiajna',
				'oaspeti'   => 'FC Hermannstadt',
				'g_gazde'   => 2,
				'g_oaspeti' => 0,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 4,
				'data'      => '2018-08-11',
				'ora'       => '18:00',
		    ], [
				'gazde'     => 'FC Botoșani',
				'oaspeti'   => 'Astra Giurgiu',
				'g_gazde'   => 1,
				'g_oaspeti' => 1,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 4,
				'data'      => '2018-08-10',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'Gaz Metan Mediaș',
				'oaspeti'   => 'Dinamo București',
				'g_gazde'   => 3,
				'g_oaspeti' => 2,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 3,
				'data'      => '2018-08-06',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'FC Viitorul',
				'oaspeti'   => 'FC Voluntari',
				'g_gazde'   => 2,
				'g_oaspeti' => 0,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 3,
				'data'      => '2018-08-06',
				'ora'       => '18:00',
		    ], [
				'gazde'     => 'FCSB',
				'oaspeti'   => 'Poli Iași',
				'g_gazde'   => 4,
				'g_oaspeti' => 0,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 3,
				'data'      => '2018-08-05',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'FC Hermannstadt',
				'oaspeti'   => 'Dunărea Călărași',
				'g_gazde'   => 1,
				'g_oaspeti' => 1,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 3,
				'data'      => '2018-08-05',
				'ora'       => '18:00',
		    ], [
				'gazde'     => 'CFR Cluj',
				'oaspeti'   => 'Concordia Chiajna',
				'g_gazde'   => 2,
				'g_oaspeti' => 1,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 3,
				'data'      => '2018-08-04',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'Astra Giurgiu',
				'oaspeti'   => 'Sepsi',
				'g_gazde'   => 1,
				'g_oaspeti' => 1,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 3,
				'data'      => '2018-08-04',
				'ora'       => '18:00',
		    ], [
				'gazde'     => 'U Craiova 1948 CS',
				'oaspeti'   => 'FC Botoșani',
				'g_gazde'   => 2,
				'g_oaspeti' => 2,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 3,
				'data'      => '2018-08-03',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'Concordia Chiajna',
				'oaspeti'   => 'FC Viitorul',
				'g_gazde'   => 1,
				'g_oaspeti' => 1,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 2,
				'data'      => '2018-07-30',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'FC Voluntari',
				'oaspeti'   => 'Gaz Metan Mediaș',
				'g_gazde'   => 1,
				'g_oaspeti' => 1,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 2,
				'data'      => '2018-07-30',
				'ora'       => '18:00',
		    ], [
				'gazde'     => 'FCSB',
				'oaspeti'   => 'Dinamo București',
				'g_gazde'   => 3,
				'g_oaspeti' => 3,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 2,
				'data'      => '2018-07-29',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'Sepsi',
				'oaspeti'   => 'U Craiova 1948 CS',
				'g_gazde'   => 1,
				'g_oaspeti' => 0,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 2,
				'data'      => '2018-07-29',
				'ora'       => '18:00',
		    ], [
				'gazde'     => 'Poli Iași',
				'oaspeti'   => 'Astra Giurgiu',
				'g_gazde'   => 1,
				'g_oaspeti' => 1,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 2,
				'data'      => '2018-07-28',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'Dunărea Călărași',
				'oaspeti'   => 'CFR Cluj',
				'g_gazde'   => 0,
				'g_oaspeti' => 0,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 2,
				'data'      => '2018-07-28',
				'ora'       => '18:00',
		    ], [
				'gazde'     => 'FC Botoșani',
				'oaspeti'   => 'FC Hermannstadt',
				'g_gazde'   => 2,
				'g_oaspeti' => 0,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 2,
				'data'      => '2018-07-27',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'U Craiova 1948 CS',
				'oaspeti'   => 'Poli Iași',
				'g_gazde'   => 0,
				'g_oaspeti' => 0,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 1,
				'data'      => '2018-07-23',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'Gaz Metan Mediaș',
				'oaspeti'   => 'Concordia Chiajna',
				'g_gazde'   => 2,
				'g_oaspeti' => 1,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 1,
				'data'      => '2018-07-23',
				'ora'       => '18:00',
		    ], [
				'gazde'     => 'Dinamo București',
				'oaspeti'   => 'FC Voluntari',
				'g_gazde'   => 2,
				'g_oaspeti' => 1,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 1,
				'data'      => '2018-07-22',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'FC Viitorul',
				'oaspeti'   => 'Dunărea Călărași',
				'g_gazde'   => 0,
				'g_oaspeti' => 1,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 1,
				'data'      => '2018-07-22',
				'ora'       => '18:00',
		    ], [
				'gazde'     => 'Astra Giurgiu',
				'oaspeti'   => 'FCSB',
				'g_gazde'   => 1,
				'g_oaspeti' => 0,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 1,
				'data'      => '2018-07-21',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'FC Hermannstadt',
				'oaspeti'   => 'Sepsi',
				'g_gazde'   => 1,
				'g_oaspeti' => 0,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 1,
				'data'      => '2018-07-21',
				'ora'       => '18:00',
		    ], [
				'gazde'     => 'CFR Cluj',
				'oaspeti'   => 'FC Botoșani',
				'g_gazde'   => 1,
				'g_oaspeti' => 1,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 1,
				'data'      => '2018-07-20',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'Dunărea Călărași',
				'oaspeti'   => 'Poli Iași',
				'g_gazde'   => NULL,
				'g_oaspeti' => NULL,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 6,
				'data'      => '2018-08-25',
				'ora'       => '18:00',
		    ], [
				'gazde'     => 'Dinamo București',
				'oaspeti'   => 'FC Hermannstadt',
				'g_gazde'   => NULL,
				'g_oaspeti' => NULL,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 6,
				'data'      => '2018-08-25',
				'ora'       => '21:00',
		    ], [
				'gazde'     => 'Gaz Metan Mediaș',
				'oaspeti'   => 'CFR Cluj',
				'g_gazde'   => NULL,
				'g_oaspeti' => NULL,
				'liga'      => 1,
				'serie'     => NULL,
				'etapa'     => 6,
				'data'      => '2018-08-26',
				'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Viitorul',
		        'oaspeti'   => 'FCSB',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 6,
		        'data'      => '2018-08-26',
		        'ora'       => '21:00',
		    ], [
		        'gazde'     => 'FC Botoșani',
		        'oaspeti'   => 'Sepsi',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 6,
		        'data'      => '2018-08-27',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Voluntari',
		        'oaspeti'   => 'U Craiova 1948 CS',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 6,
		        'data'      => '2018-08-27',
		        'ora'       => '21:00',
		    ], [
		        'gazde'     => 'Sepsi',
		        'oaspeti'   => 'Dunărea Călărași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 7,
		        'data'      => '2018-08-31',
		        'ora'       => '19:30',
		    ], [
		        'gazde'     => 'FC Hermannstadt',
		        'oaspeti'   => 'Gaz Metan Mediaș',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 7,
		        'data'      => '2018-09-01',
		        'ora'       => '16:00',
		    ], [
		        'gazde'     => 'Astra Giurgiu',
		        'oaspeti'   => 'FC Voluntari',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 7,
		        'data'      => '2018-09-01',
		        'ora'       => '18:30',
		    ], [
		        'gazde'     => 'U Craiova 1948 CS',
		        'oaspeti'   => 'Dinamo București',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 7,
		        'data'      => '2018-09-01',
		        'ora'       => '21:30',
		    ], [
		        'gazde'     => 'CFR Cluj',
		        'oaspeti'   => 'FC Viitorul',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 7,
		        'data'      => '2018-09-02',
		        'ora'       => '18:30',
		    ], [
		        'gazde'     => 'FCSB',
		        'oaspeti'   => 'FC Botoșani',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 7,
		        'data'      => '2018-09-02',
		        'ora'       => '21:30',
		    ], [
		        'gazde'     => 'Poli Iași',
		        'oaspeti'   => 'Concordia Chiajna',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 7,
		        'data'      => '2018-09-03',
		        'ora'       => '21:00',
		    ], [
		        'gazde'     => 'CFR Cluj',
		        'oaspeti'   => 'FCSB',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 8,
		        'data'      => '2018-09-15',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Concordia Chiajna',
		        'oaspeti'   => 'Sepsi',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 8,
		        'data'      => '2018-09-15',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dinamo București',
		        'oaspeti'   => 'Astra Giurgiu',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 8,
		        'data'      => '2018-09-15',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dunărea Călărași',
		        'oaspeti'   => 'FC Botoșani',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 8,
		        'data'      => '2018-09-15',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Viitorul',
		        'oaspeti'   => 'FC Hermannstadt',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 8,
		        'data'      => '2018-09-15',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Voluntari',
		        'oaspeti'   => 'Poli Iași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 8,
		        'data'      => '2018-09-15',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Gaz Metan Mediaș',
		        'oaspeti'   => 'U Craiova 1948 CS',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 8,
		        'data'      => '2018-09-15',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Astra Giurgiu',
		        'oaspeti'   => 'Gaz Metan Mediaș',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 9,
		        'data'      => '2018-09-22',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Botoșani',
		        'oaspeti'   => 'Concordia Chiajna',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 9,
		        'data'      => '2018-09-22',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Hermannstadt',
		        'oaspeti'   => 'CFR Cluj',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 9,
		        'data'      => '2018-09-22',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FCSB',
		        'oaspeti'   => 'Dunărea Călărași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 9,
		        'data'      => '2018-09-22',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Poli Iași',
		        'oaspeti'   => 'Dinamo București',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 9,
		        'data'      => '2018-09-22',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Sepsi',
		        'oaspeti'   => 'FC Voluntari',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 9,
		        'data'      => '2018-09-22',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'U Craiova 1948 CS',
		        'oaspeti'   => 'FC Viitorul',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 9,
		        'data'      => '2018-09-22',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'CFR Cluj',
		        'oaspeti'   => 'U Craiova 1948 CS',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 10,
		        'data'      => '2018-09-29',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Concordia Chiajna',
		        'oaspeti'   => 'Dunărea Călărași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 10,
		        'data'      => '2018-09-29',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dinamo București',
		        'oaspeti'   => 'Sepsi',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 10,
		        'data'      => '2018-09-29',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Hermannstadt',
		        'oaspeti'   => 'FCSB',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 10,
		        'data'      => '2018-09-29',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Viitorul',
		        'oaspeti'   => 'Astra Giurgiu',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 10,
		        'data'      => '2018-09-29',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Voluntari',
		        'oaspeti'   => 'FC Botoșani',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 10,
		        'data'      => '2018-09-29',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Gaz Metan Mediaș',
		        'oaspeti'   => 'Poli Iași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 10,
		        'data'      => '2018-09-29',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Astra Giurgiu',
		        'oaspeti'   => 'CFR Cluj',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 11,
		        'data'      => '2018-10-06',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dunărea Călărași',
		        'oaspeti'   => 'FC Voluntari',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 11,
		        'data'      => '2018-10-06',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Botoșani',
		        'oaspeti'   => 'Dinamo București',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 11,
		        'data'      => '2018-10-06',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FCSB',
		        'oaspeti'   => 'Concordia Chiajna',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 11,
		        'data'      => '2018-10-06',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Poli Iași',
		        'oaspeti'   => 'FC Viitorul',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 11,
		        'data'      => '2018-10-06',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Sepsi',
		        'oaspeti'   => 'Gaz Metan Mediaș',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 11,
		        'data'      => '2018-10-06',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'U Craiova 1948 CS',
		        'oaspeti'   => 'FC Hermannstadt',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 11,
		        'data'      => '2018-10-06',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'CFR Cluj',
		        'oaspeti'   => 'Poli Iași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 12,
		        'data'      => '2018-10-20',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dinamo București',
		        'oaspeti'   => 'Dunărea Călărași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 12,
		        'data'      => '2018-10-20',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Hermannstadt',
		        'oaspeti'   => 'Astra Giurgiu',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 12,
		        'data'      => '2018-10-20',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Viitorul',
		        'oaspeti'   => 'Sepsi',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 12,
		        'data'      => '2018-10-20',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Voluntari',
		        'oaspeti'   => 'Concordia Chiajna',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 12,
		        'data'      => '2018-10-20',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Gaz Metan Mediaș',
		        'oaspeti'   => 'FC Botoșani',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 12,
		        'data'      => '2018-10-20',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'U Craiova 1948 CS',
		        'oaspeti'   => 'FCSB',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 12,
		        'data'      => '2018-10-20',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Astra Giurgiu',
		        'oaspeti'   => 'U Craiova 1948 CS',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 13,
		        'data'      => '2018-10-27',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Concordia Chiajna',
		        'oaspeti'   => 'Dinamo București',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 13,
		        'data'      => '2018-10-27',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dunărea Călărași',
		        'oaspeti'   => 'Gaz Metan Mediaș',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 13,
		        'data'      => '2018-10-27',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Botoșani',
		        'oaspeti'   => 'FC Viitorul',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 13,
		        'data'      => '2018-10-27',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FCSB',
		        'oaspeti'   => 'FC Voluntari',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 13,
		        'data'      => '2018-10-27',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Poli Iași',
		        'oaspeti'   => 'FC Hermannstadt',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 13,
		        'data'      => '2018-10-27',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Sepsi',
		        'oaspeti'   => 'CFR Cluj',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 13,
		        'data'      => '2018-10-27',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Concordia Chiajna',
		        'oaspeti'   => 'Gaz Metan Mediaș',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 14,
		        'data'      => '2018-11-03',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dunărea Călărași',
		        'oaspeti'   => 'FC Viitorul',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 14,
		        'data'      => '2018-11-03',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Botoșani',
		        'oaspeti'   => 'CFR Cluj',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 14,
		        'data'      => '2018-11-03',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Voluntari',
		        'oaspeti'   => 'Dinamo București',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 14,
		        'data'      => '2018-11-03',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FCSB',
		        'oaspeti'   => 'Astra Giurgiu',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 14,
		        'data'      => '2018-11-03',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Poli Iași',
		        'oaspeti'   => 'U Craiova 1948 CS',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 14,
		        'data'      => '2018-11-03',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Sepsi',
		        'oaspeti'   => 'FC Hermannstadt',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 14,
		        'data'      => '2018-11-03',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Astra Giurgiu',
		        'oaspeti'   => 'Poli Iași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 15,
		        'data'      => '2018-11-10',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'CFR Cluj',
		        'oaspeti'   => 'Dunărea Călărași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 15,
		        'data'      => '2018-11-10',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dinamo București',
		        'oaspeti'   => 'FCSB',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 15,
		        'data'      => '2018-11-10',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Hermannstadt',
		        'oaspeti'   => 'FC Botoșani',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 15,
		        'data'      => '2018-11-10',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Viitorul',
		        'oaspeti'   => 'Concordia Chiajna',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 15,
		        'data'      => '2018-11-10',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Gaz Metan Mediaș',
		        'oaspeti'   => 'FC Voluntari',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 15,
		        'data'      => '2018-11-10',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'U Craiova 1948 CS',
		        'oaspeti'   => 'Sepsi',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 15,
		        'data'      => '2018-11-10',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Concordia Chiajna',
		        'oaspeti'   => 'CFR Cluj',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 16,
		        'data'      => '2018-11-24',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dinamo București',
		        'oaspeti'   => 'Gaz Metan Mediaș',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 16,
		        'data'      => '2018-11-24',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dunărea Călărași',
		        'oaspeti'   => 'FC Hermannstadt',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 16,
		        'data'      => '2018-11-24',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Botoșani',
		        'oaspeti'   => 'U Craiova 1948 CS',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 16,
		        'data'      => '2018-11-24',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Voluntari',
		        'oaspeti'   => 'FC Viitorul',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 16,
		        'data'      => '2018-11-24',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Poli Iași',
		        'oaspeti'   => 'FCSB',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 16,
		        'data'      => '2018-11-24',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Sepsi',
		        'oaspeti'   => 'Astra Giurgiu',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 16,
		        'data'      => '2018-11-24',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Astra Giurgiu',
		        'oaspeti'   => 'FC Botoșani',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 17,
		        'data'      => '2018-12-01',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'CFR Cluj',
		        'oaspeti'   => 'FC Voluntari',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 17,
		        'data'      => '2018-12-01',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Hermannstadt',
		        'oaspeti'   => 'Concordia Chiajna',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 17,
		        'data'      => '2018-12-01',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Viitorul',
		        'oaspeti'   => 'Dinamo București',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 17,
		        'data'      => '2018-12-01',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FCSB',
		        'oaspeti'   => 'Gaz Metan Mediaș',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 17,
		        'data'      => '2018-12-01',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Poli Iași',
		        'oaspeti'   => 'Sepsi',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 17,
		        'data'      => '2018-12-01',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'U Craiova 1948 CS',
		        'oaspeti'   => 'Dunărea Călărași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 17,
		        'data'      => '2018-12-01',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Concordia Chiajna',
		        'oaspeti'   => 'U Craiova 1948 CS',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 18,
		        'data'      => '2018-12-05',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dinamo București',
		        'oaspeti'   => 'CFR Cluj',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 18,
		        'data'      => '2018-12-05',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dunărea Călărași',
		        'oaspeti'   => 'Astra Giurgiu',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 18,
		        'data'      => '2018-12-05',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Botoșani',
		        'oaspeti'   => 'Poli Iași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 18,
		        'data'      => '2018-12-05',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Voluntari',
		        'oaspeti'   => 'FC Hermannstadt',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 18,
		        'data'      => '2018-12-05',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Gaz Metan Mediaș',
		        'oaspeti'   => 'FC Viitorul',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 18,
		        'data'      => '2018-12-05',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Sepsi',
		        'oaspeti'   => 'FCSB',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 18,
		        'data'      => '2018-12-05',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Astra Giurgiu',
		        'oaspeti'   => 'Concordia Chiajna',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 19,
		        'data'      => '2018-12-08',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'CFR Cluj',
		        'oaspeti'   => 'Gaz Metan Mediaș',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 19,
		        'data'      => '2018-12-08',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Hermannstadt',
		        'oaspeti'   => 'Dinamo București',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 19,
		        'data'      => '2018-12-08',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FCSB',
		        'oaspeti'   => 'FC Viitorul',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 19,
		        'data'      => '2018-12-08',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Poli Iași',
		        'oaspeti'   => 'Dunărea Călărași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 19,
		        'data'      => '2018-12-08',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Sepsi',
		        'oaspeti'   => 'FC Botoșani',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 19,
		        'data'      => '2018-12-08',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'U Craiova 1948 CS',
		        'oaspeti'   => 'FC Voluntari',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 19,
		        'data'      => '2018-12-08',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Concordia Chiajna',
		        'oaspeti'   => 'Poli Iași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 20,
		        'data'      => '2018-12-15',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dinamo București',
		        'oaspeti'   => 'U Craiova 1948 CS',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 20,
		        'data'      => '2018-12-15',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dunărea Călărași',
		        'oaspeti'   => 'Sepsi',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 20,
		        'data'      => '2018-12-15',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Botoșani',
		        'oaspeti'   => 'FCSB',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 20,
		        'data'      => '2018-12-15',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Viitorul',
		        'oaspeti'   => 'CFR Cluj',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 20,
		        'data'      => '2018-12-15',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Voluntari',
		        'oaspeti'   => 'Astra Giurgiu',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 20,
		        'data'      => '2018-12-15',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Gaz Metan Mediaș',
		        'oaspeti'   => 'FC Hermannstadt',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 20,
		        'data'      => '2018-12-15',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Astra Giurgiu',
		        'oaspeti'   => 'Dinamo București',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 21,
		        'data'      => '2018-12-20',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Botoșani',
		        'oaspeti'   => 'Dunărea Călărași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 21,
		        'data'      => '2018-12-20',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Hermannstadt',
		        'oaspeti'   => 'FC Viitorul',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 21,
		        'data'      => '2018-12-20',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FCSB',
		        'oaspeti'   => 'CFR Cluj',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 21,
		        'data'      => '2018-12-20',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Poli Iași',
		        'oaspeti'   => 'FC Voluntari',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 21,
		        'data'      => '2018-12-20',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Sepsi',
		        'oaspeti'   => 'Concordia Chiajna',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 21,
		        'data'      => '2018-12-20',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'U Craiova 1948 CS',
		        'oaspeti'   => 'Gaz Metan Mediaș',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 21,
		        'data'      => '2018-12-20',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'CFR Cluj',
		        'oaspeti'   => 'FC Hermannstadt',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 22,
		        'data'      => '2018-02-02',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Concordia Chiajna',
		        'oaspeti'   => 'FC Botoșani',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 22,
		        'data'      => '2018-02-02',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dinamo București',
		        'oaspeti'   => 'Poli Iași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 22,
		        'data'      => '2018-02-02',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dunărea Călărași',
		        'oaspeti'   => 'FCSB',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 22,
		        'data'      => '2018-02-02',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Viitorul',
		        'oaspeti'   => 'U Craiova 1948 CS',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 22,
		        'data'      => '2018-02-02',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Voluntari',
		        'oaspeti'   => 'Sepsi',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 22,
		        'data'      => '2018-02-02',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Gaz Metan Mediaș',
		        'oaspeti'   => 'Astra Giurgiu',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 22,
		        'data'      => '2018-02-02',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Astra Giurgiu',
		        'oaspeti'   => 'FC Viitorul',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 23,
		        'data'      => '2018-02-09',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dunărea Călărași',
		        'oaspeti'   => 'Concordia Chiajna',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 23,
		        'data'      => '2018-02-09',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Botoșani',
		        'oaspeti'   => 'FC Voluntari',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 23,
		        'data'      => '2018-02-09',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FCSB',
		        'oaspeti'   => 'FC Hermannstadt',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 23,
		        'data'      => '2018-02-09',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Poli Iași',
		        'oaspeti'   => 'Gaz Metan Mediaș',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 23,
		        'data'      => '2018-02-09',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Sepsi',
		        'oaspeti'   => 'Dinamo București',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 23,
		        'data'      => '2018-02-09',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'U Craiova 1948 CS',
		        'oaspeti'   => 'CFR Cluj',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 23,
		        'data'      => '2018-02-09',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'CFR Cluj',
		        'oaspeti'   => 'Astra Giurgiu',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 24,
		        'data'      => '2018-02-16',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Concordia Chiajna',
		        'oaspeti'   => 'FCSB',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 24,
		        'data'      => '2018-02-16',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dinamo București',
		        'oaspeti'   => 'FC Botoșani',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 24,
		        'data'      => '2018-02-16',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Hermannstadt',
		        'oaspeti'   => 'U Craiova 1948 CS',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 24,
		        'data'      => '2018-02-16',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Viitorul',
		        'oaspeti'   => 'Poli Iași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 24,
		        'data'      => '2018-02-16',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Voluntari',
		        'oaspeti'   => 'Dunărea Călărași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 24,
		        'data'      => '2018-02-16',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Gaz Metan Mediaș',
		        'oaspeti'   => 'Sepsi',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 24,
		        'data'      => '2018-02-16',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Astra Giurgiu',
		        'oaspeti'   => 'FC Hermannstadt',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 25,
		        'data'      => '2018-02-23',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Concordia Chiajna',
		        'oaspeti'   => 'FC Voluntari',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 25,
		        'data'      => '2018-02-23',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dunărea Călărași',
		        'oaspeti'   => 'Dinamo București',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 25,
		        'data'      => '2018-02-23',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Botoșani',
		        'oaspeti'   => 'Gaz Metan Mediaș',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 25,
		        'data'      => '2018-02-23',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FCSB',
		        'oaspeti'   => 'U Craiova 1948 CS',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 25,
		        'data'      => '2018-02-23',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Poli Iași',
		        'oaspeti'   => 'CFR Cluj',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 25,
		        'data'      => '2018-02-23',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Sepsi',
		        'oaspeti'   => 'FC Viitorul',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 25,
		        'data'      => '2018-02-23',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'CFR Cluj',
		        'oaspeti'   => 'Sepsi',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 26,
		        'data'      => '2018-03-02',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Dinamo București',
		        'oaspeti'   => 'Concordia Chiajna',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 26,
		        'data'      => '2018-03-02',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Hermannstadt',
		        'oaspeti'   => 'Poli Iași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 26,
		        'data'      => '2018-03-02',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Viitorul',
		        'oaspeti'   => 'FC Botoșani',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 26,
		        'data'      => '2018-03-02',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'FC Voluntari',
		        'oaspeti'   => 'FCSB',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 26,
		        'data'      => '2018-03-02',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'Gaz Metan Mediaș',
		        'oaspeti'   => 'Dunărea Călărași',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 26,
		        'data'      => '2018-03-02',
		        'ora'       => '18:00',
		    ], [
		        'gazde'     => 'U Craiova 1948 CS',
		        'oaspeti'   => 'Astra Giurgiu',
		        'g_gazde'   => NULL,
		        'g_oaspeti' => NULL,
		        'liga'      => 1,
		        'serie'     => NULL,
		        'etapa'     => 26,
		        'data'      => '2018-03-02',
		        'ora'       => '18:00',
		    ]
		];

		Echipe::where('liga', 1)->where('serie', null)->delete();
		foreach ($echipe as $echipa) {
			$adauga = new Echipe;
			$adauga->echipa = trim($echipa['echipa']);
			$adauga->liga   = $echipa['liga'];
			$adauga->serie  = $echipa['serie'];
			$adauga->save();
		}

		Etape::where('liga', 1)->where('serie', null)->delete();
		foreach ($etape as $etapa) {
			$adauga = new Etape;
			$adauga->gazde     = trim($etapa['gazde']);
			$adauga->oaspeti   = trim($etapa['oaspeti']);
			$adauga->g_gazde   = $etapa['g_gazde'];
			$adauga->g_oaspeti = $etapa['g_oaspeti'];
			$adauga->liga      = $etapa['liga'];
			$adauga->serie     = $etapa['serie'];
			$adauga->etapa     = $etapa['etapa'];
			$adauga->data      = $etapa['data'];
			$adauga->ora       = $etapa['ora'];
			$adauga->save();
		}
    }
}
